;; arbace.lang.Symbol and arbace.lang.Keyword.

;; Symbol.intern(String) splits at the first "/" unless the name is "/" alone
(each [s ["a" "a/b" "a/b/c" "/" "a/" "/a" "" "a.b.c/d" "ns//" "//" "kebab-case?" "été" "a b"]]
  (def sy (Symbol/intern s))
  (.getName sy)
  (.getNamespace sy)
  (.toString sy)
  (.hashCode sy)
  (.hasheq sy))
(def s1 (Symbol/intern "ns" "name"))
(.getNamespace s1)
(.getName s1)
(.toString s1)
(def s1b (Symbol/intern "ns/name"))
(.equals s1 s1b)
(.hashCode s1)
(.hasheq s1)
(.hasheq s1b)
(def s2 (Symbol/intern nil "name"))
(.toString s2)
(.getNamespace s2)
(def s3 (Symbol/intern "name"))
(.equals s2 s3)
(.equals s1 s3)
(Symbol/create "x")
(Symbol/create "x/y")
(Symbol/create "x" "y/z")
(def sz (Symbol/create "x" "y/z"))
(.getName sz)
(.toString sz)
(Symbol/intern "x" nil)

;; compareTo: nil namespace first, then by namespace, then by name
(def sa (Symbol/intern "a"))
(def sb (Symbol/intern "b"))
(def sab (Symbol/intern "a" "b"))
(def sba (Symbol/intern "b" "a"))
(def sB (Symbol/intern "B"))
(.compareTo sa sb)
(.compareTo sb sa)
(.compareTo sa sa)
(.compareTo sa sab)
(.compareTo sab sa)
(.compareTo sab sba)
(.compareTo sB sa)
(.compareTo sa sB)

;; meta
(def ka (Keyword/intern "a"))
(def mt (RT/map (array Object ka 1)))
(def sm (.withMeta sa mt))
(.meta sm)
(.equals sm sa)
(.hasheq sm)
(.meta sa)

;; invoke on a map
(def m (RT/map (array Object sa 1 ka 2)))
(.invoke sa m)
(.invoke sb m)
(.invoke sb m "default")
(.invoke sa nil)
(.invoke sa "string")

;; Keyword
(def k1 (Keyword/intern "kw"))
(.getName k1)
(.getNamespace k1)
(.toString k1)
(.hashCode k1)
(.hasheq k1)
(def k1s (.-sym k1))
(.hasheq k1s)
(def k2 (Keyword/intern "my.ns" "kw"))
(.getName k2)
(.getNamespace k2)
(.toString k2)
(.hasheq k2)
(def k3 (Keyword/intern "my.ns/kw"))
(.equals k2 k3)
(Util/identical k2 k3)
(def ksym (Symbol/intern "q" "r"))
(def k4 (Keyword/intern ksym))
(.toString k4)
(def ksm (.withMeta ksym mt))
(def k5 (Keyword/intern ksm))
(Util/identical k4 k5)
(Keyword/intern "")
(Keyword/intern "/")
(Keyword/intern "a/b/c")
(def kabc (Keyword/intern "a/b/c"))
(.getNamespace kabc)
(.getName kabc)
(Keyword/intern nil "x")
(Keyword/find "kw")
(Keyword/find "my.ns" "kw")
(Keyword/find "oracle-never-interned-keyword-zz9")
(def fsym (Symbol/intern "kw"))
(Keyword/find fsym)
(.compareTo k1 k2)
(.compareTo k2 k1)
(.compareTo k1 k1)
(def kb (Keyword/intern "kx"))
(.compareTo k1 kb)
(.compareTo kb k1)
(def m2 (RT/map (array Object k1 "v" k2 nil)))
(.invoke k1 m2)
(.invoke k2 m2)
(.invoke k2 m2 "nf")
(.invoke kb m2)
(.invoke kb m2 "nf")
(.invoke k1 nil)
(.invoke k1 "str")
(def st (RT/set (array Object k1)))
(.invoke k1 st)
(.invoke kb st)
(def v (RT/vector (array Object k1)))
(.invoke k1 v)
(.invoke k1)
(def args (ArraySeq/create (array Object m2)))
(.applyTo k1 args)
(def args0 (ArraySeq/create (array Object)))
(.applyTo k1 args0)
(RT/keyword "a" "b")
(RT/keyword nil "b")
(Util/hasheq k1)
(Util/hash k1)
(Util/equiv k1 k3)
(Util/equiv k2 k3)
(Util/equiv k1 fsym)
