;; arbace.lang.PersistentArrayMap: small maps in insertion order, promoted to a
;; PersistentHashMap past 8 entries.

(def e PersistentArrayMap/EMPTY)
(.count e)
(.seq e)
(.capacity e)
(.hasheq e)
(.toString e)
(.without e 1)
(.valAt e nil)

(def ka (Keyword/intern "a"))
(def kb (Keyword/intern "b"))
(def kns (Keyword/intern "ns" "x"))
(def m (new PersistentArrayMap (array Object ka 1 kb 2 "s" 3 nil 4 1 5)))
(.count m)
(.seq m)
(.capacity m)
(.valAt m ka)
(.valAt m "s")
(.valAt m nil)
(.valAt m 1)
(.valAt m (int 1))
(.valAt m 1.0)
(.valAt m (biginteger "1"))
(.valAt m kns)
^{:sig [Object Object]} (.valAt m "q" "nf")
(.containsKey m nil)
(.containsKey m "t")
(.entryAt m nil)
(.entryAt m 1)
(.hasheq m)
(.hashCode m)
(.toString m)
(def it (.iterator m))
(.next it)
(.next it)
(def ki (.keyIterator m))
(.next ki)
(.next ki)
(def vi (.valIterator m))
(.next vi)
(.drop m 2)
(.drop m 0)
(.drop m 5)
(.drop m 9)

;; assoc: replace in place (order kept), add at the end
(.assoc m kb 20)
(.assoc m kb 2)
(.assoc m (int 1) "int key")
(.assoc m "new" 6)
(.assocEx m "new" 6)
(.assocEx m ka 6)
(.without m kb)
(.without m ka)
(.without m 1)
(.without m "absent")
(def one (new PersistentArrayMap (array Object ka 1)))
(.without one ka)

;; growing to 8, 9 entries: the type changes to PersistentHashMap
(def g PersistentArrayMap/EMPTY)
(def g (.assoc g 0 "v0"))
(def g (.assoc g 1 "v1"))
(def g (.assoc g 2 "v2"))
(def g (.assoc g 3 "v3"))
(def g (.assoc g 4 "v4"))
(def g (.assoc g 5 "v5"))
(def g (.assoc g 6 "v6"))
(def g (.assoc g 7 "v7"))
(.count g)
(.assoc g 7 "again")
(def g9 (.assoc g 8 "v8"))
(.count g9)
(.valAt g9 8)
(.valAt g9 0)
(.equiv g9 g)
(def g9b (.assoc g 8.5 "v8"))
(def g8 (.without g9 8))
(.equiv g8 g)
(.hasheq g)
(.hasheq g8)

;; RT/map and the factories
(RT/map (array Object 1 2 3 4))
(RT/map (array Object 1 2 1 3))
(RT/map (array Object 0 0 1 1 2 2 3 3 4 4 5 5 6 6 7 7))
(RT/map (array Object 0 0 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8))
(RT/map (array Object))
(RT/map nil)
(RT/mapUniqueKeys (array Object 1 2 3 4))
(PersistentArrayMap/createWithCheck (array Object 1 2 3 4))
(PersistentArrayMap/createWithCheck (array Object 1 2 1 4))
(PersistentArrayMap/createWithCheck (array Object (int 1) 2 1 4))
(PersistentArrayMap/createAsIfByAssoc (array Object 1 2 1 4 3 5 1 6))
(PersistentArrayMap/createAsIfByAssoc (array Object 1 2 3))
(PersistentArrayMap/canBePAM (array Object 1 2 3 4))
(PersistentArrayMap/canBePAM (array Object 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18))
(def jm (new java.util.TreeMap))
(.put jm "b" 2)
(.put jm "a" 1)
^{:sig [java.util.Map]} (PersistentArrayMap/create jm)

;; equality with other maps
(def hm ^{:sig ["Object[]"]} (PersistentHashMap/create (array Object ka 1 kb 2 "s" 3 nil 4 1 5)))
(.equiv m hm)
(.equals m hm)
(.equiv hm m)
(.hasheq hm)
(.equiv m jm)
(def mint (new PersistentArrayMap (array Object (int 1) 5 ka 1 kb 2 "s" 3 nil 4)))
(.equiv m mint)
(.equals m mint)
(def md (new PersistentArrayMap (array Object 1.0 5 ka 1 kb 2 "s" 3 nil 4)))
(.equiv m md)
(def vm (new PersistentArrayMap (array Object ka nil)))
(def vm2 (new PersistentArrayMap (array Object kb nil)))
(.equiv vm vm2)
(.equiv vm one)

;; meta
(def mt (RT/map (array Object kb true)))
(def mm (.withMeta m mt))
(.meta mm)
(def mm2 (.assoc mm 9 9))
(.meta mm2)
(def mm3 (.without mm ka))
(.meta mm3)
(def mm4 (.empty mm))
(.meta mm4)
(def mm5 (.assoc mm 9 9))
(def mmh (.assoc g mt 1))
(def mmg (.withMeta g mt))
(def mmg9 (.assoc mmg 8 8))
(.meta mmg9)

;; transients
(def t (.asTransient m))
(.count t)
(def t (.assoc t "x" 1))
(def t (.assoc t ka 100))
(.valAt t ka)
(def t (.without t kb))
(.count t)
(def tp (.persistent t))
(.seq tp)
(.count t)
(def t2 (.asTransient e))
(def t2 (.assoc t2 0 0))
(def t2 (.assoc t2 1 1))
(def t2 (.assoc t2 2 2))
(def t2 (.assoc t2 3 3))
(def t2 (.assoc t2 4 4))
(def t2 (.assoc t2 5 5))
(def t2 (.assoc t2 6 6))
(def t2 (.assoc t2 7 7))
(def t2 (.assoc t2 8 8))
(.count t2)
(def t2p (.persistent t2))
(.count t2p)
