;; arbace.lang.PersistentTreeMap: the red-black tree, with the default comparator
;; (Util.compare) and others; seq order, rseq, seqFrom, min/max.

(def e PersistentTreeMap/EMPTY)
(.count e)
(.seq e)
(.rseq e)
(.minKey e)
(.maxKey e)
(.toString e)
(.hasheq e)
(.without e 1)
(.valAt e 1)
(.valAt e "string key on an empty map")
(.depth e)

(def m (.assoc e 40 "v40"))
(def m (.assoc m 50 "v50"))
(def m (.assoc m 20 "v20"))
(def m (.assoc m 80 "v80"))
(def m (.assoc m 10 "v10"))
(def m (.assoc m 30 "v30"))
(def m (.assoc m 70 "v70"))
(def m (.assoc m 90 "v90"))
(def m (.assoc m 5 "v5"))
(def m (.assoc m 15 "v15"))
(def m (.assoc m 25 "v25"))
(def m (.assoc m 35 "v35"))
(def m (.assoc m 1 "v1"))
(def m (.assoc m 2 "v2"))
(def m (.assoc m 3 "v3"))
(def m (.assoc m 4 "v4"))
(def m (.assoc m 100 "v100"))
(def m (.assoc m 60 "v60"))
(def m (.assoc m 65 "v65"))
(def m (.assoc m 75 "v75"))
(def m (.assoc m 85 "v85"))
(.count m)
(.depth m)
(.minKey m)
(.maxKey m)
(.valAt m 25)
(.valAt m 26)
(.valAt m (int 25))
(.valAt m 25.0)
(.valAt m (biginteger "25"))
(.valAt m (bigdecimal "25"))
^{:sig [Object Object]} (.valAt m 26 "nf")
(.containsKey m 100)
(.containsKey m 101)
(.entryAt m 65)
(.entryAt m 66)
(.rseq m)
^{:sig [boolean]} (.seq m false)
^{:sig [Object boolean]} (.seqFrom m 33 true)
^{:sig [Object boolean]} (.seqFrom m 35 true)
^{:sig [Object boolean]} (.seqFrom m 33 false)
^{:sig [Object boolean]} (.seqFrom m 35 false)
^{:sig [Object boolean]} (.seqFrom m 0 false)
^{:sig [Object boolean]} (.seqFrom m 1000 true)
(.hasheq m)
(.hashCode m)
(.assoc m 25 "again")
(.assoc m 25 "v25")
(.assocEx m 25 "x")
(.assoc m nil 1)
(.valAt m nil)
(def w (.without m 1000))
(def w (.without w 40))
(.count w)
(def w (.without w 50))
(.count w)
(def w (.without w 20))
(.count w)
(def w (.without w 1))
(.count w)
(def w (.without w 100))
(.count w)
(.seq w)
(.depth w)
(def w (.without w 65))
(.count w)
(def w (.without w 70))
(.count w)
(def w (.without w 4))
(.count w)
(.seq w)
(.depth w)
(def w (.without w 3))
(.count w)
(def w (.without w 2))
(.count w)
(def w (.without w 80))
(.count w)
(def w (.without w 10))
(.count w)
(def w (.without w 30))
(.count w)
(.seq w)
(.depth w)
(def w (.without w 90))
(.count w)
(def w (.without w 5))
(.count w)
(def w (.without w 15))
(.count w)
(def w (.without w 25))
(.count w)
(.seq w)
(.depth w)
(def w (.without w 35))
(.count w)
(def w (.without w 60))
(.count w)
(def w (.without w 75))
(.count w)
(def w (.without w 85))
(.count w)
(.seq w)
(.minKey w)

;; the seq: entries, rest, count
(def s (.seq m))
(.first s)
(.count s)
(def sn (.next s))
(.first sn)
(.count sn)
(def rs (.rseq m))
(.first rs)
(.count rs)
(def ki (.keys m))
(.next ki)
(.next ki)
(def vi (.vals m))
(.next vi)
(def ri (.reverseIterator m))
(.next ri)
(def nmin (.min m))
(.key nmin)
(.val nmin)
(def nmax (.max m))
(.key nmax)
(.getKey nmax)
(.getValue nmax)

;; other comparators
(def rc (java.util.Collections/reverseOrder))
(def items (ArraySeq/create (array Object 3 "three" 1 "one" 2 "two")))
(def r ^{:sig [java.util.Comparator arbace.lang.ISeq]} (PersistentTreeMap/create rc items))
(.seq r)
(.rseq r)
(.minKey r)
(.maxKey r)
^{:sig [Object boolean]} (.seqFrom r 2 true)
^{:sig [Object boolean]} (.seqFrom r 2 false)
(.comparator r)
(def cio String/CASE_INSENSITIVE_ORDER)
(def sitems (ArraySeq/create (array Object "b" 1 "A" 2 "c" 3 "B" 4)))
(def ci ^{:sig [java.util.Comparator arbace.lang.ISeq]} (PersistentTreeMap/create cio sitems))
(.count ci)
(.seq ci)
(.valAt ci "C")
(.containsKey ci "a")
(def dc RT/DEFAULT_COMPARATOR)
(def d ^{:sig [java.util.Comparator arbace.lang.ISeq]} (PersistentTreeMap/create dc sitems))
(.seq d)
^{:sig [arbace.lang.ISeq]} (PersistentTreeMap/create sitems)
(def odd (RT/list 1 2 3))
^{:sig [arbace.lang.ISeq]} (PersistentTreeMap/create odd)

;; mixed and odd keys under the default comparator
(def ka (Keyword/intern "a"))
(def kb (Keyword/intern "b"))
(def kns (Keyword/intern "z" "a"))
(def kw (.assoc e kb 1))
(def kw (.assoc kw kns 2))
(def kw (.assoc kw ka 3))
(.seq kw)
(def sb (Symbol/intern "b"))
(def sy (.assoc e sb 1))
(def ve ^{:sig ["Object[]"]} (PersistentVector/create (array Object 1 2)))
(def ve2 ^{:sig ["Object[]"]} (PersistentVector/create (array Object 1)))
(def vm (.assoc e ve 1))
(def vm (.assoc vm ve2 2))
(.seq vm)
(def nm (.assoc e 1 "long"))
(def nm (.assoc nm 1.5 "double"))
(def nm (.assoc nm (int 2) "int"))
(def nm (.assoc nm (biginteger "3") "bi"))
(def nm (.assoc nm (bigdecimal "0.5") "bd"))
(def nm (.assoc nm -0.0 "neg zero"))
(.seq nm)
(.valAt nm 2)
(.valAt nm 0.0)
(.valAt nm 0)
(.assoc nm 1.0 "replaced?")
(.assoc nm ##NaN "nan")
(def nilm (.assoc e nil "n"))
(def nilm (.assoc nilm 1 "one"))
(.seq nilm)
(.valAt nilm nil)
(.without nilm nil)

;; equality with other maps
(def am (RT/map (array Object 1 "v1" 2 "v2")))
(def tm (.assoc e 2 "v2"))
(def tm (.assoc tm 1 "v1"))
(.equiv tm am)
(.equals tm am)
(.equiv am tm)
(.hasheq tm)
(.hasheq am)
(.hashCode tm)
(.hashCode am)

;; meta
(def mt (RT/map (array Object ka 1)))
(def mm (.withMeta tm mt))
(.meta mm)
(def mm2 (.assoc mm 3 3))
(.meta mm2)
(def mm3 (.without mm 1))
(.meta mm3)
(def mm4 (.empty mm))
(.meta mm4)
(.comparator mm4)
