;; arbace.lang.PersistentList (and its EmptyList), Cons.

(def e PersistentList/EMPTY)
(.count e)
(.seq e)
(.first e)
(.next e)
(.more e)
(.peek e)
(.pop e)
(.hasheq e)
(.hashCode e)
(.toString e)
(.equiv e e)
(def ev PersistentVector/EMPTY)
(.equiv e ev)
(.equals e ev)
(.isEmpty e)
(.size e)
(.contains e nil)
(.indexOf e 1)
(.empty e)

(def l1 (.cons e 3))
(def l2 (.cons l1 nil))
(def l3 (.cons l2 "one"))
(.count l3)
(.first l3)
(.next l3)
(.more l3)
(.peek l3)
(.pop l3)
(def p1 (.pop l3))
(def p2 (.pop p1))
(def p3 (.pop p2))
(.count p3)
(.pop p3)
(def m1 (.more l1))
(.next l1)
(.seq l3)
(.hasheq l3)
(.hashCode l3)
(.toString l3)
(.get l3 2)
(.get l3 3)
(.indexOf l3 nil)
(.lastIndexOf l3 3)
(.contains l3 3)
(.contains l3 (int 3))
(.contains l3 3.0)
(.size l3)
(.subList l3 1 3)
(def arr (.toArray l3))
(RT/vector arr)
(def it (.iterator l3))
(.next it)
(.next it)
(.next it)
(.hasNext it)
(.add l3 1)
(.remove l3 nil)

(def v ^{:sig ["Object[]"]} (PersistentVector/create (array Object "one" nil 3)))
(.equiv l3 v)
(.equals l3 v)
(.equiv v l3)
(def vi ^{:sig ["Object[]"]} (PersistentVector/create (array Object "one" nil (int 3))))
(.equiv l3 vi)
(.equals l3 vi)
(.hasheq vi)
(.hashCode vi)
(def vd ^{:sig ["Object[]"]} (PersistentVector/create (array Object "one" nil 3.0)))
(.equiv l3 vd)

(PersistentList/create v)
(PersistentList/create ev)
(def jl (new java.util.ArrayList))
(.add jl "a")
(.add jl 2)
(PersistentList/create jl)
(def pc PersistentList/creator)
(.invoke pc 1 2 3)
(.invoke pc)
(def sq (ArraySeq/create (array Object 1 2)))
(.applyTo pc sq)

(def ka (Keyword/intern "a"))
(def mt (RT/map (array Object ka 1)))
(def lm (.withMeta l3 mt))
(.meta lm)
(.equiv lm l3)
(def lm2 (.cons lm 0))
(.meta lm2)
(def lm3 (.pop lm))
(.meta lm3)
(def lm4 (.empty lm))
(.meta lm4)
(def em (.withMeta e mt))
(.meta em)
(.count em)

;; Cons
(def c (new Cons 1 nil))
(.count c)
(.first c)
(.next c)
(.more c)
(def c2 (new Cons 0 c))
(.count c2)
(.toString c2)
(.hasheq c2)
(def c3 (new Cons "x" l3))
(.count c3)
(.next c3)
(.equiv c2 l3)
(def l01 (RT/list 0 1))
(.equiv c2 l01)
(.equals c2 l01)
(.hasheq l01)
(def c5 (.cons c2 -1))
(.withMeta c5 mt)
(def c6 (.withMeta c5 mt))
(.meta c6)
(.meta c5)
(.empty c6)
(RT/cons 1 nil)
(RT/cons 1 ev)
(RT/cons 1 v)
(RT/cons 1 l3)
(RT/cons nil nil)
(RT/listStar 1 2 l3)
(RT/list)
(RT/list nil)
(RT/list 1 2 3 4 5)
(RT/arrayToList (array Object 1 2))
(RT/length l3)
(RT/boundedLength l3 2)
