;; arbace.lang.PersistentVector: the tree of 32-wide nodes and its tail, transients, seqs.

(def e PersistentVector/EMPTY)
(.count e)
(.seq e)
(.rseq e)
(.hashCode e)
(.hasheq e)
(.peek e)
(.pop e)
(.nth e 0)
^{:sig [int Object]} (.nth e 0 "none")
(.-shift e)
(.isEmpty e)
(.toString e)
(def el PersistentList/EMPTY)
(.equiv e el)
(.equals e el)
(.empty e)
(.meta e)

;; conj one by one through the first tail
(def v (.cons e 0))
(def v (.cons v 1))
(def v (.cons v nil))
(def v (.cons v "three"))
(.count v)
(.nth v 2)
(.nth v 3)
(.nth v 4)
(.nth v -1)
^{:sig [int Object]} (.nth v 4 "nf")
^{:sig [int Object]} (.nth v -1 "nf")
(.peek v)
(.pop v)
(.seq v)
(.rseq v)
(.hashCode v)
(.hasheq v)
(.toString v)
(.length v)
(.indexOf v nil)
(.indexOf v "three")
(.indexOf v 7)
(.lastIndexOf v 0)
(.contains v nil)
(.containsKey v 3)
(.containsKey v 4)
(.containsKey v "a")
(.containsKey v (int 2))
(.entryAt v 1)
(.entryAt v 9)
^{:sig [Object]} (.valAt v 3)
^{:sig [Object Object]} (.valAt v 30 "dflt")
^{:sig [Object Object]} (.valAt v 1.0 "dflt")
(.invoke v 1)
(.invoke v 10)
^{:sig [Object]} (.invoke v "x")

;; assocN: replace, append at count, beyond
(.assocN v 0 "zero")
(.assocN v 3 4)
(.assocN v 4 "appended")
(.assocN v 5 "beyond")
(.assocN v -1 "neg")
^{:sig [Object Object]} (.assoc v 1 "one")
^{:sig [Object Object]} (.assoc v (int 1) "int one")
^{:sig [Object Object]} (.assoc v "k" "v")
(.toString v)

;; across the tail boundary (32) and the root boundary (1056 = 32 + 32*32)
(def r31 (LongRange/create 0 31))
(def v31 ^{:sig [arbace.lang.ISeq]} (PersistentVector/create r31))
(.-shift v31)
(def v32 (.cons v31 31))
(.-shift v32)
(def v33 (.cons v32 32))
(.-shift v33)
(.count v33)
(.nth v33 31)
(.nth v33 32)
(.nth v33 33)
(.peek v33)
(def p32 (.pop v33))
(.count p32)
(.peek p32)
(.equiv p32 v32)
(.equals p32 v32)
(.hasheq p32)
(.hasheq v32)
(.hashCode v33)
(.assocN v33 33 33)
(.assocN v33 0 "a")
(.assocN v33 32 "last")
(.assocN v33 31 "first in tail?")
(def pp (.pop p32))
(.count pp)
(.equiv pp v31)

(def r1056 (LongRange/create 0 1056))
(def big ^{:sig [arbace.lang.ISeq]} (PersistentVector/create r1056))
(.count big)
(.-shift big)
(.nth big 0)
(.nth big 31)
(.nth big 32)
(.nth big 1023)
(.nth big 1024)
(.nth big 1055)
(.nth big 1056)
(.hasheq big)
(.hashCode big)
(def big2 (.cons big "x"))
(.count big2)
(.-shift big2)
(.nth big2 1056)
(.nth big2 1055)
(.nth big2 500)
(.peek big2)
(.hasheq big2)
(def back (.pop big2))
(.count back)
(.-shift back)
(.equiv back big)
(.hasheq back)
(def big3 (.assocN big2 1056 "y"))
(.nth big3 1056)
(def big4 (.assocN big2 1057 "z"))
(.count big4)
(.nth big4 1057)
(.nth big4 1024)
(.-shift big4)
(def big5 (.assocN big4 777 "mid"))
(.nth big5 777)
(.nth big4 777)
(.nth big5 776)

;; seqs: chunked
(def s (.seq v33))
(.first s)
(def cf (.chunkedFirst s))
(.count cf)
(.nth cf 0)
(.nth cf 31)
(def cn (.chunkedNext s))
(.first cn)
(.count cn)
(.chunkedMore cn)
(.chunkedNext cn)
(.next cn)
(def s2 (.next s))
(.first s2)
(.count s2)
(def sd (.drop v33 30))
(.drop v33 0)
(.drop v33 33)
(.drop v33 40)
(def rs (.rseq v33))
(.first rs)
(.count rs)
(def rv (.rseq v))
(.next rv)
(def rsn (.next rs))
(.first rsn)
(.index rsn)
(.equiv s v33)
(.hasheq s)

;; equality and comparison with other sequentials and maps
(def l (PersistentList/create v))
(.equiv v l)
(.equals v l)
(def vs (.seq v))
(.equiv v vs)
(def lv ^{:sig [java.util.List]} (PersistentVector/create l))
(.equals lv v)
(.compareTo v31 v32)
(.compareTo v32 v31)
(.compareTo v32 v32)
(def a1 ^{:sig ["Object[]"]} (PersistentVector/create (array Object 1 2 3)))
(def a2 ^{:sig ["Object[]"]} (PersistentVector/create (array Object 1 2 4)))
(.compareTo a1 a2)
(.compareTo a2 a1)
(def a3 ^{:sig ["Object[]"]} (PersistentVector/create (array Object (int 1) 2 3)))
(.equiv a1 a3)
(.equals a1 a3)
(.hasheq a3)
(.hashCode a3)
(.hashCode a1)
(def a4 ^{:sig ["Object[]"]} (PersistentVector/create (array Object 1.0 2 3)))
(.equiv a1 a4)
(.equals a1 a4)
(.hasheq a4)
(def a5 ^{:sig ["Object[]"]} (PersistentVector/create (array Object 1 2 3 4)))
(.compareTo a1 a5)

;; adopt, LazilyPersistentVector
(def ad (PersistentVector/adopt (array Object "a" "b")))
(.count ad)
(def lz (LazilyPersistentVector/createOwning (array Object 1 2 3)))
(LazilyPersistentVector/createOwning (array Object))
(LazilyPersistentVector/create v)
(LazilyPersistentVector/create l)
(LazilyPersistentVector/create r31)
(LazilyPersistentVector/create nil)
(LazilyPersistentVector/create (array Object "x" nil))

;; meta
(def kw (Keyword/intern "tag"))
(def m (RT/map (array Object kw "t")))
(def vm (.withMeta v m))
(.meta vm)
(.equiv vm v)
(.hasheq vm)
(def vm1 (.cons vm 9))
(.meta vm1)
(def vm2 (.pop vm))
(.meta vm2)
(def vm3 (.assocN vm 0 1))
(.meta vm3)
(def vm4 (.empty vm))
(.meta vm4)
(.withMeta e m)

;; transients
(def t (.asTransient v31))
(.count t)
(def t (.conj t 31))
(def t (.conj t 32))
(.count t)
(.nth t 32)
(.nth t 33)
(.valAt t 32)
^{:sig [Object Object]} (.valAt t 40 "nf")
(.containsKey t 0)
(.containsKey t 33)
(.entryAt t 1)
(.invoke t 1)
(def t (.assocN t 0 "zero"))
(def t (.assocN t 33 "append"))
(.assocN t 35 "beyond")
^{:sig [Object Object]} (.assoc t 1 "one")
^{:sig [Object Object]} (.assoc t "k" "v")
(def t (.pop t))
(.count t)
(def pv (.persistent t))
(.count pv)
(.conj t 1)
(.count t)
(.nth t 0)
(.persistent t)

(def tb (.asTransient big))
(def tb (.conj tb "x"))
(.count tb)
(.nth tb 1056)
(def tb (.assocN tb 3 "three"))
(def tb (.pop tb))
(def tb (.pop tb))
(.count tb)
(.nth tb 1054)
(.nth tb 3)
(.nth big 3)
(def te (.asTransient e))
(.pop te)
(def te2 (.asTransient a1))
(def te2 (.pop te2))
(def te2 (.pop te2))
(def te2 (.pop te2))
(.count te2)
(.persistent te2)

;; java.util.List surface
(.get v 1)
(.get v 9)
(.size v33)
(.subList a5 1 3)
(def arr (.toArray a1))
(RT/vector arr)
(.add v 1)
(.set v 0 1)
(.remove v 0)
(.containsAll a5 a1)
(.containsAll a1 a5)
(def it (.iterator a1))
(.next it)
(.next it)
(.hasNext it)
(.next it)
(.hasNext it)
(.next it)
