;; arbace.lang.PersistentHashMap: the HAMT (bitmap indexed, array and hash collision nodes),
;; the nil key, transients. The iteration order (seq, printed form) follows hasheq.

(def e PersistentHashMap/EMPTY)
(.count e)
(.seq e)
(.hasheq e)
(.hashCode e)
(.toString e)
(.valAt e "a")
(.containsKey e nil)
(.without e "a")
(.entryAt e nil)

(def ka (Keyword/intern "a"))
(def kb (Keyword/intern "b"))
(def kc (Keyword/intern "c"))
(def m1 ^{:sig ["Object[]"]} (PersistentHashMap/create (array Object ka 1 kb 2 kc 3)))
(.count m1)
(.seq m1)
(.valAt m1 ka)
(.valAt m1 kb)
(.valAt m1 "a")
^{:sig [Object Object]} (.valAt m1 kc "nf")
^{:sig [Object Object]} (.valAt m1 "c" "nf")
(.containsKey m1 ka)
(.containsKey m1 "a")
(.entryAt m1 kb)
(.entryAt m1 "b")
(.hasheq m1)
(.hashCode m1)
(.toString m1)
(.invoke m1 ka)
^{:sig [Object Object]} (.invoke m1 "zz" "nf")
(def m2 (.assoc m1 ka 10))
(.valAt m2 ka)
(.valAt m1 ka)
(.assoc m1 ka 1)
(.assocEx m1 ka 2)
(.assocEx m1 "new" 2)
(def m3 (.without m1 kb))
(.count m3)
(.seq m3)
(.without m1 "absent")
(.equiv m1 m3)
(.equals m1 m2)
(def m1b ^{:sig ["Object[]"]} (PersistentHashMap/create (array Object kc 3 kb 2 ka 1)))
(.equiv m1 m1b)
(.equals m1 m1b)
(.hasheq m1b)

;; duplicate keys: create keeps the last, createWithCheck throws
^{:sig ["Object[]"]} (PersistentHashMap/create (array Object 1 "a" 1 "b"))
^{:sig ["Object[]"]} (PersistentHashMap/createWithCheck (array Object 1 "a" 1 "b"))
^{:sig ["Object[]"]} (PersistentHashMap/createWithCheck (array Object 1 "a" 2 "b"))
^{:sig ["Object[]"]} (PersistentHashMap/create (array Object 1 "a" 2))

;; numeric keys: equal by equiv (Long 1 and Integer 1), not BigDecimal or Double
(def mn ^{:sig ["Object[]"]} (PersistentHashMap/create (array Object 1 "long" 2.0 "double")))
(.valAt mn (int 1))
(.valAt mn (short 1))
(.valAt mn (byte 1))
(.valAt mn (biginteger "1"))
(.valAt mn (bigdecimal "1"))
(.valAt mn 1.0)
(.valAt mn 2.0)
(.valAt mn (float 2.0))
(.valAt mn 2)
(.assoc mn (int 1) "int")

;; the nil key
(def mz (.assoc m1 nil "nil value"))
(.count mz)
(.valAt mz nil)
(.containsKey mz nil)
(.entryAt mz nil)
(.seq mz)
(.hasheq mz)
(def mz2 (.assoc mz nil "again"))
(.valAt mz2 nil)
(.count mz2)
(def mz3 (.without mz nil))
(.count mz3)
(.containsKey mz3 nil)
(.equiv mz3 m1)
(.assoc e nil nil)
(def mnil (.assoc e nil nil))
(.containsKey mnil nil)
(.count mnil)
(.seq mnil)

;; hash collisions: "Aa" and "BB" (and every 4-char mix) have equal String.hashCode and so
;; equal hasheq
(Util/hasheq "Aa")
(Util/hasheq "BB")
(Util/hasheq "AaAa")
(Util/hasheq "BBBB")
(def hc ^{:sig ["Object[]"]} (PersistentHashMap/create (array Object "Aa" 1 "BB" 2)))
(.count hc)
(.seq hc)
(.valAt hc "Aa")
(.valAt hc "BB")
(.valAt hc "Ab")
(def hc2 (.assoc hc "AaAa" 3))
(def hc3 (.assoc hc2 "AaBB" 4))
(def hc4 (.assoc hc3 "BBAa" 5))
(def hc5 (.assoc hc4 "BBBB" 6))
(.count hc5)
(.valAt hc5 "BBAa")
(.valAt hc5 "BBBB")
(.valAt hc5 "AaAa")
(def hc6 (.assoc hc5 "BBAa" 50))
(.valAt hc6 "BBAa")
(.count hc6)
(def hc7 (.without hc6 "AaBB"))
(.count hc7)
(.valAt hc7 "AaBB")
(.valAt hc7 "BBBB")
(def hc8 (.without hc7 "BBAa"))
(def hc9 (.without hc8 "BBBB"))
(.seq hc9)
(def hc10 (.without hc9 "AaAa"))
(.seq hc10)
(def hc11 (.without hc10 "Aa"))
(.seq hc11)
(.without hc11 "BB")
(.hasheq hc5)
(.hashCode hc5)
(def hcb ^{:sig ["Object[]"]} (PersistentHashMap/create (array Object "BBBB" 6 "BBAa" 5 "AaBB" 4 "AaAa" 3 "BB" 2 "Aa" 1)))
(.equiv hc5 hcb)
(.hasheq hcb)

;; growing past 16 entries in a node (array node) and shrinking back
(def g ^{:sig ["Object[]"]} (PersistentHashMap/create (array Object 0 0 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9 10 10 11 11 12 12 13 13 14 14 15 15)))
(.count g)
(def g (.assoc g 16 16))
(def g (.assoc g 17 17))
(def g (.assoc g 18 18))
(def g (.assoc g "s" "s"))
(def g (.assoc g ka "kw"))
(def g (.assoc g 1.5 "d"))
(def g (.assoc g (biginteger "99999999999999999999") "bi"))
(.count g)
(.valAt g 17)
(.valAt g "s")
(.valAt g 1.5)
(.valAt g (biginteger "99999999999999999999"))
(.valAt g 19)
(.hasheq g)
(def g1 ^{:sig ["Object[]"]} (PersistentHashMap/create (array Object 100 0 101 1 102 2 103 3 104 4 105 5 106 6 107 7 108 8 109 9 110 10 111 11 112 12 113 13 114 14 115 15 116 16 117 17 118 18 119 19 120 20 121 21 122 22 123 23 124 24 125 25 126 26 127 27 128 28 129 29 130 30 131 31 132 32 133 33 134 34 135 35)))
(.count g1)
(def g2 (.without g1 100))
(def g2 (.without g2 101))
(def g2 (.without g2 102))
(def g2 (.without g2 103))
(def g2 (.without g2 104))
(def g2 (.without g2 105))
(def g2 (.without g2 106))
(def g2 (.without g2 107))
(def g2 (.without g2 108))
(def g2 (.without g2 109))
(def g2 (.without g2 110))
(def g2 (.without g2 111))
(def g2 (.without g2 112))
(def g2 (.without g2 113))
(def g2 (.without g2 114))
(def g2 (.without g2 115))
(def g2 (.without g2 116))
(def g2 (.without g2 117))
(def g2 (.without g2 118))
(def g2 (.without g2 119))
(def g2 (.without g2 120))
(def g2 (.without g2 121))
(def g2 (.without g2 122))
(def g2 (.without g2 123))
(def g2 (.without g2 124))
(def g2 (.without g2 125))
(def g2 (.without g2 126))
(def g2 (.without g2 127))
(def g2 (.without g2 128))
(def g2 (.without g2 129))
(def g2 (.without g2 130))
(.count g2)
(.valAt g2 135)
(.valAt g2 130)

;; keys, vals, iterators
(RT/keys m1)
(RT/vals m1)
(RT/keys e)
(def ki (.keyIterator hc5))
(.next ki)
(.next ki)
(def vi (.valIterator hc5))
(.next vi)
(def it (.iterator mz))
(.next it)
(.next it)

;; Map interface
(.get m1 ka)
(.size m1)
(.isEmpty e)
(.containsValue m1 2)
(.containsValue m1 7)
(.put m1 1 2)
(.remove m1 ka)

;; meta
(def md (RT/map (array Object ka 1)))
(def mm (.withMeta m1 md))
(.meta mm)
(def mm2 (.assoc mm kb 7))
(.meta mm2)
(def mm3 (.without mm ka))
(.meta mm3)
(.equiv mm m1)

;; with another map kind
(def am (RT/map (array Object ka 1 kb 2 kc 3)))
(.equiv m1 am)
(.equals m1 am)
(.hasheq am)
(.hashCode am)
(def pm (PersistentHashMap/create am (array Object "x" 1)))
(.count pm)
(.valAt pm "x")
(def jm (new java.util.HashMap))
(.put jm "j" 1)
(.put jm "k" 2)
(.equiv m1 jm)
(def fromj ^{:sig [java.util.Map]} (PersistentHashMap/create jm))
(.valAt fromj "k")
(.equals fromj jm)
(def sq ^{:sig ["Object[]"]} (PersistentHashMap/create (array Object)))
(.count sq)
(def lst (RT/list ka 1 kb))
^{:sig [arbace.lang.ISeq]} (PersistentHashMap/create lst)
(def lst2 (RT/list ka 1 kb 2))
^{:sig [arbace.lang.ISeq]} (PersistentHashMap/create lst2)
^{:sig [arbace.lang.ISeq]} (PersistentHashMap/createWithCheck lst2)

;; transients
(def t (.asTransient m1))
(.count t)
(def t (.assoc t "x" 1))
(def t (.assoc t nil 2))
(def t (.assoc t "Aa" 3))
(def t (.assoc t "BB" 4))
(.count t)
(.valAt t nil)
(.valAt t "BB")
^{:sig [Object Object]} (.valAt t "CC" "nf")
(.containsKey t nil)
(.entryAt t "Aa")
(def t (.without t ka))
(def t (.without t nil))
(def t (.without t "Aa"))
(def t (.without t "absent"))
(.count t)
(def tp (.persistent t))
(.count tp)
(.seq tp)
(.assoc t 1 1)
(def t2 (.asTransient e))
(def t2 (.assoc t2 1 1))
(def t2 (.assoc t2 (int 1) 2))
(def t2 (.assoc t2 1.0 3))
(.count t2)
(.persistent t2)
(def tg (.asTransient g1))
(def tg (.without tg 100))
(def tg (.without tg 101))
(def tg (.without tg 102))
(def tg (.without tg 103))
(def tg (.without tg 104))
(def tg (.without tg 105))
(def tg (.without tg 106))
(def tg (.without tg 107))
(def tg (.without tg 108))
(def tg (.without tg 109))
(def tg (.without tg 110))
(def tg (.without tg 111))
(def tg (.without tg 112))
(def tg (.without tg 113))
(def tg (.without tg 114))
(def tg (.without tg 115))
(def tg (.without tg 116))
(def tg (.without tg 117))
(def tg (.without tg 118))
(def tg (.without tg 119))
(def tg (.without tg 120))
(def tg (.without tg 121))
(def tg (.without tg 122))
(def tg (.without tg 123))
(def tg (.without tg 124))
(def tg (.without tg 125))
(def tg (.without tg 126))
(def tg (.without tg 127))
(def tg (.without tg 128))
(def tg (.without tg 129))
(def tg (.without tg 130))
(.count tg)
(.persistent tg)
(.equiv g2 g1)
