;; The seq classes that need no function: LongRange, Range, Repeat, Cycle, Iterate (with a
;; vector as the function), ArraySeq, StringSeq, ChunkedCons, RT.seq of the seqable things.

;; LongRange
(LongRange/create 5)
(LongRange/create 0)
(LongRange/create -3)
(LongRange/create 2 7)
(LongRange/create 7 2)
(LongRange/create 0 10 3)
(LongRange/create 10 0 -3)
(LongRange/create 10 0 3)
(LongRange/create 0 10 -1)
(def lz (LongRange/create 0 10 0))
(.first lz)
(def lr (LongRange/create 0 100 7))
(.count lr)
(.first lr)
(.next lr)
(def cf (.chunkedFirst lr))
(.count cf)
(.nth cf 0)
(.nth cf 14)
(.chunkedNext lr)
(.chunkedMore lr)
(.drop lr 3)
(.drop lr 14)
(.drop lr 15)
(.drop lr 0)
(.hasheq lr)
(def lv ^{:sig ["Object[]"]} (PersistentVector/create (array Object 0 7 14 21 28 35 42 49 56 63 70 77 84 91 98)))
(.equiv lr lv)
(.equals lr lv)
(.hasheq lv)
(def l40 (LongRange/create 0 40))
(def l40c (.chunkedNext l40))
(.first l40c)
(def l40cc (.chunkedFirst l40c))
(.count l40cc)
(LongRange/create 9223372036854775800 9223372036854775807 3)
(LongRange/create -9223372036854775808 -9223372036854775805)
(def lbig (LongRange/create 0 9223372036854775807 4611686018427387904))
(.count lbig)
(LongRange/create 9223372036854775806 9223372036854775807)

;; Range (Object bounds)
(Range/create 3)
(Range/create 1.5)
(Range/create 0 2.5)
(Range/create 0 1 0.25)
(Range/create 1 0 -0.25)
(def r13 (new Ratio (biginteger "1") (biginteger "3")))
(Range/create 0 1 r13)
(Range/create 0 (biginteger "3"))
(Range/create (bigdecimal "0.5") 3)
(def bi (BigInt/fromLong 2))
(Range/create bi 5)
(def rinf (Range/create 0 10 0))
(def rr (Range/create 0.0 1.0 0.1))
(.count rr)
(.first rr)
(def rrn (.next rr))
(.first rrn)

;; Repeat
(def rep (Repeat/create "x"))
(.first rep)
(def repn (.next rep))
(.first repn)
(def rep3 (Repeat/create 3 "y"))
(RT/printString rep3)
(.count rep3)
(def rep3n (.next rep3))
(RT/printString rep3n)
(Repeat/create 0 "z")
(Repeat/create -1 "z")
(def rep1 (Repeat/create 1 nil))
(RT/printString rep1)
(.next rep1)
(def repd (.drop rep3 2))
(RT/printString repd)
(.drop rep3 3)
(def repid (.drop rep 1000))
(.first repid)

;; Cycle
(def three (ArraySeq/create (array Object 1 2 3)))
(def cy (Cycle/create three))
(.first cy)
(def cy1 (.next cy))
(.first cy1)
(def cy2 (.next cy1))
(.first cy2)
(def cy3 (.next cy2))
(.first cy3)
(.isRealized cy)
(Cycle/create nil)
(def ea (ArraySeq/create (array Object)))
(Cycle/create ea)

;; Iterate with a vector as the function: 0 -> 1 -> 2 -> 0 ...
(def f ^{:sig ["Object[]"]} (PersistentVector/create (array Object 1 2 0)))
(def it (Iterate/create f 0))
(.first it)
(def it1 (.next it))
(.first it1)
(def it2 (.next it1))
(.first it2)
(def it3 (.next it2))
(.first it3)
(.isRealized it)

;; ArraySeq
(ArraySeq/create)
(ArraySeq/create (array Object))
(def as (ArraySeq/create (array Object "a" nil 3 4.5)))
(.count as)
(.first as)
(.next as)
(.index as)
(def as2 (.next as))
(.index as2)
(.count as2)
(.hasheq as)
(.toString as)
(ArraySeq/create nil)
(def asi (RT/seq (array int 1 2 3)))
(.first asi)
(.count asi)
(RT/seq (array long 1 2))
(RT/seq (array double 1.5 2))
(RT/seq (array char \a \b))
(RT/seq (array boolean true false))
(RT/seq (array byte 1 -1))
(RT/seq (array short 7))
(RT/seq (array float 1.5))
(RT/seq (array int))
(RT/seq (array String "s" "t"))

;; StringSeq
(def ss (StringSeq/create "héllo"))
(.count ss)
(.first ss)
(.next ss)
(.index ss)
(.drop ss 2)
(.drop ss 5)
(StringSeq/create "")
(def su (StringSeq/create "a😀b"))
(.count su)
(RT/printString su)
(def su1 (.next su))
(RT/printString su1)
(RT/seq "abc")
(RT/seq "")
(def sb (new StringBuilder "xy"))
(RT/seq sb)

;; RT.seq of collections and other seqables
(RT/seq nil)
(def ka (Keyword/intern "a"))
(def m (RT/map (array Object ka 1 "b" 2)))
(RT/seq m)
(def ms (RT/seq m))
(.first ms)
(def st (RT/set (array Object 1)))
(RT/seq st)
(def jl (new java.util.ArrayList))
(.add jl 1)
(.add jl "two")
(RT/seq jl)
(def jle (new java.util.ArrayList))
(RT/seq jle)
(def jm (new java.util.TreeMap))
(.put jm "k" "v")
(def jms (RT/seq jm))
(.count jms)
(RT/seq 5)
(RT/seq ka)
(RT/canSeq ka)
(RT/canSeq "s")
(RT/canSeq jl)
(RT/canSeq nil)
(RT/count "abc")
(RT/count jl)
(RT/count jm)
(RT/count (array int 1 2))
(RT/count nil)
(RT/count 5)

;; chunked seqs of vectors: ChunkedCons, chunk buffers
(def cb (new ChunkBuffer 4))
(.add cb 1)
(.add cb 2)
(.count cb)
(def ch (.chunk cb))
(.count ch)
(.nth ch 1)
(def chd (.dropFirst ch))
(.count chd)
(.nth chd 0)
(def tail (ArraySeq/create (array Object 9)))
(def cc (new ChunkedCons ch tail))
(.first cc)
(.next cc)
(.count cc)
(.chunkedNext cc)
(.chunkedMore cc)
(def ccd (new ChunkedCons chd nil))
(.next ccd)
(.more ccd)
(.toString cc)
(.hasheq cc)
(def ac (new ArrayChunk (array Object 1 2 3 4) 1 3))
(.count ac)
(.nth ac 0)
(.nth ac 2)
^{:sig [int Object]} (.nth ac 2 "nf")
(def acd (.dropFirst ac))
(.count acd)
(def ac0 (new ArrayChunk (array Object 1) 1))
(.dropFirst ac0)

;; Iterator and enumeration seqs
(def jit (.iterator jl))
(def itseq (IteratorSeq/create jit))
(RT/printString itseq)
(def jit2 (.iterator jl))
(def ciseq (RT/chunkIteratorSeq jit2))
(RT/printString ciseq)
(def jit3 (.iterator jle))
(IteratorSeq/create jit3)
