;; arbace.lang.PersistentHashSet and PersistentTreeSet.

(def e PersistentHashSet/EMPTY)
(.count e)
(.seq e)
(.hasheq e)
(.hashCode e)
(.toString e)
(.contains e nil)
(.disjoin e 1)

(def ka (Keyword/intern "a"))
(def s ^{:sig ["Object[]"]} (PersistentHashSet/create (array Object 1 "two" ka nil 3.0)))
(.count s)
(.seq s)
(.contains s 1)
(.contains s (int 1))
(.contains s 1.0)
(.contains s 3.0)
(.contains s 3)
(.contains s nil)
(.contains s "two")
(.get s "two")
(.get s "three")
(.invoke s ka)
^{:sig [Object Object]} (.invoke s "zz" "nf")
(.hasheq s)
(.hashCode s)
(.toString s)
(def s2 (.cons s 4))
(.count s2)
(.cons s 1)
(.cons s (int 1))
(def s3 (.disjoin s nil))
(.contains s3 nil)
(.count s3)
(.disjoin s "absent")
(def s4 ^{:sig ["Object[]"]} (PersistentHashSet/create (array Object 3.0 nil ka "two" 1)))
(.equiv s s4)
(.equals s s4)
(.hasheq s4)
^{:sig ["Object[]"]} (PersistentHashSet/create (array Object 1 1 2))
^{:sig ["Object[]"]} (PersistentHashSet/createWithCheck (array Object 1 1 2))
^{:sig ["Object[]"]} (PersistentHashSet/createWithCheck (array Object 1 (int 1)))
(def lst ^{:sig ["Object[]"]} (PersistentVector/create (array Object "x" "y" "x")))
^{:sig [java.util.List]} (PersistentHashSet/create lst)
^{:sig [java.util.List]} (PersistentHashSet/createWithCheck lst)
(def sq (ArraySeq/create (array Object "p" "q")))
^{:sig [arbace.lang.ISeq]} (PersistentHashSet/create sq)
(def coll ^{:sig ["Object[]"]} (PersistentHashSet/create (array Object "Aa" "BB" "AaAa" "BBBB" "AaBB")))
(.count coll)
(.seq coll)
(.contains coll "BBAa")
(.contains coll "AaBB")
(def coll2 (.disjoin coll "BB"))
(.seq coll2)
(.contains coll2 "Aa")
(def big ^{:sig ["Object[]"]} (PersistentHashSet/create (array Object 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39)))
(.count big)
(.seq big)
(.contains big 39)
(.hasheq big)
(def t (.asTransient s))
(def t (.conj t 9))
(def t (.disjoin t 1))
(.count t)
(.contains t 9)
(.contains t 1)
(.get t 9)
(.invoke t 9)
(def tp (.persistent t))
(.seq tp)
(.conj t 1)

;; java.util.Set surface
(.size s)
(.isEmpty e)
(.containsAll s s3)
(.containsAll s3 s)
(.add s 1)
(def arr (.toArray s))
(RT/vector arr)

;; meta
(def mt (RT/map (array Object ka 1)))
(def sm (.withMeta s mt))
(.meta sm)
(def sm2 (.cons sm 99))
(.meta sm2)
(def sm3 (.disjoin sm 1))
(.meta sm3)
(def sm4 (.empty sm))
(.meta sm4)

;; RT/set
(RT/set (array Object 1 2 3))
(RT/set (array Object 1 2 1))
(RT/set (array Object))

;; sorted sets
(def te PersistentTreeSet/EMPTY)
(.count te)
(.seq te)
(.rseq te)
(.toString te)
(def ts ^{:sig [arbace.lang.ISeq]} (PersistentTreeSet/create sq))
(def nums (ArraySeq/create (array Object 5 3 9 1 7 3 (int 5) 2.5)))
(def tn ^{:sig [arbace.lang.ISeq]} (PersistentTreeSet/create nums))
(.count tn)
(.seq tn)
(.rseq tn)
(.contains tn 7)
(.contains tn 7.0)
(.contains tn 4)
^{:sig [boolean]} (.seq tn false)
^{:sig [Object boolean]} (.seqFrom tn 4 true)
^{:sig [Object boolean]} (.seqFrom tn 4 false)
^{:sig [Object boolean]} (.seqFrom tn 5 true)
^{:sig [Object boolean]} (.seqFrom tn 100 true)
^{:sig [Object boolean]} (.seqFrom tn 0 false)
(def tn2 (.cons tn 4))
(.seq tn2)
(def tn3 (.disjoin tn2 5))
(.seq tn3)
(.disjoin tn3 42)
(.hasheq tn)
(.hashCode tn)
(def hn ^{:sig ["Object[]"]} (PersistentHashSet/create (array Object 1 2.5 3 5 7 9)))
(.equiv tn hn)
(.equals tn hn)
(.equiv hn tn)
(.hasheq hn)
(.comparator tn)
(def rc (java.util.Collections/reverseOrder))
(def nums2 (ArraySeq/create (array Object 5 3 9 1 7 3)))
(def tr ^{:sig [java.util.Comparator arbace.lang.ISeq]} (PersistentTreeSet/create rc nums2))
(.seq tr)
(.rseq tr)
^{:sig [Object boolean]} (.seqFrom tr 4 true)
(def strs (ArraySeq/create (array Object "b" "A" "a" "B" "é" "e" "z" "")))
(def tstr ^{:sig [arbace.lang.ISeq]} (PersistentTreeSet/create strs))
(.seq tstr)
(def cio String/CASE_INSENSITIVE_ORDER)
(def tci ^{:sig [java.util.Comparator arbace.lang.ISeq]} (PersistentTreeSet/create cio strs))
(.seq tci)
(.count tci)
(def tsm (.withMeta tn mt))
(.meta tsm)
(def tsm2 (.cons tsm 0))
(.meta tsm2)
(def tsm3 (.empty tsm))
(.meta tsm3)
(.comparator tsm3)
