;; java.lang.StringBuilder and String, Double/Float/Long/Integer to and from strings (the
;; parts of the JDK the runtime relies on), Compiler.munge/demunge, and the toString of names.

;; StringBuilder
(def sb (new StringBuilder))
(.length sb)
(.toString sb)
(def sb (.append sb "abc"))
^{:sig [char]} (.append sb \d)
^{:sig [int]} (.append sb (int 42))
^{:sig [long]} (.append sb -9223372036854775808)
^{:sig [boolean]} (.append sb true)
^{:sig [double]} (.append sb 1.0E10)
^{:sig [double]} (.append sb 0.1)
^{:sig [float]} (.append sb (float 0.1))
^{:sig [Object]} (.append sb nil)
^{:sig [String]} (.append sb nil)
(def ka (Keyword/intern "kw"))
^{:sig [Object]} (.append sb ka)
(def v (RT/vector (array Object 1 "s")))
^{:sig [Object]} (.append sb v)
^{:sig [java.lang.CharSequence int int]} (.append sb "0123456789" 2 5)
^{:sig ["char[]"]} (.append sb (array char \x \y))
(.toString sb)
(.length sb)
(.charAt sb 0)
(.charAt sb 1000)
(.indexOf sb "42")
^{:sig [String int]} (.indexOf sb "a" 1)
(.lastIndexOf sb "null")
(.indexOf sb "absent")
^{:sig [int String]} (.insert sb 0 ">>")
^{:sig [int char]} (.insert sb 2 \|)
^{:sig [int Object]} (.insert sb 0 ka)
^{:sig [int String]} (.insert sb 1000 "x")
(.substring sb 0 6)
^{:sig [int]} (.substring sb 50)
(.deleteCharAt sb 0)
(.delete sb 0 3)
(.replace sb 0 2 "REPLACED")
(.toString sb)
(.setCharAt sb 0 \r)
(.setLength sb 5)
(.toString sb)
(.setLength sb 7)
(.toString sb)
(.setLength sb 0)
(.toString sb)
(.setLength sb -1)

;; surrogate pairs (U+1F600) and lone surrogates
(def su (new StringBuilder "a😀b😁"))
(.length su)
(.codePointAt su 1)
(.codePointAt su 2)
(.codePointBefore su 3)
(.codePointCount su 0 6)
(.offsetByCodePoints su 0 2)
(.reverse su)
(.toString su)
(def lone (new StringBuilder "x\ud800y\udc00"))
(.reverse lone)
(.toString lone)
(def pair (new StringBuilder))
(.appendCodePoint pair 128512)
(.appendCodePoint pair 65)
(.appendCodePoint pair 1114111)
(.length pair)
(.toString pair)
(.appendCodePoint pair 1114112)
(def rev2 (new StringBuilder "\udc00\ud800"))
(.reverse rev2)
(.toString rev2)
(def cs (new StringBuilder "abc"))
(.compareTo cs su)
(def cs2 (new StringBuilder "abc"))
(.compareTo cs cs2)
(.equals cs cs2)
(def abc (new String "abc"))
(.contentEquals abc cs)

;; String
(each [s ["" "abc" "ABC" "été" "a😀b" "\ud800" " pad\t\n" "ß" "İ" "x\u0000y"]]
  (def st (new String s))
  (.length st)
  (.hashCode st)
  (.isEmpty st)
  (.isBlank st)
  (.trim st)
  (.strip st)
  ^{:sig [int]} (.codePointAt st 0)
  (.compareTo st "abc")
  (.equalsIgnoreCase st "ABC")
  (.compareToIgnoreCase st "ABC"))
(def hello (new String "hello"))
(def emo (new String "a😀b"))
(def abc2 (new String "a.b.c"))
(def ab (new String "ab"))
(.substring hello 1 3)
(.substring hello 3 1)
^{:sig [String]} (.indexOf hello "l")
^{:sig [int]} (.indexOf hello (int 108))
^{:sig [int]} (.indexOf emo (int 128512))
^{:sig [String]} (.lastIndexOf hello "l")
(.startsWith hello "he")
(.endsWith hello "lo")
^{:sig [java.lang.CharSequence]} (.contains hello "ell")
^{:sig [java.lang.CharSequence java.lang.CharSequence]} (.replace abc2 "." "--")
^{:sig [char char]} (.replace abc2 \. \/)
(.repeat ab 3)
(.repeat ab 0)
(.repeat ab -1)
(.concat ab "cd")
(.charAt abc 3)
(String/valueOf 1.0E-5)
^{:sig [Object]} (String/valueOf nil)
^{:sig [char]} (String/valueOf \c)
^{:sig ["char[]"]} (String/valueOf (array char \a \b))
(String/join "," (array java.lang.CharSequence "a" "b"))

;; numbers to and from strings: Java's shortest-repr double printing
(each [d [0.0 -0.0 1.0 0.1 0.2 0.3 1.0E7 9999999.0 1.0E-3 0.001 1.0E-4 123456789012.0 1.7976931348623157E308 4.9E-324 2.2250738585072014E-308 1.0E21 1.0E22 100.0 2.5E-5 0.30000000000000004 ##NaN ##Inf ##-Inf 5.0E-324 9007199254740993.0 1.2345678901234567E-10]]
  (Double/toString d)
  (Double/hashCode d)
  (Double/doubleToLongBits d))
(each [f [(float 0.1) (float 1.0E10) (float 3.4028234663852886E38) (float 1.4E-45) (float 16777217.0) (float 1.0E-3)]]
  ^{:sig [float]} (Float/toString f))
(each [s ["1" "-1.5" "1e3" "  2.5  " ".5" "5." "0x1p3" "Infinity" "-Infinity" "NaN" "1d" "1f" "abc" "" "1e400" "4.9e-325" "1_0"]]
  (Double/parseDouble s))
(each [s ["0" "-0" "+5" "9223372036854775807" "9223372036854775808" "-9223372036854775808" "1.0" " 1" "" "0x10" "007"]]
  (Long/parseLong s))
^{:sig [String int]} (Long/parseLong "zz" 36)
^{:sig [String int]} (Long/parseLong "-ff" 16)
^{:sig [long int]} (Long/toString -255 16)
^{:sig [long int]} (Long/toString 35 36)
(Long/toHexString -1)
(Long/toBinaryString 10)
(Long/toOctalString -1)
(Integer/toHexString -1)
(Integer/toString -2147483648)
(Long/hashCode -1)
(Long/hashCode 4294967296)
(Long/numberOfLeadingZeros 1)
(Long/bitCount -1)
(Character/isWhitespace (char 160))
(Character/isWhitespace (char 8232))
(Character/isLetter (char 233))
(Character/isDigit (char 1635))
^{:sig [char int]} (Character/digit \7 10)
^{:sig [char int]} (Character/digit \z 36)
^{:sig [char]} (Character/toUpperCase (char 223))
^{:sig [char]} (Character/toLowerCase (char 304))
^{:sig [int]} (Character/toChars 128512)
(Character/isHighSurrogate (char 55357))
(Character/getNumericValue (char 8555))
(Character/toString 128512)

;; Compiler.munge and demunge
(each [s ["a" "a-b" "a.b" "a/b" "foo?" "set!" "*v*" "+" "->x" "<=" "a'b" "a#" "%" "&" "|" "é" "a_b" "__x" "x$y" "..." ":" "[]" "{}" "@" "~" "^" "\\" "\"" "a b"]]
  (def mm (Compiler/munge s))
  (Compiler/demunge mm))
(Compiler/demunge "foo_QMARK_")
(Compiler/demunge "a_b")
(Compiler/demunge "my.ns$fn__1234")
(Compiler/demunge "my.ns$my_fn$inner")

;; the toString of names
(def sym (Symbol/intern "my.ns" "na-me"))
(.toString sym)
(def nsym (Symbol/intern "oracle.classes.strings-ns"))
(def ns (Namespace/findOrCreate nsym))
(.toString ns)
(def kq (Keyword/intern "my.ns" "k"))
(.toString kq)
(def vr (RT/var "oracle.classes.strings-ns" "v" 1))
(.toString vr)
