;; arbace.lang.Util (equiv, equals, compare) and the RT collection functions.

(def ka (Keyword/intern "a"))
(def kb (Keyword/intern "b"))
(def sa (Symbol/intern "a"))
(def r (new Ratio (biginteger "1") (biginteger "2")))
(def bn (BigInt/fromLong 1))
(def v ^{:sig ["Object[]"]} (PersistentVector/create (array Object 1 2)))
(def l (RT/list 1 2))
(def jl (new java.util.ArrayList))
(.add jl 1)
(.add jl 2)
(def st (RT/set (array Object 1 2)))
(def m (RT/map (array Object 1 2)))
(def jm (new java.util.HashMap))
(.put jm 1 2)

(each [x [nil 1 (int 1) 1.0 bn (biginteger "1") (bigdecimal "1.0") r "a" \a ka sa v l jl st m jm]
       y [1 1.0 (bigdecimal "1") "a" v l m]]
  ^{:sig [Object Object]} (Util/equiv x y)
  (Util/equals x y))
;; compare: nil first, numbers across types, then within one kind (other mixes throw a
;; ClassCastException whose JVM message is not portable)
(each [x [nil 1 1.5 r bn (bigdecimal "0.5") ##NaN]
       y [nil 2 1.5 r ##NaN]]
  (Util/compare x y))
(each [x ["a" "b" "B" "" "\u00e9"]
       y [nil "a" "ab"]]
  (Util/compare x y))
(def sb (Symbol/intern "b"))
(def kns (Keyword/intern "n" "a"))
(each [x [ka kb kns]
       y [ka kb kns]]
  (Util/compare x y))
(each [x [sa sb]
       y [sa sb]]
  (Util/compare x y))
(Util/compare v nil)
(Util/compare nil v)
(def v3 ^{:sig ["Object[]"]} (PersistentVector/create (array Object 1 2 3)))
(Util/compare v v3)
(Util/compare v3 v)
(def vc ^{:sig ["Object[]"]} (PersistentVector/create (array Object 1 3)))
(Util/compare v vc)
(Util/compare true false)
(Util/compare false nil)
^{:sig [char char]} (Util/equiv \a \a)
^{:sig [boolean boolean]} (Util/equiv true true)
^{:sig [long long]} (Util/equiv 1 1)
^{:sig [double double]} (Util/equiv ##NaN ##NaN)
^{:sig [Object Object]} (Util/equiv ##NaN ##NaN)
(Util/identical ka ka)
(Util/identical 1 1)
(Util/isInteger 1)
(Util/isInteger (int 1))
(Util/isInteger bn)
(Util/isInteger (biginteger "1"))
(Util/isInteger 1.0)
(Util/isInteger r)
(Util/pcequiv v l)

;; RT collection functions
(each [c [nil v l st m jl jm "ab" ka]]
  (RT/count c)
  (RT/seq c)
  (RT/first c)
  (RT/second c)
  (RT/next c)
  (RT/more c))
(each [c [nil v m st "ab" jm jl]
       k [0 1 2 "a" nil]]
  (RT/get c k)
  (RT/contains c k)
  (RT/find c k))
(RT/get v 1 "nf")
(RT/get m 9 "nf")
(RT/get nil 9 "nf")
(def ia (RT/aclone (array int 10 20)))
(RT/get ia 1)
(RT/get ia 5)
(RT/get ia 5 "nf")
(RT/contains ia 1)
(RT/nth v 1)
(RT/nth v 5)
^{:sig [Object int Object]} (RT/nth v 5 "nf")
(RT/nth l 1)
(RT/nth "abc" 2)
(RT/nth ia 0)
(RT/nth jl 1)
(RT/nth nil 0)
(def me (new MapEntry "k" "v"))
(RT/nth me 0)
(RT/nth me 1)
(RT/nth me 2)
(RT/nth m 0)
(def sq (RT/seq v3))
(RT/nth sq 2)
^{:sig [Object int Object]} (RT/nth sq 3 "nf")
(RT/assoc v 0 "x")
(RT/assoc v 2 "x")
(RT/assoc m "k" "v")
(RT/assoc nil "k" "v")
(RT/dissoc m 1)
(RT/dissoc nil 1)
(RT/conj v 3)
(RT/conj l 0)
(RT/conj st 3)
(RT/conj m me)
(RT/conj m v)
(RT/conj nil 1)
(RT/conj m v3)
(RT/peek v)
(RT/peek nil)
(RT/pop v)
(RT/pop nil)
(RT/keys m)
(RT/keys nil)
(RT/vals m)
(RT/vals jm)
(RT/keys jm)
(RT/meta v)
(RT/meta 1)
(RT/subvec v3 1 3)
(RT/subvec v3 0 0)
(RT/subvec v3 2 1)
(RT/subvec v3 0 4)
(def sv (RT/subvec v3 1 3))
(.count sv)
(.nth sv 0)
(.nth sv 2)
(.cons sv 9)
(.assocN sv 2 "end")
(.assocN sv 3 "beyond")
(.pop sv)
(RT/subvec sv 1 2)
(RT/vector (array Object 1 2))
(RT/vector (array Object))
(RT/list)
(RT/list 1)
(RT/set (array Object))
(RT/map (array Object 1 2))
(def ta (RT/toArray v3))
(RT/vector ta)
(def ta2 (RT/toArray "ab"))
(RT/vector ta2)
(def ta3 (RT/toArray nil))
(RT/vector ta3)
(RT/toArray 5)
(def sa2 (RT/seqToArray sq))
(RT/vector sa2)
(RT/booleanCast nil)
(RT/booleanCast false)
(RT/booleanCast 0)
(RT/booleanCast "")
^{:sig [Object]} (RT/intCast 3.9)
^{:sig [Object]} (RT/intCast 2147483648)
^{:sig [long]} (RT/intCast 2147483648)
^{:sig [double]} (RT/intCast -3.9)
^{:sig [Object]} (RT/longCast 1.0E19)
^{:sig [double]} (RT/longCast ##NaN)
^{:sig [Object]} (RT/longCast r)
^{:sig [Object]} (RT/longCast bn)
^{:sig [long]} (RT/uncheckedIntCast 2147483648)
^{:sig [Object]} (RT/charCast 65)
^{:sig [long]} (RT/charCast 65536)
^{:sig [Object]} (RT/charCast -1)
^{:sig [Object]} (RT/byteCast 200)
^{:sig [long]} (RT/uncheckedByteCast 200)
^{:sig [Object]} (RT/shortCast 32767)
^{:sig [Object]} (RT/floatCast 1.0E39)
^{:sig [Object]} (RT/floatCast -1.0E39)
^{:sig [Object]} (RT/floatCast 0.1)
^{:sig [Object]} (RT/doubleCast r)
(RT/isReduced v)
(RT/boundedLength l 1)
