;; arbace.lang.Var and arbace.lang.Namespace, on fresh namespaces (their names are unique to
;; this script). Namespaces and vars print with identity, so they are observed through their
;; methods.

(def nsym (Symbol/intern "oracle.classes.vn-one"))
(Namespace/find nsym)
(def ns1 (Namespace/findOrCreate nsym))
(.toString ns1)
(.getName ns1)
(def ns1b (Namespace/findOrCreate nsym))
(Util/identical ns1 ns1b)
(def ns1c (Namespace/find nsym))
(Util/identical ns1 ns1c)

(def xsym (Symbol/intern "x"))
(def strsym (Symbol/intern "String"))
(def strmap (.getMapping ns1 strsym))
(.getName strmap)
(.getMapping ns1 xsym)
(.findInternedVar ns1 xsym)
(def al1 (.getAliases ns1))
(RT/count al1)

;; interning
(def vx (.intern ns1 xsym))
(.toString vx)
(.isBound vx)
(.hasRoot vx)
(.isDynamic vx)
(.isMacro vx)
(.isPublic vx)
(def unb (.deref vx))
(.toString unb)
(def unb2 (.getRawRoot vx))
(Util/identical unb unb2)
(.bindRoot vx 42)
(.isBound vx)
(.hasRoot vx)
(.deref vx)
(.get vx)
(.getRawRoot vx)
(def vx2 (.intern ns1 xsym))
(Util/identical vx vx2)
(def vx3 (.findInternedVar ns1 xsym))
(Util/identical vx vx3)
(def vx4 (.getMapping ns1 xsym))
(Util/identical vx vx4)
(.-sym vx)
(def vxns (.-ns vx))
(Util/identical vxns ns1)
(.toSymbol vx)
(.unbindRoot vx)
(.isBound vx)
(.hasRoot vx)
(def nsxsym (Symbol/intern "other.ns" "x"))
(.intern ns1 nsxsym)

;; Var.intern with a root, replacing the root
(def ysym (Symbol/intern "y"))
(def vy ^{:sig [arbace.lang.Namespace arbace.lang.Symbol Object]} (Var/intern ns1 ysym "root"))
(.deref vy)
(def vy2 ^{:sig [arbace.lang.Namespace arbace.lang.Symbol Object]} (Var/intern ns1 ysym "new root"))
(Util/identical vy vy2)
(.deref vy)
(def vy3 ^{:sig [arbace.lang.Namespace arbace.lang.Symbol Object boolean]} (Var/intern ns1 ysym "kept" false))
(.deref vy)
(def vy4 ^{:sig [arbace.lang.Namespace arbace.lang.Symbol]} (Var/intern ns1 ysym))
(.deref vy)
(def fq (Symbol/intern "oracle.classes.vn-one" "y"))
(def vy5 (Var/find fq))
(Util/identical vy vy5)
(def fq2 (Symbol/intern "oracle.classes.vn-one" "nope"))
(Var/find fq2)
(def fq3 (Symbol/intern "oracle.classes.vn-none" "nope"))
(Var/find fq3)
(def fq4 (Symbol/intern "nope"))
(Var/find fq4)
(def ystr (RT/var "oracle.classes.vn-one" "y"))
(Util/identical vy ystr)
(def zstr (RT/var "oracle.classes.vn-one" "z" 7))
(.deref zstr)
(.toString zstr)

;; dynamic vars (thread bindings cannot span steps: each step is evaluated on its own)
(.isDynamic vy)
(def vyd (.setDynamic vy))
(.isDynamic vy)
(.set vy "no binding")
(.setDynamic vy false)
(.isDynamic vy)
(def vzb (RT/map (array Object zstr 1)))
(Var/pushThreadBindings vzb)

;; macros and meta
(.setMacro zstr)
(.isMacro zstr)
(def ka (Keyword/intern "private"))
(def pm (RT/map (array Object ka true)))
(.setMeta zstr pm)
(.isPublic zstr)
(def ktag (Keyword/intern "tag"))
(.getTag zstr)
(def tsym (Symbol/intern "String"))
(.setTag zstr tsym)
(.getTag zstr)

;; anonymous vars
(def anon (Var/create))
(.toString anon)
(.isBound anon)
(def anon2 (Var/create 5))
(.deref anon2)
(.toString anon2)
(.hasRoot anon2)
(def anonu (.deref anon))
(.toString anonu)

;; invoking a var invokes its root: a keyword root
(def kvar (RT/var "oracle.classes.vn-one" "kfn" ka))
(def pmap (RT/map (array Object ka "found")))
(.invoke kvar pmap)
(def unbound-call (RT/var "oracle.classes.vn-one" "unbound-call"))
(.invoke unbound-call 1)

;; refer, unmap, aliases
(def ns2sym (Symbol/intern "oracle.classes.vn-two"))
(def ns2 (Namespace/findOrCreate ns2sym))
(def rsym (Symbol/intern "ry"))
(def rv (.refer ns2 rsym vy))
(def rv2 (.getMapping ns2 rsym))
(Util/identical rv2 vy)
(.findInternedVar ns2 rsym)
(.unmap ns2 rsym)
(.getMapping ns2 rsym)
(def asym (Symbol/intern "one"))
(.addAlias ns2 asym ns1)
(def al (.lookupAlias ns2 asym))
(Util/identical al ns1)
(.addAlias ns2 asym ns2)
(.removeAlias ns2 asym)
(.lookupAlias ns2 asym)
(def isym (Symbol/intern "y"))
(def ivar (.intern ns2 isym))
(.toString ivar)
(def clash (.refer ns2 isym vy))
(.toString clash)

;; removal
(def rmd (Namespace/remove ns2sym))
(Util/identical rmd ns2)
(Namespace/find ns2sym)
(Namespace/remove ns2sym)
(def coresym (Symbol/intern "arbace.core"))
(Namespace/remove coresym)
(def core (Namespace/find coresym))
(.toString core)
(def plussym (Symbol/intern "+"))
(def plus (.findInternedVar core plussym))
(.toString plus)
(.isBound plus)
