;; The namespace of Java package arbace.asm, written by arbace.j2c from Clojure 98d735fab02f;
;; see doc/VENDOR-NOTES.md.

(ns arbace.asm)

(load "asm/AnnotationVisitor")
(load "asm/AnnotationWriter")
(load "asm/Attribute")
(load "asm/ByteVector")
(load "asm/ClassReader")
(load "asm/ClassTooLargeException")
(load "asm/ClassVisitor")
(load "asm/ClassWriter")
(load "asm/ComputeLimits")
(load "asm/ConstantDynamic")
(load "asm/Constants")
(load "asm/Context")
(load "asm/Frame")
(load "asm/CurrentFrame")
(load "asm/Edge")
(load "asm/FieldVisitor")
(load "asm/FieldWriter")
(load "asm/Handle")
(load "asm/Handler")
(load "asm/Label")
(load "asm/LimitExceededException")
(load "asm/MethodTooLargeException")
(load "asm/MethodVisitor")
(load "asm/MethodWriter")
(load "asm/ModuleVisitor")
(load "asm/ModuleWriter")
(load "asm/Opcodes")
(load "asm/RecordComponentVisitor")
(load "asm/RecordComponentWriter")
(load "asm/Symbol")
(load "asm/SymbolTable")
(load "asm/Type")
(load "asm/TypePath")
(load "asm/TypeReference")
