;; The REPL session of bin/arbace-bench's startup benchmark: a short interactive session, read
;; by the REPL from stdin; the same on every implementation (no namespace-qualified names).
(defn square [x] (* x x))
(map square (range 10))
(def m {:a 1 :b [1 2 3] :c {:d "e"}})
(update-in m [:c :d] str "f")
(doc map)
(defrecord Pt [x y])
(->Pt 1 2)
(defprotocol Len (len [x]))
(extend-protocol Len String (len [s] (count s)))
(len "hello")
(reduce + (filter odd? (range 1000)))
(str "a" 1 :b)
(let [{:keys [a b]} m] [a b])
(for [x (range 3) y (range 3) :when (< x y)] [x y])
(try (/ 1 0) (catch ArithmeticException e (.getMessage e)))
(frequencies "mississippi")
(sort-by val > {:x 3 :y 1 :z 2})
