;; Collections: vectors, lists, maps, sets, sorted collections, queues, transients, arrays.

(require '[arbace.set :as set])

;; ----- vector basics
[]
[1 2 3]
(vector)
(vector 1 2 3 4 5 6 7)
(vec nil)
(vec '(1 2 3))
(vec "abc")
(vec {:a 1})
(class [1 2])
(class (vec (range 40)))
(conj [] 1)
(conj [1 2] 3 4 5)
(conj nil 1)
(conj [1] nil)
(assoc [1 2 3] 0 :a)
(assoc [1 2 3] 3 :end)
(assoc [1 2 3] 4 :x)
(assoc [1 2 3] -1 :x)
(assoc [] 0 :first)
(assoc [1 2] 1.5 :x)
(pop [1 2 3])
(pop [1])
(pop [])
(peek [1 2 3])
(peek [])
(nth [1 2 3] 0)
(nth [1 2 3] 3)
(nth [1 2 3] 3 :default)
(nth [1 2 3] -1 :neg)
(nth [1 2 3] 1.7)
(get [1 2 3] 1)
(get [1 2 3] 5)
(get [1 2 3] 5 :nf)
(get [1 2 3] -1)
(get [1 2 3] :a)
(get [1 2 3] 1.0)
(contains? [1 2 3] 0)
(contains? [1 2 3] 3)
(contains? [1 2 3] 1)
(contains? [:a :b] :a)
([10 20 30] 1)
([10 20 30] 3)
([10 20 30] :x)
(subvec [1 2 3 4 5] 1 3)
(subvec [1 2 3 4 5] 2)
(subvec [1 2 3 4 5] 5)
(subvec [1 2 3 4 5] 3 2)
(subvec [1 2 3 4 5] 0 6)
(conj (subvec [1 2 3 4 5] 1 3) :x)
(assoc (subvec [1 2 3 4 5] 1 3) 2 :y)
(pop (subvec [1 2 3 4 5] 1 3))
(class (subvec [1 2 3] 1))
(rseq [1 2 3])
(rseq [])
(class (rseq [1 2 3]))
(rseq (subvec [1 2 3 4] 1 3))
(empty [1 2 3])
(meta (empty (with-meta [1] {:m 1})))
(vector-of :int 1 2 3)
(class (vector-of :long 1 2))
(conj (vector-of :double 1 2) 3)
(vector-of :byte 1 2 300)
(mapv inc [1 2 3])
(vec (range 5))
(= [1 2 3] (vec (range 1 4)))
(hash [])
(hash [1 2 3])
(hash [nil])
(hash [[1] [2]])
(compare [1 2] [1 3])
(compare [1 2 3] [1 3])
(compare [] [0])
(sort [[2 1] [1 2] [1] [1 1 1]])
(.indexOf [1 2 3 2] 2)
(.lastIndexOf [1 2 3 2] 2)
(.indexOf [1 2] 5)
(count [1 2 3])
(count [])

;; ----- large vectors: tail and tree boundaries
(def v32 (vec (range 32)))
(def v33 (vec (range 33)))
(def v1056 (vec (range 1056)))
(def v1057 (vec (range 1057)))
(def v40000 (vec (range 40000)))
(count v32)
(count (conj v32 :x))
(nth (conj v32 :x) 32)
(peek (conj v32 :x))
(pop v33)
(count (pop v33))
(peek (pop v33))
(count v1056)
(nth v1056 1055)
(nth v1056 1024)
(nth v1056 1023)
(peek (conj v1056 :x))
(count (conj v1056 :x))
(nth (conj v1056 :x) 1056)
(count (pop v1057))
(peek (pop v1057))
(nth (pop v1057) 1055)
(count (pop (pop v1057)))
(nth (assoc v1057 1056 :last) 1056)
(nth (assoc v1057 500 :mid) 500)
(nth (assoc v1057 1057 :end) 1057)
(assoc v1057 1058 :bad)
(nth v1057 1057)
(nth v40000 39999)
(nth v40000 32768)
(nth v40000 32767)
(reduce + v40000)
(count (pop v40000))
(peek (pop v40000))
(nth (assoc v40000 33000 :x) 33000)
(subvec v1057 1020 1040)
(take 5 (rseq v1057))
(reduce + (subvec v1057 100 900))
(= v1057 (vec (range 1057)))
(= v1057 (range 1057))
(hash v1057)
(hash v33)
(loop [v v1057 n 0] (if (empty? v) n (recur (pop v) (inc n))))
(let [v (reduce conj [] (range 2000))] [(count v) (nth v 1999) (nth v 1056) (hash v)])
(let [v (loop [v v1057 i 0] (if (= i 1000) v (recur (pop v) (inc i))))] [(count v) (peek v) (hash v)])
(count (into v1056 (range 100)))

;; ----- transient vectors
(persistent! (conj! (transient []) 1))
(persistent! (reduce conj! (transient []) (range 40)))
(count (persistent! (reduce conj! (transient []) (range 1100))))
(let [t (transient [1 2 3])] (assoc! t 0 :a) (persistent! t))
(persistent! (assoc! (transient [1 2 3]) 3 :end))
(assoc! (transient [1 2 3]) 5 :x)
(persistent! (pop! (transient [1 2 3])))
(pop! (transient []))
(let [t (transient (vec (range 33)))] (persistent! (pop! t)))
(count (persistent! (pop! (transient v1057))))
(nth (transient [1 2 3]) 1)
(get (transient [1 2 3]) 2)
(count (transient [1 2 3]))
((transient [:a :b]) 1)
(let [t (transient [])] (persistent! t) (conj! t 1))
(let [t (transient [])] (persistent! t) (persistent! t))
(let [t (transient [1])] (persistent! t) (count t))
(let [t (transient [1])] (persistent! t) (nth t 0))
(class (transient []))
(transient '(1 2))

;; ----- lists
'()
'(1 2 3)
(list)
(list 1 2 3)
(list* 1 2 [3 4])
(list* nil)
(list* 1 nil)
(class '())
(class '(1))
(class (list* 1 [2]))
(conj '(1 2) 0)
(conj '() 1 2 3)
(cons 0 '(1 2))
(class (cons 0 '(1 2)))
(peek '(1 2 3))
(pop '(1 2 3))
(pop '(1))
(pop '())
(peek '())
(first '())
(rest '())
(next '())
(count '(1 2 3))
(nth '(1 2 3) 2)
(nth '(1 2 3) 3)
(nth '(1 2 3) 3 :nf)
(get '(1 2 3) 0)
(contains? '(1 2 3) 0)
(empty '(1 2))
(hash '(1 2 3))
(hash '())
(= '(1 2 3) [1 2 3])
(= [1 2 3] '(1 2 3))
(= '() [])
(= '() nil)
(= '() {})
(= [] #{})
(list? '(1))
(list? [1])
(list? (cons 1 nil))
(list? (range 3))
(into '() [1 2 3])

;; ----- maps: array-map and promotion
{}
{:a 1}
(class {})
(class {:a 1 :b 2})
(array-map :b 1 :a 2)
(hash-map :b 1 :a 2)
(class (hash-map))
(def m8 (apply array-map (interleave (map #(keyword (str "k" %)) (range 8)) (range 8))))
m8
(class m8)
(assoc m8 :k8 8)
(class (assoc m8 :k8 8))
(class (assoc m8 8 8))
(class (apply array-map (interleave (map #(keyword (str "k" %)) (range 64)) (range 64))))
(class (zipmap (map #(keyword (str "k" %)) (range 64)) (range 64)))
(class (zipmap (map #(keyword (str "k" %)) (range 65)) (range 65)))
(class (reduce (fn [m i] (assoc m (keyword (str "k" i)) i)) {} (range 64)))
(class (reduce (fn [m i] (assoc m (keyword (str "k" i)) i)) {} (range 65)))
(class (assoc (zipmap (map #(keyword (str "k" %)) (range 20)) (range 20)) "s" 1))
(take 3 (zipmap (map #(keyword (str "k" %)) (range 30)) (range 30)))
(keys (assoc m8 :k8 8))
(def m9 (into {} (map (fn [i] [i (* i i)]) (range 9))))
m9
(class m9)
(into {} (map (fn [i] [i i]) (range 8)))
(class (into {} (map (fn [i] [i i]) (range 8))))
(apply hash-map (range 20))
(zipmap (range 12) (range 12 24))
(zipmap [:a :b :c] [1 2])
(zipmap [] [])
(zipmap [:a :a] [1 2])
(class (dissoc (assoc m8 :k8 8) :k8))
(dissoc (assoc m8 :k8 8) :k8)
(array-map :a 1 :a 2)
{:z 1 :y 2 :x 3 :w 4}
(into {} [[:z 1] [:y 2] [:x 3]])
(hash-map "x" 1 "y" 2 "z" 3 "a" 4 "b" 5 "c" 6 "d" 7 "e" 8 "f" 9)
(into {} (map vector "abcdefghijk" (range)))
(into (sorted-map) (map vector "kjihgfedcba" (range)))

;; ----- map operations
(assoc {} :a 1)
(assoc {:a 1} :a 2)
(assoc {:a 1} :b 2 :c 3)
(assoc nil :a 1)
(dissoc {:a 1 :b 2} :a)
(dissoc {:a 1 :b 2} :a :b :c)
(dissoc {:a 1} :z)
(dissoc nil :a)
(dissoc {:a 1})
(merge {:a 1} {:b 2} {:a 3})
(merge)
(merge nil)
(merge nil {:a 1})
(merge {:a 1} nil)
(merge {:a 1} [:b 2])
(merge-with + {:a 1 :b 2} {:a 10 :c 3} {:a 100})
(merge-with into {:a [1]} {:a [2] :b [3]})
(merge-with + nil nil)
(update {:a 1} :a inc)
(update {:a 1} :b (fnil inc 0))
(update {:a 1} :b inc)
(update {:a [1]} :a conj 2 3 4 5)
(update [1 2 3] 1 * 10)
(update-in {:a {:b {:c 1}}} [:a :b :c] inc)
(update-in {} [:a :b] (fnil conj []) 1)
(update-in {:a [1 2 {:x 1}]} [:a 2 :x] + 100)
(update-in {:a 1} [] identity)
(assoc-in {} [:a :b :c] 1)
(assoc-in {:a [0 1]} [:a 2] 2)
(assoc-in {:a [0 1]} [:a 3] 2)
(assoc-in [] [0 :k] :v)
(assoc-in {:a 1} [:a :b] 2)
(get-in {:a {:b {:c 42}}} [:a :b :c])
(get-in {:a {:b {:c 42}}} [:a :x :c])
(get-in {:a {:b {:c 42}}} [:a :x :c] :nf)
(get-in {:a [10 20]} [:a 1])
(get-in {:a 1} [])
(get-in nil [:a])
(get-in {nil {nil :deep}} [nil nil])
(select-keys {:a 1 :b 2 :c 3} [:a :c :z])
(select-keys {:a 1} [])
(select-keys nil [:a])
(select-keys [10 20 30] [0 2 5])
(group-by even? (range 10))
(group-by count ["a" "bb" "c" "dd" "eee"])
(group-by :k [{:k 1 :v :a} {:k 2 :v :b} {:k 1 :v :c}])
(group-by identity [])
(frequencies [:a :b :a :c :a :b])
(frequencies "mississippi")
(frequencies [])
(keys {:a 1 :b 2})
(vals {:a 1 :b 2})
(keys {})
(vals {})
(keys nil)
(class (keys {:a 1}))
(find {:a 1 :b 2} :a)
(find {:a 1} :z)
(find {:a nil} :a)
(class (find {:a 1} :a))
(key (find {:a 1} :a))
(val (find {:a 1} :a))
(reduce-kv (fn [acc k v] (+ acc v)) 0 {:a 1 :b 2 :c 3})
(reduce-kv (fn [acc k v] (conj acc [v k])) [] {:a 1 :b 2})
(reduce-kv (fn [acc i v] (+ acc (* i v))) 0 [10 20 30])
(reduce-kv (fn [acc k v] (if (= k :b) (reduced k) acc)) nil (array-map :a 1 :b 2 :c 3))
(reduce-kv assoc {} nil)
(into {} [[:a 1] [:b 2]])
(into {} [{:a 1} {:b 2}])
(into {:x 0} {:a 1})
(into {} [[:a 1 2]])
(into {} [:a])
(into {} [[:a]])
(get {:a 1} :a)
(get {:a 1} :b :default)
(get {:a nil} :a :default)
({:a 1} :a)
({:a 1} :b :nf)
(:a {:a 1})
(:b {:a 1} :nf)
(get {[1 2] :vec} '(1 2))
(get {1 :long} 1.0)
(get {1 :long} (int 1))
(get {1.0 :double} 1)
(get {(bigint 1) :big} 1)
(contains? {:a nil} :a)
(contains? {:a 1} :b)
(contains? nil :a)
(count {:a 1 :b 2})
(empty {:a 1})
(empty? {})
(seq {})
(seq {:a 1})
(first {:a 1})
(class (first {:a 1}))
(= {:a 1 :b 2} {:b 2 :a 1})
(= {:a 1} (hash-map :a 1))
(= {1 :a} {1.0 :a})
(= {:a [1 2]} {:a '(1 2)})
(hash {})
(hash {:a 1})
(hash {:a 1 :b 2})
(= (hash {:a 1 :b 2}) (hash (hash-map :b 2 :a 1)))
(hash (into {} (map vector (range 20) (range 20))))
(conj {:a 1} [:b 2])
(conj {:a 1} {:b 2 :c 3})
(conj {:a 1} nil)
(conj {} '(:a 1))
(conj {} [:a 1 :b])
(seq (array-map :c 3 :a 1 :b 2))
(sort (keys (zipmap (range 30) (range 30))))
(map-entry? (first {:a 1}))
(map-entry? [:a 1])
(update-keys {:a 1 :b 2} name)
(update-vals {:a 1 :b 2} inc)
(update-vals {} inc)
(update-keys {1 :a 2 :b} (constantly 0))
(max-key val (first {:a 1}) (first {:b 3}))

;; ----- nil keys and values
{nil 1}
(assoc {} nil :v)
(get {nil :v} nil)
(contains? {nil :v} nil)
(dissoc {nil 1 :a 2} nil)
(assoc (zipmap (range 10) (range 10)) nil :nil)
(get (assoc (zipmap (range 10) (range 10)) nil :nil) nil)
(count (dissoc (assoc (zipmap (range 10) (range 10)) nil :nil) nil))
(find (hash-map nil 1) nil)
(keys (hash-map nil nil))
(persistent! (assoc! (transient (hash-map)) nil 5))
#{nil}
(conj #{1} nil)
(contains? #{nil} nil)
(disj #{nil 1} nil)

;; ----- colliding hashes
(hash "Aa")
(hash "BB")
(= (hash "Aa") (hash "BB"))
(def coll-m (hash-map "Aa" 1 "BB" 2))
(get coll-m "Aa")
(get coll-m "BB")
(count coll-m)
(count (dissoc coll-m "Aa"))
(get (dissoc coll-m "Aa") "BB")
(def big-coll (into (hash-map) (concat (map vector (range 20) (range 20)) [["Aa" :aa] ["BB" :bb] ["AaAa" 1] ["BBBB" 2] ["AaBB" 3] ["BBAa" 4]])))
(map #(get big-coll %) ["Aa" "BB" "AaAa" "BBBB" "AaBB" "BBAa"])
(count big-coll)
(count (reduce dissoc big-coll ["Aa" "AaBB"]))
(get (reduce dissoc big-coll ["Aa" "AaBB"]) "BBAa")
(set (map hash ["AaAa" "BBBB" "AaBB" "BBAa"]))
(count #{"Aa" "BB"})
(disj #{"Aa" "BB"} "Aa")
(= (hash-map "Aa" 1 "BB" 2) (hash-map "BB" 2 "Aa" 1))
(let [t (transient (hash-map))] (persistent! (reduce (fn [t k] (assoc! t k (count k))) t ["Aa" "BB" "AaAa" "BBBB" "C"])))
(= (hash -1) (hash 0))
(hash -1)
(hash 0)
(count (hash-map -1 :a 0 :b))
(hash 1)
(hash (int 1))
(hash 1.0)
(hash (bigint 1))
(hash 1N)
(hash 1M)
(hash "")
(hash nil)
(hash true)
(hash :a)
(hash :a/b)
(hash 'a)
(hash \a)

;; ----- sets
#{}
#{1 2 3}
(hash-set 3 2 1)
(set [1 2 2 3])
(set nil)
(set "hello")
(set {:a 1})
(class #{})
(class (set (range 100)))
(conj #{1 2} 3)
(conj #{1 2} 2)
(disj #{1 2 3} 2)
(disj #{1 2 3} 4)
(disj #{1 2 3} 1 2 3)
(disj nil 1)
(contains? #{1 2} 1)
(contains? #{1 2} 3)
(#{1 2} 1)
(#{1 2} 3)
(#{false nil} false)
(get #{:a} :a)
(get #{:a} :b :nf)
(:a #{:a})
(count #{1 2 3})
(= #{1 2} #{2 1})
(= #{1 2} [1 2])
(= #{1} #{1.0})
(hash #{})
(hash #{1 2 3})
(hash-set 1 1)
(sort (set (range 50)))
(set/union)
(set/union #{1 2} #{2 3})
(set/union #{1} #{2} #{3} #{4})
(set/union #{1} nil)
(set/intersection #{1 2 3} #{2 3 4})
(set/intersection #{1 2 3} #{2 3 4} #{3 4})
(set/intersection #{1} #{2})
(set/difference #{1 2 3} #{2})
(set/difference #{1 2 3} #{2} #{3})
(set/difference #{1 2} #{})
(set/select odd? #{1 2 3 4 5})
(set/select odd? #{})
(def rel #{{:name "a" :age 1 :id 10} {:name "b" :age 2 :id 20} {:name "c" :age 1 :id 30}})
(set/project rel [:name])
(sort-by :id (set/project rel [:id :age]))
(set/rename-keys {:a 1 :b 2} {:a :x})
(set/rename-keys {:a 1 :b 2} {:a :b :b :a})
(set/rename-keys {:a 1} {:z :y})
(sort-by :n (set/rename rel {:name :n}))
(sort-by first (map (fn [[k v]] [(:age k) (sort (map :id v))]) (set/index rel [:age])))
(keys (set/index rel [:age]))
(set/map-invert {:a 1 :b 2})
(set/map-invert {:a 1 :b 1})
(set/map-invert {})
(set/subset? #{1} #{1 2})
(set/subset? #{1 3} #{1 2})
(set/subset? #{} #{})
(set/superset? #{1 2} #{1})
(set/superset? #{1} #{1 2})
(sort-by :id (set/join #{{:id 1 :a 1} {:id 2 :a 2}} #{{:id 1 :b :x}}))
(set/union [1 2] [3])
(set/intersection #{1 2} [2])

;; ----- sorted collections
(sorted-map)
(sorted-map :c 3 :a 1 :b 2)
(sorted-map-by > 1 :a 3 :c 2 :b)
(sorted-map "b" 1 "a" 2 "c" 3)
(class (sorted-map))
(sorted-set 3 1 2)
(sorted-set-by > 3 1 2)
(sorted-set "b" "a" "c" "A")
(sorted-set :b :a :a/b :c)
(sorted-set 1 2.5 1N 3/2)
(sorted-set 1 :a)
(sorted-map 1 :a :b 2)
(conj (sorted-set 1 3) 2)
(disj (sorted-set 1 2 3) 2)
(assoc (sorted-map :a 1) :b 2 :0 0)
(dissoc (sorted-map :a 1 :b 2) :a)
(first (sorted-map :b 2 :a 1))
(last (sorted-map :b 2 :a 1))
(rseq (sorted-map :b 2 :a 1 :c 3))
(rseq (sorted-set 3 1 2))
(subseq (sorted-set 1 2 3 4 5 6) > 2)
(subseq (sorted-set 1 2 3 4 5 6) >= 2 < 5)
(rsubseq (sorted-set 1 2 3 4 5 6) < 4)
(rsubseq (sorted-set 1 2 3 4 5 6) > 1 <= 4)
(subseq (sorted-map :a 1 :b 2 :c 3) > :a)
(subseq (sorted-set) > 1)
(subseq (sorted-set 1 2 3) > 10)
(get (sorted-map :a 1) :a)
(get (sorted-map :a 1) "x")
(contains? (sorted-set 1 2) 2)
(contains? (sorted-set 1 2) :x)
(sorted? (sorted-map))
(sorted? {})
(sorted? (sorted-set))
(sorted? [1 2 3])
(= (sorted-map :a 1 :b 2) {:a 1 :b 2})
(= (sorted-set 1 2) #{1 2})
(hash (sorted-map :a 1))
(hash (sorted-set 1 2 3))
(into (sorted-map) {3 :c 1 :a 2 :b})
(into (sorted-set) [5 3 1 3])
(keys (sorted-map 3 :c 1 :a 2 :b))
(vals (sorted-map 3 :c 1 :a 2 :b))
(empty (sorted-map-by > 1 1))
(assoc (empty (sorted-map-by > 1 1)) 1 1 2 2 3 3)
(take 10 (keys (into (sorted-map) (map vector (range 1000 0 -1) (range)))))
(count (into (sorted-set) (range 500)))
(nth (seq (into (sorted-set) (range 500))) 250)
(sorted-map-by (fn [a b] (compare (count a) (count b))) "aa" 1 "b" 2 "ccc" 3 "dd" 4)
(compare (sorted-set 1) (sorted-set 2))
(sorted-set nil 1)
(sorted-map nil 1 2 3)
(sorted-set [2 1] [1 2] [1])

;; ----- queues
(def q (conj arbace.lang.PersistentQueue/EMPTY 1 2 3))
(seq q)
(peek q)
(seq (pop q))
(seq (conj q 4))
(count q)
(class q)
(peek arbace.lang.PersistentQueue/EMPTY)
(pop arbace.lang.PersistentQueue/EMPTY)
(seq arbace.lang.PersistentQueue/EMPTY)
(= q [1 2 3])
(= q '(1 2 3))
(into [] q)
(hash q)
(vec (pop (pop (pop (pop q)))))
(seq (-> q pop pop (conj 10 11) pop))
(empty q)
(class (empty q))
(seq (into arbace.lang.PersistentQueue/EMPTY (range 40)))
(reduce + (into arbace.lang.PersistentQueue/EMPTY (range 40)))
(sequential? q)
(counted? q)
(reversible? q)
(pr-str q)
(contains? q 1)
(get q 0)
(nth q 0)

;; ----- transients of maps and sets
(persistent! (assoc! (transient {}) :a 1 :b 2))
(persistent! (dissoc! (transient {:a 1 :b 2}) :a))
(persistent! (conj! (transient {}) [:a 1]))
(persistent! (reduce (fn [t i] (assoc! t i i)) (transient {}) (range 20)))
(count (persistent! (reduce (fn [t i] (assoc! t i i)) (transient {}) (range 1000))))
(class (persistent! (reduce (fn [t i] (assoc! t i i)) (transient {}) (range 9))))
(class (persistent! (reduce (fn [t i] (assoc! t i i)) (transient {}) (range 8))))
(persistent! (conj! (transient #{}) 1 2 3))
(persistent! (disj! (transient #{1 2 3}) 2))
(get (transient {:a 1}) :a)
(get (transient #{:a}) :a)
(count (transient {:a 1}))
(contains? (transient #{:x}) :x)
(:a (transient {:a 1}))
(let [t (transient {})] (persistent! t) (assoc! t :a 1))
(let [t (transient #{})] (persistent! t) (conj! t 1))
(transient (sorted-map))
(conj! (transient []) 1 2)
(class (conj!))
(class (conj! (transient [])))
(persistent! (conj!))
(assoc! (transient {}) :a)

;; ----- equality across collection types
(= [1 2] '(1 2))
(= [1 2] (seq [1 2]))
(= [1 2] (range 1 3))
(= [] '())
(= [] nil)
(= {} #{})
(= [[1]] ['(1)])
(= #{[1 2]} #{'(1 2)})
(= {:a 1} (sorted-map :a 1))
(= [1 2] (java.util.ArrayList. [1 2]))
(= #{1 2} (java.util.HashSet. #{1 2}))
(= {:a 1} (java.util.HashMap. {:a 1}))
(= (java.util.ArrayList. [1 2]) [1 2])
(= [1 2] (into-array [1 2]))
(= "ab" [\a \b])
(= (seq "ab") [\a \b])
(defrecord P [x y])
(= (->P 1 2) {:x 1 :y 2})
(= {:x 1 :y 2} (->P 1 2))
(= (->P 1 2) (->P 1 2))
(= (->P 1 2) (map->P {:x 1 :y 2}))
(identical? [] [])
(identical? '() '())
(identical? {} {})
(= 1 1.0)
(== 1 1.0)
(= [1] [1.0])
(= [1] [(int 1)])
(= [1] [1N])

;; ----- empty, not-empty
(empty nil)
(empty "abc")
(empty 1)
(empty (range 3))
(empty (seq [1 2]))
(empty (map inc [1]))
(empty #{1})
(empty (->P 1 2))
(not-empty [])
(not-empty [1])
(not-empty nil)
(not-empty "")
(not-empty "a")
(not-empty {})
(empty? [])
(empty? nil)
(empty? "")
(empty? (range 0))
(empty? 1)

;; ----- into with targets
(into [] '(1 2 3))
(into '() [1 2 3])
(into #{} [1 2 1])
(into {} {:a 1})
(into (sorted-set) [3 1 2])
(into [1] nil)
(into nil [1 2])
(into)
(into [1])
(into [] (map inc) [1 2 3])
(into #{} (filter even?) (range 10))
(into {} (map (fn [[k v]] [v k])) {:a 1 :b 2})
(into (vector-of :int) [1 2 3])
(into [] "abc")
(into [] {:a 1 :b 2})
(meta (into (with-meta [] {:m 1}) [1]))
(meta (into (with-meta {} {:m 1}) {:a 1}))
(into arbace.lang.PersistentQueue/EMPTY [1 2])
(into "" [1])

;; ----- peek/pop of each kind
(peek [1 2])
(peek '(1 2))
(peek (conj arbace.lang.PersistentQueue/EMPTY 1 2))
(peek nil)
(pop nil)
(peek #{1})
(pop {:a 1})
(peek (range 3))
(pop (range 3))
(pop (seq [1 2 3]))
(peek (vector-of :int 5 6))
(pop (vector-of :int 5 6))

;; ----- predicates
(map coll? [[] '() {} #{} nil "s" (range 1) (seq [1]) (->P 1 2) (int-array 1)])
(map seq? [[] '() {} #{} nil "s" (range 1) (seq [1]) (lazy-seq nil) (cons 1 nil)])
(map sequential? [[] '() {} #{} nil "s" (range 1) (seq [1]) (subvec [1] 0)])
(map associative? [[] '() {} #{} nil "s" (->P 1 2) (sorted-map)])
(map counted? [[] '() {} #{} nil "s" (range 1) (seq [1]) (lazy-seq nil) (cons 1 nil) (int-array 1)])
(map reversible? [[] '() {} #{} (sorted-map) (sorted-set) (range 3) (subvec [1] 0)])
(map sorted? [[] {} (sorted-map) (sorted-set) (sorted-map-by >)])
(map seqable? [[] nil "s" 1 :a (int-array 1) (java.util.ArrayList.) {}])
(map indexed? [[] '() (subvec [1 2] 1) "s" (vector-of :int)])
(map ifn? [[] {} #{} :a 'a "s" 1 (->P 1 2) inc])
(map fn? [inc :a [] #'inc])
(map vector? [[] (subvec [1] 0) (vector-of :int) '() (first {:a 1})])
(map map? [{} (sorted-map) (->P 1 2) [] (java.util.HashMap.)])
(map set? [#{} (sorted-set) [] (java.util.HashSet.)])
(map list? ['() (list 1) (cons 1 '()) []])
(map record? [(->P 1 2) {}])
(map nil? [nil false []])
(map some? [nil false []])
(map distinct? [1 2 3] [1 2 1] [:a :b :c])
(distinct? 1)
(distinct? 1 1)
(map boolean [nil false 0 "" []])

;; ----- find, get on vectors, strings, arrays
(find [:a :b :c] 1)
(find [:a :b :c] 3)
(find [:a :b :c] -1)
(find [] 0)
(find [:a] :a)
(class (find [:a :b] 0))
(get "abc" 1)
(get "abc" 3)
(get "abc" -1 :nf)
(get "abc" :a)
(nth "abc" 2)
(nth "abc" 5)
(nth "abc" 5 \z)
(contains? "abc" 2)
(contains? "abc" 3)
(get (int-array [1 2 3]) 1)
(get (int-array [1 2 3]) 5)
(get (object-array [:a :b]) 0)
(get (long-array 3) 1 :nf)
(nth (int-array [7 8]) 1)
(nth (int-array [7 8]) 2)
(contains? (int-array 3) 2)
(get 42 0)
(get nil :a)
(get (java.util.HashMap. {:a 1}) :a)
(get (java.util.ArrayList. [1 2]) 0)
(nth (java.util.ArrayList. [1 2]) 1)
(count "hello")
(count nil)
(count (int-array 7))
(count (java.util.HashMap. {:a 1}))
(count 5)
(count :a)

;; ----- arrays
(vec (into-array [1 2 3]))
(class (into-array [1 2 3]))
(class (into-array ["a" "b"]))
(class (into-array [1 "b"]))
(class (into-array Integer/TYPE [1 2]))
(class (into-array []))
(into-array Long/TYPE [1 2.5])
(vec (into-array String ["a" nil]))
(into-array String [1])
(let [a (int-array 3)] (aset a 1 42) (vec a))
(let [a (object-array 2)] (aset a 0 :x) (vec a))
(let [a (int-array 3)] (aset a 3 1))
(aget (int-array [1 2 3]) 2)
(aget (int-array [1 2 3]) 3)
(aget (int-array [1 2 3]) -1)
(alength (int-array 5))
(alength (object-array 0))
(let [a (int-array [1 2 3]) b (aclone a)] (aset b 0 99) [(vec a) (vec b)])
(vec (amap (int-array [1 2 3]) i ret (* 2 (aget ret i))))
(areduce (int-array [1 2 3 4]) i acc 0 (+ acc (aget (int-array [1 2 3 4]) i)))
(let [a (long-array [1 2 3])] (areduce a i s 0 (+ s (aget a i))))
(vec (to-array [1 2 3]))
(vec (to-array nil))
(vec (to-array "ab"))
(vec (to-array {:a 1}))
(count (to-array-2d [[1 2] [3]]))
(map vec (to-array-2d [[1 2] [3]]))
(vec (int-array 4))
(vec (int-array 3 7))
(vec (int-array [1 2.9 -3.9]))
(vec (long-array 2))
(vec (long-array [1 2 3]))
(vec (long-array 4 [1 2]))
(vec (double-array [1 2]))
(vec (float-array [1.5 2]))
(vec (boolean-array 2))
(vec (boolean-array [true false nil]))
(vec (char-array "abc"))
(vec (char-array 2))
(vec (byte-array [1 2 -1 127]))
(vec (byte-array [128]))
(vec (short-array 2))
(vec (object-array [1 :a "s"]))
(vec (make-array Long/TYPE 3))
(map vec (make-array Integer/TYPE 2 3))
(vec (int-array -1))
(int-array "x")
(seq (int-array 0))
(seq (int-array [5 6]))
(class (seq (int-array [5 6])))
(reduce + (int-array (range 100)))
(apply + (long-array (range 10)))
(vec (aset-int (int-array 2) 0 5))
(let [a (int-array 2)] (aset-int a 0 5) (vec a))
(let [a (double-array 2)] (aset-double a 1 2.5) (vec a))
(let [a (to-array-2d [[1 2] [3 4]])] (aget a 1 0))
(let [a (to-array-2d [[1 2] [3 4]])] (aset a 1 0 :x) (map vec a))
(class (int-array 1))
(class (long-array 1))
(class (double-array 1))
(class (object-array 1))
(class (char-array 1))
(class (make-array String 1))
(.getName (class (make-array Integer/TYPE 1 1)))
(vec (ints (int-array [1])))
(longs (int-array [1]))
(vec (sort (into-array [3 1 2])))
(let [a (into-array [3 1 2])] (java.util.Arrays/sort a) (vec a))
(vec (amap (double-array [1 2]) i r (* 0.5 (aget r i))))
(= (int-array [1 2]) (int-array [1 2]))
(java.util.Arrays/equals (int-array [1 2]) (int-array [1 2]))
(hash (vec (int-array [1 2])))
(vec (into-array (range 40)))
(count (long-array 1000))

;; ----- large maps
(def big (zipmap (range 1000) (map #(* 2 %) (range 1000))))
(count big)
(hash big)
(reduce + (vals big))
(take 10 (sort (keys big)))
(get big 999)
(get big 1000)
(count (dissoc big 0 1 2))
(count (reduce dissoc big (range 500)))
(hash (reduce dissoc big (range 500)))
(= big (into {} (map (fn [i] [i (* 2 i)]) (range 999 -1 -1))))
(def bigs (zipmap (map #(str "key" %) (range 1000)) (range 1000)))
(get bigs "key500")
(hash bigs)
(take 10 (sort (keys bigs)))
(count (set (vals bigs)))
(reduce-kv (fn [a k v] (+ a v (count k))) 0 bigs)
(def bigset (set (map #(keyword (str "kw" %)) (range 1000))))
(count bigset)
(hash bigset)
(contains? bigset :kw999)
(take 5 (sort bigset))
(count (persistent! (reduce dissoc! (transient big) (range 0 1000 2))))
(hash (persistent! (reduce dissoc! (transient big) (range 0 1000 2))))
(count (into {} (map (fn [i] [(keyword (str i)) i]) (range 1000))))
(let [m (reduce (fn [m i] (assoc m (* i 7919) i)) {} (range 3000))] [(count m) (hash m) (get m (* 1234 7919))])
(let [s (reduce conj #{} (map #(str (char (+ 65 (mod % 26))) %) (range 2000)))] [(count s) (hash s)])

;; ----- misc printing of collections
(pr-str [1 "a" \b :c 'd nil true 1.5 1/2 1N 1M])
(str [1 "a" \b])
(print-str [1 "a" \b])
(pr-str {:a "x"})
(str {:a "x"})
(pr-str #{"a"})
(pr-str '(quote x))
(pr-str '(1 (2 (3))))
(pr-str (list))
(pr-str (lazy-seq nil))
(str (lazy-seq [1 2]))
(seq (first {:a 1}))
(vec (first {:a 1}))
(conj (first {:a 1}) :x)
(assoc (first {:a 1}) 0 :b)
(nth (first {:a 1}) 1)
(count (first {:a 1}))
(arbace.lang.MapEntry/create 1 2)
(key [1 2])
