;; Destructuring, macros and their expansions, fns: arities, conditions, recursion, closures.

(require '[arbace.walk :as walk] '[arbace.string :as str])

;; norm: gensym numbers in expansions replaced by N, whatever their prefix
(defn norm [form]
  (walk/postwalk (fn [x] (if (and (symbol? x) (re-find #"\d{2,}" (name x)))
                           (symbol (namespace x) (str/replace (name x) #"\d{2,}" "N"))
                           x))
                 form))

;; ----- sequential destructuring
(let [[a b c] [1 2 3]] [a b c])
(let [[a b c] [1 2]] [a b c])
(let [[a b] [1 2 3 4]] [a b])
(let [[a & r] [1 2 3]] [a r])
(let [[a & r] [1]] [a r])
(let [[a & r] []] [a r])
(let [[a b :as all] [1 2 3]] [a b all])
(let [[a & r :as all] '(1 2 3)] [a r all])
(let [[_ _ c] [1 2 3]] c)
(let [[[a b] [c d]] [[1 2] [3 4]]] [a b c d])
(let [[a [b [c]]] [1 [2 [3]]]] [a b c])
(let [[a b] "xy"] [a b])
(let [[a b & r] "hello"] [a b r])
(let [[a b] nil] [a b])
(let [[a & r] nil] [a r])
(let [[a b] (range)] [a b])
(let [[a b] (java.util.ArrayList. [1 2])] [a b])
(let [[a b] (int-array [7 8])] [a b])
(let [[a b] {:x 1}] a)
(let [[a b] #{1}] a)
(let [[a] 42] a)
(let [[a] :kw] a)
(let [[a & [b c]] [1 2 3]] [a b c])
(let [[a & {:keys [x y]}] [1 :x 10 :y 20]] [a x y])
(let [[a & {:as m}] [1 :x 10]] [a m])
(let [[a & {:keys [x]}] [1 {:x 5}]] [a x])
(let [[& r] (range 3)] r)
(let [[a b] (map (fn [x] (println "item" x) x) '(1 2 3 4))] [a b])
(let [[a & r] (map (fn [x] (println "lazy" x) x) '(1 2 3 4))] a)

;; ----- associative destructuring
(let [{a :a b :b} {:a 1 :b 2}] [a b])
(let [{:keys [a b]} {:a 1 :b 2}] [a b])
(let [{:keys [a b] :or {b 42}} {:a 1}] [a b])
(let [{:keys [a b] :or {b 42}} {:a 1 :b nil}] [a b])
(let [{:keys [a b] :or {b 42}} {:a 1 :b false}] [a b])
(let [{:keys [a] :as m} {:a 1 :z 2}] [a m])
(let [{:strs [a b]} {"a" 1 "b" 2}] [a b])
(let [{:syms [a b]} {'a 1 'b 2}] [a b])
(let [{:keys [x/a b/c]} {:x/a 1 :b/c 2}] [a c])
(let [{:x/keys [a b]} {:x/a 1 :x/b 2 :a 3}] [a b])
(let [{:keys [:a :x/b]} {:a 1 :x/b 2}] [a b])
(let [{:x/syms [a]} {'x/a 1}] a)
(let [{:keys [::a]} {::a 1}] a)
(let [{::keys [a b]} {::a 1 ::b 2}] [a b])
(let [{:keys [a]} nil] a)
(let [{:keys [a]} 1] a)
(let [{:keys [a]} (identity 1)] a)
(let [{:keys [a]} (identity :k)] a)
(let [{:keys [a]} "str"] a)
(let [{:keys [a]} [:a 1]] a)
(let [{:keys [a]} '(:a 1)] a)
(let [{:keys [a]} (list {:a 7})] a)
(let [{:keys [a]} '(:a)] a)
(let [{a 0 b 2} [:x :y :z]] [a b])
(let [{[x y] :point} {:point [1 2]}] [x y])
(let [{{c :c} :b} {:b {:c 3}}] c)
(let [{:keys [a] {:keys [b]} :inner} {:a 1 :inner {:b 2}}] [a b])
(let [{:keys [a b] :or {a b b 2}} {}] [a b])
(let [{:or {a 5} :keys [a]} {}] a)
(let [{:as m} {:a 1}] m)
(let [{:keys [a]} (sorted-map :a 1)] a)
(let [{:keys [x y]} (->> {:x 1 :y 2} (into (sorted-map)))] (+ x y))
(defrecord Pt [x y])
(let [{:keys [x y]} (->Pt 3 4)] (+ x y))
(let [{:keys [a b c]} (java.util.HashMap. {:a 1})] [a b c])

;; ----- fn and defn destructuring, kwargs
(defn kw [a & {:keys [x y] :or {y :dy}}] [a x y])
(kw 1)
(kw 1 :x 2)
(kw 1 :x 2 :y 3)
(kw 1 {:x 2})
(kw 1 {:x 2} :y 3)
(kw 1 :x)
(defn kwm [& {:as opts}] opts)
(kwm)
(kwm :a 1)
(kwm {:a 1})
((fn [[a b] {:keys [c]}] [a b c]) [1 2] {:c 3})
((fn [& [a b]] [a b]) 1)
((fn [{:keys [a] :as m} & more] [a m more]) {:a 1} 2 3)
(map (fn [[k v]] (str k v)) {:a 1 :b 2})
(loop [[x & xs] [1 2 3] acc 0] (if x (recur xs (+ acc x)) acc))
(loop [{:keys [n acc]} {:n 5 :acc 1}] (if (zero? n) acc (recur {:n (dec n) :acc (* acc n)})))
(for [[k v] {:a 1 :b 2}] [v k])
(doseq [{:keys [a]} [{:a 1} {:a 2}]] (println "a" a))
(let [a 1 [a b] [a 2] {a :a} {:a a}] a)
(let [x 1 x (inc x) x (* x 10)] x)
(let [] 1)
(let [a 1])

;; ----- destructuring and binding errors
(let [1 2] 1)
(let [a] a)
(let [{:keys [1]} {}] 1)
(let (a 1) a)
(let [[a & b c] [1 2 3]] a)
(fn [1] 1)
(fn [a & b c] a)
(loop [a] a)

;; ----- user macros and expansion
(defmacro unless [c & body] `(if ~c nil (do ~@body)))
(unless false 1 2)
(unless true 1)
(macroexpand-1 '(unless x (a) (b)))
(macroexpand '(unless x y))
(defmacro twice [x] `(do ~x ~x))
(twice (println "hey"))
(macroexpand-1 '(twice (f)))
(defmacro my-let1 [v e & body] `(let [~v ~e] ~@body))
(my-let1 q 5 (* q q))
(defmacro with-tmp [& body] `(let [tmp# 10] (+ tmp# ~@body)))
(with-tmp 1 2)
(norm (macroexpand-1 '(with-tmp 1)))
(let [[_ [g]] (macroexpand-1 '(with-tmp 1))] (str/starts-with? (name g) "tmp__"))
(let [[_ [g1] [_ g2]] (macroexpand-1 '(with-tmp 1))] (= g1 g2))
(defmacro sq [] `(list a b/c :k ::k "s" 1 ~'raw))
(macroexpand-1 '(sq))
`foo
`(foo bar/baz ~(+ 1 2) ~@[4 5])
`[1 ~@(range 3) :x]
`{:a ~(inc 1)}
`#{~(inc 1)}
`(1 `(2 ~(3 ~(+ 1 3))))
`nil
`"str"
`:kw
`map
`if
`String
`java.util.List
`Pt
`Pt.
`.method
`arbace.core/inc
`(~'x ~@nil)
(let [x 5] `(a ~x))
(let [xs [1 2]] `(a ~@xs ~xs))
(defmacro arity2 [a b] [a b])
(arity2 1 2)
(arity2 1)
(macroexpand-1 '(arity2 1 2 3))
(defmacro show-form [& args] `'~&form)
(show-form 1 (+ 2 3))
(defmacro form-line [] (some? (:line (meta &form))))
(form-line)
(defmacro locals [] `'~(vec (sort (map str (keys &env)))))
(locals)
(let [a 1 b 2] (locals))
(fn? (let [a 1] (fn [z] (let [c 3] (locals)))))
((let [a 1] (fn [z] (let [c 3] (locals)))) 0)
(defmacro mm [x] (if (symbol? x) `(quote ~x) x))
(mm abc)
(mm (+ 1 2))
(macroexpand '(mm abc))
(defmacro thrower [] (throw (IllegalStateException. "macro boom")))
(thrower)
(fn [] (thrower))
(defmacro ^:private priv-mac [] 1)
(priv-mac)
(:macro (meta #'unless))
(:macro (meta #'when))
(:macro (meta #'map))
(macroexpand '(fn [x] x))
(macroexpand-1 'not-a-macro)
(macroexpand-1 '(not-a-macro 1))
(macroexpand-1 '(.toString x))
(macroexpand-1 '(String. "a"))
(macroexpand-1 '(Math/abs -1))
(macroexpand-1 '(String/.length "a"))
(macroexpand '(-> a b))
(macroexpand-1 '[when x])
(macroexpand-1 1)

;; ----- core macro expansions
(macroexpand-1 '(-> x f (g a) (h b c)))
(macroexpand-1 '(-> x))
(macroexpand-1 '(-> x :k))
(macroexpand-1 '(->> x f (g a) (h b c)))
(macroexpand '(->> (range 10) (map inc) (filter odd?)))
(-> 5 (- 1) (* 2))
(->> 5 (- 1) (* 2))
(-> {:a {:b 1}} :a :b)
(-> [1 2] (conj 3) count)
(macroexpand-1 '(when x a b))
(macroexpand-1 '(when-not x a))
(macroexpand-1 '(if-not x a b))
(norm (macroexpand-1 '(when-let [a (f)] (g a))))
(norm (macroexpand-1 '(if-let [a (f)] (g a) :else)))
(norm (macroexpand-1 '(when-some [a (f)] (g a))))
(norm (macroexpand-1 '(if-some [a (f)] a b)))
(when-let [a nil] :never)
(when-let [a false] :never)
(when-let [a 0] [:got a])
(if-let [a nil] :then :else)
(if-let [[x y] [1 2]] (+ x y) :no)
(if-let [a false] :then)
(if-some [a false] [:then a] :else)
(when-some [a nil] :never)
(when-let [a 1 b 2] a)
(norm (macroexpand-1 '(when-first [x xs] x)))
(macroexpand-1 '(cond a 1 b 2 :else 3))
(macroexpand '(cond a 1))
(macroexpand-1 '(cond))
(cond false 1 nil 2)
(cond :x 1)
(cond false 1 :else 2)
(cond 1)
(norm (macroexpand-1 '(condp = x 1 :one 2 :two :other)))
(condp = 2 1 :one 2 :two :other)
(condp = 3 1 :one :other)
(condp = 3 1 :one)
(condp some [1 2 3] #{0 6} :> inc #{4 3} :>> dec :none)
(condp < 5 10 :a 3 :b)
(condp get :k {:z 1} :>> identity {:k 2} :>> identity)
(norm (macroexpand-1 '(cond-> x a (f) b (g 1))))
(cond-> 1 true inc false (* 100) true (* 2))
(cond->> [1 2] true (map inc) false (map dec))
(cond-> {} true (assoc :a 1) nil (assoc :b 2))
(norm (macroexpand-1 '(some-> x f (g 1))))
(some-> {:a {:b 1}} :a :b inc)
(some-> {:a nil} :a :b inc)
(some->> [1 2] (map inc) (reduce +))
(some->> nil (map inc))
(norm (macroexpand-1 '(as-> x $ (f $) (g $ 1))))
(as-> 5 v (inc v) (* v v) (- v 1))
(as-> [1 2] [a b] [b a])
(norm (macroexpand-1 '(doto (java.util.ArrayList.) (.add 1) (.add 2))))
(doto (java.util.ArrayList.) (.add 1) (.add 2))
(doto (java.util.HashMap.) (.put :a 1))
(doto 5)
(macroexpand-1 '(and a b c))
(macroexpand-1 '(and))
(norm (macroexpand-1 '(or a b)))
(and 1 2 nil 3)
(and)
(or nil false)
(or)
(or nil 0)
(and true false)
(macroexpand-1 '(.. a (b c) d))
(.. "abc" (toUpperCase) (substring 1))
(macroexpand-1 '(comment anything (+ 1 2)))
(comment (/ 1 0))
(norm (macroexpand-1 '(dotimes [i 3] (f i))))
(norm (macroexpand-1 '(while (pred) (f))))
(let [a (atom 3)] (while (pos? @a) (println "w" @a) (swap! a dec)))
(macroexpand-1 '(letfn [(f [x] (g x)) (g [y] y)] (f 1)))
(norm (macroexpand-1 '(with-open [r (open)] (read r))))
(macroexpand-1 '(declare a b))
(macroexpand-1 '(defn f [x] x))
(macroexpand-1 '(defn f "doc" ([x] x) ([x y] y)))
(macroexpand-1 '(defn- p [] 1))
(macroexpand-1 '(defmacro m [x] x))
(macroexpand-1 '(fn f [x] x))
(norm (macroexpand-1 '(fn [[a]] a)))
(norm (macroexpand '(let [[a b] v] a)))
(norm (macroexpand '(let [{:keys [a]} m] a)))
(macroexpand-1 '(assert x))
(macroexpand-1 '(assert x "msg"))
(macroexpand-1 '(time x))
(macroexpand-1 '(binding [*x* 1] (f)))
(macroexpand-1 '(with-redefs [f g] (h)))
(macroexpand-1 '(delay (f)))
(macroexpand-1 '(lazy-seq (f)))
(macroexpand-1 '(defonce x 1))
(macroexpand-1 '(when-not x))
(macroexpand-1 '(case))

;; ----- case
(case 1 1 :one 2 :two :default)
(case 3 1 :one 2 :two :default)
(case 3 1 :one 2 :two)
(case "b" "a" 1 "b" 2)
(case :k :j 1 :k 2)
(case 'sym sym :symbol other :other)
(case [1 2] [1 2] :vec 3)
(case '(1 2) [1 2] :vec 3)
(case 2 (1 2 3) :small (4 5) :big)
(case 'x (x y) :xy :other)
(case nil nil :nil :other)
(case \a \a :char :other)
(case 1.0 1.0 :double :other)
(case 1 1.0 :double :other)
(case (int 1) 1 :one :other)
(case 1N 1 :one :other)
(case "Aa" "Aa" :aa "BB" :bb :none)
(case "BB" "Aa" :aa "BB" :bb :none)
(case "Cc" "Aa" :aa "BB" :bb :none)
(case 1 1 :a 1 :b)
(case 5 0 :z 100 :h 1000000 :m :d)
(case 1000000 0 :z 100 :h 1000000 :m :d)
(case -1 -1 :neg 0 :zero 1 :pos)
(case 2 -1 :neg 0 :zero 1 :pos)
(case {:a 1} {:a 1} :map :other)
(case #{1} #{1} :set :other)
(case true true :t false :f)
(case false true :t false :f)
(case 'foo/bar foo/bar :q :other)
(case :a/b :a/b :ns-kw :b :plain)
(case 10 (10 20) :tens (1 2) :ones)
(let [x 3] (case x 1 :a (2 3) :b :c))
(case (+ 1 1) 2 :computed)
(macroexpand-1 '(case x 1 :a :d))
(norm (macroexpand-1 '(case x "a" 1 "b" 2 :d)))
(case 1 (quote 1) :q :d)
(case 'quote (quote 1) :q :d)

;; ----- for, doseq, dotimes
(for [x (range 5) :when (odd? x)] x)
(for [x (range 10) :while (< x 3)] x)
(for [x (range 3) :let [y (* x x)]] [x y])
(for [x (range 4) :let [y (* 2 x)] :when (> y 2) z [:a :b]] [x y z])
(for [x [1 2 3] y [1 2 3] :while (< y x)] [x y])
(for [x [1 2 3] :while (< x 3) y [:a]] [x y])
(for [x []] x)
(for [x [1] y []] [x y])
(for [[k v] (sorted-map :b 2 :a 1)] (str k v))
(take 3 (for [x (range) y (range x)] [x y]))
(for [x (range 3) :when (odd? x) :let [z (inc x)]] z)
(count (for [a (range 10) b (range 10) c (range 10)] 1))
(class (for [x [1]] x))
(doseq [x (range 3) :when (odd? x)] (println x))
(doseq [x (range 10) :while (< x 2)] (println "dw" x))
(doseq [x [1 2] :let [y (* x 10)]] (println y))
(doseq [x []] (println x))
(doseq [x (range 40)] (when (> x 37) (print x)))
(dotimes [i 0] (println i))
(dotimes [i -2] (println i))
(dotimes [_ 2] (print "."))
(let [v (volatile! [])] (doseq [a [1 2] b [3 4]] (vswap! v conj (* a b))) @v)
(for [x 1] x)
(for [x [1] :bad 1] x)

;; ----- letfn, with-open
(letfn [(ev? [n] (if (zero? n) true (od? (dec n)))) (od? [n] (if (zero? n) false (ev? (dec n))))] [(ev? 10) (od? 7) (ev? 3)])
(letfn [(f [] 1)] (f))
(letfn [(f ([] (f 1)) ([x] (* x 10)))] (f))
(letfn [] 1)
(with-open [r (java.io.StringReader. "hello")] (.read r))
(with-open [r (java.io.BufferedReader. (java.io.StringReader. "l1\nl2"))] (vec (line-seq r)))
(with-open [a (java.io.StringReader. "a") b (java.io.StringReader. "b")] (str (char (.read a)) (char (.read b))))
(let [r (java.io.StringReader. "x")] (with-open [r2 r] (.read r2)) (.read r))
(with-open [r (java.io.StringReader. "x")] (throw (ex-info "inside" {})))
(with-open [] 5)
(with-open [x 1] x)

;; ----- defn: conditions, arities
(defn pos-only [x] {:pre [(pos? x)]} x)
(pos-only 1)
(pos-only -1)
(defn small-result [x] {:post [(< % 10)]} (* x 2))
(small-result 2)
(small-result 20)
(defn both [x y] {:pre [(number? x) (number? y)] :post [(pos? %)]} (- x y))
(both 5 2)
(both "a" 2)
(both 1 2)
(defn pre-msg [x] {:pre [(string? x)]} x)
(pre-msg 1)
(binding [*assert* false] (eval '(defn no-assert [x] {:pre [(pos? x)]} x)))
(no-assert -5)
(defn just-map [x] {:pre [(pos? x)]})
(just-map 1)
(defn map-body [x] {:a x})
(map-body 1)
(defn multi ([] :zero) ([a] [:one a]) ([a b] [:two a b]) ([a b & more] [:many a b more]))
(multi)
(multi 1)
(multi 1 2)
(multi 1 2 3 4)
(defn fixed2 [a b] [a b])
(fixed2 1)
(fixed2 1 2 3)
(fixed2)
(apply fixed2 (range 5))
(defn var1 [a & r] [a r])
(var1)
(var1 1)
(var1 1 2)
(defn arity-msg [f & args] (try (apply f args) (catch arbace.lang.ArityException e (str/replace (ex-message e) #"(eval|--)\d+" "$1N"))))
(arity-msg (fn [] 1) 2)
(arity-msg (fn named [x] x))
(arity-msg (fn [x y] x) 1)
(arity-msg (fn ([x] x) ([x y z] x)) 1 2)
(arity-msg (fn [x & y] x))
(arity-msg #(+ %1 %2) 1)
(arity-msg (fn* [] 1) 1)
((fn [& r] r))
((fn [a b c d e f g h i j k l m n o p q r s t] t) 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20)
(arity-msg (fn [a b c d e f g h i j k l m n o p q r s t] t) 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21)
((fn [a b c d e f g h i j k l m n o p q r s t & u] u) 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22)
(fn ([a] 1) ([b] 2))
(fn ([a & b] 1) ([a b & c] 2))
(fn ([a b] 1) ([a & c] 2))
(defn doc-fn "the doc" {:added "x"} [a] a)
(:doc (meta #'doc-fn))
(:added (meta #'doc-fn))
(:arglists (meta #'doc-fn))
(:arglists (meta #'multi))
(defn ^:private hidden [] :h)
(:private (meta #'hidden))
(defn typed ^long [^long x] (inc x))
(typed 5)
(:arglists (meta #'typed))
(defn ^String tagged [] "s")
(:tag (meta #'tagged))
(tagged)
(defn with-attr-map ([a] a) {:extra 1})
(:extra (meta #'with-attr-map))
(defn)
(defn bad-params x)

;; ----- recur
(loop [i 0 acc []] (if (< i 5) (recur (inc i) (conj acc i)) acc))
(defn count-down [n] (if (pos? n) (recur (dec n)) :done))
(count-down 100000)
((fn [n acc] (if (zero? n) acc (recur (dec n) (* acc n)))) 20 1)
((fn [& xs] (if (seq xs) (recur (next xs)) :end)) 1 2 3)
((fn [a & xs] (if (seq xs) (recur (+ a (first xs)) (next xs)) a)) 1 2 3 4)
(fn [x] (recur 1 2))
(loop [a 1] (recur))
(loop [a 1] (+ 1 (recur 2)))
(fn [x] (if x (recur x) (do (recur x) 1)))
(loop [x 1] (fn [] (recur 2)))
(recur 1)
(loop [i 0] (when (< i 3) (println "loop" i) (recur (inc i))))
(loop [x (int 0)] (if (< x 5) (recur (inc x)) x))
(loop [x 0.5] (if (< x 4) (recur (* x 2)) x))
(let [x 1] (loop [] (if false (recur) x)))
(loop [[f & r] [1 2 3] out ()] (if f (recur r (cons f out)) out))

;; ----- fn names, self recursion, closures
(defn fact [n] (if (<= n 1) 1 (*' n (fact (dec n)))))
(fact 20)
(fact 25)
((fn fib [n] (if (< n 2) n (+ (fib (- n 1)) (fib (- n 2))))) 20)
(let [f (fn me [n] (if (zero? n) [] (conj (me (dec n)) n)))] (f 4))
(defn make-counter [] (let [n (atom 0)] (fn [] (swap! n inc))))
(let [c (make-counter)] (c) (c) (c))
(let [c1 (make-counter) c2 (make-counter)] (c1) (c1) [(c1) (c2)])
(let [adders (map (fn [i] (fn [x] (+ x i))) (range 3))] (map #(% 10) adders))
(let [x 1 f (fn [] x) x 2] [(f) x])
(def fs (vec (for [i (range 3)] (fn [] i))))
(map #(%) fs)
(let [y 5] ((fn [x] (+ x y)) 1))
(#(+ %1 %2) 1 2)
(#(vector %1 %&) 1 2 3)
(#(vector % %2) 1 2)
(#(list %&))
(#(do %3) 1 2 3)
(#(identity %) 9)
(map #(* 2 %) [1 2])
(#(%2) 1 (constantly :c))
(macroexpand-1 '#(+ % %2))
(norm '#(+ % %2 %&))

;; ----- trampoline, memoize
(declare t-odd?)
(defn t-even? [n] (if (zero? n) true #(t-odd? (dec n))))
(defn t-odd? [n] (if (zero? n) false #(t-even? (dec n))))
(trampoline t-even? 10000)
(trampoline t-odd? 10001)
(trampoline (fn [] 5))
(trampoline + 1 2)
(trampoline (fn [] (fn [] (fn [] :deep))))
(def calls (atom 0))
(def slow-sq (memoize (fn [x] (swap! calls inc) (* x x))))
[(slow-sq 4) (slow-sq 4) (slow-sq 5) @calls]
(def mfib (memoize (fn [n] (if (< n 2) n (+' (mfib (- n 1)) (mfib (- n 2)))))))
(mfib 80)
(let [m (memoize (fn [& args] (println "computing" args) (count args)))] [(m) (m) (m 1 2) (m 1 2) (m nil)])
(let [m (memoize (fn [x] (println "nil-memo") nil))] [(m 1) (m 1)])
