;; java.io.File and the file system, arbace.java.io on files and file: URLs, java.net.URL, and
;; java.nio.file's Path and Files (doc/go/JRT-NOTES.md, "Files"). The results do not depend on
;; where or when the run is: path arithmetic on fixed strings, and the file system in a
;; temporary directory made for the run, whose own path never shows (DIR in messages), removed
;; at the end.

(require '[arbace.java.io :as io])
(import '(java.io File FileInputStream FileOutputStream FileReader FileWriter BufferedReader
                  FileNotFoundException IOException)
        '(java.net URL URI MalformedURLException)
        '(java.nio.file Files Path Paths LinkOption OpenOption StandardOpenOption CopyOption
                        StandardCopyOption NoSuchFileException FileAlreadyExistsException
                        DirectoryNotEmptyException)
        '(java.nio.file.attribute FileAttribute))

;; ----- File: path arithmetic, no file system
(.getPath (File. "a//b/"))
(.getPath (File. "/"))
(.getPath (File. ""))
(.getPath (File. "//x///y//"))
(.getName (File. "/x/y/z.txt"))
(.getName (File. "z"))
(.getName (File. "/"))
(.getParent (File. "/x/y/z.txt"))
(.getParent (File. "z.txt"))
(.getParent (File. "/z"))
(.getParent (File. "/"))
(.getPath (.getParentFile (File. "a/b/c")))
(.isAbsolute (File. "/a"))
(.isAbsolute (File. "a"))
(.isAbsolute (File. ""))
(.getPath (File. "/a" "b"))
(.getPath (File. "/a/" "/b/"))
(.getPath (File. "/" "b"))
(.getPath (File. "a" ""))
(.getPath (File. "" "b"))
(.getPath (File. ^File (File. "a") "b"))
(let [^File n nil] (.getPath (File. n "b")))
(let [^String n nil] (.getPath (File. n "b")))
(str (File. "a/b/../c"))
(= (File. "a") (File. "a"))
(= (File. "a") (File. "a/"))
(= (File. "a") (File. "b"))
(compare (File. "a") (File. "b"))
(compare (File. "b") (File. "a"))
(.compareTo (File. "abc") (File. "abd"))
(.hashCode (File. "abc"))
(.hashCode (File. "/x/y"))
(hash (File. "abc"))
File/separator
File/separatorChar
File/pathSeparator
File/pathSeparatorChar
(.getPath (File. (URI. "file:/x/y%20z")))
(.getPath (File. (URI. "file:/x/y/")))
(try (File. (URI. "http://h/x")) (catch IllegalArgumentException e (.getMessage e)))
(try (File. (URI. "file:x")) (catch IllegalArgumentException e (.getMessage e)))
(try (let [^String n nil] (File. n)) (catch NullPointerException e :npe))
(str (.toURI (File. "/nonexistent-oracle/a b")))
(str (.toURI (File. "/nonexistent-oracle/c%d#e")))
(str (.toURL (File. "/nonexistent-oracle/x y")))
(.getPath (.getAbsoluteFile (File. "/a/./b")))
(.exists (File. "/nonexistent-oracle/x"))
(.isDirectory (File. "/nonexistent-oracle/x"))
(.isFile (File. "/nonexistent-oracle/x"))
(.length (File. "/nonexistent-oracle/x"))
(.lastModified (File. "/nonexistent-oracle/x"))
(.list (File. "/nonexistent-oracle/x"))
(.listFiles (File. "/nonexistent-oracle/x"))
(.delete (File. "/nonexistent-oracle/x"))
(.mkdir (File. "/nonexistent-oracle/x/y"))
(.canRead (File. "/nonexistent-oracle/x"))
(.isDirectory (File. "/"))
(.exists (File. "/"))
(.getPath (.getCanonicalFile (File. "/")))
(.getCanonicalPath (File. "/nonexistent-oracle/a/../b/./c"))
(.getCanonicalPath (File. "/nonexistent-oracle/../x"))
(.getCanonicalPath (File. "/../.."))
(vec (map str (File/listRoots)))
(.isHidden (File. "/x/.hidden"))
(.isHidden (File. "/x/shown"))

;; ----- arbace.java.io: coercions, no file system
(io/file "a")
(str (io/file "a" "b" "c"))
(str (io/file (File. "a") "b"))
(io/file nil)
(= (File. "foo/bar/baz") (io/file "foo" "bar" "baz"))
(io/as-relative-path "foo")
(io/as-relative-path (File. "bar"))
(try (io/as-relative-path (File. "/abs")) (catch IllegalArgumentException e (.getMessage e)))
(try (io/file "a" "/b") (catch IllegalArgumentException e (.getMessage e)))
(io/as-file "foo")
(io/as-file nil)
(io/as-file (URL. "file:baz"))
(io/as-file (URL. "file:bar+baz"))
(io/as-file (URL. "file:bar%20baz%20qux"))
(io/as-file (URI. "file:quux"))
(io/as-file (URL. "file:abc%c3%add/foo.txt"))
(try (io/as-file (URL. "http://example.com/x")) (catch IllegalArgumentException e (.getMessage e)))
(io/as-url nil)
(str (io/as-url "file:foo"))
(str (io/as-url (URL. "file:baz")))
(str (io/as-url (URI. "file:quux")))
(str (io/as-url (File. "/nonexistent-oracle/f")))
(= (URL. "file:foo") (io/as-url "file:foo"))
(try (io/as-url "no-protocol") (catch MalformedURLException e (.getMessage e)))
(try (io/reader nil) (catch IllegalArgumentException e (.getMessage e)))
(try (io/output-stream nil) (catch IllegalArgumentException e (.getMessage e)))
(try (slurp "/nonexistent-oracle/whitespace = #'\\s+'") (catch FileNotFoundException e (.getMessage e)))
(try (slurp "/nonexistent-oracle/x") (catch FileNotFoundException e (.getMessage e)))
(try (slurp (URL. "file:/nonexistent-oracle/x")) (catch FileNotFoundException e (.getMessage e)))

;; ----- java.net.URL
(str (URL. "file:/a/b?q#r"))
(str (URL. "FILE:/a"))
(str (URL. "file:///a/b"))
(str (URL. "file://localhost/a/b"))
(let [u (URL. "http://User@Example.com:8080/p/a.txt?x=1#f")]
  [(.getProtocol u) (.getHost u) (.getPort u) (.getDefaultPort u) (.getPath u) (.getQuery u)
   (.getRef u) (.getUserInfo u) (.getAuthority u) (.getFile u) (.toExternalForm u)])
(let [u (URL. "https://example.com/")] [(.getPort u) (.getDefaultPort u) (.getPath u)])
(let [u (URL. "jar:file:/x/y.jar!/a/b.clj")] [(.getProtocol u) (.getPath u) (.getFile u) (str u)])
(let [u (URL. "file:a/b")] [(.getHost u) (.getPath u) (.getAuthority u)])
(str (URL. (URL. "file:/a/b/c") "../d"))
(str (URL. (URL. "file:/a/b/c") "d?e#f"))
(str (URL. (URL. "http://h/a/b") "/x"))
(str (URL. (URL. "http://h/a/b") "//g/y"))
(str (URL. "file" "" "/a b"))
(str (URL. "http" "h" 81 "/p"))
(= (URL. "file:/a") (URL. "file:/a"))
(= (URL. "file:/a") (URL. "file:/b"))
(= (URL. "file:/a") (URL. "file://localhost/a"))
(= (URL. "file:/a#x") (URL. "file:/a"))
(.sameFile (URL. "file:/a#x") (URL. "file:/a"))
(.hashCode (URL. "file:/a"))
(.hashCode (URL. "file:/a/b?q#r"))
(.hashCode (URL. "file://localhost/a"))
(str (.toURI (URL. "file:/a/b")))
(try (URL. "nope") (catch MalformedURLException e (.getMessage e)))
(try (URL. "zzz:x") (catch MalformedURLException e (.getMessage e)))
(try (URL. "http://h:x/") (catch MalformedURLException e (.getMessage e)))
(try (let [^String n nil] (URL. n)) (catch MalformedURLException e :malformed))
(java.net.URLDecoder/decode "a%20b+c%c3%a9" "UTF-8")
(try (java.net.URLDecoder/decode "a%2" "UTF-8") (catch IllegalArgumentException e (.getMessage e)))
(java.net.URLConnection/guessContentTypeFromName "x.zzzz")

;; ----- java.nio.file.Path: path arithmetic, no file system
(defn p [s & more] (Path/of s (into-array String more)))
(str (p "a" "b" "c"))
(str (p "/a//b/"))
(str (p ""))
(str (p "a" "" "b"))
(str (Paths/get "x" (into-array String ["y"])))
(.isAbsolute (p "/a"))
(.isAbsolute (p "a"))
(.getNameCount (p "/a/b/c"))
(.getNameCount (p "/"))
(.getNameCount (p ""))
(str (.getName (p "/a/b/c") 1))
(str (.getFileName (p "/a/b/c")))
(.getFileName (p "/"))
(str (.getFileName (p "")))
(str (.getParent (p "/a/b/c")))
(str (.getParent (p "/a")))
(.getParent (p "a"))
(str (.getRoot (p "/a")))
(.getRoot (p "a"))
(str (.subpath (p "/a/b/c/d") 1 3))
(try (.subpath (p "/a/b") 1 1) (catch IllegalArgumentException e :iae))
(str (.normalize (p "/a/./b/../c")))
(str (.normalize (p "a/../../b")))
(str (.normalize (p "/../a")))
(str (.normalize (p "a/..")))
(str (.normalize (p "./a/./")))
(str (.resolve (p "/a") "b"))
(str (.resolve (p "/a") "/b"))
(str (.resolve (p "/a") ""))
(str (.resolve (p "") "b"))
(str (.resolve (p "/") "b"))
(str (.resolveSibling (p "/a/b") "c"))
(str (.relativize (p "/a/b") (p "/a/c/d")))
(str (.relativize (p "/a/b/c") (p "/a")))
(str (.relativize (p "a") (p "a")))
(str (.relativize (p "a/b") (p "a/b/c")))
(try (.relativize (p "/a") (p "b")) (catch IllegalArgumentException e (.getMessage e)))
(.startsWith (p "/a/b") "/a")
(.startsWith (p "/a/b") "/a/b")
(.startsWith (p "/a/bc") "/a/b")
(.startsWith (p "a/b") "/a")
(.endsWith (p "/a/b") "b")
(.endsWith (p "/a/b") "a/b")
(.endsWith (p "/a/b") "/a/b")
(.endsWith (p "/a/bc") "c")
(= (p "/a/b") (p "/a//b/"))
(= (p "a") (p "b"))
(compare (p "a") (p "b"))
(.hashCode (p "/a/b"))
(mapv str (seq (p "/a/b/c")))
(str (.toUri (p "/nonexistent-oracle/a b")))
(.toFile (p "/nonexistent-oracle/x"))
(str (.toPath (File. "/nonexistent-oracle/y")))
(= (.toPath (File. "a/b")) (p "a" "b"))
(str (Path/of (URI. "file:///nonexistent-oracle/z/")))
(try (p "a\u0000b") (catch java.nio.file.InvalidPathException e (.getMessage e)))

;; ----- the file system, in a directory of its own
(def dir (.toFile (Files/createTempDirectory "oracle-files" (into-array FileAttribute []))))
(defn hide [s] (.replace (str s) (.getPath dir) "DIR"))
(.isDirectory dir)
(.startsWith (.getName dir) "oracle-files")
(vec (.list dir))
(def f (File. dir "a.txt"))
(.exists f)
(.createNewFile f)
(.createNewFile f)
(.length f)
(spit f "héllo\nwörld\n")
[(.exists f) (.isFile f) (.isDirectory f) (.length f)]
[(.canRead f) (.canWrite f) (.canExecute f)]
(slurp f)
(slurp (.getPath f))
(slurp (str "file:" (.getPath f)))
(slurp (.toURI f))
(slurp (io/as-url f))
(slurp f :encoding "ISO-8859-1")
(with-open [r (io/reader f)] (doall (line-seq r)))
(with-open [r (BufferedReader. (FileReader. f))] (.readLine r))
(with-open [s (io/input-stream f)] (.read s))
(spit f "more\n" :append true)
(slurp f)
(with-open [w (FileWriter. f)] (.write w "via FileWriter"))
(slurp f)
(with-open [w (io/writer f :append true)] (.write w "!"))
(slurp f)
(spit (.getPath f) "by path")
(slurp f)
(spit (io/as-url f) "by url")
(slurp f)
(.setLastModified f 1000000000000)
(.lastModified f)
(.setLastModified f 1234567890123)
(.lastModified f)
(.setExecutable f true)
(.canExecute f)
(.setExecutable f false)
(.canExecute f)
(.setReadOnly f)
(.setWritable f true)
(.canWrite f)
(def g (File. dir "sub/deeper"))
(.mkdir g)
(.mkdirs g)
(.mkdirs g)
(.isDirectory g)
(.exists (File. dir "sub"))
(io/make-parents dir "p" "q" "r.txt")
(.isDirectory (File. dir "p/q"))
(.exists (File. dir "p/q/r.txt"))
(vec (sort (.list dir)))
(vec (sort (map #(.getName ^File %) (.listFiles dir))))
(vec (sort (map #(.getName ^File %) (.listFiles dir (reify java.io.FileFilter (accept [_ x] (.isDirectory ^File x)))))))
(vec (sort (.list dir (reify java.io.FilenameFilter (accept [_ d n] (.endsWith ^String n ".txt"))))))
(.length (File. dir "sub"))
(.renameTo f (File. dir "b.txt"))
(.exists f)
(slurp (File. dir "b.txt"))
(io/copy (File. dir "b.txt") (File. dir "c.txt"))
(slurp (File. dir "c.txt"))
(io/copy "text" (File. dir "d.txt"))
(slurp (File. dir "d.txt"))
(io/copy (.getBytes "bytes") (File. dir "d.txt"))
(slurp (File. dir "d.txt"))
(let [o (java.io.ByteArrayOutputStream.)] (io/copy (File. dir "d.txt") o) (String. (.toByteArray o)))
(.delete (File. dir "sub"))
(.delete (File. dir "nope"))
(io/delete-file (File. dir "nope") :silently)
(try (io/delete-file (File. dir "nope")) (catch IOException e (hide (.getMessage e))))
(try (FileInputStream. (File. dir "nope")) (catch FileNotFoundException e (hide (.getMessage e))))
(try (FileInputStream. dir) (catch FileNotFoundException e (hide (.getMessage e))))
(try (FileOutputStream. (File. dir "nope/x")) (catch FileNotFoundException e (hide (.getMessage e))))
(let [t (File/createTempFile "pre" ".suf" dir)]
  [(.startsWith (.getName t) "pre") (.endsWith (.getName t) ".suf") (.length t) (.exists t)
   (= (.getParentFile t) dir)])
(let [t (File/createTempFile "pre" nil dir)] (.endsWith (.getName t) ".tmp"))
(try (File/createTempFile "ab" nil) (catch IllegalArgumentException e (.getMessage e)))
(.getName (.getCanonicalFile (File. dir "p/q/../q/./")))
(= (.getCanonicalPath (File. dir "p/../b.txt")) (.getCanonicalPath (File. dir "b.txt")))
(hide (.getCanonicalPath (File. dir "p/missing/../../b.txt")))
(pos? (.getTotalSpace dir))
(<= (.getUsableSpace dir) (.getFreeSpace dir) (.getTotalSpace dir))
(.getTotalSpace (File. dir "nope"))

;; ----- java.nio.file.Files
(def e (.toPath (File. dir "e.txt")))
(str (.getFileName e))
(= (.toFile e) (File. dir "e.txt"))
(Files/exists e (into-array LinkOption []))
(Files/notExists e (into-array LinkOption []))
(= e (Files/writeString e "line1\nline2" (into-array OpenOption [])))
(Files/exists e (into-array LinkOption []))
(Files/readString e)
(vec (Files/readAllLines e))
(with-open [r (Files/newBufferedReader e)] (vec (line-seq r)))
(vec (Files/readAllBytes e))
(Files/size e)
(Files/isRegularFile e (into-array LinkOption []))
(Files/isDirectory e (into-array LinkOption []))
(Files/isDirectory (.toPath dir) (into-array LinkOption []))
(Files/isReadable e)
(= e (Files/writeString e "\nline3" (into-array OpenOption [StandardOpenOption/APPEND])))
(Files/readString e)
(= e (Files/write e (.getBytes "bytes") (into-array OpenOption [])))
(Files/readString e)
(with-open [w (Files/newBufferedWriter e (into-array OpenOption []))] (.write w "buffered"))
(Files/readString e)
(with-open [in (Files/newInputStream e (into-array OpenOption []))] (slurp in))
(with-open [out (Files/newOutputStream e (into-array OpenOption []))] (.write out (.getBytes "out")))
(Files/readString e)
(try (Files/newInputStream (.toPath (File. dir "nope")) (into-array OpenOption [])) (catch NoSuchFileException x (hide (.getMessage x))))
(try (Files/readString (.toPath (File. dir "nope"))) (catch NoSuchFileException x (hide (.getMessage x))))
(try (Files/size (.toPath (File. dir "nope"))) (catch NoSuchFileException x (hide (.getMessage x))))
(try (Files/delete (.toPath (File. dir "nope"))) (catch NoSuchFileException x (hide (.getMessage x))))
(Files/deleteIfExists (.toPath (File. dir "nope")))
(try (Files/delete (.toPath (File. dir "sub"))) (catch DirectoryNotEmptyException x (hide (.getMessage x))))
(try (Files/createDirectory (.toPath dir) (into-array FileAttribute [])) (catch FileAlreadyExistsException x (hide (.getMessage x))))
(try (Files/createFile e (into-array FileAttribute [])) (catch FileAlreadyExistsException x (hide (.getMessage x))))
(Files/isDirectory (Files/createDirectory (.toPath (File. dir "n1")) (into-array FileAttribute [])) (into-array LinkOption []))
(Files/isDirectory (Files/createDirectories (.toPath (File. dir "n2/n3/n4")) (into-array FileAttribute [])) (into-array LinkOption []))
(= (.toPath (File. dir "n2")) (Files/createDirectories (.toPath (File. dir "n2")) (into-array FileAttribute [])))
(Files/size (Files/createFile (.toPath (File. dir "n1/empty")) (into-array FileAttribute [])))
(Files/deleteIfExists (.toPath (File. dir "n1/empty")))
(let [t (Files/createTempFile (.toPath dir) "tf" ".x" (into-array FileAttribute []))]
  [(.startsWith (str (.getFileName t)) "tf") (.endsWith (str t) ".x") (Files/size t)])
(let [t (Files/createTempDirectory (.toPath dir) "td" (into-array FileAttribute []))]
  [(.startsWith (str (.getFileName t)) "td") (Files/isDirectory t (into-array LinkOption []))])
(str (.getFileName (Files/copy e (.toPath (File. dir "e2.txt")) (into-array CopyOption []))))
(Files/readString (.toPath (File. dir "e2.txt")))
(try (Files/copy e (.toPath (File. dir "e2.txt")) (into-array CopyOption [])) (catch FileAlreadyExistsException x (hide (.getMessage x))))
(Files/readString (Files/copy e (.toPath (File. dir "e2.txt")) (into-array CopyOption [StandardCopyOption/REPLACE_EXISTING])))
(str (.getFileName (Files/move (.toPath (File. dir "e2.txt")) (.toPath (File. dir "e3.txt")) (into-array CopyOption []))))
[(.exists (File. dir "e2.txt")) (.exists (File. dir "e3.txt"))]
(Files/isSameFile e (.toPath (File. dir "p/../e.txt")))
(hide (.toRealPath (.toPath (File. dir "p/../e.txt")) (into-array LinkOption [])))
(try (.toRealPath (.toPath (File. dir "nope")) (into-array LinkOption [])) (catch NoSuchFileException x (hide (.getMessage x))))
(with-open [s (Files/lines e)] (vec (iterator-seq (.iterator s))))

;; ----- load-file and the reader on files
(spit (File. dir "l.clj") "(ns oracle.loaded) (def x (+ 1 2)) [(.getName (java.io.File. *file*)) x]")
(load-file (.getPath (File. dir "l.clj")))
(spit (File. dir "m.clj") "{:a 1 :b [2 3]}")
(with-open [r (java.io.PushbackReader. (io/reader (File. dir "m.clj")))] (read r))
(read-string (slurp (File. dir "m.clj")))

;; ----- clean up
(defn rm-r [^File x] (when (.isDirectory x) (run! rm-r (.listFiles x))) (.delete x))
(rm-r dir)
(.exists dir)
