;; hash of values: every scalar and collection kind, equal values with equal hashes,
;; hash-ordered-coll, hash-unordered-coll, mix-collection-hash, hash-combine, .hashCode.

;; ----- scalars
(hash nil)
(hash true)
(hash false)
(hash 0)
(hash 1)
(hash -1)
(hash 42)
(hash 1000000)
(hash Long/MAX_VALUE)
(hash Long/MIN_VALUE)
(hash (int 42))
(hash (short 42))
(hash (byte 42))
(hash 42N)
(hash 18446744073709551616N)
(hash -18446744073709551616N)
(hash (biginteger 42))
(hash (biginteger 18446744073709551616N))
(hash 42.0)
(hash 42.5)
(hash -42.5)
(hash (float 42.5))
(hash 1e300)
(hash Double/MIN_VALUE)
(hash ##-Inf)
(hash 42M)
(hash 42.0M)
(hash 42.50M)
(hash 0.1M)
(hash -1.5M)
(hash 1/3)
(hash -1/3)
(hash 22/7)
(hash 123456789012345678901/2)
(hash "")
(hash "a")
(hash "A")
(hash "ab")
(hash "ba")
(hash "hello")
(hash "The quick brown fox jumps over the lazy dog")
(hash "é")
(hash "😀")
(hash "\n")
(hash \a)
(hash \b)
(hash \space)
(hash \é)
(hash :a)
(hash :b)
(hash :abc)
(hash :a/b)
(hash :b/a)
(hash :user/x)
(hash ::x)
(hash (keyword "a b"))
(hash 'a)
(hash 'b)
(hash 'a/b)
(hash 'arbace.core/map)
(hash (symbol "a b"))
(= (hash :a) (hash 'a))
(hash (keyword "a"))
(hash (symbol "a"))

;; ----- collections
(hash [])
(hash '())
(hash (list))
(hash {})
(hash #{})
(hash (seq []))
(hash (lazy-seq nil))
(hash (range 0))
(hash [1])
(hash '(1))
(hash (list 1))
(hash (seq [1]))
(hash (range 1 2))
(hash (lazy-seq [1]))
(hash [1 2])
(hash [2 1])
(hash '(1 2))
(hash (range 1 3))
(hash (map identity [1 2]))
(hash (cons 1 [2]))
(hash (cons 1 '(2)))
(hash (vector-of :long 1 2))
(hash (subvec [0 1 2 3] 1 3))
(hash (rseq [2 1]))
(hash (concat [1] [2]))
(hash [1 2 3])
(hash (range 10))
(hash (vec (range 100)))
(hash (range 100))
(hash [nil])
(hash [nil nil])
(hash [[]])
(hash [[1 2] [3 4]])
(hash [:a "b" \c 1.5 nil true])
(hash {:a 1})
(hash {:a 1 :b 2})
(hash {:b 2 :a 1})
(hash (hash-map :a 1 :b 2))
(hash (sorted-map :a 1 :b 2))
(hash (array-map :b 2 :a 1))
(hash {1 2})
(hash {2 1})
(hash {nil nil})
(hash {[1] {:x #{2}}})
(hash (zipmap (range 20) (range 20)))
(hash #{1})
(hash #{1 2})
(hash #{2 1})
(hash (sorted-set 1 2))
(hash (hash-set 1 2))
(hash #{nil})
(hash #{[1 2] #{3}})
(hash (set (range 50)))
(hash (first {:a 1}))
(hash (find {:a 1} :a))
(hash [:a 1])
(= (hash (first {:a 1})) (hash [:a 1]))
(hash (key (first {:a 1})))
(hash (conj arbace.lang.PersistentQueue/EMPTY 1 2))
(hash arbace.lang.PersistentQueue/EMPTY)
(hash (java.util.ArrayList. [1 2]))
(hash (java.util.HashMap. {:a 1}))
(hash (java.util.HashSet. #{1}))
(hash (seq (java.util.ArrayList. [1 2])))
(hash (doto (java.util.ArrayList.) (.add 1) (.add 2)))
(hash (java.util.Collections/emptyList))
(hash (java.util.Arrays/asList (to-array [1 2])))
(hash (java.util.UUID. 0 1))
(hash #uuid "00000000-0000-0000-0000-000000000001")
(hash (java.util.Date. 0))
(hash #inst "2020-01-01T00:00:00Z")

;; ----- records and types
(defrecord R [a b])
(hash (->R 1 2))
(hash (->R 2 1))
(hash (map->R {:a 1 :b 2}))
(hash (assoc (->R 1 2) :c 3))
(hash {:a 1 :b 2})
(= (hash (->R 1 2)) (hash {:a 1 :b 2}))
(= (->R 1 2) {:a 1 :b 2})
(= {:a 1 :b 2} (->R 1 2))
(.hashCode (->R 1 2))
(.hashCode {:a 1 :b 2})
(defrecord S [a b])
(= (hash (->R 1 2)) (hash (->S 1 2)))
(= (->R 1 2) (->S 1 2))
(hash (->R nil nil))
(deftype T [x] Object (hashCode [_] 7) (equals [_ o] true))
(hash (T. 1))
(.hashCode (T. 1))
(deftype H [x] arbace.lang.IHashEq (hasheq [_] 99))
(hash (H. 1))
(hash [(T. 1) (H. 1)])

;; ----- equal values, equal hashes
(= (hash 1) (hash 1N))
(= (hash 1) (hash (int 1)))
(= (hash 1) (hash (byte 1)))
(= (hash 1) (hash (biginteger 1)))
(= (hash 1.0) (hash (float 1.0)))
(= (hash 1.5) (hash (float 1.5)))
(= (hash 1M) (hash 1.0M))
(= (hash [1 2]) (hash '(1 2)))
(= (hash [1 2]) (hash (seq [1 2])))
(= (hash [1 2]) (hash (range 1 3)))
(= (hash [1 2]) (hash (java.util.ArrayList. [1 2])))
(= (hash {:a 1}) (hash (sorted-map :a 1)))
(= (hash {:a 1}) (hash (java.util.HashMap. {:a 1})))
(= (hash #{1 2}) (hash (sorted-set 2 1)))
(= (hash #{1 2}) (hash (java.util.HashSet. #{1 2})))
(= (hash []) (hash ()))
(= (hash {}) (hash #{}))
(= (hash "a") (hash \a))
(= (hash 'a) (hash "a"))
(= (hash [1]) (hash [1N]))
(= (hash [1]) (hash [1.0]))
(= [1] [1.0])
(= (hash #{1}) (hash #{1N}))
(= (hash {1 :a}) (hash {1N :a}))
(let [vs [nil true 1 1N 1.5 1/2 1M "s" \c :k 'sym [1] '(1) {:a 1} #{1} (->R 1 2)]]
  (every? (fn [v] (= (hash v) (hash (read-string (pr-str v))))) (remove record? vs)))
(map hash [0 1 2 3 4 5 6 7 8 9])
(map hash [:a :b :c :d])
(map hash ["a" "b" "c" "d"])
(map hash (map str (range 10)))
(map #(hash (vec (range %))) (range 6))
(map #(hash (set (range %))) (range 6))
(map #(hash (zipmap (range %) (range %))) (range 4))

;; ----- hash-ordered-coll, hash-unordered-coll, mix-collection-hash
(hash-ordered-coll [])
(hash-ordered-coll [1 2 3])
(= (hash-ordered-coll [1 2 3]) (hash [1 2 3]))
(hash-ordered-coll '(1 2 3))
(hash-ordered-coll (java.util.ArrayList. [1 2 3]))
(hash-ordered-coll "abc")
(hash-ordered-coll nil)
(hash-unordered-coll [])
(hash-unordered-coll [1 2 3])
(hash-unordered-coll [3 2 1])
(= (hash-unordered-coll [1 2 3]) (hash #{1 2 3}))
(hash-unordered-coll {:a 1})
(= (hash-unordered-coll {:a 1}) (hash {:a 1}))
(hash-unordered-coll nil)
(mix-collection-hash 0 0)
(mix-collection-hash 1 1)
(mix-collection-hash 12345 3)
(mix-collection-hash -1 10)
(mix-collection-hash Long/MAX_VALUE 1)
(mix-collection-hash 1 Long/MAX_VALUE)
(= (mix-collection-hash (reduce unchecked-add-int (map hash [:a :b])) 2) (hash #{:a :b}))
(hash-combine 1 2)
(hash-combine 0 0)
(hash-combine -1 (hash :a))
(hash-combine 1 "x")
(arbace.lang.Murmur3/hashInt 1)
(arbace.lang.Murmur3/hashLong 1)
(arbace.lang.Murmur3/hashUnencodedChars "abc")
(arbace.lang.Murmur3/mixCollHash 1 1)
(arbace.lang.Util/hasheq "abc")
(arbace.lang.Util/hash nil)
(arbace.lang.Util/hash "abc")
(arbace.lang.Util/hashCombine 1 2)

;; ----- .hashCode (Java hashes) of Clojure values
(.hashCode [])
(.hashCode [1 2])
(.hashCode '(1 2))
(.hashCode {:a 1})
(.hashCode #{1 2})
(.hashCode :a)
(.hashCode 'a)
(.hashCode 'a/b)
(.hashCode "a")
(.hashCode \a)
(.hashCode true)
(.hashCode false)
(.hashCode 1N)
(.hashCode 1.5)
(.hashCode 1/2)
(.hashCode [nil])
(.hashCode (first {:a 1}))
(.hashCode (seq [1 2]))
(.hashCode (range 1 3))
(.hashCode (java.util.ArrayList. [1 2]))
(.hashCode (lazy-seq [1 2]))
(.hashCode (sorted-map :a 1))
(.hashCode [[1] #{2} {3 4}])

;; ----- hash maps and sets: iteration order follows hashes
(seq (hash-set 1 2 3 4 5 6 7 8 9 10))
(seq (hash-set :a :b :c :d :e :f :g :h :i :j))
(seq (hash-set "a" "b" "c" "d" "e" "f" "g" "h" "i"))
(keys (hash-map :a 1 :b 2 :c 3 :d 4 :e 5 :f 6 :g 7 :h 8 :i 9 :j 10))
(keys (zipmap (map str (range 15)) (range 15)))
(seq (set (range 40)))
(seq (set (map #(* % 1000003) (range 20))))
(seq (into #{} [1.5 2.5 1/2 1N "x" \x :x 'x nil]))
(seq (into #{} [[1] [2] [1 2] [] '(3)]))
(keys (into {} (map vector (range 33) (range 33))))
(seq (disj (set (range 20)) 5 10 15))
(seq (persistent! (reduce conj! (transient #{}) (range 20))))
(vals (dissoc (zipmap (range 12) (map keyword (map str (range 12)))) 3 7))
(first (set (range 1000)))
(count (set (map hash (range 1000))))
(seq #{(->R 1 2) (->R 2 1) {:a 1 :b 2}})
(count #{(->R 1 2) {:a 1 :b 2}})
(seq (set [-1 -2 -3 Long/MIN_VALUE Long/MAX_VALUE 0]))
(seq (set ["" " " "  "]))
(seq (hash-set ##Inf ##-Inf 0.0 -0.0))
(count (hash-set 0.0 -0.0))
(count (hash-set 1 1.0 1N 1M 1.0M))
(seq (hash-set 1 1.0 1N 1M 1.0M))
(count #{##NaN})
