;; java.util's plain Java added to the Go build (doc/go/JAVA-BASE.md, amendment JB1): the
;; primitive sorts, parallel sorts and prefixes, the natural-order comparators, SortedSet and
;; TreeSet's views, TreeMap's sorted copies, BitSet, PriorityQueue, WeakHashMap,
;; StringTokenizer, Base64, SplittableRandom, the random streams, BitSieve, the event classes.
;; Results are shown as Clojure data (no identity hashes).

(import (quote (java.util Arrays Collections Comparator TreeMap TreeSet SortedSet NavigableSet
                          BitSet PriorityQueue WeakHashMap StringTokenizer Base64 SplittableRandom
                          Random ArrayList HashMap LinkedHashMap EventObject Observable Observer
                          List)))
(defn lcg-ints [n seed] (let [r (Random. seed)] (int-array (repeatedly n #(.nextInt r)))))
(defn lcg-longs [n seed] (let [r (Random. seed)] (long-array (repeatedly n #(.nextLong r)))))
(defn lcg-doubles [n seed] (let [r (Random. seed)] (double-array (repeatedly n #(- (.nextDouble r) 0.5)))))
(defn sorted-ok? [a] (let [v (vec a)] (= v (sort v))))
;; ----- Arrays.sort of primitive arrays
(let [a (int-array [3 1 2])] (Arrays/sort a) (vec a))
(let [a (int-array [5 -1 0 Integer/MIN_VALUE Integer/MAX_VALUE 7 7 -1])] (Arrays/sort a) (vec a))
(let [a (int-array [9 8 7 6 5 4 3 2 1])] (Arrays/sort a 2 7) (vec a))
(let [a (long-array [3 -9 0 Long/MAX_VALUE Long/MIN_VALUE 4])] (Arrays/sort a) (vec a))
(let [a (short-array [3 -2 1 0])] (Arrays/sort a) (vec a))
(let [a (char-array "the quick brown fox")] (Arrays/sort a) (apply str a))
(let [a (byte-array [3 -128 127 0 -1])] (Arrays/sort a) (vec a))
(let [a (float-array [3.5 Float/NaN -0.0 0.0 -1.5 Float/NEGATIVE_INFINITY])] (Arrays/sort a) (mapv str a))
(let [a (double-array [##NaN 2.0 -0.0 0.0 ##-Inf ##Inf -3.25 0.0 -0.0])] (Arrays/sort a) (mapv str a))
(let [a (lcg-ints 5000 42)] (Arrays/sort a) [(sorted-ok? a) (aget a 0) (aget a 2500) (aget a 4999)])
(let [a (lcg-longs 5000 7)] (Arrays/sort a) [(sorted-ok? a) (aget a 0) (aget a 4999)])
(let [a (lcg-doubles 5000 9)] (Arrays/sort a) [(sorted-ok? a) (aget a 0) (aget a 4999)])
(let [a (int-array (concat (range 1000) (range 1000)))] (Arrays/sort a) [(sorted-ok? a) (aget a 1) (aget a 1999)])
(let [a (int-array (range 3000 0 -1))] (Arrays/sort a) [(aget a 0) (aget a 2999)])
(let [a (char-array (map char (range 2000 0 -1)))] (Arrays/sort a) [(int (aget a 0)) (int (aget a 1999))])
(let [a (short-array (map short (range 5000 0 -1)))] (Arrays/sort a) [(aget a 0) (aget a 4999)])
(let [a (byte-array (map byte (take 1000 (cycle (range -128 128)))))] (Arrays/sort a) [(aget a 0) (aget a 999) (sorted-ok? a)])
(let [a (int-array [1 2])] (try (Arrays/sort a 2 1) (catch IllegalArgumentException e (.getMessage e))))
(let [a (int-array [1 2])] (try (Arrays/sort a 0 3) (catch ArrayIndexOutOfBoundsException e (.getMessage e))))
;; ----- parallelSort, parallelPrefix
(let [a (lcg-ints 100000 1)] (Arrays/parallelSort a) [(sorted-ok? a) (aget a 0) (aget a 50000) (aget a 99999)])
(let [a (lcg-longs 50000 2)] (Arrays/parallelSort a) [(sorted-ok? a) (aget a 0)])
(let [a (lcg-doubles 50000 3)] (Arrays/parallelSort a) [(sorted-ok? a) (aget a 0)])
(let [a (int-array [4 2 3 1])] (Arrays/parallelSort a) (vec a))
(let [a (into-array String (map str (range 20000 0 -1)))] (Arrays/parallelSort a) [(aget a 0) (aget a 1) (aget a 19999)])
(let [a (to-array (map #(mod (* % 7919) 10007) (range 30000)))] (Arrays/parallelSort a (Comparator/reverseOrder)) [(aget a 0) (aget a 29999)])
(let [a (int-array (range 1 11))] (Arrays/parallelPrefix a (reify java.util.function.IntBinaryOperator (applyAsInt [_ x y] (+ x y)))) (vec a))
(let [a (long-array (repeat 20000 1))] (Arrays/parallelPrefix a (reify java.util.function.LongBinaryOperator (applyAsLong [_ x y] (+ x y)))) [(aget a 0) (aget a 19999)])
(let [a (double-array [1 2 3 4])] (Arrays/parallelPrefix a 1 3 (reify java.util.function.DoubleBinaryOperator (applyAsDouble [_ x y] (* x y)))) (vec a))
(let [a (to-array ["a" "b" "c" "d"])] (Arrays/parallelPrefix a (reify java.util.function.BinaryOperator (apply [_ x y] (str x y)))) (vec a))
;; ----- natural-order comparators
(.compare (Comparator/naturalOrder) 1 2)
(.compare (Comparator/naturalOrder) "b" "a")
(.compare (Comparator/reverseOrder) 1 2)
(vec (sort (Comparator/naturalOrder) [3 1 2]))
(vec (sort (Comparator/nullsFirst (Comparator/naturalOrder)) [3 nil 1 nil 2]))
(vec (sort (Comparator/nullsLast (Comparator/naturalOrder)) [3 nil 1 nil 2]))
(vec (sort (Comparator/nullsLast (Comparator/reverseOrder)) [3 nil 1 2]))
(vec (sort (.reversed (Comparator/naturalOrder)) [3 1 2]))
(vec (sort (.reversed (Comparator/nullsFirst (Comparator/naturalOrder))) [3 nil 1]))
(vec (sort (.thenComparing (Comparator/nullsFirst (Comparator/naturalOrder)) (Comparator/reverseOrder)) [2 1 nil]))
(vec (sort (Collections/reverseOrder (Collections/reverseOrder)) [3 1 2]))
(vec (sort (Collections/reverseOrder (Comparator/naturalOrder)) [3 1 2]))
(identical? (Comparator/naturalOrder) (Collections/reverseOrder (Collections/reverseOrder)))
(let [l (ArrayList. [3 1 2])] (.sort l nil) (vec l))
(let [l (ArrayList. ["b" "c" "a"])] (Collections/sort l (Comparator/naturalOrder)) (vec l))
(try (.compare (Comparator/naturalOrder) nil 1) (catch NullPointerException e :npe))
;; ----- SortedSet and TreeSet's views
(instance? SortedSet (TreeSet.))
(instance? SortedSet (sorted-set 1 2))
(let [s (TreeSet. [5 1 4 2 3])] [(vec (.headSet s 3)) (vec (.tailSet s 3)) (vec (.subSet s 2 4))])
(let [s (TreeSet. [5 1 4 2 3])] [(vec (.headSet s 3 true)) (vec (.tailSet s 3 false)) (vec (.subSet s 1 false 5 true))])
(let [^SortedSet s (TreeSet. ["b" "a" "c"])] [(.first s) (.last s) (.comparator s)])
(let [s (TreeSet. [5 1 4 2 3]) h (.headSet s 4)] (.add s 0) (.remove s 2) (vec h))
(let [s (TreeSet. [1 2 3])] (try (.add (.headSet s 2) 5) (catch IllegalArgumentException e (.getMessage e))))
(let [s (TreeSet. (TreeSet. [3 1 2]))] [(vec s) (class s)])
(let [s (TreeSet. ^SortedSet (TreeSet. (Comparator/reverseOrder)))] (.addAll s [1 3 2]) (vec s))
(let [s (TreeSet.)] (.addAll s (TreeSet. [9 7 8])) (vec s))
(vec (Collections/unmodifiableSortedSet (TreeSet. [2 1])))
(try (.add (Collections/unmodifiableSortedSet (TreeSet. [2 1])) 3) (catch UnsupportedOperationException e :unsupported))
(vec (Collections/synchronizedSortedSet (TreeSet. [2 1 3])))
(vec (.headSet (Collections/checkedSortedSet (TreeSet. [2 1 3]) Long) 3))
(try (.add (Collections/checkedSortedSet (TreeSet. [2 1 3]) Long) "x") (catch ClassCastException e :cce))
(vec (Collections/emptySortedSet))
(vec (.subSet (TreeSet. (range 10)) 3 7))
(vec (.descendingSet (TreeSet. [1 2 3])))
(vec (.reversed (TreeSet. [1 2 3])))
;; ----- TreeMap's copies from sorted maps
(let [t (doto (TreeMap.) (.put 2 :b) (.put 1 :a) (.put 3 :c))] (into {} (TreeMap. t)))
(let [t (doto (TreeMap.) (.put 2 :b) (.put 1 :a))] (str (TreeMap. t)))
(let [t (doto (TreeMap. (Comparator/reverseOrder)) (.put 2 :b) (.put 1 :a) (.put 3 :c))] (vec (.keySet (TreeMap. t))))
(let [t (doto (TreeMap.) (.put "x" 1) (.put "y" 2))] (str (.clone t)))
(let [t (doto (TreeMap.) (.put "x" 1) (.put "y" 2)) c (.clone t)] (.put c "z" 3) [(str t) (str c)])
(let [t (doto (TreeMap.) (.put 1 1) (.put 2 2)) m (TreeMap.)] (.putAll m t) (str m))
(let [m (TreeMap.)] (.putAll m (TreeMap. {5 :e 3 :c 4 :d 1 :a 2 :b})) [(str m) (.firstKey m) (.lastKey m) (str (.headMap m 3))])
(let [m (TreeMap.)] (.putAll m (into (sorted-map) {1 2 3 4})) (str m))
(let [m (TreeMap. (into (sorted-map) (zipmap (range 100) (range 100))))] [(.size m) (.firstKey m) (.lastKey m) (str (.floorEntry m 50))])
(let [m (TreeMap. (into (sorted-map) (zipmap (range 1000) (range 1000))))] (.remove m 500) (.put m 2000 0) [(.size m) (.lastKey m) (.containsKey m 500)])
;; ----- BitSet
(let [b (BitSet.)] (.set b 1) (.set b 5) (.set b 64) (str b))
(let [b (BitSet. 10)] (.set b 2 6) (.clear b 3) [(str b) (.cardinality b) (.length b) (.nextSetBit b 3) (.nextClearBit b 2) (.previousSetBit b 10)])
(let [a (doto (BitSet.) (.set 0 10)) b (doto (BitSet.) (.set 5 15))] (.and a b) (str a))
(let [a (doto (BitSet.) (.set 0 10)) b (doto (BitSet.) (.set 5 15))] (.or a b) (str a))
(let [a (doto (BitSet.) (.set 0 10)) b (doto (BitSet.) (.set 5 15))] (.xor a b) (str a))
(let [a (doto (BitSet.) (.set 0 10)) b (doto (BitSet.) (.set 5 15))] (.andNot a b) [(str a) (.intersects a b)])
(let [b (BitSet/valueOf (long-array [5 -1]))] [(str b) (vec (.toLongArray b)) (vec (.toByteArray b))])
(vec (.toByteArray (BitSet/valueOf (byte-array [1 2 -128]))))
(let [b (doto (BitSet.) (.set 3) (.set 200))] [(.size b) (.hashCode b) (= b (.clone b)) (vec (.toArray (.stream b)))])
(let [b (doto (BitSet.) (.flip 0 5) (.flip 2))] [(str b) (str (.get b 1 4)) (.isEmpty b)])
(try (.set (BitSet.) -1) (catch IndexOutOfBoundsException e (.getMessage e)))
;; ----- PriorityQueue
(let [q (PriorityQueue. [5 1 4 2 3])] (loop [acc []] (if-let [x (.poll q)] (recur (conj acc x)) acc)))
(let [q (PriorityQueue. 4 (Comparator/reverseOrder))] (doseq [x [5 1 4 2 3]] (.add q x)) [(.peek q) (.size q) (.poll q) (.poll q) (.size q)])
(let [q (PriorityQueue. ["pear" "apple" "fig"])] [(.peek q) (.contains q "fig") (.remove q "fig") (.size q) (sort (vec (.toArray q)))])
(let [q (PriorityQueue. (PriorityQueue. [3 1 2]))] [(.poll q) (.poll q) (.poll q) (.poll q)])
(let [q (PriorityQueue. (TreeSet. [3 1 2]))] (.poll q))
(let [q (PriorityQueue. (map #(mod (* % 37) 101) (range 200)))] (take 10 (repeatedly #(.poll q))))
(let [q (PriorityQueue. [1 2 3 4 5 6])] (.removeIf q even?) (sort (vec q)))
(try (.add (PriorityQueue.) nil) (catch NullPointerException e :npe))
(try (.add (doto (PriorityQueue.) (.add 1)) "x") (catch ClassCastException e :cce))
(let [q (PriorityQueue.)] [(.poll q) (.peek q) (try (.element q) (catch java.util.NoSuchElementException e :nse))])
;; ----- WeakHashMap (strongly held keys)
(let [k1 "a" k2 "b" m (WeakHashMap.)] (.put m k1 1) (.put m k2 2) [(.get m "a") (.size m) (.containsKey m "b") (into (sorted-map) m)])
(let [m (WeakHashMap. {:x 1 :y 2})] (.remove m :x) [(.size m) (.get m :y) (.isEmpty m)])
(let [m (WeakHashMap.)] (.put m nil 0) [(.get m nil) (.containsKey m nil)])
;; ----- StringTokenizer
(let [t (StringTokenizer. "a b  c\td")] [(.countTokens t) (vec (take-while some? (repeatedly #(when (.hasMoreTokens t) (.nextToken t)))))])
(let [t (StringTokenizer. "a,b;c" ",;" true)] (vec (take-while some? (repeatedly #(when (.hasMoreTokens t) (.nextToken t))))))
(let [t (StringTokenizer. "a=1&b=2" "&")] [(.nextToken t) (.nextToken t "=") (.nextToken t)])
(let [t (StringTokenizer. "x y")] [(.nextElement t) (.hasMoreElements t) (.nextToken t) (try (.nextToken t) (catch java.util.NoSuchElementException e :nse))])
(enumeration-seq (StringTokenizer. "p q r"))
;; ----- Base64
(.encodeToString (Base64/getEncoder) (.getBytes "hello world"))
(.encodeToString (Base64/getEncoder) (byte-array [-1 -2 -3 0 1]))
(.encodeToString (Base64/getUrlEncoder) (byte-array [-1 -2 -3 0 1]))
(.encodeToString (.withoutPadding (Base64/getEncoder)) (.getBytes "ab"))
(.encodeToString (Base64/getMimeEncoder) (byte-array (range 100)))
(.encodeToString (Base64/getMimeEncoder 16 (.getBytes "|")) (byte-array (range 30)))
(String. (.decode (Base64/getDecoder) "aGVsbG8gd29ybGQ="))
(vec (.decode (Base64/getUrlDecoder) "__79AAE"))
(vec (.decode (Base64/getMimeDecoder) "AAEC\r\nAwQF"))
(try (.decode (Base64/getDecoder) "a$b=") (catch IllegalArgumentException e (.getMessage e)))
(try (vec (.decode (Base64/getDecoder) "abc")) (catch IllegalArgumentException e (.getMessage e)))
(let [o (java.io.ByteArrayOutputStream.)] (with-open [w (.wrap (Base64/getEncoder) o)] (.write w (.getBytes "stream me"))) (str o))
(let [i (.wrap (Base64/getDecoder) (java.io.ByteArrayInputStream. (.getBytes "c3RyZWFtIG1l")))] (slurp i))
(vec (.encode (Base64/getEncoder) (.getBytes "xyz")))
;; ----- SplittableRandom, Random's streams, RandomGenerator's defaults
(let [r (SplittableRandom. 42)] [(.nextInt r) (.nextLong r) (.nextInt r 100) (.nextInt r 10 20) (.nextDouble r) (.nextBoolean r)])
(let [r (SplittableRandom. 42) s (.split r)] [(.nextLong r) (.nextLong s)])
(let [r (SplittableRandom. 7)] (vec (.toArray (.ints r 5 0 10))))
(let [r (SplittableRandom. 7)] (vec (.toArray (.limit (.longs r) 3))))
(let [r (Random. 42)] (vec (.toArray (.ints r 5))))
(let [r (Random. 42)] (vec (.toArray (.ints r 5 0 100))))
(let [r (Random. 42)] (vec (.toArray (.limit (.longs r) 3))))
(let [r (Random. 42)] (vec (.toArray (.doubles r 3))))
(let [r (Random. 42)] (vec (.toArray (.doubles r 3 1.0 2.0))))
(let [r (Random. 42)] [(.nextInt r 5 10) (.nextLong r 100) (.nextLong r 5 10) (.nextDouble r 2.0) (.nextFloat r 3.0) (.nextGaussian r 1.0 0.5)])
(let [r (Random. 1)] (.nextExponential r))
(let [r (Random. 1)] (try (.nextInt r 5 5) (catch IllegalArgumentException e (.getMessage e))))
(.isDeprecated (Random. 1))
;; ----- BigInteger.nextProbablePrime (BitSieve above 95 bits)
(.nextProbablePrime (biginteger 100))
(str (.nextProbablePrime (.shiftLeft BigInteger/ONE 100)))
(str (.nextProbablePrime (.shiftLeft BigInteger/ONE 200)))
;; ----- the event classes, Observable
(let [e (EventObject. "src")] [(.getSource e) (str e)])
(try (EventObject. nil) (catch IllegalArgumentException e (.getMessage e)))
(let [seen (atom []) o (Observable.) w (reify Observer (update [_ obs arg] (swap! seen conj arg)))]
  (.addObserver o w) (.addObserver o w) (.notifyObservers o :ignored)
  [@seen (.countObservers o) (.hasChanged o) (do (.deleteObserver o w) (.countObservers o))])
(.getMessage (java.util.InputMismatchException. "bad input"))
(let [e (java.util.MissingResourceException. "m" "C" "k")] [(.getMessage e) (.getClassName e) (.getKey e)])
(.getMessage (java.util.IllformedLocaleException. "bad" 3))
(.getErrorIndex (java.util.IllformedLocaleException. "bad" 3))
[java.util.FormattableFlags/LEFT_JUSTIFY java.util.FormattableFlags/UPPERCASE java.util.FormattableFlags/ALTERNATE]
(instance? Error (java.util.ServiceConfigurationError. "x"))
(.getMessage (java.util.InvalidPropertiesFormatException. "props"))
(.getMessage (java.util.TooManyListenersException. "many"))
;; ----- unseeded generators (their values differ per run)
(instance? SplittableRandom (SplittableRandom.))
(.nextInt (SplittableRandom.) 1)
(.isDeprecated (SplittableRandom. 1))
(<= 0 (.nextInt (.split (SplittableRandom.)) 10) 9)
;; ----- Comparator's serializable lambdas (intersection casts with Serializable)
(.compare (Comparator/comparing (reify java.util.function.Function (apply [_ x] (count x)))) "a" "bb")
(.compare (Comparator/comparingInt (reify java.util.function.ToIntFunction (applyAsInt [_ x] (count x)))) "ccc" "bb")
(.compare (Comparator/comparingLong (reify java.util.function.ToLongFunction (applyAsLong [_ x] (count x)))) "a" "a")
(vec (sort (.thenComparing (Comparator/comparing (reify java.util.function.Function (apply [_ x] (count x)))) (Comparator/naturalOrder)) ["bb" "a" "ab" "c"]))
(vec (sort (.thenComparingInt (Comparator/comparing (reify java.util.function.Function (apply [_ x] (count x)))) (reify java.util.function.ToIntFunction (applyAsInt [_ x] (int (first x))))) ["bb" "a" "ab" "c"]))
(mapv key (sort (java.util.Map$Entry/comparingByKey) (seq {3 :c 1 :a 2 :b})))
(mapv key (sort (java.util.Map$Entry/comparingByValue (Comparator/reverseOrder)) (seq {3 :c 1 :a 2 :b})))
(instance? java.io.Serializable (Comparator/comparing (reify java.util.function.Function (apply [_ x] x))))
