;; Multimethods and hierarchies, protocols, records, deftype, reify.

;; ----- multimethods
(defmulti area :shape)
(some? (defmethod area :square [{:keys [side]}] (* side side)))
(some? (defmethod area :rect [{:keys [w h]}] (* w h)))
(area {:shape :square :side 3})
(area {:shape :rect :w 2 :h 5})
(area {:shape :circle :r 1})
(some? (defmethod area :default [m] [:unknown (:shape m)]))
(area {:shape :circle :r 1})
(area {})
(count (methods area))
(sort (map str (keys (methods area))))
(contains? (methods area) :default)
(some? (remove-method area :default))
(area {:shape :circle})
(count (methods area))
(fn? (get-method area :square))
(get-method area :nothing)
((get-method area :rect) {:w 3 :h 3})
(defmulti greet (fn [x] (class x)))
(some? (defmethod greet String [s] (str "string " s)))
(some? (defmethod greet Long [n] (str "long " n)))
(some? (defmethod greet Number [n] (str "number " n)))
(some? (defmethod greet Object [o] "object"))
(greet "a")
(greet 1)
(greet 1.5)
(greet :k)
(greet nil)
(some? (defmethod greet nil [_] "nil!"))
(greet nil)
(defmulti with-default identity :default ::none)
(some? (defmethod with-default ::none [x] [:custom-default x]))
(some? (defmethod with-default 1 [x] :one))
(with-default 1)
(with-default 2)
(defmulti vec-dispatch (fn [a b] [(class a) (class b)]))
(some? (defmethod vec-dispatch [Long Long] [a b] :both-long))
(some? (defmethod vec-dispatch [String Long] [a b] :string-long))
(some? (defmethod vec-dispatch [Object Object] [a b] :objects))
(vec-dispatch 1 2)
(vec-dispatch "a" 2)
(vec-dispatch :a :b)
(vec-dispatch 1 "a")
(defmulti arity-mm (fn [& args] (count args)))
(some? (defmethod arity-mm 0 [] :none))
(some? (defmethod arity-mm 1 [a] [:one a]))
(some? (defmethod arity-mm 2 [a b] [:two a b]))
(some? (defmethod arity-mm :default [& args] [:many (count args)]))
(arity-mm)
(arity-mm 1)
(arity-mm 1 2)
(arity-mm 1 2 3 4 5)
(apply arity-mm [1 2])
(apply arity-mm 1 2 [3])
(map (partial arity-mm :p) [1 2])
((partial arity-mm) 1)
(defmulti no-methods identity)
(no-methods 5)
(defmulti throws-in-dispatch (fn [x] (/ 1 x)))
(throws-in-dispatch 0)
(defmulti redefined identity)
(some? (defmethod redefined :a [_] :first))
(some? (defmethod redefined :a [_] :second))
(redefined :a)
(defmulti kw-dispatch :type)
(some? (defmethod kw-dispatch :x [m] (:v m)))
(kw-dispatch {:type :x :v 10})
(defmulti multi-arity-method identity)
(some? (defmethod multi-arity-method :k ([x] [:one x]) ([x y] [:two x y])))
(multi-arity-method :k)
(multi-arity-method :k 2)
(some? (defmethod area :tri named-method [m] :tri))
(area {:shape :tri})
(class area)
(instance? arbace.lang.MultiFn area)

;; ----- hierarchies: global
(derive ::square ::rect)
(derive ::rect ::shape)
(derive ::circle ::shape)
(isa? ::square ::rect)
(isa? ::square ::shape)
(isa? ::shape ::square)
(isa? ::square ::square)
(isa? ::circle ::rect)
(parents ::square)
(ancestors ::square)
(descendants ::shape)
(parents ::shape)
(ancestors ::shape)
(isa? [::square ::circle] [::rect ::shape])
(isa? [::square] [::rect ::shape])
(isa? Long Number)
(isa? Long Comparable)
(isa? String Object)
(isa? Long String)
(isa? 1 1)
(isa? [1 2] [1 2])
(sort-by str (parents Long))
(contains? (ancestors Long) Number)
(contains? (ancestors arbace.lang.PersistentVector) arbace.lang.IPersistentVector)
(defmulti describe identity)
(some? (defmethod describe ::shape [x] [:shape x]))
(some? (defmethod describe ::rect [x] [:rect x]))
(describe ::square)
(describe ::circle)
(describe ::rect)
(describe ::other)
(derive ::sq2 ::rect)
(derive ::sq2 ::circle)
(some? (defmethod describe ::circle [x] [:circle x]))
(describe ::sq2)
(some? (prefer-method describe ::rect ::circle))
(describe ::sq2)
(contains? (prefers describe) ::rect)
(some? (prefer-method describe ::circle ::rect))
(derive ::square ::square)
(derive ::shape ::square)
(derive "str" ::x)
(derive ::x "str")
(underive ::sq2 ::circle)
(parents ::sq2)
(describe ::sq2)
(derive :unqualified ::x)
(derive 'qualified/sym 'other/sym)
(isa? 'qualified/sym 'other/sym)

;; ----- hierarchies: local
(def h (-> (make-hierarchy) (derive :dog :animal) (derive :cat :animal) (derive :puppy :dog)))
h
(isa? h :puppy :animal)
(isa? h :puppy :cat)
(parents h :puppy)
(ancestors h :puppy)
(descendants h :animal)
(descendants h :puppy)
(parents h :unknown)
(isa? :puppy :animal)
(def h2 (underive h :puppy :dog))
(isa? h2 :puppy :animal)
(ancestors h2 :puppy)
(:parents h2)
(make-hierarchy)
(derive (make-hierarchy) :a :a)
(def h3 (derive (make-hierarchy) String :stringy))
(isa? h3 String :stringy)
(sort-by str (ancestors h3 String))
(derive (make-hierarchy) :a String)
(defmulti speak :kind :hierarchy #'h)
(some? (defmethod speak :animal [_] "..."))
(some? (defmethod speak :dog [_] "woof"))
(speak {:kind :puppy})
(speak {:kind :cat})
(speak {:kind :rock})
(def mh (atom (make-hierarchy)))
(defmulti via-atom identity :hierarchy mh)
(swap! mh derive :x :y)
(some? (defmethod via-atom :y [_] :y-method))
(via-atom :x)
(defmulti ambig identity)
(derive ::amb ::p1)
(derive ::amb ::p2)
(some? (defmethod ambig ::p1 [_] :p1))
(some? (defmethod ambig ::p2 [_] :p2))
(ambig ::amb)
(ambig ::p1)
(some? (prefer-method ambig ::p2 ::p1))
(ambig ::amb)
(some? (prefer-method ambig ::p1 ::p2))
(defmulti class-ambig class)
(some? (defmethod class-ambig Comparable [_] :comparable))
(some? (defmethod class-ambig java.io.Serializable [_] :serializable))
(class-ambig "s")
(some? (prefer-method class-ambig Comparable java.io.Serializable))
(class-ambig "s")

;; ----- protocols
(defprotocol Shape
  (area2 [this])
  (scale [this k] [this kx ky]))
(defrecord Sq [side]
  Shape
  (area2 [_] (* side side))
  (scale [_ k] (->Sq (* side k)))
  (scale [_ kx ky] [:non-uniform kx ky]))
(area2 (->Sq 3))
(scale (->Sq 2) 5)
(area2 (scale (->Sq 2) 5))
(scale (->Sq 2) 1 2)
(area2 "string")
(area2 nil)
(scale (->Sq 1))
(satisfies? Shape (->Sq 1))
(satisfies? Shape "x")
(extends? Shape Sq)
(extends? Shape String)
(:on Shape)
(sort (keys (:sigs Shape)))
(:arglists (:scale (:sigs Shape)))
(:doc (meta #'area2))
(:arglists (meta #'scale))
(:protocol (meta #'area2))
(instance? user.Shape (->Sq 1))
(defprotocol Describe (desc [x] "describes x"))
(:doc (meta #'desc))
(extend-type String Describe (desc [s] (str "String of " (count s))))
(extend-type Long Describe (desc [n] (str "Long " n)))
(extend-type nil Describe (desc [_] "nothing"))
(desc "abc")
(desc 42)
(desc nil)
(desc 1.5)
(desc :k)
(extend-type Object Describe (desc [o] (str "some " (.getSimpleName (class o)))))
(desc 1.5)
(desc :k)
(desc "abc")
(extend-protocol Describe
  arbace.lang.IPersistentVector (desc [v] (str "vector of " (count v)))
  arbace.lang.IPersistentMap (desc [m] (str "map of " (count m)))
  Number (desc [n] (str "number " n)))
(desc [1 2])
(desc {:a 1})
(desc 2.5)
(desc 7)
(desc (->Sq 1))
(desc '(1))
(desc (sorted-map))
(satisfies? Describe 1)
(satisfies? Describe (Object.))
(extends? Describe String)
(extends? Describe Object)
(sort (map str (extenders Describe)))
(count (extenders Describe))
(extend-protocol Describe Character (desc [c] (str "char " c)))
(desc \x)
(defprotocol Arities (ar [x] [x y] [x y z]))
(extend-protocol Arities Long (ar ([x] 1) ([x y] 2) ([x y z] 3)))
[(ar 1) (ar 1 2) (ar 1 2 3)]
(ar 1 2 3 4)
(ar)
(defprotocol Partial (p1 [x]) (p2 [x]))
(extend-type Long Partial (p1 [x] :p1))
(p1 1)
(p2 1)
(defprotocol Meta-P :extend-via-metadata true (via-meta [x]))
(via-meta (with-meta [1 2] {`via-meta (fn [v] [:meta (count v)])}))
(via-meta [1 2])
(via-meta (with-meta {} {'user/via-meta (fn [_] :symbol-key)}))
(extend-type arbace.lang.PersistentVector Meta-P (via-meta [v] :direct))
(via-meta (with-meta [1 2] {`via-meta (fn [v] [:meta (count v)])}))
(via-meta [1])
(satisfies? Meta-P (with-meta {} {`via-meta identity}))
(extend String Describe {:desc (fn [s] (str "extended " s))})
(desc "x")
(extend Long Describe {:desc (fn [s] (str "extended long " s))} Shape {:area2 (fn [n] (* n n))})
(desc 3)
(area2 4)
(defprotocol Empty-P)
(satisfies? Empty-P 1)
(defprotocol Bad (bad-m []))
(defprotocol Dup (m1 [x]) (m1 [x y]))
(extend-type Long Describe (not-a-method [x] 1))
(defprotocol Hier (hier [x]))
(extend-protocol Hier
  java.util.Collection (hier [_] :collection)
  java.util.List (hier [_] :list)
  Object (hier [_] :object))
(hier [1])
(hier #{1})
(hier (java.util.ArrayList.))
(hier 1)

;; ----- records
(defrecord R [a b])
(def r (->R 1 2))
r
(pr-str r)
(str r)
(print-str r)
(class r)
(type r)
(.getName (class r))
(:a r)
(:b r)
(:c r)
(:c r :nf)
(.a r)
(.-b r)
(get r :a)
(try (r :a) (catch ClassCastException e :not-a-fn))
(assoc r :a 10)
(assoc r :c 3)
(class (assoc r :c 3))
(:c (assoc r :c 3))
(dissoc r :c)
(dissoc (assoc r :c 3) :c)
(class (dissoc (assoc r :c 3) :c))
(dissoc r :a)
(class (dissoc r :a))
(map->R {:a 1 :b 2 :c 3})
(map->R {:a 1})
(map->R {})
(try (->R 1) (catch arbace.lang.ArityException e (.-actual e)))
(R. 1 2)
(R. 1 2 {:m 1} {:x 9})
(meta (R. 1 2 {:m 1} {:x 9}))
(R/create {:a 5 :b 6})
(R/getBasis)
(= r (->R 1 2))
(= r {:a 1 :b 2})
(= {:a 1 :b 2} r)
(= r (map->R {:a 1 :b 2}))
(= (->R 1 2) (assoc (->R 1 2) :c 3))
(defrecord R2 [a b])
(= (->R 1 2) (->R2 1 2))
(hash r)
(= (hash r) (hash (->R 1 2)))
(hash (->R 1 nil))
(hash (assoc r :z 1))
(count r)
(count (assoc r :c 3))
(keys r)
(vals r)
(seq r)
(keys (assoc r :z 1 :y 2))
(into {} r)
(into r {:a 100 :q 1})
(conj r [:a 7])
(conj r {:b 8})
(merge r {:c 1})
(class (merge r {:c 1}))
(merge {:c 1} r)
(class (merge {:c 1} r))
(contains? r :a)
(contains? r :zz)
(find r :a)
(empty? r)
(map? r)
(record? r)
(record? {})
(instance? R r)
(instance? arbace.lang.IRecord r)
(instance? arbace.lang.IPersistentMap r)
(instance? java.util.Map r)
(reduce-kv (fn [acc k v] (conj acc [k v])) [] (assoc r :c 3))
(update r :a inc)
(update-in {:r r} [:r :b] * 10)
(with-meta r {:m 1})
(meta (with-meta r {:m 1}))
(meta (assoc (with-meta r {:m 1}) :a 5))
(read-string "#user.R[1 2]")
(= r (read-string "#user.R{:a 1 :b 2}"))
(read-string "#user.R{:a 3 :b 4}")
(class (read-string "#user.R{:a 3 :b 4}"))
(eval (read-string "#user.R[5 6]"))
(read-string "#user.R{:a 3 :b 4 :c 5}")
(read-string "#user.Nope{:a 1}")
(binding [*print-dup* true] (pr-str r))
(binding [*print-namespace-maps* true] (pr-str (->R :x/a :x/b)))
(set [r (->R 1 2) (->R 2 1)])
(count (hash-set r (->R 1 2)))
(get {r :found} (->R 1 2))
(get {r :found} {:a 1 :b 2})
(defrecord Cmp [n] Comparable (compareTo [_ o] (compare n (:n o))))
(sort [(->Cmp 3) (->Cmp 1) (->Cmp 2)])
(map :n (sort [(->Cmp 3) (->Cmp 1) (->Cmp 2)]))
(sorted-set (->Cmp 2) (->Cmp 1))
(compare (->Cmp 1) (->Cmp 2))
(try (sort [(->R 2 1) (->R 1 2)]) (catch ClassCastException e :not-comparable))
(sorted? (sorted-set (->Cmp 1)))
(defrecord WithMethods [x] Object (toString [_] (str "WM<" x ">")))
(str (->WithMethods 1))
(pr-str (->WithMethods 1))
(defrecord Empty [])
(->Empty)
(assoc (->Empty) :a 1)
(= (->Empty) {})
(hash (->Empty))
(defrecord Fields [a-b c?])
(->Fields 1 2)
(:a-b (->Fields 1 2))
(:c? (->Fields 1 2))
(.-a_b (->Fields 1 2))
(defrecord Nested [inner])
(->Nested (->R 1 (->R 2 3)))
(get-in (->Nested (->R 1 (->R 2 3))) [:inner :b :a])
(defrecord WithProto [v] Describe (desc [_] (str "with-proto " v)))
(desc (->WithProto 3))
(defrecord RIFn [v] arbace.lang.IFn (invoke [_ x] (* v x)))
((->RIFn 3) 5)
(->R (->R 1 2) [3])
(defrecord Lng [^long n])
(->Lng 5)
(->Lng 1.9)
(:n (->Lng 7))
(->Lng nil)

;; ----- deftype
(deftype Pt [x y])
(def pt (Pt. 1 2))
(.-x pt)
(.y pt)
(class pt)
(.getName (class pt))
(:x pt)
(= pt (Pt. 1 2))
(= pt pt)
(map? pt)
(coll? pt)
(class (->Pt 3 4))
(.-x (->Pt 3 4))
(deftype Point [x y]
  Object
  (toString [_] (str "Point(" x "," y ")"))
  (equals [_ o] (and (instance? Point o) (= x (.-x ^Point o)) (= y (.-y ^Point o))))
  (hashCode [_] (+ (* 31 (hash x)) (hash y))))
(str (Point. 1 2))
(pr-str (Point. 1 2))
(= (Point. 1 2) (Point. 1 2))
(= (Point. 1 2) (Point. 2 1))
(hash (Point. 1 2))
(.hashCode (Point. 1 2))
(count (hash-set (Point. 1 2) (Point. 1 2) (Point. 3 4)))
(get {(Point. 1 2) :v} (Point. 1 2))
(deftype Counter [^:unsynchronized-mutable n]
  arbace.lang.IFn
  (invoke [this] (set! n (inc n)) n)
  (invoke [this k] (set! n (+ n k)) n))
(let [c (Counter. 0)] (c) (c) (c 10))
(let [c (Counter. 0)] [(c) (c) (c)])
(deftype VCell [^:volatile-mutable v]
  arbace.lang.IDeref (deref [_] v)
  arbace.lang.IFn (invoke [_ nv] (set! v nv)))
(let [c (VCell. 1)] (c 5) @c)
(deftype Mutable [^:unsynchronized-mutable x])
(set! (.-x (Mutable. 1)) 2)
(deftype Bag [items]
  arbace.lang.Counted (count [_] (count items))
  arbace.lang.ILookup
  (valAt [_ k] (get items k))
  (valAt [_ k nf] (get items k nf))
  arbace.lang.Seqable (seq [_] (seq items))
  Object (toString [_] (str "Bag" items)))
(def bag (Bag. [:a :b :c]))
(count bag)
(get bag 1)
(get bag 7 :none)
(:x bag)
(seq bag)
(map name bag)
(str bag)
(counted? bag)
(seqable? bag)
(into [] bag)
(deftype Fn2 [] arbace.lang.IFn (invoke [_ a b] (+ a b)) (applyTo [this args] (arbace.lang.AFn/applyToHelper this args)))
((Fn2.) 1 2)
(apply (Fn2.) [3 4])
((Fn2.) 1)
(deftype WithProto2 [v] Describe (desc [_] (str "type " v)))
(desc (WithProto2. 9))
(satisfies? Describe (WithProto2. 9))
(extend-type Pt Describe (desc [p] (str "pt " (.-x p))))
(desc pt)
(deftype Cmp2 [n] Comparable (compareTo [_ o] (compare n (.-n ^Cmp2 o))))
(map #(.-n ^Cmp2 %) (sort [(Cmp2. 3) (Cmp2. 1)]))
(deftype WithMeta [m]
  arbace.lang.IObj (withMeta [_ nm] (WithMeta. nm))
  arbace.lang.IMeta (meta [_] m))
(meta (with-meta (WithMeta. nil) {:a 1}))
(instance? Pt pt)
(instance? Point pt)
(deftype NoSuch [] Describe (nope [_] 1))
(Pt. 1)
(Pt/getBasis)
(:arglists (meta #'->Pt))

;; ----- reify (results only)
(def rd (reify Describe (desc [_] "reified")))
(desc rd)
(satisfies? Describe rd)
(instance? user.Describe rd)
(.toString (reify Object (toString [_] "custom")))
(str (reify Object (toString [_] "custom2")))
(let [x 10 o (reify arbace.lang.IFn (invoke [_ y] (+ x y)))] (o 5))
(let [o (reify arbace.lang.IDeref (deref [_] :derefed))] @o)
(let [o (reify arbace.lang.Counted (count [_] 42))] (count o))
(let [o (reify arbace.lang.ILookup (valAt [_ k] [:got k]) (valAt [_ k nf] nf))] [(:a o) (get o :b :nf)])
(let [o (reify java.util.Comparator (compare [_ a b] (compare b a)))] (sort o [1 3 2]))
(let [o (reify Comparable (compareTo [_ other] 0))] (compare o o))
(let [o (reify Arities (ar [_] 1) (ar [_ a] 2) (ar [_ a b] 3))] [(ar o) (ar o 1) (ar o 1 2)])
(let [o (reify Shape (area2 [_] 9))] (area2 o))
(let [o (reify Shape (area2 [_] 9))] (scale o 2))
(let [o (reify java.lang.Runnable (run [_] (println "ran")))] (.run o) :done)
(let [o (reify java.util.function.Function (apply [_ x] (* 2 x)))] (.apply o 21))
(let [o (reify Object (equals [this other] true) (hashCode [_] 7))] [(= o 1) (hash o)])
(let [o (reify)] (instance? Object o))
(let [o (with-meta (reify Describe (desc [_] "m")) {:k 1})] [(meta o) (desc o)])
(reify Describe (not-desc [_] 1))
(reify NotAType (x [_] 1))
(let [o (reify Describe (desc [_] "v"))] (class? (class o)))

;; ----- instance?, type, class
(instance? String "a")
(instance? Number 1)
(instance? Long 1)
(instance? Integer 1)
(instance? Double 1.0)
(instance? arbace.lang.Keyword :k)
(instance? arbace.lang.Symbol 'a)
(instance? arbace.lang.IFn :k)
(instance? arbace.lang.IFn inc)
(instance? arbace.lang.Fn inc)
(instance? arbace.lang.Fn :k)
(instance? java.util.List [1])
(instance? java.util.Map {})
(instance? java.util.Set #{})
(instance? java.util.RandomAccess [])
(instance? java.lang.Iterable '())
(instance? arbace.lang.ISeq '())
(instance? arbace.lang.ISeq [])
(instance? Object nil)
(instance? String nil)
(instance? "not a class" 1)
(type 1)
(type "s")
(type nil)
(type (with-meta [] {:type ::custom}))
(type (with-meta {} {:type :plain}))
(class (with-meta [] {:type ::custom}))
(type r)
(class Long)
(class nil)
(class 1N)
(class 1M)
(class 1/2)
(class 1.0)
(class (float 1))
(class (int 1))
(class (short 1))
(class (byte 1))
(class \a)
(class :a)
(class 'a)
(class #"re")
(class true)
(class #'map)
(class (var-get #'*out*))
(class {:a 1})
(class (lazy-seq nil))
(class (seq "ab"))
(class (seq {:a 1}))
(class (seq (sorted-map :a 1)))
(class (keys (sorted-map :a 1)))
(class (delay 1))
(class (atom 1))
(class (volatile! 1))
(class (ref 1))
(class (promise))
(class (agent 1))
(class (->R 1 2))
(class R)
(class (class 1))
(sort-by str (supers Long))
(bases Long)
(sort-by str (supers arbace.lang.Keyword))
(bases arbace.lang.PersistentHashSet)
(sort-by str (ancestors R))
(contains? (ancestors R) arbace.lang.IRecord)
(cast Number 1)
(cast String 1)
(cast String nil)
(class? String)
(class? "String")
(fn? (fn []))
(ifn? (->RIFn 1))
