;; Printing: the print functions, every literal and collection kind, the print control vars,
;; print-method, pprint and cl-format.

(require '[arbace.pprint :as pp])

;; ----- the print functions
(pr 1 "a" \b)
(prn 1 "a" \b)
(print 1 "a" \b)
(println 1 "a" \b)
(pr)
(prn)
(print)
(println)
(pr nil)
(print nil)
(println nil nil)
(pr-str)
(pr-str nil)
(pr-str 1 2)
(pr-str "a" "b")
(prn-str "a" 1)
(print-str "a" "b" \c)
(println-str "a" "b")
(println-str)
(print-str nil)
(with-out-str)
(with-out-str (print "x") (print "y"))
(with-out-str (prn :a) (prn :b))
(with-out-str (println "a" nil))
(with-out-str (pr "q\"") (print "q\""))
(with-out-str (printf "%d-%s" 1 "z"))
(printf "%s|%5d|%-5s|" "a" 42 "b")
(printf "no args")
(printf "%.2f%n" 3.14159)
(newline)
(with-out-str (newline))
(flush)
(with-out-str (print [1 "a"]) (pr [1 "a"]))
(with-out-str (binding [*out* *out*] (print "nested")))
(let [w (java.io.StringWriter.)] (binding [*out* w] (pr {:a "b"})) (str w))
(let [w (java.io.StringWriter.)] (print-method [1 2] w) (str w))
(let [w (java.io.StringWriter.)] (print-dup [1 2] w) (str w))
(binding [*out* *err*] (println "to err"))
(do (print "a") (println "b") 3)

;; ----- literals
(pr-str nil)
(pr-str true)
(pr-str false)
(pr-str 0)
(pr-str -42)
(pr-str 1.5)
(pr-str 1/3)
(pr-str 2N)
(pr-str 2.50M)
(pr-str ##NaN)
(pr-str "s")
(pr-str \c)
(pr-str :k)
(pr-str :ns/k)
(pr-str ::k)
(pr-str 's)
(pr-str 'ns/s)
(pr-str '/)
(pr-str 'arbace.core//)
(pr-str (symbol "a b"))
(pr-str (symbol "with space/and"))
(pr-str (symbol ""))
(pr-str (symbol "1abc"))
(pr-str (symbol "a,b"))
(pr-str (symbol ":kw"))
(pr-str (keyword "a b"))
(pr-str (keyword ""))
(pr-str (keyword "ns" "n"))
(pr-str (keyword "1"))
(pr-str (keyword nil "x"))
(pr-str 'a.b/c.d)
(pr-str '+)
(pr-str 'a?)
(pr-str 'a->b)
(pr-str '*x*)
(pr-str '.method)
(pr-str 'Class.)
(pr-str #"a\d+b")
(pr-str #"\"quoted\"")
(pr-str #"a/b")
(pr-str (re-pattern "x\ny"))
(str #"a\d")
(pr-str (re-pattern "\\Q.\\E"))
(pr-str #inst "2020-01-02T03:04:05.006Z")
(pr-str #uuid "00000000-0000-0000-0000-000000000001")
(pr-str (java.util.UUID. 1 2))
(pr-str (java.util.Date. 0))
(pr-str Long)
(pr-str String)
(pr-str arbace.lang.PersistentVector)
(pr-str (class (int-array 0)))
(pr-str 'nil)
(pr-str (symbol "nil"))
(pr-str (symbol "true"))
(pr-str (keyword "nil"))

;; ----- collections
(pr-str [])
(pr-str ())
(pr-str {})
(pr-str #{})
(pr-str [1 [2 [3 [4]]]])
(pr-str '(1 (2 (3))))
(pr-str {:a {:b {:c 1}}})
(pr-str #{#{1}})
(pr-str [nil nil])
(pr-str '(nil))
(pr-str {nil nil})
(pr-str #{nil})
(pr-str {[1 2] '(3 4)})
(pr-str {"str" \c 1.5 :x})
(pr-str (list 1 2 3))
(pr-str (list))
(pr-str (cons 0 [1 2]))
(pr-str (cons 0 nil))
(pr-str (seq [1 2 3]))
(pr-str (seq {:a 1}))
(pr-str (rseq [1 2 3]))
(pr-str (range 5))
(pr-str (range 0))
(pr-str (map inc [1 2]))
(pr-str (filter odd? (range 10)))
(pr-str (lazy-seq nil))
(pr-str (lazy-seq [1]))
(pr-str (take 3 (iterate inc 0)))
(pr-str (take 3 (cycle [:a :b])))
(pr-str (repeat 2 "x"))
(pr-str (concat [1] '(2) #{3}))
(pr-str (subvec [1 2 3 4] 1 3))
(pr-str (vector-of :int 1 2))
(pr-str (vec (int-array [1 2])))
(pr-str (first {:a 1}))
(pr-str (find {:a 1} :a))
(pr-str (map-entry? (first {:a 1})))
(pr-str (key (first {:a 1})))
(pr-str (keys {:a 1 :b 2}))
(pr-str (vals {:a 1 :b 2}))
(pr-str (keys {}))
(pr-str (sorted-map :b 2 :a 1 :c 3))
(pr-str (sorted-map))
(pr-str (sorted-set 3 1 2))
(pr-str (sorted-set-by > 3 1 2))
(pr-str (sorted-map-by > 1 :a 2 :b))
(pr-str (array-map :z 1 :a 2))
(pr-str (hash-map :a 1))
(pr-str (hash-set :a))
(pr-str (seq arbace.lang.PersistentQueue/EMPTY))
(pr-str (vec arbace.lang.PersistentQueue/EMPTY))
(pr-str (vec (conj arbace.lang.PersistentQueue/EMPTY 1 2 3)))
(pr-str (seq (conj arbace.lang.PersistentQueue/EMPTY 1 2 3)))
(pr-str (seq (pop (conj arbace.lang.PersistentQueue/EMPTY 1 2 3))))
(pr-str [(count (conj arbace.lang.PersistentQueue/EMPTY 1 2 3)) (hash (conj arbace.lang.PersistentQueue/EMPTY 1 2 3))])
(pr-str (peek (conj arbace.lang.PersistentQueue/EMPTY 1 2 3)))
(pr-str (persistent! (transient [1])))
(pr-str (zipmap [:a :b] [1 2]))
(pr-str (frequencies [:a :b :a]))
(pr-str (group-by odd? (range 5)))
(pr-str (partition 2 (range 5)))
(pr-str (partition-all 2 (range 5)))
(pr-str (split-at 2 [1 2 3]))
(pr-str (interleave [1 2] [:a :b]))
(pr-str (into (sorted-map) {3 :c 1 :a}))
(pr-str (tree-seq vector? seq [1 [2]]))
(pr-str (re-seq #"\w" "ab"))
(pr-str (vec (object-array 0)))
(print-str [1 "a" \b :c nil])
(print-str {:a "x"})
(print-str #{"s"})
(print-str '("a" \b))
(print-str (first {"k" "v"}))
(print-str (list 'quote 'x))
(pr-str ''x)
(pr-str '(quote x y))
(pr-str '@x)
(pr-str '#'x)
(pr-str '(var x))
(pr-str '`x)
(pr-str '~x)
(pr-str '#(+ % 1))
(pr-str (with-meta [1] {:m 1}))

;; ----- namespaced maps
(pr-str {:a/x 1 :a/y 2})
(pr-str {:a/x 1 :b/y 2})
(pr-str {:a/x 1 :y 2})
(pr-str {:a/x {:a/y 1}})
(pr-str {'a/x 1 'a/y 2})
(pr-str {:a/x 1 'a/y 2})
(pr-str {"a/x" 1})
(pr-str {::x 1 ::y 2})
(pr-str {:a/x 1})
(pr-str #:a{:x 1 :y 2})
(pr-str #:a{:x 1 :_/y 2})
(pr-str #:a{:x 1 :b/y 2})
(pr-str (sorted-map :a/x 1 :a/y 2))
(binding [*print-namespace-maps* false] (pr-str {:a/x 1 :a/y 2}))
(binding [*print-namespace-maps* true] (pr-str {:a/x 1 :a/y 2}))
(binding [*print-namespace-maps* true] (print-str {:a/x 1 :a/y 2}))
*print-namespace-maps*
(set! *print-namespace-maps* false)
(pr-str {:a/x 1 :a/y 2})
{:a/x 1 :a/y 2}
(set! *print-namespace-maps* true)
{:a/x 1 :a/y 2}
{}

;; ----- records and types
(defrecord Point [x y])
(->Point 1 2)
(pr-str (->Point 1 2))
(print-str (->Point 1 "s"))
(map->Point {:x 1 :y 2 :z 3})
(assoc (->Point 1 2) :z 3)
(dissoc (->Point 1 2) :x)
(pr-str (->Point {:a/x 1} [nil]))
(pr-str [(->Point 1 2)])
(binding [*print-namespace-maps* true] (pr-str (map->Point {:x 1 :y 2 :a/z 3})))
(defrecord Empty [])
(->Empty)
(defrecord Shape [kind])
(do (defmethod print-method Shape [s ^java.io.Writer w] (.write w (str "<shape " (name (:kind s)) ">"))) :defined)
(->Shape :circle)
(pr-str (->Shape :square))
(pr-str [(->Shape :a) (->Shape :b)])
(print-str (->Shape :c))
(deftype Pair [a b])
(.a (Pair. 1 2))
(do (defmethod print-method Pair [p ^java.io.Writer w] (.write w (str "#pair " (.a p) " " (.b p)))) :defined)
(pr-str (Pair. 1 2))
(Pair. :x :y)
(do (remove-method print-method Shape) :removed)
(pr-str (->Shape :plain))
(binding [*print-dup* true] (pr-str (->Point 1 2)))
(binding [*print-readably* false] (pr-str (->Point "a" \b)))
(record? (->Point 1 2))
(pr-str (into {} (->Point 1 2)))

;; ----- print-length and print-level
(binding [*print-length* 3] (pr-str (range 10)))
(binding [*print-length* 3] (pr-str [1 2 3]))
(binding [*print-length* 3] (pr-str [1 2 3 4]))
(binding [*print-length* 0] (pr-str [1 2]))
(binding [*print-length* 0] (pr-str []))
(binding [*print-length* 1] (pr-str {:a 1 :b 2}))
(binding [*print-length* 1] (pr-str #{1}))
(binding [*print-length* 2] (pr-str (iterate inc 0)))
(binding [*print-length* 2] (pr-str [[1 2 3] [4 5 6] [7]]))
(binding [*print-length* 2] (pr-str "abcdef"))
(binding [*print-length* 2] (print-str (range 5)))
(binding [*print-length* 2] (pr-str (->Point 1 2)))
(binding [*print-length* 1] (pr-str (->Point 1 2)))
(binding [*print-level* 0] (pr-str [1]))
(binding [*print-level* 0] (pr-str 1))
(binding [*print-level* 1] (pr-str [1 [2] 3]))
(binding [*print-level* 2] (pr-str [1 [2 [3 [4]]]]))
(binding [*print-level* 2] (pr-str {:a {:b {:c 1}}}))
(binding [*print-level* 1] (pr-str '(1 (2))))
(binding [*print-level* 1] (pr-str #{#{}}))
(binding [*print-level* 1 *print-length* 1] (pr-str [[1 2] [3]]))
(binding [*print-level* 1] (pr-str (->Point [1] 2)))
(set! *print-length* 4)
(range 100)
(pr-str (range 100))
[1 2 3 4 5 6]
{:a 1 :b 2 :c 3 :d 4 :e 5}
(str (range 100))
(set! *print-length* nil)
(range 6)
(set! *print-level* 2)
[1 [2 [3]]]
(set! *print-level* nil)
[1 [2 [3]]]

;; ----- print-meta
(binding [*print-meta* true] (pr-str (with-meta [1] {:tag 'foo})))
(binding [*print-meta* true] (pr-str (with-meta 'sym {:a 1})))
(binding [*print-meta* true] (pr-str (with-meta {:k 1} {:m true})))
(binding [*print-meta* true] (pr-str ^:private [1]))
(binding [*print-meta* true] (pr-str '^String s))
(binding [*print-meta* true] (pr-str [(with-meta [] {:x 1})]))
(binding [*print-meta* true] (print-str (with-meta [1] {:a 1})))
(binding [*print-meta* true] (pr-str (with-meta '(1) {:a 1})))
(binding [*print-meta* true] (pr-str (with-meta #{} {:a 1})))
(binding [*print-meta* true] (pr-str (with-meta [] {})))
(meta ^:foo [1])
(meta '^:foo s)
(meta ^{:a 1 :b 2} [])
(set! *print-meta* true)
(with-meta [1 2] {:m 1})
(pr-str (with-meta [1 2] {:m 1}))
(set! *print-meta* false)
(with-meta [1 2] {:m 1})

;; ----- print-dup
(binding [*print-dup* true] (pr-str 1))
(binding [*print-dup* true] (pr-str 1N))
(binding [*print-dup* true] (pr-str 1.5M))
(binding [*print-dup* true] (pr-str 1/2))
(binding [*print-dup* true] (pr-str "s"))
(binding [*print-dup* true] (pr-str :k))
(binding [*print-dup* true] (pr-str 'sym))
(binding [*print-dup* true] (pr-str [1 2]))
(binding [*print-dup* true] (pr-str (list 1 2)))
(binding [*print-dup* true] (pr-str {:a 1}))
(binding [*print-dup* true] (pr-str #{1}))
(binding [*print-dup* true] (pr-str (sorted-set 1 2)))
(binding [*print-dup* true] (pr-str (int 1)))
(binding [*print-dup* true] (pr-str (float 1.5)))
(binding [*print-dup* true] (pr-str 1.5))
(binding [*print-dup* true] (pr-str \a))
(binding [*print-dup* true] (pr-str nil))
(binding [*print-dup* true] (pr-str true))
(binding [*print-dup* true] (pr-str #"a.b"))
(binding [*print-dup* true] (pr-str Long))
(binding [*print-dup* true] (pr-str (with-meta [1] {:m 1})))
(binding [*print-dup* true] (pr-str (biginteger 5)))
(binding [*print-dup* true] (pr-str (java.util.Date. 0)))

;; ----- print-readably
(binding [*print-readably* false] (pr-str "a\nb"))
(binding [*print-readably* false] (pr-str \a))
(binding [*print-readably* false] (pr-str ["s" \c :k]))
(binding [*print-readably* false] (pr-str {"k" "v"}))
(binding [*print-readably* false] (prn-str "x"))
(binding [*print-readably* true] (print-str "x"))
(binding [*print-readably* nil] (pr-str "x" \y))
*print-readably*
*print-length*
*print-level*
*print-meta*
*print-dup*

;; ----- pprint
(with-out-str (pp/pprint [1 2 3]))
(with-out-str (pp/pprint {:a 1 :b 2}))
(with-out-str (pp/pprint nil))
(with-out-str (pp/pprint "str"))
(with-out-str (pp/pprint (range 30)))
(with-out-str (pp/pprint (zipmap (range 12) (map #(keyword (str "k" %)) (range 12)))))
(with-out-str (pp/pprint {:name "Arbace" :tags [:a :b :c] :nested {:deep {:deeper [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15]}}}))
(with-out-str (pp/pprint '(defn f [x] (let [y (* x x) z (+ y 1)] (if (pos? z) (println "positive" z) (println "non-positive" z))))))
(with-out-str (binding [pp/*print-right-margin* 20] (pp/pprint [:aaaa :bbbb :cccc :dddd :eeee])))
(with-out-str (binding [pp/*print-right-margin* 20] (pp/pprint {:aaaa 1 :bbbb 2 :cccc 3})))
(with-out-str (binding [pp/*print-right-margin* 10] (pp/pprint [[1 2] [3 4] [5 6]])))
(with-out-str (binding [pp/*print-right-margin* 120] (pp/pprint (vec (range 40)))))
(with-out-str (binding [*print-length* 5] (pp/pprint (range 100))))
(with-out-str (binding [*print-level* 2] (pp/pprint [1 [2 [3 [4]]]])))
(with-out-str (pp/pprint (sorted-set :z :y :x)))
(with-out-str (pp/pprint #{}))
(with-out-str (pp/pprint (->Point 1 2)))
(with-out-str (pp/pprint {:a/x 1 :a/y 2}))
(with-out-str (pp/pprint [\a "b\nc" 1.5 1/2 nil true]))
(with-out-str (pp/pprint (list 'quote 'x)))
(with-out-str (pp/pprint ''x))
(with-out-str (pp/pprint '@x))
(with-out-str (pp/pprint (vec (repeat 6 {:key "value" :other "thing"}))))
(with-out-str (pp/with-pprint-dispatch pp/code-dispatch (pp/pprint '(defn foo [a b] (cond (= a b) :eq (< a b) :lt :else :gt)))))
(with-out-str (pp/with-pprint-dispatch pp/code-dispatch (pp/pprint '(let [a 1 b 2 c 3 d 4 e 5 f 6 g 7 h 8 i 9] (+ a b c d e f g h i)))))
(with-out-str (pp/pp))
(pp/write [1 2] :stream nil)
(pp/write {:a 1} :stream nil :pretty false)
(with-out-str (pp/print-table [{:a 1 :b 2} {:a 3 :b 4}]))
(with-out-str (pp/print-table [:b] [{:a 1 :b "x"} {:a 3 :b "yy"}]))
(with-out-str (pp/print-table []))

;; ----- cl-format
(pp/cl-format nil "~a" "s")
(pp/cl-format nil "~s" "s")
(pp/cl-format nil "~a and ~a" 1 :k)
(pp/cl-format nil "~d" 1234567)
(pp/cl-format nil "~:d" 1234567)
(pp/cl-format nil "~5d|" 42)
(pp/cl-format nil "~5,'0d" 42)
(pp/cl-format nil "~b" 10)
(pp/cl-format nil "~o" 8)
(pp/cl-format nil "~x" 255)
(pp/cl-format nil "~:@x" 255)
(pp/cl-format nil "~r" 42)
(pp/cl-format nil "~:r" 42)
(pp/cl-format nil "~@r" 1999)
(pp/cl-format nil "~:@r" 4)
(pp/cl-format nil "~36r" 1295)
(pp/cl-format nil "~,2f" 3.14159)
(pp/cl-format nil "~8,3f|" 3.14159)
(pp/cl-format nil "~e" 12345.678)
(pp/cl-format nil "~$" 3.5)
(pp/cl-format nil "~{~a~^, ~}" [1 2 3])
(pp/cl-format nil "~{~a=~a~^; ~}" [:a 1 :b 2])
(pp/cl-format nil "~[zero~;one~;two~:;many~]" 1)
(pp/cl-format nil "~[zero~;one~;two~:;many~]" 7)
(pp/cl-format nil "~:[no~;yes~]" true)
(pp/cl-format nil "~:[no~;yes~]" nil)
(pp/cl-format nil "~d item~:p" 1)
(pp/cl-format nil "~d item~:p" 3)
(pp/cl-format nil "~@(~a~)" "hello world")
(pp/cl-format nil "~:@(~a~)" "hello world")
(pp/cl-format nil "~(~a~)" "HeLLo")
(pp/cl-format nil "~10a|" "left")
(pp/cl-format nil "~10@a|" "right")
(pp/cl-format nil "~%a~%b")
(pp/cl-format nil "~~")
(pp/cl-format nil "~c" \x)
(pp/cl-format nil "~@c" \x)
(pp/cl-format nil "~:c" \space)
(pp/cl-format nil "~a" nil)
(pp/cl-format nil "~a" [1 "s" \c])
(pp/cl-format nil "~s" [1 "s" \c])
(pp/cl-format nil "~z" 1)
(pp/cl-format nil "~a ~a" 1)
(with-out-str (pp/cl-format true "to out ~a" 1))
(pp/cl-format nil "~d" 12345678901234567890N)
(pp/cl-format nil "~d" 1/2)
(pp/cl-format nil "~:d" -1234567)
(pp/cl-format nil "~@d" 5)
