;; The reader: read-string of every literal, macro characters, syntax-quote, reader
;; conditionals, tagged literals, arbace.edn, and reader errors.

(require '[arbace.edn :as edn])
(require '[arbace.string :as str])

;; ----- numbers
(read-string "42")
(read-string "-42")
(read-string "+42")
(read-string "0")
(read-string "-0")
(read-string "42N")
(read-string "1.5")
(read-string "-1.5e3")
(read-string "1E3")
(read-string "1.5M")
(read-string "1M")
(read-string "1e3M")
(read-string "1/2")
(read-string "-3/6")
(read-string "4/2")
(class (read-string "4/2"))
(read-string "0x1F")
(read-string "0X1f")
(read-string "-0x1F")
(read-string "017")
(read-string "0")
(read-string "08")
(read-string "019")
(read-string "2r1111")
(read-string "36rZ")
(read-string "-16rFF")
(read-string "16r-FF")
(read-string "0r1")
(read-string "1r1")
(read-string "1e")
(read-string "1e+")
(read-string "0x")
(read-string "0xG")
(read-string ".5")
(read-string "5.")
(class (read-string "5."))
(read-string "-.5")
(read-string "1..2")
(read-string "1.2.3")
(read-string "1a")
(read-string "1/")
(read-string "/2")
(read-string "1/2/3")
(read-string "1.0/2")
(read-string "##Inf")
(read-string "##-Inf")
(read-string "##NaN")
(read-string "##Foo")
(read-string "##")
(read-string "9223372036854775807")
(read-string "9223372036854775808")
(read-string "-9223372036854775808")
(class (read-string "-9223372036854775808"))
(read-string "0x8000000000000000")
(read-string "1e400")
(read-string "-1e400")
(read-string "1e-400")
(read-string "007")
(read-string "0.0001")
(read-string "00.5")
(read-string "1N/2")

;; ----- characters
(read-string "\\a")
(read-string "\\A")
(read-string "\\newline")
(read-string "\\space")
(read-string "\\tab")
(read-string "\\return")
(read-string "\\backspace")
(read-string "\\formfeed")
(read-string "\\u0041")
(read-string "\\u00e9")
(read-string "\\ud83d")
(int (read-string "\\ud83d"))
(read-string "\\o101")
(read-string "\\o0")
(read-string "\\o400")
(read-string "\\o9")
(read-string "\\u12")
(read-string "\\uXYZW")
(read-string "\\foo")
(read-string "\\")
(read-string "\\\\")
(read-string "\\(")
(read-string "\\ ")
(read-string "\\é")
(read-string "\\😀")
(read-string "[\\a\\b]")
(read-string "\\abc")
(read-string "\\n")
(read-string "\\nl")
(read-string "\\u")
(read-string "\\o")
(read-string "\\uD800")

;; ----- strings
(read-string "\"abc\"")
(read-string "\"\"")
(read-string "\"a\\nb\"")
(read-string "\"a\\tb\"")
(read-string "\"a\\rb\"")
(read-string "\"a\\bb\"")
(read-string "\"a\\fb\"")
(read-string "\"q\\\"q\"")
(read-string "\"back\\\\slash\"")
(read-string "\"\\u0041\\u00e9\"")
(read-string "\"\\ud83d\\ude00\"")
(count (read-string "\"\\ud83d\\ude00\""))
(read-string "\"\\ud83d\"")
(read-string "\"\\101\"")
(read-string "\"\\0\"")
(read-string "\"\\377\"")
(read-string "\"\\400\"")
(read-string "\"\\8\"")
(read-string "\"\\x\"")
(read-string "\"\\u12\"")
(read-string "\"\\uGGGG\"")
(read-string "\"unterminated")
(read-string "\"multi\nline\"")
(read-string "\"tab\tinside\"")
(read-string "\"é😀\"")

;; ----- keywords and symbols
(read-string ":a")
(read-string ":a/b")
(read-string ":a.b/c")
(read-string "::a")
(read-string "::a/b")
(read-string "::str/x")
(read-string "::nope/x")
(read-string ":")
(read-string "::")
(read-string ":a:")
(read-string ":a:b")
(read-string ":1")
(read-string ":a/")
(read-string ":/a")
(read-string ":/")
(read-string ":a/b/c")
(read-string ":::a")
(read-string ":a#")
(read-string ":é")
(namespace (read-string ":a/b"))
(name (read-string ":a/b"))
(namespace (read-string "::a"))
(read-string "a")
(read-string "a/b")
(read-string "a.b/c")
(read-string "a/b/c")
(read-string "a/")
(read-string "/")
(read-string "a//")
(read-string "arbace.core//")
(read-string "/a")
(read-string "a:b")
(read-string "a:")
(read-string "a::b")
(read-string "a#")
(read-string "a'b")
(read-string "+a")
(read-string "-a")
(read-string "+1a")
(read-string ".a")
(read-string "a.")
(read-string "..")
(read-string "*a*")
(read-string "<=>")
(read-string "a?!")
(read-string "é")
(read-string "😀")
(read-string "nil")
(read-string "true")
(read-string "false")
(class (read-string "nil"))
(read-string "nil/a")
(read-string "true/a")
(read-string "a/nil")
(read-string "Nil")
(read-string "a$b")
(read-string "a%b")
(read-string "a&b")
(read-string "&")
(read-string "%")
(read-string "%1")
(namespace (read-string "a/b"))
(namespace (read-string "a/b/c"))
(name (read-string "a/b/c"))

;; ----- collections
(read-string "()")
(read-string "[]")
(read-string "{}")
(read-string "#{}")
(read-string "(1 2 3)")
(class (read-string "(1 2 3)"))
(class (read-string "()"))
(read-string "[1 [2 (3 {4 #{5}})]]")
(read-string "{:a 1 :b 2}")
(read-string "{:a 1, :b 2,}")
(read-string ",,,[1,,2],,,")
(read-string "{:a}")
(read-string "{:a 1 :a 2}")
(read-string "#{1 1}")
(read-string "#{1 2 1}")
(read-string "{1 1 1.0 2}")
(read-string "#{[1] [1]}")
(read-string "(1 2")
(read-string "[1 2")
(read-string "{:a 1")
(read-string "#{1")
(read-string ")")
(read-string "]")
(read-string "}")
(read-string "(]")
(read-string "[)")
(read-string "")
(read-string "   ")
(read-string ";; only a comment")
(read-string "1 2")
(read-string "(1 ; comment\n 2)")
(read-string "#!shebang\n5")
(read-string "#:a{:x 1 :y 2}")
(read-string "#:a{:x 1 :b/y 2 :_/z 3}")
(read-string "#:a{x 1}")
(read-string "#::{:x 1}")
(read-string "#::str{:x 1}")
(read-string "#:a {:x 1}")
(read-string "#:a[1]")
(read-string "#:{:x 1}")
(read-string "#:a{:x 1 :x 2}")
(class (read-string "{:a 1 :b 2 :c 3 :d 4 :e 5 :f 6 :g 7 :h 8 :i 9}"))
(class (read-string "{:a 1}"))
(count (read-string "[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]"))

;; ----- metadata
(meta (read-string "^:foo [1]"))
(meta (read-string "^{:a 1} [1]"))
(meta (read-string "^String x"))
(meta (read-string "^\"java.lang.String\" x"))
(meta (read-string "^[String] x"))
(meta (read-string "^:a ^:b [1]"))
(meta (read-string "^{:a 1} ^{:a 2} [1]"))
(meta (read-string "^:foo (1 2)"))
(meta (read-string "^:foo {:a 1}"))
(meta (read-string "^:foo #{1}"))
(read-string "^:foo 1")
(read-string "^1 [1]")
(read-string "^:foo")
(meta (read-string "(a b)"))
(meta (read-string "[a b]"))
(meta (read-string "^:foo a"))
(binding [*print-meta* true] (pr-str (read-string "^:foo [^:bar a]")))

;; ----- discard and comments
(read-string "#_1 2")
(read-string "#_ #_ 1 2 3")
(read-string "[1 #_2 3]")
(read-string "[1 #_ (2 3) 4]")
(read-string "{:a #_:b 1}")
(read-string "#_1")
(read-string "(comment 1 2)")
(read-string "[1 #_]")

;; ----- quote and syntax-quote
(read-string "'a")
(read-string "'(1 2)")
(read-string "''a")
(read-string "'")
(read-string "`a")
(read-string "`str/join")
(read-string "`map")
(read-string "`arbace.core/map")
(read-string "`String")
(read-string "`java.lang.String")
(read-string "`String.")
(read-string "`.method")
(read-string "`nope/x")
(read-string "`:k")
(read-string "`1")
(read-string "`\"s\"")
(read-string "`nil")
(read-string "`(a ~b)")
(read-string "`(a ~@b)")
(read-string "`[1 ~x]")
(read-string "`{:a ~x}")
(read-string "`#{~x}")
(read-string "`()")
(read-string "`[]")
(read-string "`(quote x)")
(read-string "`~x")
(read-string "~x")
(read-string "~@x")
(read-string "`(~@a)")
(read-string "``a")
(read-string "`&")
(read-string "`if")
(read-string "`recur")
(read-string "`def")
(read-string "`fn*")
(read-string "`a.b")
(read-string "`a.b/c")
(read-string "`^:m [x]")
(eval (read-string "(let [x 1 y [2 3]] `(a ~x ~@y))"))
(let [x 1 y [2 3]] `(a ~x ~@y))
(let [x 1] `[x ~x])
(let [xs []] `(f ~@xs))
`map
`(map inc)
`str/join
`nope/x
`String
`[:a "s" 1 nil true]
`{:k ~(+ 1 2)}
(let [s 'sym] `(quote ~s))
(first `(x# y#))
(= (first `(x# x#)) (second `(x# x#)))
(name (first `(a# a#)))
(str/starts-with? (name (first `(abc#))) "abc__")
(str/ends-with? (name (first `(abc#))) "__auto__")

;; ----- deref, var, fn literals
(read-string "@a")
(read-string "@@a")
(read-string "#'a")
(read-string "#'a/b")
(read-string "#(+ 1 2)")
(read-string "#(+ % %2)")
(read-string "#(+ %1 %3)")
(read-string "#(apply + %&)")
(read-string "#(list % %&)")
(read-string "#(vector %)")
(read-string "#(%)")
(read-string "#()")
(read-string "#(#(%))")
(read-string "#(%0)")
(read-string "#(%a)")
(read-string "%")
(read-string "#(%21)")
(#(+ % %2) 1 2)
(#(vector %&) 1 2)
(#(do %3) 1 2 3)
(#(identity %&))
(read-string "#\"a+b\"")
(class (read-string "#\"a+b\""))
(str (read-string "#\"\\d+\""))
(str (read-string "#\"\\\"\""))
(read-string "#\"[\"")
(read-string "#\"(\"")
(read-string "#\"\\u0041\"")
(str (read-string "#\"\\u0041\""))
(read-string "#\"unterminated")
(read-string "#")
(read-string "#?")
(read-string "#!")
(read-string "#=")
(read-string "#<foo>")
(read-string "#foo")
(read-string "#foo 1")
(read-string "#foo/bar 1")
(read-string "#^:a [1]")

;; ----- reader conditionals
(read-string "#?(:clj 1 :cljs 2)")
(read-string {:read-cond :allow} "#?(:clj 1 :cljs 2)")
(read-string {:read-cond :allow} "#?(:cljs 2 :clj 1)")
(read-string {:read-cond :allow} "#?(:cljs 2)")
(read-string {:read-cond :allow} "[1 #?(:cljs 2) 3]")
(read-string {:read-cond :allow} "#?(:cljs 2 :default 3)")
(read-string {:read-cond :allow} "#?(:default 3 :clj 1)")
(read-string {:read-cond :allow} "[#?@(:clj [1 2] :cljs [3])]")
(read-string {:read-cond :allow} "#?@(:clj [1 2])")
(read-string {:read-cond :allow} "[#?@(:clj 1)]")
(read-string {:read-cond :allow} "#?(:clj)")
(read-string {:read-cond :allow} "#?(:clj 1 :cljs)")
(read-string {:read-cond :allow} "#?[:clj 1]")
(read-string {:read-cond :allow} "#?(clj 1)")
(read-string {:read-cond :allow} "#?(:clj #?(:clj 1))")
(read-string {:read-cond :allow :features #{:cljs}} "#?(:cljs 2 :clj 1)")
(read-string {:read-cond :allow :features #{:foo}} "#?(:foo 3 :clj 1)")
(read-string {:read-cond :preserve} "#?(:clj 1 :cljs 2)")
(class (read-string {:read-cond :preserve} "#?(:clj 1 :cljs 2)"))
(read-string {:read-cond :preserve} "#?@(:clj [1 2])")
(read-string {:read-cond :preserve} "[#?@(:clj [1 2])]")
(:form (read-string {:read-cond :preserve} "#?(:clj 1 :cljs 2)"))
(:splicing? (read-string {:read-cond :preserve} "#?@(:clj [1])"))
(read-string {:read-cond :preserve} "#foo [1]")
(class (read-string {:read-cond :preserve} "#foo [1]"))
(read-string {:read-cond :bogus} "#?(:clj 1)")
(read-string {:eof :done} "")
(read-string {:eof nil} "")
(read-string {} "")
(read-string {:read-cond :allow} "#?(:clj 1 :clj 2)")
(reader-conditional '(:clj 1) false)
(reader-conditional? (reader-conditional '(:clj 1) false))
(tagged-literal 'foo [1])
(tagged-literal? (tagged-literal 'foo [1]))
(:tag (tagged-literal 'foo [1]))
(:form (tagged-literal 'foo [1]))

;; ----- tagged literals
(read-string "#inst \"2020-01-01T00:00:00Z\"")
(class (read-string "#inst \"2020-01-01T00:00:00Z\""))
(read-string "#inst \"2020\"")
(read-string "#inst \"nope\"")
(read-string "#inst 5")
(read-string "#uuid \"00000000-0000-0000-0000-000000000000\"")
(class (read-string "#uuid \"00000000-0000-0000-0000-000000000000\""))
(read-string "#uuid \"not-a-uuid\"")
(read-string "#uuid 1")
(read-string "#unknown/tag 1")
(binding [*data-readers* {'my/tag (fn [x] [:tagged x])}] (read-string "#my/tag 5"))
(binding [*data-readers* {'my/tag (fn [x] (* 2 x))}] (read-string "[#my/tag 5 #my/tag 6]"))
(binding [*data-readers* {'my/tag (fn [x] (throw (ex-info "bad" {:x x})))}] (read-string "#my/tag 5"))
(binding [*data-readers* {'inst (fn [x] [:my-inst x])}] (read-string "#inst \"2020\""))
(binding [*default-data-reader-fn* (fn [t v] [:default t v])] (read-string "#any/thing [1 2]"))
(binding [*default-data-reader-fn* (fn [t v] [:default t v])] (read-string "#inst \"2020-01-01\""))
(binding [*default-data-reader-fn* tagged-literal] (read-string "#x/y {:a 1}"))
(binding [*default-data-reader-fn* tagged-literal] (pr-str (read-string "#x/y {:a 1}")))
(binding [*data-readers* {'my/tag (fn [x] x)}] (read-string "#my/tag"))
(binding [*default-data-reader-fn* (fn [t v] nil)] (read-string "#a/b 1"))

;; ----- read-eval
(read-string "#=(+ 1 2)")
(read-string "#=(list 1 2)")
(read-string "#=java.lang.Long")
(read-string "#=(java.lang.Long. \"5\")")
(binding [*read-eval* false] (read-string "#=(+ 1 2)"))
(binding [*read-eval* false] (read-string "[1 2]"))
(binding [*read-eval* :unknown] (read-string "[1 2]"))
*read-eval*

;; ----- read with options and readers
(read (java.io.PushbackReader. (java.io.StringReader. "[1 2] 3")))
(let [r (java.io.PushbackReader. (java.io.StringReader. "1 2"))] [(read r) (read r) (read r false :eof)])
(let [r (java.io.PushbackReader. (java.io.StringReader. ""))] (read r))
(let [r (java.io.PushbackReader. (java.io.StringReader. "a"))] (read {:eof :e} r))
(let [r (arbace.lang.LineNumberingPushbackReader. (java.io.StringReader. "\n\n(a\n b)"))] (meta (read r)))
(read+string (arbace.lang.LineNumberingPushbackReader. (java.io.StringReader. "  (a b) c")))
(load-string "(+ 1 2) (* 3 4)")
(load-string "")
(load-string "(def from-load 7)")
from-load

;; ----- arbace.edn
(edn/read-string "{:a [1 2.5 \"s\" \\c nil true]}")
(edn/read-string "")
(edn/read-string nil)
(edn/read-string {:eof :end} "")
(edn/read-string "1 2")
(edn/read-string "#inst \"2020-01-01T00:00:00.000-00:00\"")
(edn/read-string "#uuid \"00000000-0000-0000-0000-000000000001\"")
(edn/read-string "#my/tag 1")
(edn/read-string {:readers {'my/tag inc}} "#my/tag 1")
(edn/read-string {:readers {'my/tag inc}} "[#my/tag 1 #my/tag 2]")
(edn/read-string {:default (fn [t v] [t v])} "#x/y 1")
(edn/read-string {:readers {'inst str}} "#inst \"2020\"")
(edn/read-string "#=(+ 1 2)")
(edn/read-string "::a")
(edn/read-string "`a")
(edn/read-string "'a")
(edn/read-string "@a")
(edn/read-string "#(inc %)")
(edn/read-string "#'a")
(edn/read-string "#\"re\"")
(edn/read-string "^:m [1]")
(meta (edn/read-string "^:m [1]"))
(edn/read-string "#_ 1 2")
(edn/read-string "#{1 1}")
(edn/read-string "{:a 1 :a 2}")
(edn/read-string "#?(:clj 1)")
(edn/read-string "1/2")
(edn/read-string "1N")
(edn/read-string "1.5M")
(edn/read-string "0x10")
(edn/read-string "017")
(edn/read-string "2r101")
(edn/read-string "##Inf")
(edn/read-string "\\newline")
(edn/read-string "\\u0041")
(edn/read-string "\"\\u00e9\"")
(edn/read-string ":a/b")
(edn/read-string "a/b")
(edn/read-string "#:a{:x 1}")
(edn/read-string "(1 (2))")
(edn/read-string "(")
(edn/read-string "}")
(edn/read-string "#{")
(edn/read-string "nil")
(edn/read-string "  true  ")
