;; Sequence functions, laziness and chunking, transducers, higher-order helpers.

;; ----- map, mapcat, filter, keep
(map inc [1 2 3])
(map + [1 2 3] [10 20 30])
(map + [1 2 3] [10 20])
(map vector [1 2] [:a :b] ["x" "y"])
(map list [1 2 3] [4 5 6] [7 8 9] [10 11 12])
(map inc nil)
(map inc [])
(class (map inc [1]))
(map first [[1 2] [3 4]])
(map #(* % %) (range 5))
(map :a [{:a 1} {:a 2} {}])
(map str "abc")
(map inc {1 2})
(map inc 5)
(mapcat reverse [[1 2] [3 4]])
(mapcat identity [[1] [] [2 3]])
(mapcat (fn [x y] [x y]) [1 2] [:a :b])
(mapcat seq ["ab" "cd"])
(filter even? (range 10))
(filter even? nil)
(filter identity [1 nil false 2])
(filter (set "aeiou") "education")
(filterv odd? (range 10))
(remove even? (range 10))
(remove nil? [1 nil 2])
(keep #(when (odd? %) (* % %)) (range 10))
(keep identity [1 nil false 2])
(keep-indexed (fn [i x] (when (even? i) x)) [:a :b :c :d :e])
(keep-indexed (fn [i x] (if (odd? i) false nil)) [1 2 3])
(map-indexed vector [:a :b :c])
(map-indexed (fn [i x] (* i x)) [5 5 5])
(mapv + [1 2] [3 4] [5 6])

;; ----- reduce, reductions
(reduce + [])
(reduce + [5])
(reduce + 10 [])
(reduce + (range 101))
(reduce * 1 (range 1 11))
(reduce conj [] '(1 2 3))
(reduce (fn [a x] (if (> a 10) (reduced a) (+ a x))) 0 (range 100))
(reduce (fn [a x] (reduced :early)) 0 [1 2])
(reduce (fn [a x] (reduced :early)) 0 [])
(reduce max [3 9 2])
(reduce str "" ["a" "b"])
(reduce + nil)
(reduce (fn [] :zero) [])
(reduce (fn [acc [k v]] (+ acc v)) 0 {:a 1 :b 2})
(reduce + (map inc (range 10)))
(reduce + 0 (range 10 0 -1))
(reductions + [1 2 3 4])
(reductions + 100 [1 2 3])
(reductions + [])
(reductions + 5 [])
(reductions (fn [a x] (if (> a 3) (reduced a) (+ a x))) [1 1 1 1 1 1])
(reductions conj [] [1 2 3])
(reduced? (reduced 1))
(deref (reduced 1))
(unreduced (reduced 2))
(unreduced 3)
@(ensure-reduced (reduced 4))
(reduced? (ensure-reduced 4))
(class (ensure-reduced 4))

;; ----- take, drop and friends
(take 3 (range 10))
(take 0 [1 2])
(take -1 [1 2])
(take 10 [1 2])
(take 3 nil)
(drop 3 (range 6))
(drop 0 [1 2])
(drop -5 [1 2])
(drop 10 [1 2])
(take-while neg? [-2 -1 0 1 -3])
(take-while neg? [])
(drop-while neg? [-2 -1 0 1 -3])
(drop-while pos? [1 2])
(take-last 2 [1 2 3 4])
(take-last 0 [1 2])
(take-last 5 [1 2])
(take-last 2 nil)
(drop-last [1 2 3 4])
(drop-last 2 [1 2 3 4])
(drop-last 10 [1 2])
(drop-last -1 [1 2])
(take-nth 2 (range 10))
(take-nth 3 [1 2 3 4 5 6 7])
(take 5 (take-nth 0 [1 2]))
(take 3 (take-nth -1 [1 2]))
(nthrest (range 10) 7)
(nthrest [1 2] 5)
(nthrest [1 2] 0)
(nthnext (range 10) 7)
(nthnext [1 2] 5)
(nthnext [] 0)
(split-at 2 [1 2 3 4 5])
(split-at 0 [1 2])
(split-at 9 [1 2])
(split-with odd? [1 3 4 5 7])
(split-with odd? [])

;; ----- partition
(partition 2 (range 7))
(partition 3 1 (range 5))
(partition 2 3 (range 10))
(partition 3 3 [:pad] (range 7))
(partition 3 3 [:a :b :c :d] (range 7))
(partition 3 3 [] (range 7))
(partition 3 3 nil (range 7))
(partition 4 2 (range 10))
(partition 1 [])
(partition 5 [1 2])
(partition 5 5 [:p] [1 2])
(take 3 (partition 0 [1 2]))
(partition-all 3 (range 8))
(partition-all 3 1 (range 5))
(partition-all 2 4 (range 9))
(partition-all 2 [])
(partition-by odd? [1 3 2 4 5 6 6 7])
(partition-by identity "aabbbcdda")
(partition-by identity [])
(partition-by count ["a" "b" "cc" "d"])
(class (first (partition 2 [1 2])))
(class (first (partition-all 2 [1 2])))

;; ----- combining
(interleave [1 2 3] [:a :b :c])
(interleave [1 2 3] [:a])
(interleave [1 2] [:a :b] ["x" "y"])
(interleave [1 2])
(interleave)
(interpose ", " ["a" "b" "c"])
(interpose :x [])
(interpose :x [1])
(apply str (interpose "-" (range 5)))
(concat [1 2] '(3) nil [4 5] "ab")
(concat)
(concat nil nil)
(class (concat [1]))
(lazy-cat [1 2] [3])
(flatten [1 [2 [3 [4]]] '(5 (6))])
(flatten [])
(flatten nil)
(flatten 5)
(flatten {:a [1 2]})
(flatten [{:a 1} #{2}])
(flatten [[[]]])
(distinct [1 2 1 3 2 4])
(distinct [])
(distinct [1 1.0 1N (int 1)])
(distinct [[1] '(1) [2]])
(dedupe [1 1 2 2 2 1 3 3])
(dedupe [])
(dedupe [nil nil 1])
(sort [3 1 2])
(sort > [3 1 2])
(sort ["b" "A" "a" "B"])
(sort [nil 2 1])
(sort [[1 2] [1] []])
(sort [:b :a :c/a :a/z])
(sort [1 "a"])
(sort-by count ["ccc" "a" "bb"])
(sort-by - [1 3 2])
(sort-by :n > [{:n 1} {:n 3} {:n 2}])
(sort-by first [[2 :a] [1 :b] [2 :c] [1 :d]])
(sort-by identity compare [3 1])
(sort (comparator <) [3 1 2])
(sort #(compare %2 %1) [1 3 2])
(reverse [1 2 3])
(reverse nil)
(reverse "abc")
(group-by odd? [1 2 3])
(frequencies [[1] [1] '(1)])

;; ----- predicates on seqs
(some even? [1 3 4 5])
(some even? [1 3])
(some #{3 4} [1 2 3])
(some :a [{:b 1} {:a 2}])
(some identity [nil false])
(some even? nil)
(every? even? [2 4])
(every? even? [2 3])
(every? even? [])
(every? even? nil)
(not-any? even? [1 3])
(not-any? even? [1 2])
(not-every? even? [2 4])
(not-every? even? [1 2])
(every? #{1 2} [1 2 1])

;; ----- first, second, last ...
(first [1 2 3])
(first nil)
(first "abc")
(first {:a 1})
(first #{})
(second [1 2 3])
(second [1])
(last [1 2 3])
(last [])
(last nil)
(butlast [1 2 3])
(butlast [1])
(butlast nil)
(ffirst [[1 2] [3]])
(fnext [1 2 3])
(nfirst [[1 2] [3]])
(nnext [1 2 3 4])
(nnext [1 2])
(rest [1])
(rest nil)
(next [1])
(next nil)
(class (rest [1 2 3]))
(cons 1 nil)
(cons 1 [2 3])
(cons nil nil)
(cons 1 (cons 2 nil))
(class (cons 1 nil))
(conj (seq [1 2]) 0)
(conj (range 3) :x)
(conj (map inc [1 2]) 0)
(conj (cons 1 nil) 0)
(first (first (first [[[1]]])))

;; ----- range
(range 5)
(range 0)
(range -3)
(range 2 8)
(range 8 2)
(range 2 2)
(range 0 10 3)
(range 10 0 -3)
(range 10 0 -1)
(range 0 10 -1)
(range 0 -10 -2)
(take 5 (range 0 10 0))
(take 5 (range 3 3 0))
(range 0 1 0.25)
(range 1.5 4)
(range 0.1 0.5 0.1)
(range 1/2 3)
(range 0 1 1/3)
(range 1N 5N)
(range 1 2 1/2)
(range 1.0 0.0 -0.5)
(take 5 (range))
(nth (range) 1000000)
(class (range 5))
(class (range 0.5 5))
(class (range))
(count (range 5))
(count (range 10 0 -3))
(count (range 0 1 0.1))
(count (range 1000000))
(count (range 0 100 7))
(nth (range 10) 3)
(nth (range 10) 10)
(nth (range 10) 10 :nf)
(nth (range 0 100 7) 5)
(nth (range 10 0 -2) 2)
(nth (range 1/2 3) 1)
(reduce + (range 1000))
(reduce + (range 0.5 5))
(reduce + 0 (range 10 0 -1))
(apply + (range 1/3 3))
(seq (range 0))
(seq (range 1))
(rest (range 1))
(next (range 1))
(last (range 1000))
(range 9223372036854775800 9223372036854775807 3)
(count (range 9223372036854775800 9223372036854775807))
(range 9223372036854775806 9223372036854775807)
(range -9223372036854775807 -9223372036854775806)
(= (range 5) [0 1 2 3 4])
(hash (range 5))
(hash (range 100))
(empty (range 5))
(take 3 (drop 5 (range)))
(range 5 :a)

;; ----- repeat, iterate, cycle, repeatedly
(repeat 3 :x)
(repeat 0 :x)
(repeat -1 :x)
(take 4 (repeat 7))
(count (repeat 5 nil))
(class (repeat 3 1))
(class (repeat 1))
(reduce + (repeat 10 3))
(nth (repeat 5 :x) 4)
(take 5 (iterate inc 0))
(take 6 (iterate #(* 2 %) 1))
(take 4 (iterate (fn [[a b]] [b (+ a b)]) [0 1]))
(nth (iterate inc 0) 100)
(class (iterate inc 0))
(reduce (fn [a x] (if (> x 10) (reduced a) (+ a x))) 0 (iterate inc 0))
(take 7 (cycle [1 2 3]))
(cycle [])
(take 3 (cycle nil))
(class (cycle [1]))
(take 5 (drop 1000 (cycle (range 7))))
(let [n (atom 0)] (doall (repeatedly 4 #(swap! n inc))))
(let [n (atom 0)] (take 3 (repeatedly #(swap! n + 10))))
(repeatedly 0 (constantly 1))
(let [n (volatile! 0)] [(vec (repeatedly 3 #(vswap! n inc))) @n])

;; ----- laziness, side effects and chunking
(let [s (map (fn [x] (println "m" x) x) [1 2 3])] (println "before") (first s))
(first (map (fn [x] (println "realize" x) x) (range 100)))
(first (map (fn [x] (println "unchunked" x) x) (iterate inc 0)))
(first (map (fn [x] (println "list" x) x) '(1 2 3 4)))
(take 2 (map (fn [x] (println "v" x) x) [1 2 3 4 5]))
(doall (take 2 (map (fn [x] (println "vd" x) x) [1 2 3 4 5])))
(dorun (map println [1 2]))
(dorun 1 (map (fn [x] (println "dr" x)) '(1 2 3 4)))
(doall 2 (map (fn [x] (println "da" x) x) '(1 2 3 4)))
(let [s (lazy-seq (println "realizing") [1 2])] (println "created") (realized? s))
(let [s (lazy-seq (println "realizing") [1 2])] (first s) (realized? s))
(realized? (range 5))
(realized? (iterate inc 0))
(realized? (map inc [1]))
(let [s (map inc [1])] (seq s) (realized? s))
(realized? (delay 1))
(realized? (cycle [1]))
(let [c (atom 0) s (map (fn [x] (swap! c inc) x) (range 100))] (first s) @c)
(let [c (atom 0) s (map (fn [x] (swap! c inc) x) (range 100))] (nth s 32) @c)
(let [c (atom 0) s (filter (fn [x] (swap! c inc) true) (vec (range 50)))] (first s) @c)
(let [c (atom 0) s (map (fn [x] (swap! c inc) x) (seq (vec (range 70))))] (doall (take 40 s)) @c)
(let [c (atom 0)] (first (mapcat (fn [x] (swap! c inc) [x]) (range 100))) @c)
(let [c (atom 0)] (dorun (take 5 (map (fn [x] (swap! c inc)) (iterate inc 0)))) @c)
(chunked-seq? (seq (range 10)))
(chunked-seq? (seq [1 2]))
(chunked-seq? (seq '(1 2)))
(chunked-seq? (map inc (range 10)))
(chunked-seq? (seq (map inc (range 10))))
(let [s (seq (vec (range 40)))] [(count (chunk-first s)) (first (chunk-rest s))])
(take 3 (lazy-seq (cons 1 (lazy-seq (cons 2 nil)))))
(letfn [(nat [n] (lazy-seq (cons n (nat (inc n)))))] (take 5 (nat 0)))
(let [fib ((fn fib [a b] (lazy-seq (cons a (fib b (+' a b))))) 0 1)] (nth fib 90))
(seq [])
(seq "")
(seq {})
(seq #{})
(seq nil)
(seq '())
(seq (int-array 0))
(seq (java.util.ArrayList.))
(seq (range 0))
(seq (lazy-seq nil))
(seq 1)
(seq :k)
(seq (java.util.ArrayList. [1 2]))
(seq (doto (java.util.LinkedHashMap.) (.put 1 2)))
(sequence nil)
(sequence [1 2])
(class (sequence [1 2]))

;; ----- transducers
(transduce (map inc) + [1 2 3])
(transduce (map inc) + 100 [1 2 3])
(transduce (filter odd?) conj [] (range 10))
(transduce (comp (map inc) (filter even?)) + (range 10))
(transduce (comp (filter even?) (map inc)) conj (range 10))
(transduce (take 3) conj (range 100))
(transduce (comp (map inc) (take 2)) + (range 100))
(transduce (partition-all 3) conj (range 8))
(transduce (partition-by odd?) conj [1 3 2 4 5])
(transduce cat conj [[1 2] [3]])
(transduce (mapcat reverse) conj [[1 2] [3 4]])
(transduce (dedupe) conj [1 1 2 1 1])
(transduce (distinct) conj [1 2 1 3 2])
(transduce (interpose :x) conj [1 2 3])
(transduce (halt-when neg?) conj [1 2 -3 4])
(transduce (halt-when neg? (fn [r x] [:halted r x])) conj [1 2 -3 4])
(transduce (halt-when neg?) conj [1 2 3])
(transduce (keep #(when (odd? %) %)) conj (range 6))
(transduce (map-indexed vector) conj [:a :b])
(transduce (keep-indexed (fn [i x] (when (odd? i) x))) conj [:a :b :c :d])
(transduce (take-while odd?) conj [1 3 4 5])
(transduce (drop-while odd?) conj [1 3 4 5])
(transduce (drop 2) conj [1 2 3 4])
(transduce (take-nth 2) conj (range 7))
(transduce (remove odd?) conj (range 7))
(transduce (replace {1 :one}) conj [1 2 1])
(transduce (map identity) str ["a" "b"])
(transduce (map inc) (completing + str) 0 [1 2])
(transduce identity + [])
(transduce (comp (partition-all 2) (map #(apply + %))) conj (range 7))
(transduce (comp (take 5) (partition-all 2)) conj (range 100))
(into [] (comp (map inc) (filter odd?) (take 3)) (range 100))
(into [] (comp cat (dedupe)) [[1 1] [1 2] [2 3]])
(into [] (comp (mapcat range) (distinct)) [3 4 2])
(into #{} (map str) [1 2 1])
(into [] (partition-all 2) [])
(into [] (take 0) [1 2])
(into [] (comp (interpose 0) (take 4)) [1 2 3 4 5])
(sequence (map inc) [1 2 3])
(sequence (comp (filter odd?) (map str)) (range 6))
(sequence (map +) [1 2 3] [10 20 30])
(sequence (map vector) [1 2] [:a :b :c])
(sequence (partition-all 2) (range 5))
(sequence (take 2) (range))
(sequence (mapcat #(repeat % %)) [1 2 3])
(class (sequence (map inc) [1]))
(sequence (halt-when #{3}) [1 2 3 4])
(eduction (map inc) [1 2 3])
(eduction (map inc) (filter even?) [1 2 3 4 5])
(class (eduction (map inc) [1]))
(reduce + (eduction (map inc) (range 10)))
(into [] (eduction (take 2) [5 6 7]))
(seq (eduction (filter even?) (range 5)))
(count (eduction (map inc) [1 2 3]))
(let [xf (comp (map (fn [x] (println "xf" x) x)) (take 2))] (into [] xf (range 10)))
(let [c (atom 0)] (first (sequence (map (fn [x] (swap! c inc) x)) (range 100))) @c)
(fn? ((map inc) conj))
(((map inc) conj) [] 1)
(((filter odd?) conj) [] 2)
(reduced? (((take 1) conj) [] 5))
@(((take 1) conj) [] 5)
(def rf ((take 2) conj))
@(rf (rf [] 1) 2)
(def pa ((partition-all 2) conj))
(pa (pa (pa [] 1) 2) 3)
(pa (pa (pa (pa [] 1) 2) 3))
(transduce identity (completing + (fn [a] (* a 10))) 0 [1 2])
((completing +) 5)

;; ----- reduce over maps and other colls
(reduce (fn [a [k v]] (assoc a v k)) {} {:a 1 :b 2})
(reduce + (vals {:a 1 :b 2 :c 3}))
(reduce + (keys {1 :a 2 :b}))
(reduce conj [] #{3})
(reduce + "abc")
(reduce + (int-array [1 2 3]))
(reduce str (seq "abc"))
(reduce + (java.util.ArrayList. [1 2 3]))
(reduce + (sorted-set 1 2 3))
(reduce (fn [a e] (conj a (key e))) [] (sorted-map :b 1 :a 2))
(reduce + (subvec [1 2 3 4] 1))
(reduce + (vector-of :int 1 2 3))
(reduce + (cons 1 [2 3]))
(reduce + 1)

;; ----- tree-seq, line-seq, iteration
(tree-seq sequential? seq [1 [2 [3]] 4])
(map first (tree-seq next rest '(:a (:b (:d) (:e)) (:c (:f)))))
(tree-seq map? vals {:a {:b 1} :c 2})
(count (tree-seq coll? seq [[1 2] [3 [4 5]]]))
(filter number? (tree-seq coll? seq {:a [1 2] :b {:c 3}}))
(line-seq (java.io.BufferedReader. (java.io.StringReader. "one\ntwo\n\nthree")))
(line-seq (java.io.BufferedReader. (java.io.StringReader. "")))
(line-seq (java.io.BufferedReader. (java.io.StringReader. "a\r\nb\rc\n")))
(vec (iteration (fn [k] (when (< k 5) {:v k :next (inc k)})) :initk 0 :vf :v :kf :next))
(vec (iteration (fn [k] {:items (range k (+ k 3)) :next (when (< k 6) (+ k 3))}) :initk 0 :vf :items :kf :next))
(into [] cat (iteration (fn [k] {:items (range k (+ k 3)) :next (when (< k 6) (+ k 3))}) :initk 0 :vf :items :kf :next))
(vec (iteration (fn [k] k) :somef #(< % 3) :kf inc :initk 0))
(reduce + (iteration (fn [k] k) :somef #(< % 10) :kf inc :initk 0))
(seq (iteration (constantly nil)))

;; ----- function combinators
((every-pred odd? pos?) 1 3 5)
((every-pred odd? pos?) 1 -3)
((every-pred odd?))
((every-pred even? #(> % 10)) 12 14)
((some-fn even? neg?) 1 3 -1)
((some-fn even? neg?) 1 3)
((some-fn :a :b) {:b 2})
((some-fn nil?))
((juxt :a :b) {:a 1 :b 2})
((juxt inc dec str) 5)
((juxt first count) "abc")
(map (juxt identity #(* % %)) [1 2 3])
((comp inc inc) 1)
((comp) 7)
((comp str +) 1 2 3)
((comp first rest) [1 2 3])
((comp (partial * 2) inc) 5)
((comp keyword str) "a" "b")
((partial + 1 2) 3 4)
((partial str "x"))
((partial vector))
((partial conj [1]) 2 3)
(map (partial * 10) [1 2])
((complement even?) 3)
((complement nil?) nil)
((complement (constantly true)) 1 2 3)
((fnil + 0) nil 5)
((fnil + 0 0) nil nil)
((fnil + 0 0 0) nil nil nil)
((fnil + 0) 1 2 3 4)
((fnil conj []) nil :x)
((fnil inc 0) 4)
((fnil (fn [a b] [a b]) :x :y) nil false)
((constantly 42))
((constantly 42) 1 2 3 4 5 6)
((constantly nil) :x)
(identity 4)
(apply + 1 2 [3 4])
(apply + [])
(apply + 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 [23 24 25])
(apply str (range 30))
(apply max [3 1 2])
(apply + (range 10000))
(apply list 1 2 [3])
(apply hash-map [:a 1 :b 2])
(apply vector 1 nil)
(apply + 1 2)
(apply (fn [& r] r) [])
(apply (fn [& r] r) nil)
(apply (fn [a b & r] [a b r]) 1 2 3 [4 5])
(apply (fn [a b c d e f g h i j k l m n o p q r s t] (+ a t)) (range 20))
(apply (fn [a b c d e f g h i j k l m n o p q r s t & u] [(+ a t) u]) (range 22))
(fn [a b c d e f g h i j k l m n o p q r s t u] a)
(apply (fn [& xs] (count xs)) (range 100))
(apply inc [1 2])
(max-key count "a" "bbb" "cc")
(min-key count "a" "bbb" "cc")
(max-key count "aa" "bb")
(min-key count "aa" "bb")
(max-key - 1 2 3)
(max-key :a {:a 1})
(apply max-key val {:a 1 :b 5 :c 3})
(apply min-key val {:a 1 :b 5 :c 3})
(min-key count)
(max 1 2.0)
(max 1)
(min 1/2 0.4)
(max 3 1 ##NaN)
(max ##NaN 1)

;; ----- assorted
(replace {1 :one 2 :two} [1 2 3 1])
(replace [:a :b :c] [0 2 5])
(replace {} '(1 2))
(class (replace {1 2} '(1)))
(zipmap [:a :b] (range))
(not-empty (filter even? [1 3]))
(rseq (vec (range 5)))
(subs "hello" 1 3)
(vec (take 3 (iterate rest [1 2 3])))
(splitv-at 2 [1 2 3 4])
(partitionv 2 [1 2 3 4 5])
(partitionv 2 2 [:p] [1 2 3])
(partitionv-all 2 [1 2 3])
(partitionv-all 2 1 [1 2 3])
(class (first (partitionv 2 [1 2])))
(group-by first ["ab" "ac" "ba"])
(frequencies (map count ["a" "bb" "cc" "ddd"]))
(when-first [x [7 8]] (* x 2))
(when-first [x []] :never)
(for [x (range 3) y "ab"] [x y])
(let [s (for [x (range 3)] (do (println "for" x) x))] (first s))
(doseq [x [1 2] y [:a :b]] (println x y))
(dotimes [i 3] (print i))
(run! println [1 2])
(run! + [])
(mapcat list [1 2] [3 4] [5 6])
(map-indexed vector nil)
(vals (group-by even? []))
(sort-by val (frequencies "abracadabra"))
(first (sort-by (juxt count identity) ["bb" "a" "c" "aa"]))
(sort-by (juxt count identity) ["bb" "a" "c" "aa"])
(seq? (seq (sorted-map 1 2)))
(peek (vec (range 100000)))
(count (filter odd? (range 100000)))
(reduce + (map * (range 1000) (range 1000)))
(last (take 10000 (iterate inc 0)))
(count (distinct (map #(mod % 17) (range 1000))))
(count (str (take 100 (range))))
(str (take 5 (range)))
(pr-str (take 5 (range)))
(print-str (map str "ab"))
(binding [*print-length* 3] (pr-str (range 10)))
(binding [*print-length* 3] (pr-str (range)))
(binding [*print-length* 0] (pr-str [1 2]))
(binding [*print-level* 2] (pr-str [1 [2 [3 [4]]]]))
(binding [*print-level* 0] (pr-str [1]))
(binding [*print-length* 2 *print-level* 2] (pr-str {:a [1 2 3] :b {:c {:d 1}} :e 1}))
