;; compare, sort, sort-by, comparators, sorted collections, subseq and rsubseq.


(require (quote [arbace.string :as str]))
;; ----- compare
(compare 1 2)
(compare 2 1)
(compare 1 1)
(compare 1 1.0)
(compare 1.0 1)
(compare 1 1N)
(compare 1/2 0.5)
(compare 1/3 0.3333)
(compare 1M 1.0)
(compare -0.0 0.0)
(compare ##-Inf ##Inf)
(compare Long/MIN_VALUE Long/MAX_VALUE)
(compare 9223372036854775808N Long/MAX_VALUE)
(compare nil nil)
(compare nil 1)
(compare 1 nil)
(compare nil "a")
(compare nil :a)
(compare nil [])
(compare false true)
(compare true false)
(compare true true)
(compare false nil)
(compare \a \b)
(compare \b \a)
(compare \a \A)
(compare \z \a)
(compare "a" "b")
(compare "abc" "abd")
(compare "b" "abc")
(compare "a" "aaaa")
(compare "B" "a")
(compare :a :b)
(compare :b :a)
(compare :a :a/b)
(compare :a/b :a)
(compare :a/b :b/a)
(compare :z/a :a/z)
(compare :a/b :a/c)
(compare 'a 'b)
(compare 'a 'a/b)
(compare 'b/a 'a/b)
(compare 'z 'a/z)
(compare [1 2] [1 3])
(compare [1 2 3] [1 3])
(compare [1 3] [1 2 3])
(compare [] [1])
(compare [9] [1 1])
(compare [1 2] [1 2])
(compare [[1] 2] [[1] 3])
(compare [1 "a"] [1 "b"])
(compare [nil] [1])
(compare [:a 1] [:a 2])
(compare (first {:a 1}) [:a 2])
(compare (subvec [1 2 3] 1) [2 3])
(compare '(1 2) '(1 3))
(compare '(1) '(2))
(compare [1] '(1))
(compare #{1} #{2})
(compare {:a 1} {:a 2})
(compare 1 "a")
(compare "a" 1)
(compare :a "a")
(compare 'a :a)
(compare :a 'a)
(compare \a "a")
(compare 1 \a)
(compare true 1)
(compare [1] [:a])
(compare [1 2] 1)
(compare (java.util.Date. 0) (java.util.Date. 1))
(compare #uuid "00000000-0000-0000-0000-000000000001" #uuid "00000000-0000-0000-0000-000000000002")
(compare 1.5M 1.50M)
(compare (int 3) 3)
(compare (byte 3) 2.5)
(compare ##NaN ##NaN)
(compare ##NaN 0.0)
(compare 0.0 ##NaN)
(compare (Object.) (Object.))

;; ----- sort on numbers and mixed numbers
(sort [3 1 2])
(sort [])
(sort nil)
(sort '())
(sort [1])
(sort [3.5 1 2N 1/2 0.25M -1])
(sort [1 1.0 1N])
(sort [1.0 1 1N])
(sort [-0.0 0.0 0])
(sort [0 -0.0 0.0])
(sort [##Inf ##-Inf 0 1e308])
(sort [Long/MAX_VALUE Long/MIN_VALUE 0 9223372036854775808N])
(sort [3 nil 1])
(sort [nil nil 1])
(sort (range 10 0 -1))
(sort (reverse (range 20)))
(sort [5 3 5 1 3])
(sort [1 ##NaN 0])
(sort [##NaN 1 0])
(sort [2 ##NaN 1 0])

;; ----- sort on strings, keywords, symbols, chars, booleans
(sort ["b" "a" "c"])
(sort ["b" "B" "a" "A" "" " "])
(sort ["abc" "ab" "abcd" "a"])
(sort ["é" "e" "f" "z" "E"])
(sort ["10" "2" "1" "20"])
(sort [:c :a :b])
(sort [:b/a :a/b :a :b :a/a])
(sort [:x/z :z :a/a :y])
(sort ['c 'a 'b])
(sort ['b/a 'a/b 'a 'b])
(sort [\c \A \a \b \Z])
(sort [true false true])
(sort [nil true false])
(sort [nil "a" ""])
(sort [nil :a])
(sort [[2 1] [1 2] [1] [] [1 1 1]])
(sort [[1 :b] [1 :a] [0 :z]])
(sort [(java.util.Date. 5) (java.util.Date. 1)])
(sort [1 "a"])
(sort ["a" :a])
(sort [:a 'a])
(sort [[1] '(1)])
(sort [#{1} #{2}])
(sort [{:a 1} {:a 2}])
(sort [1 [1]])
(sort [\a "a"])

;; ----- sort with comparators
(sort > [3 1 2])
(sort < [3 1 2])
(sort >= [3 1 2 1])
(sort <= [3 1 2 1])
(sort #(compare %2 %1) [3 1 2])
(sort (comp - compare) [3 1 2])
(sort #(< (count %1) (count %2)) ["ccc" "a" "bb"])
(sort (fn [a b] (> a b)) [1 5 3])
(sort (fn [a b] (- a b)) [3 1 2])
(sort (fn [a b] (- b a)) [3 1 2])
(sort (fn [a b] (if (< a b) -1 (if (= a b) 0 1))) [3 1 2])
(sort (fn [a b] (compare (mod a 3) (mod b 3))) (range 10))
(sort (fn [a b] (< (mod a 3) (mod b 3))) (range 10))
(sort (fn [a b] true) [1 2 3])
(sort (fn [a b] false) [3 1 2])
(sort (fn [a b] 0) [3 1 2])
(sort (fn [a b] :x) [3 1 2])
(sort compare [3 1 2])
(sort (comparator <) [3 1 2])
((comparator <) 1 2)
((comparator <) 2 1)
((comparator <) 1 1)
(sort (java.util.Collections/reverseOrder) [1 3 2])
(sort String/CASE_INSENSITIVE_ORDER ["b" "A" "a" "B"])
(sort (java.util.Comparator/reverseOrder) ["a" "c" "b"])
(sort-by :age [{:age 3 :n "c"} {:age 1 :n "a"} {:age 2 :n "b"}])
(sort-by :age > [{:age 3} {:age 1} {:age 2}])
(sort-by count ["ccc" "a" "bb" "" "dd"])
(sort-by - [1 3 2])
(sort-by first [[2 :a] [1 :b] [2 :c] [1 :d]])
(sort-by second [[:a 2] [:b 1]])
(sort-by identity [3 1 2])
(sort-by (juxt :a :b) [{:a 2 :b 1} {:a 1 :b 2} {:a 1 :b 1}])
(sort-by (juxt count identity) ["bb" "a" "ab" "c"])
(sort-by :k [{:k nil} {:k 1} {}])
(sort-by :k [{:k "a"} {:k 1}])
(sort-by str [1 :a "b" \c 'd nil])
(sort-by #(* % %) [-3 1 -2 2])
(sort-by #(mod % 3) (range 10))
(sort-by #(mod % 3) > (range 10))
(sort-by #(quot % 10) [21 11 22 12 23 13])
(sort-by :v (map (fn [i] {:i i :v (mod i 2)}) (range 8)))
(sort-by val {:a 3 :b 1 :c 2})
(sort-by key > {1 :a 3 :b 2 :c})
(sort-by str/upper-case ["b" "A"])

;; ----- stability
(sort-by first [[1 :a] [0 :b] [1 :c] [0 :d] [1 :e]])
(sort-by count ["bb" "a" "cc" "b" "aa" "c"])
(sort #(compare (first %1) (first %2)) [[1 :a] [0 :b] [1 :c] [0 :d]])
(sort-by :p [{:p 1 :i 0} {:p 0 :i 1} {:p 1 :i 2} {:p 0 :i 3} {:p 1 :i 4}])
(map :i (sort-by :p (map (fn [i] {:p (mod (* i 7) 3) :i i}) (range 15))))
(sort-by (constantly 0) [5 4 3 2 1])
(sort (constantly 0) [5 4 3 2 1])

;; ----- sort of other sources
(sort "hello")
(sort #{3 1 2})
(sort {:b 2 :a 1})
(sort (sorted-set 3 1 2))
(sort (java.util.ArrayList. [3 1 2]))
(sort (int-array [3 1 2]))
(sort (to-array [3 1 2]))
(sort (vals {:a 3 :b 1}))
(let [a (to-array [3 1 2])] (sort a) (vec a))
(class (sort [3 1 2]))
(class (sort []))
(sort 5)
(sort :a)
(sort-by)
(sort-by :a 5)

;; ----- sorted-map and sorted-set
(sorted-map)
(sorted-map :b 2 :a 1)
(sorted-map 3 :c 1 :a 2 :b)
(sorted-map "b" 1 "a" 2)
(sorted-map [1 2] :x [1] :y)
(sorted-map nil 1 0 2)
(sorted-map :a 1 :a 2)
(sorted-map :a)
(sorted-map 1 :a "b" :b)
(sorted-map 1 :a :b 2)
(sorted-map 1 :a 1.0 :b)
(sorted-map 1 :a 1N :b)
(sorted-map 1N :a 1 :b)
(assoc (sorted-map 1 :a) 2.0 :b 1.0 :c)
(sorted-map-by > 1 :a 3 :c 2 :b)
(sorted-map-by #(compare %2 %1) "a" 1 "c" 2 "b" 3)
(sorted-map-by (fn [a b] (< a b)) 3 :c 1 :a 2 :b)
(sorted-map-by (comparator >) 1 :a 2 :b)
(sorted-map-by (fn [a b] (compare (count a) (count b))) "aa" 1 "b" 2 "cc" 3)
(sorted-map-by String/CASE_INSENSITIVE_ORDER "b" 1 "A" 2 "a" 3)
(get (sorted-map-by String/CASE_INSENSITIVE_ORDER "Key" 1) "KEY")
(get (sorted-map 1 :a) 1.0)
(get (sorted-map 1 :a) 1N)
(get (sorted-map 1 :a) "x")
(get (sorted-map :a 1) 1)
(contains? (sorted-map 1 :a) 1.0)
(contains? (sorted-set 1) 1N)
(find (sorted-map 1 :a) 1.0)
(sorted-set)
(sorted-set 3 1 2 1)
(sorted-set "b" "a" "c")
(sorted-set :b :a)
(sorted-set [2] [1 1] [1])
(sorted-set nil 1)
(sorted-set 1 1.0 1N)
(sorted-set 1 "a")
(conj (sorted-set 1 2) "a")
(sorted-set-by > 1 3 2)
(sorted-set-by #(compare (count %1) (count %2)) "aa" "b" "cc" "ddd")
(sorted-set-by (fn [a b] (< (mod a 5) (mod b 5))) 1 6 2 7)
(sorted-set-by (constantly 0) 3 1 2)
(sorted-set-by (constantly -1) 3 1 2)
(sorted-set-by (constantly 1) 3 1 2)
(into (sorted-set) [5 3 1 4])
(into (sorted-map) {3 :c 1 :a})
(into (sorted-map-by >) {3 :c 1 :a 2 :b})
(first (sorted-map 2 :b 1 :a))
(last (sorted-map 2 :b 1 :a))
(keys (sorted-map 2 :b 1 :a 3 :c))
(vals (sorted-map 2 :b 1 :a 3 :c))
(rseq (sorted-map 2 :b 1 :a 3 :c))
(rseq (sorted-set 2 1 3))
(rseq (sorted-set))
(dissoc (sorted-map 1 :a 2 :b) 1)
(disj (sorted-set 1 2 3) 2)
(disj (sorted-set 1 2 3) 5)
(conj (sorted-set 2) 1)
(empty (sorted-map-by > 1 :a))
(assoc (empty (sorted-map-by > 1 :a)) 1 :a 2 :b)
(conj (empty (sorted-set-by >)) 1 2 3)
(sorted? (sorted-map))
(sorted? (sorted-set))
(sorted? {})
(sorted? [1 2])
(reversible? (sorted-map))
(= (sorted-map 1 :a) {1 :a})
(= (sorted-set 1) #{1})
(= (sorted-set-by > 1 2) #{1 2})
(count (sorted-map 1 :a 2 :b))
(seq (sorted-map))
(meta (with-meta (sorted-set 1) {:m 1}))
(nth (seq (sorted-set 5 3 4)) 1)
(vec (sorted-set 3 2 1))
(map key (sorted-map :c 3 :a 1 :b 2))
(reduce + (sorted-set 1 2 3))
(reduce-kv (fn [acc k v] (conj acc [k v])) [] (sorted-map :b 2 :a 1))
(update (sorted-map :a 1) :a inc)
(merge (sorted-map :b 1) {:a 2} {:c 3})
(merge {:b 1} (sorted-map :a 2))
(select-keys (sorted-map :a 1 :b 2 :c 3) [:c :a])
(zipmap [:b :a] [1 2])

;; ----- subseq and rsubseq
(def ss (sorted-set 1 2 3 4 5 6 7 8 9 10))
(def sm (sorted-map 1 :a 2 :b 3 :c 4 :d 5 :e))
(subseq ss > 5)
(subseq ss >= 5)
(subseq ss < 5)
(subseq ss <= 5)
(subseq ss > 3 < 7)
(subseq ss >= 3 <= 7)
(subseq ss > 3 <= 7)
(subseq ss >= 3 < 7)
(subseq ss > 100)
(subseq ss < 0)
(subseq ss > 0)
(subseq ss >= 10)
(subseq ss > 5.5)
(subseq ss >= 5.5)
(subseq ss > 7 < 3)
(rsubseq ss > 5)
(rsubseq ss >= 5)
(rsubseq ss < 5)
(rsubseq ss <= 5)
(rsubseq ss > 3 < 7)
(rsubseq ss >= 3 <= 7)
(rsubseq ss < 0)
(rsubseq ss > 100)
(subseq sm > 2)
(subseq sm >= 2 < 4)
(rsubseq sm <= 3)
(rsubseq sm > 1 <= 4)
(subseq (sorted-set) > 1)
(rsubseq (sorted-set) < 1)
(subseq (sorted-set "a" "b" "c" "d") > "b")
(subseq (sorted-set "a" "b" "c" "d") >= "bb")
(subseq (sorted-set :a :b :c) < :b)
(subseq (sorted-set [1] [1 2] [2] [0 0 0]) >= [1 5])
(subseq (sorted-set-by > 1 2 3 4 5) > 3)
(subseq (sorted-set-by > 1 2 3 4 5) < 3)
(rsubseq (sorted-set-by > 1 2 3 4 5) > 3)
(subseq ss = 5)
(subseq ss not= 5)
(subseq ss > "a")
(subseq [1 2 3] > 1)
(subseq ss > nil)
(subseq (sorted-set nil 1 2) > nil)

;; ----- min-key, max-key, and other ordering helpers
(max-key count "a" "bbb" "cc")
(min-key count "a" "bbb" "cc")
(max-key count "aa" "bb")
(min-key count "aa" "bb")
(max-key :v {:v 1} {:v 3} {:v 3 :x 1})
(min-key :v {:v 1 :x 1} {:v 1} {:v 3})
(max-key identity 1)
(apply max-key - [3 1 2])
(apply min [3 1 2])
(apply max ["a"])
(max "a" "b")
(first (sort-by - [3 1 2]))
(reverse (sort [3 1 2]))
(take 2 (sort > (range 10)))
(distinct (sort [3 1 3 2 1]))
(dedupe (sort [3 1 3 2 1]))
(partition-by odd? (sort [1 3 2 4 5]))
(group-by count (sort ["bb" "a" "cc" "b"]))
(sort (keys (group-by odd? (range 5))))
(sort-by count (vals (group-by #(mod % 3) (range 10))))
(sort (map (comp keyword str) "cab"))
(sort (frequencies "mississippi"))
(sort-by val > (frequencies "mississippi"))
(sort-by (juxt val key) (frequencies "mississippi"))
(sort-by (comp - val) (frequencies "mississippi"))
