;; Dynamic vars, reference types, exceptions, metadata, namespaces, symbols and keywords, regexes,
;; eval.

(require '[arbace.string :as str])

;; ----- dynamic vars
(def ^:dynamic *dyn* :root)
*dyn*
(binding [*dyn* :bound] *dyn*)
(binding [*dyn* 1] (binding [*dyn* 2] *dyn*))
(binding [*dyn* 1] [(binding [*dyn* 2] *dyn*) *dyn*])
(binding [*dyn* 1] (set! *dyn* 5) *dyn*)
(binding [*dyn* 1] (set! *dyn* (inc *dyn*)) (set! *dyn* (* 10 *dyn*)) *dyn*)
*dyn*
(set! *dyn* 3)
(def not-dynamic 1)
(binding [not-dynamic 2] not-dynamic)
(binding [undefined-var 1] 1)
(defn read-dyn [] *dyn*)
(binding [*dyn* :in-fn] (read-dyn))
(let [f (binding [*dyn* :captured] (fn [] *dyn*))] (f))
(let [f (binding [*dyn* :conveyed] (bound-fn [] *dyn*))] (f))
(let [s (binding [*dyn* :lazy] (map (fn [_] *dyn*) [1 2]))] (vec s))
(binding [*dyn* :a] (with-bindings {#'*dyn* :b} *dyn*))
(with-bindings* {#'*dyn* :wb} read-dyn)
(binding [*dyn* 1 *dyn* 2] *dyn*)
(bound? #'*dyn*)
(def unbound-var)
(bound? #'unbound-var)
unbound-var
(class unbound-var)
(thread-bound? #'*dyn*)
(binding [*dyn* 1] (thread-bound? #'*dyn*))
(:dynamic (meta #'*dyn*))
(.isDynamic #'*dyn*)
(.isDynamic #'not-dynamic)
(def ^:dynamic *other* 10)
(binding [*dyn* 1 *other* *dyn*] [*dyn* *other*])
(contains? (get-thread-bindings) #'*ns*)
(binding [*dyn* :x] (get (get-thread-bindings) #'*dyn*))
(def ^:dynamic not-earmuffed 1)
(binding [not-earmuffed 2] not-earmuffed)
(def *earmuffed-not-dynamic* 1)

;; ----- with-redefs, alter-var-root, var-get
(defn target [] :original)
(defn calls-target [] (target))
(with-redefs [target (fn [] :redefined)] (calls-target))
(calls-target)
(with-redefs [target (fn [] :r1) not-dynamic 99] [(target) not-dynamic])
not-dynamic
(try (with-redefs [target (fn [] :temp)] (throw (Exception. "inside"))) (catch Exception e (calls-target)))
(with-redefs-fn {#'target (constantly :fn-version)} calls-target)
(def counter 0)
(alter-var-root #'counter inc)
(alter-var-root #'counter + 10)
counter
(alter-var-root #'counter (fn [_] (throw (Exception. "no"))))
counter
(var-get #'counter)
(= map (var-get #'map))
@#'counter
(#'inc 1)
(var counter)
#'counter
(.-sym #'counter)
(.toSymbol #'counter)
(symbol #'counter)
(.ns #'counter)
(ns-name (.ns #'counter))
(var-set #'counter 5)
(binding [*dyn* 1] (var-set #'*dyn* 7) *dyn*)
(def x-redef 1)
(def x-redef 2)
x-redef
(defonce once-only 1)
(defonce once-only 2)
once-only
(def ^:const konst 42)
(+ konst 1)
(:const (meta #'konst))
(declare later)
later
(def later 3)
later
(intern 'user 'interned-var 99)
interned-var
(intern 'user 'interned-unbound)
(bound? #'interned-unbound)
(intern 'no.such.ns 'x 1)
(var no-such-var)
(find-var 'user/counter)
(find-var 'user/nope)
(find-var 'arbace.core/map)
(find-var 'no.such.ns/x)
(find-var 'unqualified)

;; ----- atoms
(def a (atom 0))
@a
(swap! a inc)
(swap! a + 10)
(swap! a + 1 2 3)
(swap! a (fn [x y z w] (+ x y z w)) 1 1 1)
(swap-vals! a inc)
(reset! a 100)
(reset-vals! a 5)
(compare-and-set! a 5 6)
(compare-and-set! a 5 7)
@a
(let [b (atom [1])] (compare-and-set! b [1] [2]))
(let [v [1] b (atom v)] (compare-and-set! b v [2]))
(let [b (atom 1)] (swap! b (fn [_] (throw (IllegalStateException. "bad swap")))))
(def va (atom 1 :validator pos?))
(swap! va inc)
(swap! va - 10)
@va
(reset! va 0)
(reset! va -1)
(atom -1 :validator pos?)
(set-validator! va #(< % 100))
(reset! va 1000)
(reset! va -5)
(set-validator! va (fn [_] (throw (ex-info "validator threw" {:k 1}))))
(reset! va 1)
(set-validator! va nil)
(reset! va -5)
(get-validator va)
(def wa (atom 0))
(add-watch wa :printer (fn [k r o n] (println "watch" k o "->" n)))
(swap! wa inc)
(reset! wa 10)
(reset! wa 10)
(add-watch wa :second (fn [k r o n] (println "second" n)))
(swap! wa inc)
(remove-watch wa :printer)
(swap! wa inc)
(remove-watch wa :second)
(swap! wa inc)
(count (.getWatches wa))
(def ma (atom 1 :meta {:m 1}))
(meta ma)
(alter-meta! ma assoc :n 2)
(meta ma)
(reset-meta! ma {})
(meta ma)
(deref a)
(deref (atom nil))
(swap! (atom {}) assoc :a 1)
(swap! (atom {}) update :n (fnil inc 0))
(swap! (atom [1 2]) conj 3)
(swap! 1 inc)

;; ----- volatiles
(def v (volatile! 1))
@v
(vswap! v inc)
(vswap! v + 10)
(vreset! v :new)
@v
(volatile? v)
(volatile? (atom 1))
(let [vv (volatile! [])] (dotimes [i 3] (vswap! vv conj i)) @vv)

;; ----- refs and transactions
(def rf (ref 1))
@rf
(dosync (alter rf inc))
(dosync (alter rf + 10) (alter rf * 2))
(dosync (ref-set rf 100))
(dosync (commute rf inc))
@rf
(alter rf inc)
(ref-set rf 5)
(dosync (ensure rf))
(def r2 (ref [] :validator vector?))
(dosync (alter r2 conj 1))
(dosync (ref-set r2 :not-vector))
@r2
(def r3 (ref 0))
(add-watch r3 :w (fn [k r o n] (println "ref-watch" o n)))
(dosync (alter r3 inc) (alter r3 inc))
(try (dosync (ref-set r3 50) (throw (Exception. "rollback"))) (catch Exception e (ex-message e)))
@r3
(dosync)
(dosync 1 2 3)
(sync nil (alter r3 inc))
(let [x (ref 1) y (ref 2)] (dosync (let [s (+ @x @y)] (ref-set x s) (ref-set y (* 2 s)))) [@x @y])
(dosync (dosync (alter r3 inc)))
(io! :ok)
(dosync (io! :not-ok))
(ref-history-count rf)
(ref-min-history rf)
(ref-max-history rf)

;; ----- delays and promises
(def d (delay (println "computing delay") :value))
(realized? d)
@d
@d
(realized? d)
(force d)
(force 5)
(force nil)
(delay? d)
(delay? 1)
(def bad-delay (delay (throw (Exception. "delay failed"))))
@bad-delay
@bad-delay
(realized? bad-delay)
(let [n (atom 0) dd (delay (swap! n inc))] [@dd @dd @n])
(def p (promise))
(realized? p)
(deliver p :delivered)
@p
(realized? p)
(deliver p :again)
@p
(deref (promise) 10 :timed-out)
(let [pp (promise)] (deliver pp nil) [(realized? pp) @pp])

;; ----- exceptions: try/catch/finally ordering
(try 1 (finally (println "finally")))
(try (println "body") 2 (catch Exception e (println "catch") 3) (finally (println "finally")))
(try (println "body") (throw (Exception. "x")) (catch Exception e (println "catch" (ex-message e)) :caught) (finally (println "finally")))
(try (throw (Exception. "x")) (finally (println "finally runs")))
(try 1 (finally 2))
(try (throw (Exception. "x")) (catch Exception e :c) (finally :ignored))
(try)
(try 1 2 3)
(try (/ 1 0) (catch ArithmeticException e (ex-message e)))
(try (/ 1 0) (catch IllegalStateException e :wrong) (catch ArithmeticException e :right))
(try (/ 1 0) (catch RuntimeException e :runtime) (catch ArithmeticException e :arith))
(try (/ 1 0) (catch Exception e :exception) (catch Throwable t :throwable))
(try (throw (Error. "err")) (catch Exception e :exception) (catch Throwable t [:throwable (ex-message t)]))
(try (try (throw (Exception. "inner")) (finally (println "inner finally"))) (catch Exception e (str "outer caught " (ex-message e))))
(try (try (throw (Exception. "first")) (catch Exception e (throw (Exception. "second" e)))) (catch Exception e [(ex-message e) (ex-message (ex-cause e))]))
(try (throw (Exception. "a")) (catch Exception e (try (throw (Exception. "b")) (catch Exception e2 [(ex-message e) (ex-message e2)]))))
(try (throw (Exception. "f")) (finally (throw (Exception. "from finally"))))
(let [log (atom [])] (try (swap! log conj :try) (throw (Exception. "x")) (catch Exception _ (swap! log conj :catch)) (finally (swap! log conj :finally))) @log)
(let [log (atom [])] (try (try (swap! log conj 1) (finally (swap! log conj 2))) (finally (swap! log conj 3))) @log)
(loop [i 0] (if (< i 3) (recur (try (inc i) (finally nil))) i))
(defn try-recur [n] (if (pos? n) (try (recur (dec n)) (finally nil)) :done))
(throw (Exception. "plain"))
(throw (RuntimeException. "runtime"))
(throw (IllegalArgumentException. "illegal arg"))
(throw (Exception.))
(throw (Exception. "with cause" (IllegalStateException. "root")))
(throw (Exception. (Exception. "cause-only")))
(throw "not throwable")
(throw nil)
(throw (ex-info "info" {:a 1}))
(throw (ex-info "info with cause" {:a 1} (ex-info "inner" {:b 2})))
(throw (ex-info "nested" {:l 1} (ex-info "two" {:l 2} (ex-info "three" {:l 3} (Exception. "bottom")))))
(throw (ex-info nil {}))
(ex-data (ex-info "m" nil))
(ex-info "m" 5)
(ex-data (ex-info "m" {:x 1}))
(ex-data (Exception. "m"))
(ex-data nil)
(ex-data 1)
(ex-message (ex-info "msg" {}))
(ex-message (Exception. "jmsg"))
(ex-message (Exception.))
(ex-message "str")
(ex-message nil)
(class (ex-cause (ex-info "a" {} (Exception. "c"))))
(ex-message (ex-cause (ex-info "a" {} (Exception. "c"))))
(ex-cause (ex-info "a" {}))
(ex-cause nil)
(class (ex-info "a" {}))
(instance? RuntimeException (ex-info "a" {}))
(instance? arbace.lang.IExceptionInfo (ex-info "a" {}))
(try (throw (ex-info "caught" {:code 42})) (catch arbace.lang.ExceptionInfo e (:code (ex-data e))))
(try (throw (ex-info "caught" {:code 42})) (catch RuntimeException e (ex-data e)))
(let [m (Throwable->map (ex-info "top" {:a 1} (IllegalStateException. "root cause")))] [(:cause m) (mapv :type (:via m)) (mapv :message (:via m)) (:data m) (mapv :data (:via m))])
(let [m (Throwable->map (Exception. "solo"))] (select-keys m [:cause :data]))
(mapv :type (:via (Throwable->map (ex-info "a" {} (ex-info "b" {:n 2} (ArithmeticException. "c"))))))
(:data (Throwable->map (ex-info "a" {} (ex-info "b" {:n 2}))))
(let [m (Throwable->map (Exception.))] [(:cause m) (map :type (:via m))])
(try (+ 1 "a") (catch ClassCastException e (ex-message e)))
(+ 1 "a")
(+ "a" 1)
(- :k)
(* 2 nil)
(inc nil)
(< 1 nil)
(> "a" 1)
(compare 1 "a")
(compare "a" 1)
(compare :a 'a)
(name 1)
(namespace "s")
(subs "abc" 5)
(subs "abc" 2 1)
(nth {} 0)
(nth #{} 0)
(nth 5 0)
(nth nil 0)
(nth nil 0 :nf)
(first 1)
(first :k)
(rest 1)
(seq 1.5)
(count (Object.))
(.toString nil)
(.length nil)
(let [s nil] (.length ^String s))
(Integer/parseInt "x")
(Long/parseLong "12a")
(Integer/parseInt nil)
(Double/parseDouble "abc")
(keyword 1)
(symbol nil)
(symbol 1)
(apply + 1)
(get-in {:a 1} :a)
(assoc-in {} [] 1)
(conj {} 1)
(into {} [1])
(hash-map 1)
(array-map 1)
(sorted-map 1)
(zipmap 1 2)
(reduce + :k)
(vec 1)
(set 1)
(char -1)
(char 70000)
(int "a")
(long :k)
(Character/toChars -1)
(java.util.ArrayList. -1)
(.get (java.util.ArrayList.) 0)
(.charAt "abc" 10)
(aget (object-array 1) 1)
(re-pattern "(")
(re-pattern "[a-")
(re-find #"a" nil)
(re-find nil "a")
(identity)
(identity 1 2)
(map)
(str/join 1 2 3 4)

;; ----- assert
(assert true)
(assert (= 1 1) "fine")
(assert false)
(assert (= 1 2))
(assert (= 1 2) "custom message")
(assert nil (str "computed " 42))
(binding [*assert* false] (eval '(assert false)))
*assert*

;; ----- metadata
(meta [1 2])
(meta (with-meta [1 2] {:k 1}))
(meta ^:tag-key [1 2])
(meta ^{:a 1 :b 2} [1])
(meta ^String [1])
(meta ^"str-tag" [1])
(meta '^[long] x)
(meta (with-meta {} {:m true}))
(meta (with-meta #{} {:m true}))
(meta (with-meta '(1) {:m true}))
(meta (with-meta 'sym {:m true}))
(meta (with-meta (sorted-map) {:m true}))
(meta (vary-meta [1] assoc :added 1))
(meta (vary-meta (with-meta [1] {:a 1}) update :a inc))
(meta (vary-meta 'sym assoc :s 1))
(meta (vary-meta {} merge {:x 1} {:y 2}))
(with-meta 1 {})
(with-meta "s" {})
(with-meta [1] 5)
(with-meta [1] nil)
(meta (with-meta [1] nil))
(let [f (with-meta (fn [] :called) {:fm 1})] [(meta f) (f)])
(let [f (with-meta inc {:fm 1})] [(meta f) (f 1)])
(meta (with-meta (with-meta inc {:a 1}) {:b 2}))
(meta (conj (with-meta [1] {:k 1}) 2))
(meta (assoc (with-meta {} {:k 1}) :a 1))
(meta (dissoc (with-meta {:a 1} {:k 1}) :a))
(meta (pop (with-meta [1 2] {:k 1})))
(meta (subvec (with-meta [1 2 3] {:k 1}) 1))
(meta (into (with-meta [] {:k 1}) [1]))
(meta (seq (with-meta [1 2] {:k 1})))
(meta (map inc (with-meta [1 2] {:k 1})))
(meta (rest (with-meta '(1 2) {:k 1})))
(meta (cons 0 (with-meta '(1 2) {:k 1})))
(meta (conj (with-meta '(1 2) {:k 1}) 0))
(meta (empty (with-meta {:a 1} {:k 1})))
(meta (persistent! (transient (with-meta [1] {:k 1}))))
(meta (vec (with-meta [1] {:k 1})))
(meta (set (with-meta #{1} {:k 1})))
(meta (disj (with-meta #{1 2} {:k 1}) 1))
(meta (merge (with-meta {} {:k 1}) {:a 1}))
(meta (update (with-meta {:a 1} {:k 1}) :a inc))
(= (with-meta [1] {:a 1}) (with-meta [1] {:b 2}))
(hash (with-meta [1] {:a 1}))
(meta '^:m sym)
(meta (quote ^:m sym))
(meta (second '(a ^:x b)))
(meta (read-string "^:rk [1]"))
(meta (read-string "^{:a 1} {}"))
(dissoc (meta (read-string "(a b)")) :line :column)
(meta (read-string "x"))
(meta :kw)
(meta 1)
(meta nil)
(defn ^:private priv-fn [] 1)
(:private (meta #'priv-fn))
(def ^{:doc "documented" :custom :val} documented 1)
(:doc (meta #'documented))
(:custom (meta #'documented))
(:name (meta #'documented))
(str (:ns (meta #'documented)))
(def ^:private priv-var 2)
(contains? (ns-publics 'user) 'priv-var)
(contains? (ns-interns 'user) 'priv-var)
(select-keys (alter-meta! #'documented assoc :extra 5) [:doc :custom :extra])
(:extra (meta #'documented))
(select-keys (alter-meta! #'documented dissoc :extra :custom) [:doc :custom :extra])
(:custom (meta #'documented))
(reset-meta! #'documented {:only :this})
(meta #'documented)
(:doc (meta #'map))
(:arglists (meta #'map))
(:arglists (meta #'reduce))
(:added (meta #'map))
(:macro (meta #'when))
(:name (meta #'map))
(str (:ns (meta #'map)))
(:static (meta #'map))
(:arglists (meta #'assoc-in))
(:doc (meta #'arbace.core/first))
(:tag (meta #'str))
(:tag (meta #'count))
(:inline (meta #'nonexistent))
(meta #'nonexistent)
(let [m (meta #'map)] (sort (filter #{:arglists :doc :added :name :static :ns :file :line :column} (keys m))))
(defn with-meta-fn {:attr 1} [] nil)
(:attr (meta #'with-meta-fn))
(def ^{:tag String} hinted "x")
(:tag (meta #'hinted))
(meta (with-meta (->> [1] (map inc)) {:x 1}))

;; ----- namespaces
(ns-name *ns*)
(str *ns*)
(class *ns*)
(ns-name (create-ns 'fresh.ns))
(count (ns-publics 'fresh.ns))
(count (ns-map 'fresh.ns))
(ns-resolve 'fresh.ns 'String)
(ns-resolve 'fresh.ns 'map)
(intern 'fresh.ns 'fv 10)
(count (ns-publics 'fresh.ns))
(ns-resolve 'fresh.ns 'fv)
@(ns-resolve 'fresh.ns 'fv)
fresh.ns/fv
(find-ns 'fresh.ns)
(some? (find-ns 'fresh.ns))
(find-ns 'never.created)
(the-ns 'never.created)
(the-ns 'fresh.ns)
(the-ns *ns*)
(in-ns 'scratch.space)
(ns-name *ns*)
(arbace.core/count (arbace.core/ns-publics 'scratch.space))
(def in-scratch 5)
in-scratch
(map inc [1])
(arbace.core/refer 'arbace.core :only '[map inc])
(map inc [1])
(arbace.core/in-ns 'user)
(ns-name *ns*)
scratch.space/in-scratch
(identity in-scratch)
(resolve 'map)
(resolve 'scratch.space/in-scratch)
(resolve 'no-such)
(resolve 'String)
(resolve 'java.util.List)
(resolve 'no.such.Class)
(resolve {'local 1} 'local)
(ns-resolve 'user 'counter)
(ns-resolve 'arbace.core 'map)
(ns-resolve 'user 'nope/x)
(create-ns 'alias.target)
(intern 'alias.target 'target-var :tv)
(alias 'at 'alias.target)
at/target-var
(read-string "::at/kw")
(keyword "alias.target" "kw")
(= (read-string "::at/kw") :alias.target/kw)
(alias 'bad 'does.not.exist)
(get (ns-aliases 'user) 'at)
(ns-unalias 'user 'at)
(get (ns-aliases 'user) 'at)
(read-string "::at/kw")
(def to-unmap 1)
(ns-unmap 'user 'to-unmap)
(resolve 'to-unmap)
(ns-unmap 'user 'never-defined)
(create-ns 'refer.src)
(intern 'refer.src 'rs1 1)
(intern 'refer.src 'rs2 2)
(refer 'refer.src)
[rs1 rs2]
(create-ns 'refer.src2)
(intern 'refer.src2 'q1 :q1)
(intern 'refer.src2 'q2 :q2)
(refer 'refer.src2 :only '[q1] :rename '{q1 renamed-q1})
renamed-q1
(resolve 'q2)
(refer 'refer.src2 :exclude '[q1])
q2
(refer 'no.such.namespace)
(def map 1)
(ns-unmap 'user 'map)
(map inc [1])
(refer 'arbace.core :only '[map])
(map inc [1])
(ns-name (.ns #'refer.src/rs1))
(ns-name (:ns (meta #'refer.src/rs1)))
(remove-ns 'fresh.ns)
(find-ns 'fresh.ns)
(ns-name 'user)
(ns-name 'nope)
(count (filter #(= 'user (ns-name %)) (all-ns)))
(contains? (set (map ns-name (all-ns))) 'arbace.core)
(contains? (ns-refers 'user) 'map)
(= inc (var-get (get (ns-refers 'user) 'inc)))
(get (ns-imports 'user) 'String)
(get (ns-imports 'user) 'Exception)
(import 'java.util.concurrent.atomic.AtomicLong)
(.get (AtomicLong. 5))
(import '(java.util ArrayDeque))
(.size (ArrayDeque.))
(import 'no.such.Clazz)
(require 'no.such.namespace)
(require 'arbace.set)
(arbace.set/union #{1} #{2})
(require '[arbace.set :as s2 :refer [difference]])
(difference #{1 2} #{1})
(s2/intersection #{1} #{1 2})
(namespace-munge 'a-b.c-d)
(munge "a-b?c!")

;; ----- symbols and keywords
(symbol "a")
(symbol "ns" "a")
(symbol nil "a")
(symbol 'already)
(symbol :kw)
(symbol :ns/kw)
(symbol "with space")
(symbol "")
(keyword "a")
(keyword "ns" "a")
(keyword nil "a")
(keyword 'sym)
(keyword 'ns/sym)
(keyword :k)
(keyword "")
(keyword "with space")
(keyword nil)
(keyword "a/b")
(namespace (keyword "a/b"))
(name (keyword "a/b"))
(keyword "a/b/c")
(namespace :a/b/c)
(name :a/b/c)
(find-keyword "definitely-not-interned-xyz-123")
(find-keyword "map")
(find-keyword "ns" "definitely-not-interned-abc-987")
:interned-now
(find-keyword "interned-now")
(name :k)
(name :ns/k)
(name 'sym)
(name 'ns/sym)
(name "string")
(name nil)
(namespace :k)
(namespace :ns/k)
(namespace 'ns/sym)
(namespace 'sym)
(namespace ::local)
(name ::local)
::local
:user/local
(= ::local :user/local)
(identical? :a :a)
(identical? (keyword "a") :a)
(identical? 'a 'a)
(= 'a 'a)
(= 'a (symbol "a"))
(= :a 'a)
(= :a "a")
(= 'a/b (symbol "a" "b"))
(:k {:k 1})
(:k {:j 1} :default)
(:k nil)
(:k nil :d)
(:k "string")
(:k [1 2])
(:k #{:k})
(:k 1 2 3)
('sym {'sym 1})
('sym {'other 1} :nf)
('sym nil)
('sym {} 1 2)
(keyword? :a)
(keyword? 'a)
(symbol? 'a)
(symbol? :a)
(simple-keyword? :a)
(simple-keyword? :a/b)
(qualified-keyword? :a/b)
(qualified-keyword? ::x)
(simple-symbol? 'a)
(qualified-symbol? 'a/b)
(ident? :a)
(ident? 'a)
(ident? "a")
(simple-ident? :a/b)
(qualified-ident? 'a/b)
(compare :a :b)
(compare :b :a)
(compare :a :a/b)
(compare :z :a/b)
(compare :a/b :b/a)
(compare 'a 'b)
(compare 'x/a 'a)
(sort [:c :a/z :b :a/a :a])
(sort ['c 'a/z 'b 'a/a 'a])
(str :k)
(str :ns/k)
(str 'sym)
(str 'ns/sym)
(pr-str (symbol "with space"))
(pr-str (keyword "with space"))
(pr-str (symbol ""))
(hash :a)
(hash :ns/a)
(hash 'a)
(hash 'ns/a)
(hash (keyword "a"))
(.hasheq :a)
(.hashCode :a)
(.hashCode 'a)
(str/starts-with? (str (gensym)) "G__")
(str/starts-with? (str (gensym "pre")) "pre")
(not= (gensym) (gensym))
(meta (with-meta 'a {:m 1}))
(= (with-meta 'a {:m 1}) 'a)
(.sym :a)
(keyword "1")
(symbol "1")
(read-string ":1")
(read-string "'a")
(read-string "a/b")

;; ----- regexes
(re-find #"\d+" "abc123def456")
(re-find #"(\d)(\d)" "x12y")
(re-find #"z" "abc")
(re-find #"(a)?b" "b")
(re-matches #"\d+" "123")
(re-matches #"\d+" "123a")
(re-matches #"(\w+)@(\w+)" "me@host")
(re-matches #"(\w+)@(\w+)" "not an email")
(re-matches #"" "")
(re-seq #"\d" "a1b2c3")
(re-seq #"(\w)(\d)" "a1 b2 c3")
(re-seq #"x" "abc")
(re-seq #"" "ab")
(re-seq #"a*" "baaac")
(let [m (re-matcher #"(\d)(\w)" "1a 2b")] [(re-find m) (re-find m) (re-find m)])
(let [m (re-matcher #"(\d)(\w)" "1a 2b")] (re-find m) (re-groups m))
(let [m (re-matcher #"\d" "1")] (re-find m) (re-groups m))
(let [m (re-matcher #"\d" "x")] (re-groups m))
(let [m (re-matcher #"(?<year>\d{4})-(?<month>\d{2})" "on 2024-05 ok")] (when (.find m) [(.group m "year") (.group m "month") (.start m) (.end m)]))
(let [m (re-matcher #"(?<word>[a-z]+)" "123")] (.find m))
(re-find #"(?<y>\d+)" "x42")
(re-find #"(?i)hello" "HeLLo world")
(re-find #"(?m)^b" "a\nb")
(re-find #"(?s)a.b" "a\nb")
(re-find #"a.b" "a\nb")
(re-seq #"\p{Upper}" "aBcD")
(re-seq #"[éè]" "étè")
(re-find #"\bword\b" "a word here")
(re-find #"(a|ab)(c|bcd)(d*)" "abcd")
(re-find #"^$" "")
(re-pattern "a+b")
(re-pattern #"already")
(class (re-pattern "x"))
(str #"a\d")
(pr-str #"a\d")
(pr-str #"\"quoted\"")
(pr-str (re-pattern "/slash"))
(= #"a" #"a")
(.pattern #"a\sb")
(re-find (re-pattern (java.util.regex.Pattern/quote "a.b")) "xa.by")
(re-find #"a.b" "axb")
(str/replace "hello world" #"o" "0")
(str/replace "hello world" #"(\w+) (\w+)" "$2 $1")
(str/replace "a1b2" #"\d" #(str "<" % ">"))
(str/replace "a1b2" #"([a-z])(\d)" (fn [[_ l d]] (str d l)))
(str/replace "x.y.z" "." "-")
(str/replace "$1" "$" "\\")
(str/replace "abc" #"b" "\\$")
(str/replace "abc" #"b" "$")
(str/replace "abc" #"b" "$2")
(str/replace "aaa" #"a" (str/re-quote-replacement "$1"))
(str/replace-first "aaa" #"a" "b")
(str/replace-first "a.a" "." "!")
(str/replace-first "abc" #"(b)" "[$1]")
(str/replace "abc" \b \x)
(str/split "a,b,,c,," #",")
(str/split "a,b,,c,," #"," -1)
(str/split "a1b22c" #"\d+")
(str/split "" #",")
(str/split "abc" #"")
(str/split " a  b " #"\s+")
(str/split "a:b:c" #":" 2)
(str/split-lines "l1\nl2\r\nl3")
(str/re-quote-replacement "a$b\\c")
(re-find #"(\d+)-(\d+)" "10-20")
(let [[_ a b] (re-find #"(\d+)-(\d+)" "10-20")] (+ (parse-long a) (parse-long b)))
(re-matches #"a" nil)
(re-seq #"a" nil)
(re-find #"\d" 123)

;; ----- eval and read-string
(eval '(+ 1 2))
(eval (list '+ 1 2 3))
(fn? (eval (list 'fn '[x] (list '* 'x 'x))))
((eval (list 'fn '[x] (list '* 'x 'x))) 7)
(eval `(let [x# 5] (* x# 2)))
(eval (read-string "(map inc [1 2 3])"))
(eval (read-string "{:a (+ 1 1)}"))
(eval [1 '(+ 1 1)])
(eval #{'(inc 1)})
(eval :kw)
(eval nil)
(eval ''quoted)
(eval '(def evald-var 77))
evald-var
(eval '(do (defn evald-fn [x] (* 3 x)) (evald-fn 3)))
(eval '(undefined-fn 1))
(eval '(let [x] x))
(eval (list 'quote (list 1 2)))
(eval (cons 'vector (range 3)))
(eval (list 'apply '+ [1 2 3]))
(eval '(if false 1))
(fn? (eval '(fn* [] 1)))
(eval '(. "abc" (toUpperCase)))
(str (eval '(new java.lang.StringBuilder "x")))
(eval '(set! *dyn* 1))
(eval '(binding [*dyn* 2] (set! *dyn* 3) *dyn*))
(read-string "(1 2 3)")
(read-string "[a b]")
(read-string "{:a 1}")
(read-string "#{1}")
(read-string "\"str\"")
(read-string "\\a")
(read-string "1.5M")
(read-string "1/2")
(read-string "0x10")
(read-string "2r101")
(read-string "#\"re\"")
(class (read-string "#\"re\""))
(read-string "nil")
(read-string "")
(read-string "   ")
(read-string "(unclosed")
(read-string ")")
(read-string "{:a}")
(read-string "#{1 1}")
(read-string "{:a 1 :a 2}")
(read-string "1 2")
(read-string "; comment\n5")
(read-string "#_ignored 6")
(read-string "@x")
(read-string "`(a ~b ~@c)")
(read-string "#(+ % 1)")
(read-string "#?(:clj 1 :default 2)")
(read-string {:read-cond :allow} "#?(:clj 1 :default 2)")
(read-string {:read-cond :allow :features #{:cljs}} "#?(:cljs 3 :default 2)")
(read-string {:read-cond :allow} "[#?@(:clj [1 2])]")
(read-string {:read-cond :preserve} "#?(:clj 1)")
(read-string {:eof :done} "")
(read-string "#inst \"2020-01-01T00:00:00.000-00:00\"")
(read-string "#uuid \"00000000-0000-0000-0000-000000000000\"")
(read-string "#unknown/tag 1")
(binding [*read-eval* false] (read-string "#=(+ 1 2)"))
(read-string "#=(+ 1 2)")
(binding [*default-data-reader-fn* (fn [t v] [:tagged t v])] (read-string "#my/tag [1]"))
(read-string "#:ns{:a 1 :b/c 2 :_/d 3}")
(read-string "#::{:a 1}")
(read-string "\\u0041")
(read-string "\\newline")
(read-string "\"\\u00e9\\t\"")
(read-string "##Inf")
(read-string "-0.0")
(read-string "9223372036854775808")
(read-string "1e400")
(read-string "08")
(read-string "+5")
(read-string "a:b")
(read-string ":a:b")
(read-string "::")
(read-string "a/")
(load-string "(def from-load 1) (+ from-load 10)")
(load-string "")
(eval (read-string "(+ 1 (* 2 3))"))
(apply eval ['(+ 1 1)])

;; ----- apply/partial on multimethods
(defmulti mm-op (fn [op & _] op))
(some? (defmethod mm-op :add [_ & xs] (apply + xs)))
(some? (defmethod mm-op :mul [_ & xs] (apply * xs)))
(apply mm-op :add [1 2 3])
(apply mm-op :mul 2 [3 4])
((partial mm-op :add 10) 5)
(map (partial mm-op :mul 2) [1 2 3])
(reduce (partial mm-op :add) 0 [1 2 3])
(apply mm-op [:add])
(try (apply mm-op []) (catch arbace.lang.ArityException e [:arity (.-actual e)]))
(mm-op :sub 1)
((comp (partial mm-op :add 1) (partial mm-op :mul 2)) 5)
(apply mm-op :add (range 30))
