;; Strings and characters: str, subs, UTF-16 counting, arbace.string, char functions,
;; printing of strings and characters, comparison, hashing and String interop.

(require '[arbace.string :as str])

;; ----- str
(str)
(str nil)
(str "a" nil "b")
(str 1 2 3)
(str "a" \b 'c :d)
(str :a)
(str :a/b)
(str ::local)
(str 'sym)
(str 'ns/sym)
(str true false)
(str [1 2 "x"])
(str '(1 2))
(str {:a "x"})
(str #{})
(str [])
(str ())
(str (list))
(str (range 3))
(str (map inc [1 2]))
(str (lazy-seq nil))
(str (seq [1 2]))
(str (cons 1 nil))
(str \a)
(str \newline)
(str 1.0 1/2 1N 1M)
(str "" "")
(str (StringBuilder. "sb"))
(str [nil])
(str {nil nil})
(str #"a+b")
(str (first {:a 1}))
(apply str (interpose "," ["a" "b" "c"]))
(apply str (reverse "hello"))
(apply str [\a \b])

;; ----- count, subs, charAt on BMP and non-BMP
(count "")
(count "abc")
(count "😀")
(.length "😀")
(count "a😀b")
(.codePointCount "a😀b" 0 4)
(count "é")
(count "ß")
(count "日本語")
(seq "a😀")
(map int "a😀")
(vec "hé")
(.charAt "abc" 1)
(.charAt "😀" 0)
(int (.charAt "😀" 0))
(int (.charAt "😀" 1))
(.charAt "abc" 3)
(nth "abc" 2)
(nth "abc" 5)
(nth "abc" 5 :none)
(get "abc" 1)
(get "abc" 10)
(first "")
(first "xyz")
(last "xyz")
(rest "xyz")
(subs "hello" 1)
(subs "hello" 1 3)
(subs "hello" 5)
(subs "hello" 0 0)
(subs "hello" 3 2)
(subs "hello" 6)
(subs "hello" -1)
(subs "a😀b" 1 3)
(subs "a😀b" 1 2)
(count (subs "a😀b" 1 2))
(.codePointAt "😀" 0)
(.codePointAt "😀" 1)
(Character/charCount 0x1F600)
(String. (Character/toChars 0x1F600))
(.offsetByCodePoints "a😀b" 0 2)
(.isEmpty "")
(empty? "")
(seq "")
(not-empty "")
(not-empty "x")

;; ----- chars and codes
(char? \a)
(char? "a")
(char? 97)
(int \a)
(int \A)
(int \0)
(int \space)
(int \newline)
(int \tab)
(int \return)
(int \backspace)
(int \formfeed)
(int \é)
(int \u00e9)
(int \o101)
(int \o377)
(char 233)
(char 0x41)
(char 0x3b1)
(Character/isLetter \a)
(Character/isLetter \1)
(Character/isLetter \é)
(Character/isDigit \7)
(Character/isDigit \a)
(Character/isWhitespace \space)
(Character/isWhitespace \u00a0)
(Character/isSpaceChar \u00a0)
(Character/isUpperCase \A)
(Character/isLowerCase \A)
(Character/isLetterOrDigit \_)
(Character/toUpperCase \a)
(Character/toLowerCase \Z)
(Character/toUpperCase \ß)
(Character/toUpperCase \é)
(Character/digit \7 10)
(Character/digit \f 16)
(Character/digit \z 10)
(Character/forDigit 11 16)
(Character/getNumericValue \9)
(Character/isHighSurrogate (.charAt "😀" 0))
(Character/isSurrogate \a)
(Character/toString 97)
(Character/getType \a)
(Character/isJavaIdentifierStart \$)
(Character/valueOf \c)
(compare \a \b)
(compare \b \a)
(compare \a \a)
(< (int \a) (int \b))
(sort [\c \a \B \b])
(= \a \a)
(= \a "a")
(= "a" (str \a))
(hash \a)
(hash \A)
(hash \u0000)
(hash \é)
(.hashCode \a)
(char-escape-string \newline)
(char-escape-string \a)
(char-escape-string \")
(char-escape-string \\)
(char-name-string \newline)
(char-name-string \space)
(char-name-string \a)
(inc (int \a))
(char (inc (int \a)))
(map char (range 65 70))
(apply str (map char (range 97 102)))

;; ----- printing strings and characters
(pr-str "plain")
(pr-str "")
(pr-str "a\nb")
(pr-str "tab\there")
(pr-str "quote\"inside")
(pr-str "back\\slash")
(pr-str "nul\u0000x")
(pr-str "bell\u0007")
(pr-str "ret\r")
(pr-str "ff\f")
(pr-str "bs\b")
(pr-str "é")
(pr-str "日本")
(pr-str "😀")
(pr-str "\u00e9")
(pr-str "\u001f")
(pr-str "\u007f")
(pr-str "\u2028")
(print-str "a\nb")
(print-str "quote\"")
(pr-str \a)
(pr-str \newline)
(pr-str \space)
(pr-str \tab)
(pr-str \return)
(pr-str \backspace)
(pr-str \formfeed)
(pr-str \u0000)
(pr-str \u0007)
(pr-str \é)
(pr-str \o101)
(pr-str \\)
(pr-str \")
(pr-str \u00a0)
(pr-str \u2028)
(pr-str [\a "a" \b])
(print-str \a \newline)
(pr-str (.charAt "😀" 0))
(pr-str (str (.charAt "😀" 0)))
(pr-str (subs "😀" 0 1))
(with-out-str (print \a))
(with-out-str (pr \a))
\a
\newline
\space
\u0041
\o101
\é
"a\tb"
"\\"

;; ----- arbace.string: join and split
(str/join ["a" "b" "c"])
(str/join ", " ["a" "b" "c"])
(str/join ", " [])
(str/join ", " [nil 1 "x" :k])
(str/join \- [1 2])
(str/join "" "abc")
(str/join "/" (range 4))
(str/split "a,b,c" #",")
(str/split "a,b,,c,," #",")
(str/split "a,b,,c,," #"," -1)
(str/split "a,b,c" #"," 2)
(str/split "" #",")
(str/split "abc" #"")
(str/split " a  b " #"\s+")
(str/split "a1b22c333" #"\d+")
(str/split "a😀b" #"")
(str/split "aXbXc" #"X" 0)
(str/split-lines "a\nb\r\nc\n")
(str/split-lines "")
(str/split-lines "\n\n")
(str/split-lines "one")

;; ----- replace
(str/replace "hello world" "o" "0")
(str/replace "hello" \l \L)
(str/replace "hello" #"l+" "L")
(str/replace "hello" #"(l)(o)" "$2$1")
(str/replace "a.b.c" "." "!")
(str/replace "a.b.c" #"." "!")
(str/replace "a$b" "$" "\\")
(str/replace "abc" #"b" "$0$0")
(str/replace "abc" #"b" (str/re-quote-replacement "$0"))
(str/replace "abc" #"x" "y")
(str/replace "hello" #"[aeiou]" str/upper-case)
(str/replace "a1b2" #"\d" (fn [d] (str (* 2 (parse-long d)))))
(str/replace "k=v;x=y" #"(\w)=(\w)" (fn [[_ k v]] (str v "=" k)))
(str/replace "" "" "x")
(str/replace "ab" "" "-")
(str/replace "😀😀" "😀" "x")
(str/replace "abc" #"b" "$1")
(str/replace "abc" #"b" "\\")
(str/replace "aaa" "aa" "b")
(str/replace-first "a-b-c" "-" "+")
(str/replace-first "a-b-c" #"-" "+")
(str/replace-first "a-b-c" \- \+)
(str/replace-first "abcabc" #"(b)(c)" "$2$1")
(str/replace-first "abc" #"b" str/upper-case)
(str/replace-first "abc" #"z" "y")
(str/replace "abc" 1 2)
(str/re-quote-replacement "$1\\x")

;; ----- case
(str/upper-case "hello")
(str/lower-case "HELLO")
(str/upper-case "straße")
(str/lower-case "İ")
(count (str/lower-case "İ"))
(str/upper-case "ı")
(str/lower-case "ΣΑΣ")
(str/upper-case "éàü")
(str/upper-case "ǆ")
(str/upper-case "ﬁ")
(str/lower-case "ẞ")
(str/upper-case "😀a")
(str/capitalize "hello WORLD")
(str/capitalize "")
(str/capitalize "a")
(str/capitalize "ßa")
(str/capitalize "élan")
(str/upper-case :kw)
(str/upper-case nil)
(.toUpperCase "abc")
(.toLowerCase "ÀÉÎ")
(.equalsIgnoreCase "abc" "ABC")
(.compareToIgnoreCase "abc" "ABD")

;; ----- trim and blank
(str/trim "  a b  ")
(str/trim "\t\n a \r\n")
(str/trim "")
(str/trim "\u00a0a\u00a0")
(str/trim "\u2003a\u2003")
(str/triml "  a  ")
(str/trimr "  a  ")
(str/trim-newline "a\n")
(str/trim-newline "a\r\n\r\n")
(str/trim-newline "a\n ")
(str/trim-newline "")
(.trim "\u0001a\u0001")
(.strip "\u2003a\u2003")
(str/blank? "")
(str/blank? "  ")
(str/blank? nil)
(str/blank? "\t\n")
(str/blank? " a ")
(str/blank? "\u00a0")
(str/blank? "\u2003")

;; ----- searching
(str/starts-with? "hello" "he")
(str/starts-with? "hello" "lo")
(str/starts-with? "hello" "")
(str/ends-with? "hello" "lo")
(str/ends-with? "hello" "hello!")
(str/includes? "hello" "ell")
(str/includes? "hello" "xyz")
(str/includes? "hello" "")
(str/index-of "hello" "l")
(str/index-of "hello" \l)
(str/index-of "hello" "l" 3)
(str/index-of "hello" "z")
(str/index-of "hello" "" 2)
(str/index-of "hello" "l" 10)
(str/last-index-of "hello" "l")
(str/last-index-of "hello" \l)
(str/last-index-of "hello" "l" 2)
(str/last-index-of "hello" "z")
(str/index-of "a😀b" "b")
(str/index-of "a😀b" "😀")
(str/starts-with? nil "a")
(str/includes? "abc" nil)
(.indexOf "hello" "l")
(.indexOf "hello" (int \o))
(.lastIndexOf "hello" "l")
(.contains "hello" "ll")
(.startsWith "hello" "ell" 1)
(.endsWith "hello" "")
(.matches "abc" "a.c")
(re-find #"\d+" "abc123def45")
(re-seq #"\d+" "abc123def45")
(re-matches #"(\w+)@(\w+)" "me@host")
(re-matches #"\w+" "a b")
(re-find #"(?i)HELLO" "say hello")

;; ----- escape and reverse
(str/escape "a<b>&c" {\< "&lt;" \> "&gt;" \& "&amp;"})
(str/escape "abc" {\b nil})
(str/escape "abc" {\b 1})
(str/escape "" {\a "b"})
(str/escape "a😀" {\a "A"})
(str/reverse "hello")
(str/reverse "")
(str/reverse "a😀b")
(map int (str/reverse "a😀b"))
(str/reverse "é")
(apply str (reverse "a😀b"))
(map int (apply str (reverse "a😀b")))
(.toString (.reverse (StringBuilder. "x😀y")))

;; ----- comparison and sorting
(compare "a" "b")
(compare "b" "a")
(compare "abc" "abd")
(compare "abc" "ab")
(compare "ab" "abc")
(compare "" "a")
(compare "A" "a")
(compare "a" "A")
(compare "Z" "a")
(compare "é" "f")
(compare "😀" "\uffff")
(compare "\uffff" "😀")
(compare "a" nil)
(compare nil "a")
(compare "a" :a)
(sort ["banana" "Apple" "cherry" "apple" ""])
(sort ["b" "a" "B" "A" "é" "e" "z" "Z"])
(sort-by count ["ccc" "a" "bb" "" "dd"])
(sort-by str/lower-case ["b" "A" "a" "B"])
(sort ["😀" "\uffff" "a"])
(sort ["10" "9" "100" "1"])
(sort compare ["x" "y" "a"])
(.compareTo "abc" "abd")
(= "abc" "abc")
(= "abc" (str "ab" "c"))
(identical? "abc" (str "ab" "c"))
(= "abc" 'abc)
(= "a" \a)
(max-key count "a" "bbb" "cc")

;; ----- hashing strings
(hash "")
(hash "a")
(hash "abc")
(hash "hello world")
(hash "😀")
(hash "é")
(hash "日本語")
(hash "\u0000")
(.hashCode "abc")
(.hashCode "")
(hash (str "ab" "c"))
(= (hash "abc") (hash (String. "abc")))
(hash (StringBuilder. "x"))
(hash ["a" "b"])
(hash #{"a"})

;; ----- String interop
(.toUpperCase "abc")
(.indexOf "abcabc" "c" 3)
(.replace "a.b.c" "." "-")
(.replace "aaa" \a \b)
(.replaceAll "a1b2" "\\d" "#")
(.replaceFirst "a1b2" "\\d" "#")
(vec (.split "a,b,,c,," ","))
(vec (.split "a,b,,c,," "," -1))
(.substring "hello" 1 3)
(.substring "hello" 2)
(.substring "hello" 3 1)
(.concat "a" "b")
(.repeat "ab" 3)
(.repeat "ab" 0)
(.isBlank "  ")
(vec (.toCharArray "abc"))
(String/valueOf 12)
(String/valueOf \c)
(String/valueOf true)
(String/join "-" ["a" "b"])
(String/format "%s-%d" (to-array ["a" 1]))
(format "%s=%d" "x" 5)
(count (.getBytes "abc" "UTF-8"))
(count (.getBytes "é" "UTF-8"))
(count (.getBytes "😀" "UTF-8"))
(count (.getBytes "日本語" "UTF-8"))
(count (.getBytes "é" "ISO-8859-1"))
(count (.getBytes "😀" "UTF-16BE"))
(vec (.getBytes "é" "UTF-8"))
(String. (byte-array [104 105]) "UTF-8")
(String. (byte-array [-61 -87]) "UTF-8")
(String. (char-array [\a \b]))
(.intern "x")
(.strip "  x ")
(vec (.toArray (.lines "a\nb\r\nc")))
(.charAt "" 0)
(.substring "abc" 5)
(.length (StringBuilder. "abc"))
(let [sb (StringBuilder.)] (.append sb "a") (.append sb 1) (.append sb \c) (.toString sb))
(let [sb (StringBuilder. "abc")] (.insert sb 1 "X") (.toString sb))
(let [sb (StringBuilder. "abc")] (.deleteCharAt sb 1) (str sb))
(let [sb (StringBuilder. "abc")] (.setCharAt sb 0 \z) (str sb))
(let [sb (StringBuilder.)] (.appendCodePoint sb 0x1F600) [(.length sb) (str sb)])
(String/valueOf (char-array [\x \y]))
(vec (.toArray (.codePoints "a😀")))
(.equals "a" "a")
(.equals "a" \a)
(.isEmpty "a")
(count (.toCharArray "😀"))
(.contentEquals "abc" (StringBuilder. "abc"))
(.regionMatches "Hello" true 0 "hE" 0 2)

;; ----- seq functions on strings
(map identity "abc")
(filter #(Character/isDigit (char %)) "a1b2")
(apply str (filter #(Character/isDigit (char %)) "a1b2"))
(frequencies "hello")
(group-by #(Character/isUpperCase (char %)) "aBcD")
(partition 2 "abcde")
(into [] "xyz")
(into #{} "aab")
(set "hello")
(reduce str "abc")
(distinct "aabbc")
(take 2 "hello")
(drop 3 "hello")
(interleave "abc" "123")
(mapcat str "ab" "12")
(keep-indexed #(when (even? %1) %2) "abcdef")
(seq (str/split "x y z" #" "))
(str/join (map str/upper-case ["a" "b"]))
(str/join "," (sort (set "banana")))
(string? "")
(string? \a)
(string? nil)
(string? (StringBuilder.))
(vec (char-array "abc"))
(seq (char-array "ab"))
(= (seq "ab") [\a \b])
(= "ab" [\a \b])
(= "ab" (seq "ab"))
