;; Types made at run time (doc/go/EVAL-NOTES.md, phase 2A): deftype, defrecord, reify,
;; definterface, protocols (inline, extend-type, extend-protocol, extend, on host types and
;; nil), satisfies?, instance? and casts, records as maps, mutable and primitive fields, IFn
;; implementations, Object overrides, covariant methods, proxy.

;; ----- definterface
(definterface IGreet (greet [name]) (^long twice [^long x]) (^String shout [^String s]))
(deftype Greeter [prefix]
  IGreet
  (greet [_ name] (str prefix " " name))
  (twice [_ x] (* 2 x))
  (shout [_ s] (.toUpperCase s)))
(def g (Greeter. "hello"))
(.greet g "you")
(.twice g 21)
(class (.twice g 21))
(.shout g "quiet")
(.greet ^IGreet g "hinted")
(.twice ^IGreet g 4)
(instance? IGreet g)
(instance? IGreet "x")
(.isInterface IGreet)
(map #(.getName %) (sort-by #(.getName %) (.getMethods IGreet)))
(.getName IGreet)
(let [o (reify IGreet (greet [_ n] [:reified n]) (twice [_ x] (inc x)) (shout [_ s] s))] [(.greet o 1) (.twice o 1) (.shout o "s")])
(definterface IBase (base []))
(definterface IDerived (derived []))
(deftype Both [] IBase (base [_] :b) IDerived (derived [_] :d))
[(.base (Both.)) (.derived (Both.))]
[(instance? IBase (Both.)) (instance? IDerived (Both.))]
(deftype Partial [] IGreet (greet [_ n] n))
(.greet (Partial.) "only")
(.twice (Partial.) 1)

;; ----- protocols: inline, extend-type, extend-protocol, extend
(defprotocol Describe (describe [x]) (describe2 [x y]))
(deftype Inline [v] Describe (describe [_] [:inline v]) (describe2 [_ y] [:inline v y]))
(describe (Inline. 1))
(describe2 (Inline. 1) 2)
(extend-type String Describe (describe [s] [:string s]) (describe2 [s y] [:string s y]))
(describe "abc")
(describe2 "abc" 3)
(extend-type nil Describe (describe [_] :nil) (describe2 [_ y] [:nil y]))
(describe nil)
(describe2 nil 1)
(extend-protocol Describe
  Long (describe [n] [:long n]) (describe2 [n y] (+ n y))
  java.util.List (describe [l] [:list (count l)]) (describe2 [l y] (conj (vec l) y))
  Object (describe [o] [:object (.getSimpleName (class o))]) (describe2 [o y] :obj))
(describe 5)
(describe2 5 6)
(describe [1 2 3])
(describe '(1 2))
(describe2 [1] 2)
(describe 1.5)
(describe :kw)
(describe2 :kw 1)
(describe (java.util.ArrayList. [1 2]))
(extend-type (Class/forName "[J") Describe (describe [a] [:longs (alength a)]) (describe2 [a y] y))
(describe (long-array 3))
(defrecord ExtRec [a])
(extend ExtRec Describe {:describe (fn [r] [:extended (:a r)]) :describe2 (fn [r y] [(:a r) y])})
(describe (->ExtRec 7))
(describe2 (->ExtRec 7) 8)
(satisfies? Describe (->ExtRec 1))
(satisfies? Describe "s")
(satisfies? Describe nil)
(satisfies? Describe 1)
(satisfies? Describe (Inline. 1))
(extends? Describe ExtRec)
(extends? Describe Inline)
(extends? Describe String)
(extends? Describe Double)
(sort (map #(if (nil? %) "nil" (.getName %)) (extenders Describe)))
(defprotocol Unextended (ux [x]))
(ux 1)
(satisfies? Unextended 1)
(defprotocol WithDoc "a protocol" (wd [x] "a method"))
(:doc (meta #'WithDoc))
(:doc (meta #'wd))
(:arglists (meta #'wd))
(sort (keys (:sigs WithDoc)))
(deftype ImplWD [] WithDoc (wd [_] :wd))
(wd (ImplWD.))
(instance? (:on-interface WithDoc) (ImplWD.))
(.getName (:on-interface WithDoc))
(defprotocol MultiArity (ma [x] [x y] [x y z]))
(extend-type Long MultiArity (ma ([x] 1) ([x y] 2) ([x y z] 3)))
[(ma 1) (ma 1 2) (ma 1 2 3)]
(defprotocol Recur1 (countdown [x n]))
(extend-type Long Recur1 (countdown [x n] (if (pos? n) (recur x (dec n)) [:done x])))
(countdown 5 10)
;; redefining an extension
(extend-type Long Recur1 (countdown [x n] :redefined))
(countdown 5 10)
;; extend-via-metadata
(defprotocol ViaMeta :extend-via-metadata true (vm [x]))
(vm (with-meta [1] {`vm (fn [x] [:via-meta (count x)])}))
(vm (with-meta {} {`vm (constantly :map)}))
(vm [1])

;; ----- instance?, casts, class names
(deftype T1 [a])
(defrecord R1 [a b])
(instance? T1 (T1. 1))
(instance? R1 (->R1 1 2))
(instance? T1 (->R1 1 2))
(instance? arbace.lang.IRecord (->R1 1 2))
(instance? arbace.lang.IRecord (T1. 1))
(instance? arbace.lang.IType (T1. 1))
(instance? arbace.lang.IType (->R1 1 2))
(instance? arbace.lang.IPersistentMap (->R1 1 2))
(instance? java.util.Map (->R1 1 2))
(instance? java.io.Serializable (->R1 1 2))
(instance? arbace.lang.IObj (->R1 1 2))
(instance? arbace.lang.IObj (T1. 1))
(.getName T1)
(.getName R1)
(.getSimpleName R1)
(class (T1. 1))
(class (->R1 1 2))
(cast T1 (T1. 1))
(cast T1 "s")
(cast R1 nil)
(record? (->R1 1 2))
(record? (T1. 1))
(record? {})
(.isInstance R1 (->R1 1 2))
(.isAssignableFrom arbace.lang.IRecord R1)
(.isAssignableFrom R1 arbace.lang.IRecord)
(sort (map #(.getName %) (.getInterfaces T1)))
(sort (map #(.getName %) (.getInterfaces R1)))
(.getSuperclass T1)
(sort (map str (supers T1)))
(sort (map str (supers R1)))
(map #(.getName %) (.getFields T1))
(sort (remove #(.startsWith ^String % "const__") (map #(.getName %) (.getFields R1))))
(T1/getBasis)
(R1/getBasis)
(meta (first (R1/getBasis)))
(let [^T1 t (T1. 42)] (.-a t))
(.-a (T1. 43))
(.-b (->R1 1 2))
(let [x (T1. 1)] (fn? x))
(let [x (T1. 1)] (ifn? x))
(ifn? (->R1 1 2))

;; ----- records as maps
(def r (->R1 1 2))
r
(pr-str r)
(str r)
(print-str r)
(:a r)
(:c r)
(:c r :nf)
(get r :b)
(keys r)
(vals r)
(seq r)
(count r)
(contains? r :a)
(contains? r :z)
(find r :b)
(assoc r :a 10)
(class (assoc r :a 10))
(assoc r :c 3)
(class (assoc r :c 3))
(:c (assoc r :c 3))
(keys (assoc r :c 3))
(dissoc r :a)
(class (dissoc r :a))
(dissoc r :c)
(class (dissoc (assoc r :c 3) :c))
(= r (->R1 1 2))
(= r {:a 1 :b 2})
(= {:a 1 :b 2} r)
(= r (map->R1 {:a 1 :b 2}))
(= r (->R1 1 3))
(= (hash r) (hash (->R1 1 2)))
(= (hash r) (hash {:a 1 :b 2}))
(= (.hashCode r) (.hashCode (->R1 1 2)))
(.equals r (->R1 1 2))
(.equals r {:a 1 :b 2})
(map->R1 {:a 1 :b 2 :c 3})
(map->R1 {:a 1})
(map->R1 {})
(:c (map->R1 {:a 1 :b 2 :c 3}))
(R1/create {:a 5 :b 6 :x 7})
(R1. 1 2)
(R1. 1 2 {:m 1} {:e 9})
(meta (R1. 1 2 {:m 1} {:e 9}))
(:e (R1. 1 2 {:m 1} {:e 9}))
(meta (with-meta r {:k :v}))
(= r (with-meta r {:k :v}))
(into r {:c 5 :a 0})
(merge r {:b 20})
(conj r [:z 26])
(reduce-kv (fn [acc k v] (conj acc [k v])) [] r)
(into {} r)
(set [(->R1 1 2) (->R1 1 2) (->R1 2 1)])
(get {(->R1 1 2) :found} (->R1 1 2))
(sort-by :a [(->R1 3 0) (->R1 1 0) (->R1 2 0)])
(select-keys r [:a])
(update r :a inc)
(update r :new (fnil inc 0))
(empty? r)
(binding [*print-namespace-maps* true] (pr-str (->R1 :x/a :x/b)))
(binding [*print-length* 1] (pr-str r))
(binding [*print-meta* true] (pr-str (with-meta r {:m 1})))
(defrecord RPrim [^long n ^double d])
(def rp (->RPrim 3 1.5))
rp
(class (:n rp))
(class (:d rp))
(class (.-n rp))
(->RPrim 3.9 1)
(:d (->RPrim 1 2))
(defrecord REmpty [])
(->REmpty)
(assoc (->REmpty) :x 1)
(= (->REmpty) {})
(defrecord RDefaults [a] Object (toString [_] (str "RD:" a)))
(str (->RDefaults 1))
(pr-str (->RDefaults 1))
(defrecord RKeys [a-b c? *d*])
(->RKeys 1 2 3)
(keys (->RKeys 1 2 3))
(:a-b (->RKeys 1 2 3))
(empty (->R1 1 2))

;; ----- deftype: mutable fields, primitive fields, Object overrides
(definterface ICount (inc_BANG_ []) (get_count []) (set_count [v]))
(deftype Cnt [^:unsynchronized-mutable ^long n]
  ICount
  (inc_BANG_ [this] (set! n (inc n)) this)
  (get_count [_] n)
  (set_count [this v] (set! n (long v)) this))
(def c (Cnt. 0))
(dotimes [_ 5] (.inc_BANG_ c))
(.get_count c)
(class (.get_count c))
(.get_count (.set_count c 100))
(.-n c)
(deftype VolCell [^:volatile-mutable v]
  arbace.lang.IDeref (deref [_] v)
  ICount (inc_BANG_ [this] (set! v (inc v)) this) (get_count [_] v) (set_count [this x] (set! v x) this))
(def vc (VolCell. 10))
(.inc_BANG_ vc)
@vc
(.set_count vc :kw)
@vc
(deftype Prims [^long l ^double d ^int i ^boolean b ^char ch])
(def pr1 (Prims. 1 2.5 3 true \x))
[(.-l pr1) (.-d pr1) (.-i pr1) (.-b pr1) (.-ch pr1)]
(map class [(.-l pr1) (.-d pr1) (.-i pr1) (.-b pr1) (.-ch pr1)])
(Prims. 1.9 2 3 false \y)
(.-l (Prims. 1.9 2 3 false \y))
(deftype Ov [x]
  Object
  (toString [_] (str "Ov(" x ")"))
  (equals [_ o] (and (instance? Ov o) (= x (.-x ^Ov o))))
  (hashCode [_] (* 31 (hash x))))
(str (Ov. 1))
(pr-str (Ov. 1))
(= (Ov. 1) (Ov. 1))
(= (Ov. 1) (Ov. 2))
(.equals (Ov. 1) (Ov. 1))
(.hashCode (Ov. 3))
(hash (Ov. 3))
(count (set [(Ov. 1) (Ov. 1) (Ov. 2)]))
(get {(Ov. 5) :five} (Ov. 5))
(count (distinct [(Ov. 1) (Ov. 1)]))
(format "%s" (Ov. 9))
(deftype NoOv [x])
(= (NoOv. 1) (NoOv. 1))
(let [o (NoOv. 1)] (= o o))
(deftype Eq [x] arbace.lang.IHashEq (hasheq [_] 99) Object (equals [_ o] true) (hashCode [_] 1))
(hash (Eq. 1))
(.hashCode (Eq. 1))
(= (Eq. 1) :anything)

;; ----- IFn implementations
(deftype F1 [k]
  arbace.lang.IFn
  (invoke [_] [:zero k])
  (invoke [_ a] [:one k a])
  (invoke [_ a b] [:two k a b])
  (applyTo [this args] (arbace.lang.AFn/applyToHelper this args)))
(def f1 (F1. :k))
(f1)
(f1 1)
(f1 1 2)
(f1 1 2 3)
(apply f1 [1 2])
(map f1 [1 2])
(apply f1 [])
(defrecord RFn [n] arbace.lang.IFn (invoke [_ x] (* n x)) (applyTo [this args] (arbace.lang.AFn/applyToHelper this args)))
((->RFn 3) 4)
(map (->RFn 2) [1 2 3])
(apply (->RFn 5) [2])
(deftype KW [] arbace.lang.ILookup (valAt [_ k] [:lookup k]) (valAt [_ k nf] [:lookup k nf]))
(:a (KW.))
(:a (KW.) :nf)
(get (KW.) :b)
(get (KW.) :b 0)

;; ----- collections implemented by deftype, covariant returns
(deftype MyVec [v]
  arbace.lang.IPersistentVector
  (cons [_ o] (MyVec. (conj v o)))
  (count [_] (count v))
  (empty [_] (MyVec. []))
  (equiv [_ o] (= v o))
  (seq [_] (seq v))
  (nth [_ i] (nth v i))
  (nth [_ i nf] (nth v i nf))
  (length [_] (count v))
  (assocN [_ i x] (MyVec. (assoc v i x)))
  (assoc [_ k x] (MyVec. (assoc v k x)))
  (containsKey [_ k] (contains? v k))
  (entryAt [_ k] (find v k))
  (valAt [_ k] (get v k))
  (valAt [_ k nf] (get v k nf))
  (peek [_] (peek v))
  (pop [_] (MyVec. (pop v)))
  (rseq [_] (rseq v)))
(def mv (MyVec. [1 2]))
(class (conj mv 3))
(seq (conj mv 3))
(count (conj mv 3))
(vector? mv)
(nth mv 1)
(get mv 0)
(seq (assoc mv 0 :x))
(class (.cons mv 9))
(class (.cons ^arbace.lang.IPersistentCollection mv 9))
(class (.cons ^arbace.lang.IPersistentVector mv 9))
(seq (pop mv))
(peek mv)
(seq (empty mv))
(= mv [1 2])
(rseq mv)
(deftype MySeq [xs]
  arbace.lang.ISeq
  (first [_] (first xs))
  (next [_] (when (next xs) (MySeq. (next xs))))
  (more [_] (if (next xs) (MySeq. (next xs)) ()))
  (cons [this o] (cons o this))
  (count [_] (count xs))
  (empty [_] ())
  (equiv [this o] (= (seq xs) (seq o)))
  (seq [this] this)
  arbace.lang.Sequential)
(seq (MySeq. [1 2 3]))
(into [] (MySeq. [1 2 3]))
(map inc (MySeq. [1 2 3]))
(count (MySeq. [1 2 3]))
(first (rest (MySeq. [1 2 3])))
(deftype Cntd [n] arbace.lang.Counted (count [_] n))
(count (Cntd. 7))
(deftype Sq2 [n] arbace.lang.Seqable (seq [_] (seq (range n))))
(seq (Sq2. 3))
(vec (Sq2. 3))
(deftype It [n] java.lang.Iterable (iterator [_] (.iterator ^java.lang.Iterable (range n))))
(vec (iterator-seq (.iterator (It. 3))))
(reduce + (It. 4))
(deftype Red [n] arbace.core.protocols/CollReduce (coll-reduce [_ f] (f n n)) (coll-reduce [_ f init] (f init n)))
(reduce + (Red. 5))
(reduce + 10 (Red. 5))
(deftype Cmp [n] Comparable (compareTo [_ o] (compare n (.-n ^Cmp o))))
(map #(.-n %) (sort [(Cmp. 3) (Cmp. 1) (Cmp. 2)]))
(compare (Cmp. 1) (Cmp. 2))
(deftype Dr [] arbace.lang.IDeref (deref [_] :dr) arbace.lang.IPending (isRealized [_] false))
@(Dr.)
(realized? (Dr.))
(deftype Mt [m] arbace.lang.IObj (withMeta [_ mm] (Mt. mm)) arbace.lang.IMeta (meta [_] m))
(meta (with-meta (Mt. nil) {:a 1}))
(meta (vary-meta (Mt. {:x 1}) assoc :y 2))
(deftype Nm [] arbace.lang.Named (getName [_] "nm") (getNamespace [_] "ns"))
[(name (Nm.)) (namespace (Nm.))]

;; ----- reify
(def counter (let [n (atom 0)] (reify arbace.lang.IDeref (deref [_] (swap! n inc)))))
[@counter @counter @counter]
(let [r (reify Describe (describe [this] (class this)) (describe2 [this y] y))] [(= (class r) (describe r)) (describe2 r :y)])
(satisfies? Describe (reify Describe (describe [_] 1) (describe2 [_ y] 2)))
(instance? arbace.lang.IObj (reify))
(meta (reify))
(meta (with-meta (reify) {:a 1}))
(let [x (with-meta (reify Object (toString [_] "rm")) {:a 1})] [(str x) (meta x)])
(.isInstance arbace.lang.IFn (reify arbace.lang.IFn))
(let [o (reify arbace.lang.IFn (invoke [_] :none))] (o))
(let [o (reify arbace.lang.IFn (invoke [_] :none))] (o 1))
(let [o (reify java.util.Comparator (compare [_ a b] (- (count a) (count b))))] (sort o ["ccc" "a" "bb"]))
(let [o (reify java.util.Iterator (hasNext [_] false) (next [_] nil))] (iterator-seq o))
(let [v [1 2 3] o (reify arbace.lang.Seqable (seq [_] (seq v)))] (seq o))
(let [o (reify Object (hashCode [_] 5) (equals [_ x] (= x 5)))] [(hash o) (= o 5) (.equals o 5)])
(defn make-r [x] (reify Describe (describe [_] [:closure x]) (describe2 [_ y] [x y])))
(map describe [(make-r 1) (make-r 2)])
(= (class (make-r 1)) (class (make-r 2)))

;; ----- proxy
(def p1 (proxy [Object] [] (toString [] "proxied")))
(str p1)
(.toString p1)
(instance? arbace.lang.IProxy p1)
(.getSuperclass (class p1))
(sort (map #(.getName %) (.getInterfaces (class p1))))
(.startsWith (.getName (class p1)) "user.proxy$java.lang.Object$")
(sort (keys (proxy-mappings p1)))
(= p1 p1)
(= (hash p1) (.hashCode p1))
(def p2 (proxy [arbace.lang.IDeref arbace.lang.ILookup] []
          (deref [] :deref)
          (valAt ([k] [:val k]) ([k nf] [:val k nf]))))
@p2
(:a p2)
(get p2 :b :nf)
(instance? arbace.lang.IDeref p2)
(instance? arbace.lang.Counted p2)
(.getName (class p2))
(def p3 (proxy [arbace.lang.Counted] []))
(count p3)
(def p4 (proxy [Object] [] (equals [o] (= o :eq)) (hashCode [] 42)))
(= p4 :eq)
(.equals p4 :no)
(hash p4)
(def w (java.io.StringWriter.))
(def pw (proxy [java.io.Writer] []
          (write ([x] (if (string? x) (.write w (.toUpperCase ^String x)) (.write w (int x))))
                 ([buf off len] (.write w (.toUpperCase (String. ^chars buf (int off) (int len))))))
          (flush [])
          (close [])))
(.write pw "abc")
(.write pw (int \d))
(.append pw "ef")
(binding [*out* pw] (print "printed") (prn :kw))
(str w)
(instance? java.io.Writer pw)
(instance? java.io.Flushable pw)
(.getSuperclass (class pw))
(let [sw (java.io.StringWriter.)
      lw (proxy [java.io.Writer] []
           (write ([x] (.write sw (str "[" x "]")))
                  ([buf off len] (.write sw (String. ^chars buf (int off) (int len)))))
           (flush []) (close []))]
  (.write lw "s")
  (.write lw (char-array "chars") 1 3)
  (str sw))
(let [out (java.io.StringWriter.)
      pw (java.io.PrintWriter. (proxy [java.io.Writer] []
                                 (write ([x] (.write out (str x)))
                                        ([buf off len] (.write out (String. ^chars buf (int off) (int len)))))
                                 (flush []) (close [])))]
  (.print pw "through ") (.println pw 42) (.flush pw)
  (str out))
(def pr2 (proxy [java.io.PushbackReader] [(java.io.StringReader. "abc")]
           (read ([] (let [c (proxy-super read)] (if (neg? c) c (int (Character/toUpperCase (char c))))))
                 ([b o l] (proxy-super read b o l)))))
[(.read pr2) (.read pr2) (.read pr2) (.read pr2)]
(def pr3 (proxy [java.io.PushbackReader] [(java.io.StringReader. "xyz")]))
(.read pr3)
(do (.unread pr3 (int \q)) [(char (.read pr3)) (char (.read pr3))])
(def ps (proxy [Object] [] (toString [] (str "s:" (proxy-super toString)))))
(.startsWith (str ps) "s:user.proxy$java.lang.Object$")
(def pu (proxy [Object] [] (toString [] "before")))
(str pu)
(do (update-proxy pu {"toString" (fn [this] "after")}) (str pu))
(do (update-proxy pu {"toString" nil}) (.startsWith (str pu) "user.proxy$"))
(do (init-proxy pu {"toString" (fn [_] "init")}) (str pu))
(proxy-mappings (init-proxy pu {}))
(def pc (get-proxy-class arbace.lang.IDeref))
(= pc (get-proxy-class arbace.lang.IDeref))
(.getName pc)
(def pci (construct-proxy pc))
(do (init-proxy pci {"deref" (fn [_] :constructed)}) @pci)
(let [x 10 p (proxy [arbace.lang.IFn] [] (invoke ([] x) ([a] (+ x a))))] [(p) (p 5)])
(let [p (proxy [java.util.Comparator] [] (compare [a b] (compare b a)))] (sort p [1 3 2]))
(let [p (proxy [java.lang.Runnable] [] (run [] (println "ran")))] (.run p) :ok)
(let [p (proxy [user.Describe] [] (describe [] :proxy-describe))] [(describe p) (satisfies? Describe p)])
(let [p (proxy [IGreet] [] (greet [n] [:proxy-greet n]))] (.greet p "x"))
(let [p (proxy [java.io.InputStream] [] (read ([] 65)))] [(.read p) (.read p)])
(let [i (atom 0) p (proxy [java.io.InputStream] [] (read ([] (if (< @i 3) (do (swap! i inc) (+ 96 @i)) -1))))] (slurp p))
(let [bs (java.io.ByteArrayOutputStream.) p (proxy [java.io.OutputStream] [] (write ([b] (.write bs (int b)))))] (.write p 104) (.write p 105) (String. (.toByteArray bs)))
(proxy [Object] [] (toString [] "a") (toString [] "b"))
(proxy [NotAClass] [])
(require 'arbace.pprint)
(arbace.pprint/cl-format nil "~a and ~s" "x" "y")
(with-out-str (arbace.pprint/pprint {:a 1 :b [1 2 3]}))
(arbace.pprint/cl-format nil "~:(~a~)" "capitalize these words")
(arbace.pprint/cl-format nil "~@(~a~)" "first word only")
(arbace.pprint/cl-format nil "~(~a~)" "LOWER")
(arbace.pprint/cl-format nil "~:@(~a~)" "upper")
(with-out-str (arbace.pprint/pprint (->R1 1 2)))
(with-out-str (arbace.pprint/pprint (Ov. 1)))
;; bean, a proxy of APersistentMap
(keys (bean "abc"))
(:empty (bean ""))
(:empty (bean "x"))
(count (bean "abc"))
(get (bean "abc") :class)
(get (bean "abc") :nope :nf)
(contains? (bean "abc") :blank)
(.getName (class (bean "abc")))
(instance? arbace.lang.APersistentMap (bean "a"))
(map? (bean "a"))
(= (bean "a") (bean "a"))
(select-keys (bean "a") [:blank :empty])
(assoc (select-keys (bean "a") [:blank]) :x 1)
(dissoc (bean "") :bytes :class)
(into {} (filter #(#{:blank :empty} (key %)) (bean "z")))
(sort (keys (bean (java.util.ArrayList.))))
;; a method defined twice
(reify java.util.List (size [_] 10) java.util.Collection (size [_] 20))
(deftype Twice [] java.util.List (size [_] 10) java.util.Collection (size [_] 20))
;; set! of a field through the object, in a method
(defprotocol PSet (setx [_ v]) (getx [_]))
(deftype TSet [^:unsynchronized-mutable x ^:volatile-mutable y]
  PSet
  (setx [this v] (set! (.x this) v) (set! (.-y this) (inc v)) [x y])
  (getx [this] [(.x this) (.-y this)]))
(def ts (TSet. 1 2))
(setx ts 10)
(getx ts)
(.-x ts)
