;; Generated by test/jrt/standins_reflect.clj (bin/jrt standins); do not edit.
;; jrt's stand-ins for JDK classes c2g will translate from jdk26u, phase 2b (doc/go/JRT-NOTES.md,
;; "Phase 2b"): the wrapper classes, java.lang.reflect.Type, InvocationTargetException, in the
;; shapes C2G-SPEC gives translated classes. Deleted when c2g's output joins the build.
(in-ns 'go.arbace.jrt)

(go/file "standin_reflect.go"
  :imports [[math "math"]])

;; ---- java.lang.Number

(go/type Number (struct Object))
(go/type Number_I
  (interface Object_I (Self_Number ^{:tag (* Number)} []) (Is_Serializable [])
    (ByteValue__B ^int8 [])
    (ShortValue__S ^int16 [])
    (IntValue__I ^int32 [])
    (LongValue__J ^int64 [])
    (FloatValue__F ^float32 [])
    (DoubleValue__D ^float64 [])))
(go/method Self_Number ^{:tag (* Number)} [^{:tag (* Number)} t] t)
(go/method Is_Serializable [^{:tag (* Number)} t])
(go/method Ctor [^{:tag (* Number)} t ^Number_I this])
(go/var Number_class
  (Define (addr (lit ClassInfo :Name "java.lang.Number" :Kind KindClass :Modifiers (bit-or AccPublic AccAbstract)
                     :Super Object_class :Interfaces (lit (slice (* Class)) Serializable_class)
                     :Go "arbace/jrt.Number"))))
(go/func Number_InstanceOf ^bool [^any x] (let [(values _ ok) (assert Number_I x)] ok))
(go/func Number_Cast ^Number_I [^any x]
  (when (== x nil) (return nil))
  (let [(values v ok) (assert Number_I x)]
    (when (not ok) (panic (ClassCast x Number_class)))
    v))

;; ---- java.lang.Boolean

(go/type Boolean (struct Object ^bool F_value))
(go/var Boolean_class
  (Define (addr (lit ClassInfo :Name "java.lang.Boolean" :Kind KindClass :Modifiers (bit-or AccPublic AccFinal)
                     :Super Object_class :Interfaces (lit (slice (* Class)) Serializable_class Comparable_class)
                     :Go "arbace/jrt.Boolean"))))
(go/var Boolean_TYPE Prim_boolean)
(go/func Boolean_New_Z ^{:tag (* Boolean)} [^bool v] (addr (lit Boolean :F_value v)))
(go/var [Boolean_TRUE (Boolean_New_Z true)] [Boolean_FALSE (Boolean_New_Z false)])
(go/func Boolean_ValueOf_Z__Boolean ^{:tag (* Boolean)} [^bool v]
  (when v (return Boolean_TRUE))
  Boolean_FALSE)
(go/method BooleanValue__Z ^bool [^{:tag (* Boolean)} t] (.-F_value t))
(go/method HashCode__I ^int32 [^{:tag (* Boolean)} t] (let [v (.-F_value t)] (if v (return 1231) (return 1237))))
(go/method Equals_O__Z ^bool [^{:tag (* Boolean)} t ^any o]
  (let [(values x ok) (assert (* Boolean) o)]
    (and ok (== (.-F_value t) (.-F_value x)))))
(go/method ToString__String ^{:tag (* String)} [^{:tag (* Boolean)} t] (let [v (.-F_value t)] (StrOfBool v)))
(go/method CompareTo_Boolean__I ^int32 [^{:tag (* Boolean)} t ^{:tag (* Boolean)} o]
  (let [a (.-F_value t) b (.-F_value (NN o))]
    (cond (== a b) (return 0) a (return 1) :else (return -1))))
(go/method CompareTo_O__I ^int32 [^{:tag (* Boolean)} t ^any o] (.CompareTo_Boolean__I t (Boolean_Cast o)))
(go/method Is_Comparable [^{:tag (* Boolean)} t])
(go/method Is_Serializable [^{:tag (* Boolean)} t])
(go/method Ref ^any [^{:tag (* Boolean)} t] (when (== t nil) (return nil)) t)
(go/method GetClass__Class ^{:tag (* Class)} [^{:tag (* Boolean)} t] Boolean_class)
(go/method Clone__O ^any [^{:tag (* Boolean)} t] (panic (CloneNotSupported t)))
(go/func Boolean_InstanceOf ^bool [^any x] (let [(values _ ok) (assert (* Boolean) x)] ok))
(go/func Boolean_Cast ^{:tag (* Boolean)} [^any x]
  (when (== x nil) (return nil))
  (let [(values v ok) (assert (* Boolean) x)]
    (when (not ok) (panic (ClassCast x Boolean_class)))
    v))

;; ---- java.lang.Character

(go/type Character (struct Object ^uint16 F_value))
(go/var Character_class
  (Define (addr (lit ClassInfo :Name "java.lang.Character" :Kind KindClass :Modifiers (bit-or AccPublic AccFinal)
                     :Super Object_class :Interfaces (lit (slice (* Class)) Serializable_class Comparable_class)
                     :Go "arbace/jrt.Character"))))
(go/var Character_TYPE Prim_char)
(go/func Character_New_C ^{:tag (* Character)} [^uint16 v] (addr (lit Character :F_value v)))
(go/var ^{:tag (slice (* Character))} characterCache (newCharacterCache))
(go/func newCharacterCache ^{:tag (slice (* Character))} []
  (let [c (make (slice (* Character)) 128)]
    (range [i _ c] (aset c i (Character_New_C (conv uint16 (+ i 0)))))
    c))
(go/func Character_ValueOf_C__Character "Character_ValueOf_C__Character is Character.valueOf: cached from 0 to 127, as jdk26u's.\n"
  ^{:tag (* Character)} [^uint16 v]
  (when (and (>= v 0) (<= v 127))
    (return (aget characterCache (- (conv int v) 0))))
  (Character_New_C v))
(go/method CharValue__C ^uint16 [^{:tag (* Character)} t] (.-F_value t))
(go/method HashCode__I ^int32 [^{:tag (* Character)} t] (let [v (.-F_value t)] (conv int32 v)))
(go/method Equals_O__Z ^bool [^{:tag (* Character)} t ^any o]
  (let [(values x ok) (assert (* Character) o)]
    (and ok (== (.-F_value t) (.-F_value x)))))
(go/method ToString__String ^{:tag (* String)} [^{:tag (* Character)} t] (let [v (.-F_value t)] (StrOfChar v)))
(go/method CompareTo_Character__I ^int32 [^{:tag (* Character)} t ^{:tag (* Character)} o]
  (let [a (.-F_value t) b (.-F_value (NN o))]
    (- (conv int32 a) (conv int32 b))))
(go/method CompareTo_O__I ^int32 [^{:tag (* Character)} t ^any o] (.CompareTo_Character__I t (Character_Cast o)))
(go/method Is_Comparable [^{:tag (* Character)} t])
(go/method Is_Serializable [^{:tag (* Character)} t])
(go/method Ref ^any [^{:tag (* Character)} t] (when (== t nil) (return nil)) t)
(go/method GetClass__Class ^{:tag (* Class)} [^{:tag (* Character)} t] Character_class)
(go/method Clone__O ^any [^{:tag (* Character)} t] (panic (CloneNotSupported t)))
(go/func Character_InstanceOf ^bool [^any x] (let [(values _ ok) (assert (* Character) x)] ok))
(go/func Character_Cast ^{:tag (* Character)} [^any x]
  (when (== x nil) (return nil))
  (let [(values v ok) (assert (* Character) x)]
    (when (not ok) (panic (ClassCast x Character_class)))
    v))

;; ---- java.lang.Byte

(go/type Byte (struct Number ^int8 F_value))
(go/var Byte_class
  (Define (addr (lit ClassInfo :Name "java.lang.Byte" :Kind KindClass :Modifiers (bit-or AccPublic AccFinal)
                     :Super Number_class :Interfaces (lit (slice (* Class)) Comparable_class)
                     :Go "arbace/jrt.Byte"))))
(go/var Byte_TYPE Prim_byte)
(go/func Byte_New_B ^{:tag (* Byte)} [^int8 v] (addr (lit Byte :F_value v)))
(go/var ^{:tag (slice (* Byte))} byteCache (newByteCache))
(go/func newByteCache ^{:tag (slice (* Byte))} []
  (let [c (make (slice (* Byte)) 256)]
    (range [i _ c] (aset c i (Byte_New_B (conv int8 (+ i -128)))))
    c))
(go/func Byte_ValueOf_B__Byte "Byte_ValueOf_B__Byte is Byte.valueOf: cached from -128 to 127, as jdk26u's.\n"
  ^{:tag (* Byte)} [^int8 v]
  (when (and (>= v -128) (<= v 127))
    (return (aget byteCache (- (conv int v) -128))))
  (Byte_New_B v))
(go/method ByteValue__B ^int8 [^{:tag (* Byte)} t] (let [v (.-F_value t)] v))
(go/method ShortValue__S ^int16 [^{:tag (* Byte)} t] (let [v (.-F_value t)] (conv int16 v)))
(go/method IntValue__I ^int32 [^{:tag (* Byte)} t] (let [v (.-F_value t)] (conv int32 v)))
(go/method LongValue__J ^int64 [^{:tag (* Byte)} t] (let [v (.-F_value t)] (conv int64 v)))
(go/method FloatValue__F ^float32 [^{:tag (* Byte)} t] (let [v (.-F_value t)] (conv float32 v)))
(go/method DoubleValue__D ^float64 [^{:tag (* Byte)} t] (let [v (.-F_value t)] (conv float64 v)))
(go/method HashCode__I ^int32 [^{:tag (* Byte)} t] (let [v (.-F_value t)] (conv int32 v)))
(go/method Equals_O__Z ^bool [^{:tag (* Byte)} t ^any o]
  (let [(values x ok) (assert (* Byte) o)]
    (and ok (== (.-F_value t) (.-F_value x)))))
(go/method ToString__String ^{:tag (* String)} [^{:tag (* Byte)} t] (let [v (.-F_value t)] (StrOfInt (conv int32 v))))
(go/method CompareTo_Byte__I ^int32 [^{:tag (* Byte)} t ^{:tag (* Byte)} o]
  (let [a (.-F_value t) b (.-F_value (NN o))]
    (- (conv int32 a) (conv int32 b))))
(go/method CompareTo_O__I ^int32 [^{:tag (* Byte)} t ^any o] (.CompareTo_Byte__I t (Byte_Cast o)))
(go/method Is_Comparable [^{:tag (* Byte)} t])
(go/method Ref ^any [^{:tag (* Byte)} t] (when (== t nil) (return nil)) t)
(go/method GetClass__Class ^{:tag (* Class)} [^{:tag (* Byte)} t] Byte_class)
(go/method Clone__O ^any [^{:tag (* Byte)} t] (panic (CloneNotSupported t)))
(go/func Byte_InstanceOf ^bool [^any x] (let [(values _ ok) (assert (* Byte) x)] ok))
(go/func Byte_Cast ^{:tag (* Byte)} [^any x]
  (when (== x nil) (return nil))
  (let [(values v ok) (assert (* Byte) x)]
    (when (not ok) (panic (ClassCast x Byte_class)))
    v))

;; ---- java.lang.Short

(go/type Short (struct Number ^int16 F_value))
(go/var Short_class
  (Define (addr (lit ClassInfo :Name "java.lang.Short" :Kind KindClass :Modifiers (bit-or AccPublic AccFinal)
                     :Super Number_class :Interfaces (lit (slice (* Class)) Comparable_class)
                     :Go "arbace/jrt.Short"))))
(go/var Short_TYPE Prim_short)
(go/func Short_New_S ^{:tag (* Short)} [^int16 v] (addr (lit Short :F_value v)))
(go/var ^{:tag (slice (* Short))} shortCache (newShortCache))
(go/func newShortCache ^{:tag (slice (* Short))} []
  (let [c (make (slice (* Short)) 256)]
    (range [i _ c] (aset c i (Short_New_S (conv int16 (+ i -128)))))
    c))
(go/func Short_ValueOf_S__Short "Short_ValueOf_S__Short is Short.valueOf: cached from -128 to 127, as jdk26u's.\n"
  ^{:tag (* Short)} [^int16 v]
  (when (and (>= v -128) (<= v 127))
    (return (aget shortCache (- (conv int v) -128))))
  (Short_New_S v))
(go/method ByteValue__B ^int8 [^{:tag (* Short)} t] (let [v (.-F_value t)] (conv int8 v)))
(go/method ShortValue__S ^int16 [^{:tag (* Short)} t] (let [v (.-F_value t)] v))
(go/method IntValue__I ^int32 [^{:tag (* Short)} t] (let [v (.-F_value t)] (conv int32 v)))
(go/method LongValue__J ^int64 [^{:tag (* Short)} t] (let [v (.-F_value t)] (conv int64 v)))
(go/method FloatValue__F ^float32 [^{:tag (* Short)} t] (let [v (.-F_value t)] (conv float32 v)))
(go/method DoubleValue__D ^float64 [^{:tag (* Short)} t] (let [v (.-F_value t)] (conv float64 v)))
(go/method HashCode__I ^int32 [^{:tag (* Short)} t] (let [v (.-F_value t)] (conv int32 v)))
(go/method Equals_O__Z ^bool [^{:tag (* Short)} t ^any o]
  (let [(values x ok) (assert (* Short) o)]
    (and ok (== (.-F_value t) (.-F_value x)))))
(go/method ToString__String ^{:tag (* String)} [^{:tag (* Short)} t] (let [v (.-F_value t)] (StrOfInt (conv int32 v))))
(go/method CompareTo_Short__I ^int32 [^{:tag (* Short)} t ^{:tag (* Short)} o]
  (let [a (.-F_value t) b (.-F_value (NN o))]
    (- (conv int32 a) (conv int32 b))))
(go/method CompareTo_O__I ^int32 [^{:tag (* Short)} t ^any o] (.CompareTo_Short__I t (Short_Cast o)))
(go/method Is_Comparable [^{:tag (* Short)} t])
(go/method Ref ^any [^{:tag (* Short)} t] (when (== t nil) (return nil)) t)
(go/method GetClass__Class ^{:tag (* Class)} [^{:tag (* Short)} t] Short_class)
(go/method Clone__O ^any [^{:tag (* Short)} t] (panic (CloneNotSupported t)))
(go/func Short_InstanceOf ^bool [^any x] (let [(values _ ok) (assert (* Short) x)] ok))
(go/func Short_Cast ^{:tag (* Short)} [^any x]
  (when (== x nil) (return nil))
  (let [(values v ok) (assert (* Short) x)]
    (when (not ok) (panic (ClassCast x Short_class)))
    v))

;; ---- java.lang.Integer

(go/type Integer (struct Number ^int32 F_value))
(go/var Integer_class
  (Define (addr (lit ClassInfo :Name "java.lang.Integer" :Kind KindClass :Modifiers (bit-or AccPublic AccFinal)
                     :Super Number_class :Interfaces (lit (slice (* Class)) Comparable_class)
                     :Go "arbace/jrt.Integer"))))
(go/var Integer_TYPE Prim_int)
(go/func Integer_New_I ^{:tag (* Integer)} [^int32 v] (addr (lit Integer :F_value v)))
(go/var ^{:tag (slice (* Integer))} integerCache (newIntegerCache))
(go/func newIntegerCache ^{:tag (slice (* Integer))} []
  (let [c (make (slice (* Integer)) 256)]
    (range [i _ c] (aset c i (Integer_New_I (conv int32 (+ i -128)))))
    c))
(go/func Integer_ValueOf_I__Integer "Integer_ValueOf_I__Integer is Integer.valueOf: cached from -128 to 127, as jdk26u's.\n"
  ^{:tag (* Integer)} [^int32 v]
  (when (and (>= v -128) (<= v 127))
    (return (aget integerCache (- (conv int v) -128))))
  (Integer_New_I v))
(go/method ByteValue__B ^int8 [^{:tag (* Integer)} t] (let [v (.-F_value t)] (conv int8 v)))
(go/method ShortValue__S ^int16 [^{:tag (* Integer)} t] (let [v (.-F_value t)] (conv int16 v)))
(go/method IntValue__I ^int32 [^{:tag (* Integer)} t] (let [v (.-F_value t)] v))
(go/method LongValue__J ^int64 [^{:tag (* Integer)} t] (let [v (.-F_value t)] (conv int64 v)))
(go/method FloatValue__F ^float32 [^{:tag (* Integer)} t] (let [v (.-F_value t)] (conv float32 v)))
(go/method DoubleValue__D ^float64 [^{:tag (* Integer)} t] (let [v (.-F_value t)] (conv float64 v)))
(go/method HashCode__I ^int32 [^{:tag (* Integer)} t] (let [v (.-F_value t)] v))
(go/method Equals_O__Z ^bool [^{:tag (* Integer)} t ^any o]
  (let [(values x ok) (assert (* Integer) o)]
    (and ok (== (.-F_value t) (.-F_value x)))))
(go/method ToString__String ^{:tag (* String)} [^{:tag (* Integer)} t] (let [v (.-F_value t)] (StrOfInt v)))
(go/method CompareTo_Integer__I ^int32 [^{:tag (* Integer)} t ^{:tag (* Integer)} o]
  (let [a (.-F_value t) b (.-F_value (NN o))]
    (cond (< a b) (return -1) (== a b) (return 0) :else (return 1))))
(go/method CompareTo_O__I ^int32 [^{:tag (* Integer)} t ^any o] (.CompareTo_Integer__I t (Integer_Cast o)))
(go/method Is_Comparable [^{:tag (* Integer)} t])
(go/method Ref ^any [^{:tag (* Integer)} t] (when (== t nil) (return nil)) t)
(go/method GetClass__Class ^{:tag (* Class)} [^{:tag (* Integer)} t] Integer_class)
(go/method Clone__O ^any [^{:tag (* Integer)} t] (panic (CloneNotSupported t)))
(go/func Integer_InstanceOf ^bool [^any x] (let [(values _ ok) (assert (* Integer) x)] ok))
(go/func Integer_Cast ^{:tag (* Integer)} [^any x]
  (when (== x nil) (return nil))
  (let [(values v ok) (assert (* Integer) x)]
    (when (not ok) (panic (ClassCast x Integer_class)))
    v))

;; ---- java.lang.Long

(go/type Long (struct Number ^int64 F_value))
(go/var Long_class
  (Define (addr (lit ClassInfo :Name "java.lang.Long" :Kind KindClass :Modifiers (bit-or AccPublic AccFinal)
                     :Super Number_class :Interfaces (lit (slice (* Class)) Comparable_class)
                     :Go "arbace/jrt.Long"))))
(go/var Long_TYPE Prim_long)
(go/func Long_New_J ^{:tag (* Long)} [^int64 v] (addr (lit Long :F_value v)))
(go/var ^{:tag (slice (* Long))} longCache (newLongCache))
(go/func newLongCache ^{:tag (slice (* Long))} []
  (let [c (make (slice (* Long)) 256)]
    (range [i _ c] (aset c i (Long_New_J (conv int64 (+ i -128)))))
    c))
(go/func Long_ValueOf_J__Long "Long_ValueOf_J__Long is Long.valueOf: cached from -128 to 127, as jdk26u's.\n"
  ^{:tag (* Long)} [^int64 v]
  (when (and (>= v -128) (<= v 127))
    (return (aget longCache (- (conv int v) -128))))
  (Long_New_J v))
(go/method ByteValue__B ^int8 [^{:tag (* Long)} t] (let [v (.-F_value t)] (conv int8 v)))
(go/method ShortValue__S ^int16 [^{:tag (* Long)} t] (let [v (.-F_value t)] (conv int16 v)))
(go/method IntValue__I ^int32 [^{:tag (* Long)} t] (let [v (.-F_value t)] (conv int32 v)))
(go/method LongValue__J ^int64 [^{:tag (* Long)} t] (let [v (.-F_value t)] v))
(go/method FloatValue__F ^float32 [^{:tag (* Long)} t] (let [v (.-F_value t)] (conv float32 v)))
(go/method DoubleValue__D ^float64 [^{:tag (* Long)} t] (let [v (.-F_value t)] (conv float64 v)))
(go/method HashCode__I ^int32 [^{:tag (* Long)} t] (let [v (.-F_value t)] (conv int32 (bit-xor v (conv int64 (>> (conv uint64 v) 32))))))
(go/method Equals_O__Z ^bool [^{:tag (* Long)} t ^any o]
  (let [(values x ok) (assert (* Long) o)]
    (and ok (== (.-F_value t) (.-F_value x)))))
(go/method ToString__String ^{:tag (* String)} [^{:tag (* Long)} t] (let [v (.-F_value t)] (StrOfLong v)))
(go/method CompareTo_Long__I ^int32 [^{:tag (* Long)} t ^{:tag (* Long)} o]
  (let [a (.-F_value t) b (.-F_value (NN o))]
    (cond (< a b) (return -1) (== a b) (return 0) :else (return 1))))
(go/method CompareTo_O__I ^int32 [^{:tag (* Long)} t ^any o] (.CompareTo_Long__I t (Long_Cast o)))
(go/method Is_Comparable [^{:tag (* Long)} t])
(go/method Ref ^any [^{:tag (* Long)} t] (when (== t nil) (return nil)) t)
(go/method GetClass__Class ^{:tag (* Class)} [^{:tag (* Long)} t] Long_class)
(go/method Clone__O ^any [^{:tag (* Long)} t] (panic (CloneNotSupported t)))
(go/func Long_InstanceOf ^bool [^any x] (let [(values _ ok) (assert (* Long) x)] ok))
(go/func Long_Cast ^{:tag (* Long)} [^any x]
  (when (== x nil) (return nil))
  (let [(values v ok) (assert (* Long) x)]
    (when (not ok) (panic (ClassCast x Long_class)))
    v))

;; ---- java.lang.Float

(go/type Float (struct Number ^float32 F_value))
(go/var Float_class
  (Define (addr (lit ClassInfo :Name "java.lang.Float" :Kind KindClass :Modifiers (bit-or AccPublic AccFinal)
                     :Super Number_class :Interfaces (lit (slice (* Class)) Comparable_class)
                     :Go "arbace/jrt.Float"))))
(go/var Float_TYPE Prim_float)
(go/func Float_New_F ^{:tag (* Float)} [^float32 v] (addr (lit Float :F_value v)))
(go/func Float_ValueOf_F__Float ^{:tag (* Float)} [^float32 v] (Float_New_F v))
(go/method ByteValue__B ^int8 [^{:tag (* Float)} t] (let [v (.-F_value t)] (conv int8 (F2I v))))
(go/method ShortValue__S ^int16 [^{:tag (* Float)} t] (let [v (.-F_value t)] (conv int16 (F2I v))))
(go/method IntValue__I ^int32 [^{:tag (* Float)} t] (let [v (.-F_value t)] (F2I v)))
(go/method LongValue__J ^int64 [^{:tag (* Float)} t] (let [v (.-F_value t)] (F2L v)))
(go/method FloatValue__F ^float32 [^{:tag (* Float)} t] (let [v (.-F_value t)] v))
(go/method DoubleValue__D ^float64 [^{:tag (* Float)} t] (let [v (.-F_value t)] (conv float64 v)))
(go/method HashCode__I ^int32 [^{:tag (* Float)} t] (let [v (.-F_value t)] (floatToIntBits v)))
(go/method Equals_O__Z ^bool [^{:tag (* Float)} t ^any o]
  (let [(values x ok) (assert (* Float) o)]
    (and ok (== (floatToIntBits (.-F_value t)) (floatToIntBits (.-F_value x))))))
(go/method ToString__String ^{:tag (* String)} [^{:tag (* Float)} t] (let [v (.-F_value t)] (StrOfFloat v)))
(go/method CompareTo_Float__I ^int32 [^{:tag (* Float)} t ^{:tag (* Float)} o]
  (let [a (.-F_value t) b (.-F_value (NN o))]
    (compareFloat64 (conv float64 a) (conv float64 b))))
(go/method CompareTo_O__I ^int32 [^{:tag (* Float)} t ^any o] (.CompareTo_Float__I t (Float_Cast o)))
(go/method Is_Comparable [^{:tag (* Float)} t])
(go/method Ref ^any [^{:tag (* Float)} t] (when (== t nil) (return nil)) t)
(go/method GetClass__Class ^{:tag (* Class)} [^{:tag (* Float)} t] Float_class)
(go/method Clone__O ^any [^{:tag (* Float)} t] (panic (CloneNotSupported t)))
(go/func Float_InstanceOf ^bool [^any x] (let [(values _ ok) (assert (* Float) x)] ok))
(go/func Float_Cast ^{:tag (* Float)} [^any x]
  (when (== x nil) (return nil))
  (let [(values v ok) (assert (* Float) x)]
    (when (not ok) (panic (ClassCast x Float_class)))
    v))

;; ---- java.lang.Double

(go/type Double (struct Number ^float64 F_value))
(go/var Double_class
  (Define (addr (lit ClassInfo :Name "java.lang.Double" :Kind KindClass :Modifiers (bit-or AccPublic AccFinal)
                     :Super Number_class :Interfaces (lit (slice (* Class)) Comparable_class)
                     :Go "arbace/jrt.Double"))))
(go/var Double_TYPE Prim_double)
(go/func Double_New_D ^{:tag (* Double)} [^float64 v] (addr (lit Double :F_value v)))
(go/func Double_ValueOf_D__Double ^{:tag (* Double)} [^float64 v] (Double_New_D v))
(go/method ByteValue__B ^int8 [^{:tag (* Double)} t] (let [v (.-F_value t)] (conv int8 (D2I v))))
(go/method ShortValue__S ^int16 [^{:tag (* Double)} t] (let [v (.-F_value t)] (conv int16 (D2I v))))
(go/method IntValue__I ^int32 [^{:tag (* Double)} t] (let [v (.-F_value t)] (D2I v)))
(go/method LongValue__J ^int64 [^{:tag (* Double)} t] (let [v (.-F_value t)] (D2L v)))
(go/method FloatValue__F ^float32 [^{:tag (* Double)} t] (let [v (.-F_value t)] (conv float32 v)))
(go/method DoubleValue__D ^float64 [^{:tag (* Double)} t] (let [v (.-F_value t)] v))
(go/method HashCode__I ^int32 [^{:tag (* Double)} t] (let [v (.-F_value t)] (let [b (doubleToLongBits v)] (conv int32 (bit-xor b (conv int64 (>> (conv uint64 b) 32)))))))
(go/method Equals_O__Z ^bool [^{:tag (* Double)} t ^any o]
  (let [(values x ok) (assert (* Double) o)]
    (and ok (== (doubleToLongBits (.-F_value t)) (doubleToLongBits (.-F_value x))))))
(go/method ToString__String ^{:tag (* String)} [^{:tag (* Double)} t] (let [v (.-F_value t)] (StrOfDouble v)))
(go/method CompareTo_Double__I ^int32 [^{:tag (* Double)} t ^{:tag (* Double)} o]
  (let [a (.-F_value t) b (.-F_value (NN o))]
    (compareFloat64 a b)))
(go/method CompareTo_O__I ^int32 [^{:tag (* Double)} t ^any o] (.CompareTo_Double__I t (Double_Cast o)))
(go/method Is_Comparable [^{:tag (* Double)} t])
(go/method Ref ^any [^{:tag (* Double)} t] (when (== t nil) (return nil)) t)
(go/method GetClass__Class ^{:tag (* Class)} [^{:tag (* Double)} t] Double_class)
(go/method Clone__O ^any [^{:tag (* Double)} t] (panic (CloneNotSupported t)))
(go/func Double_InstanceOf ^bool [^any x] (let [(values _ ok) (assert (* Double) x)] ok))
(go/func Double_Cast ^{:tag (* Double)} [^any x]
  (when (== x nil) (return nil))
  (let [(values v ok) (assert (* Double) x)]
    (when (not ok) (panic (ClassCast x Double_class)))
    v))

;; ---- java.lang.Void

(go/type Void (struct Object))
(go/var Void_class
  (Define (addr (lit ClassInfo :Name "java.lang.Void" :Kind KindClass :Modifiers (bit-or AccPublic AccFinal)
                     :Super Object_class :Go "arbace/jrt.Void"))))
(go/var Void_TYPE Prim_void)
(go/method Ref ^any [^{:tag (* Void)} t] (when (== t nil) (return nil)) t)
(go/method GetClass__Class ^{:tag (* Class)} [^{:tag (* Void)} t] Void_class)
(go/method ToString__String ^{:tag (* String)} [^{:tag (* Void)} t] (Object_toString t))
(go/method Clone__O ^any [^{:tag (* Void)} t] (panic (CloneNotSupported t)))
(go/func Void_InstanceOf ^bool [^any x] (let [(values _ ok) (assert (* Void) x)] ok))

;; the bits of Float.floatToIntBits and Double.doubleToLongBits (one NaN) and Double.compare
(go/func floatToIntBits ^int32 [^float32 f]
  (when (!= f f) (return 0x7fc00000))
  (conv int32 (math/Float32bits f)))
(go/func doubleToLongBits ^int64 [^float64 d]
  (when (!= d d) (return 0x7ff8000000000000))
  (conv int64 (math/Float64bits d)))
(go/func compareFloat64 ^int32 [^float64 a ^float64 b]
  (cond (< a b) (return -1) (> a b) (return 1))
  (let [x (doubleToLongBits a) y (doubleToLongBits b)]
    (cond (== x y) (return 0) (< x y) (return -1) :else (return 1))))

;; ---- java.lang.reflect.Type

(go/type Type
  (interface Object_I (Is_Type [])
    (GetTypeName__String ^{:tag (* String)} [])))
(go/var Type_class
  (Define (addr (lit ClassInfo :Name "java.lang.reflect.Type" :Kind KindInterface
                     :Modifiers (bit-or AccPublic AccInterface AccAbstract) :Go "arbace/jrt.Type"))))
(go/func Type_GetTypeName__String "Type_GetTypeName__String is Type.getTypeName's default: toString().\n"
  ^{:tag (* String)} [^Type this]
  (.ToString__String this))
(go/func Type_InstanceOf ^bool [^any x] (let [(values _ ok) (assert Type x)] ok))
(go/func Type_Cast ^Type [^any x]
  (when (== x nil) (return nil))
  (let [(values v ok) (assert Type x)]
    (when (not ok) (panic (ClassCast x Type_class)))
    v))

;; ---- java.lang.reflect.InvocationTargetException (getCause is the target)

(go/type InvocationTargetException (struct ReflectiveOperationException ^Throwable_I F_target))
(go/var InvocationTargetException_class
  (Define (addr (lit ClassInfo :Name "java.lang.reflect.InvocationTargetException" :Kind KindClass :Modifiers AccPublic
                     :Super ReflectiveOperationException_class :Go "arbace/jrt.InvocationTargetException"))))
(go/func InvocationTargetException_New ^{:tag (* InvocationTargetException)} []
  (let [t (addr (lit InvocationTargetException))] (.Ctor t) t))
(go/method Ctor [^{:tag (* InvocationTargetException)} t]
  (.Ctor_Throwable (.-ReflectiveOperationException t) t nil))
(go/func InvocationTargetException_New_Throwable ^{:tag (* InvocationTargetException)} [^Throwable_I target]
  (let [t (addr (lit InvocationTargetException))] (.Ctor_Throwable t target) t))
(go/method Ctor_Throwable [^{:tag (* InvocationTargetException)} t ^Throwable_I target]
  (.Ctor_Throwable (.-ReflectiveOperationException t) t nil)
  (set! (.-F_target t) target))
(go/func InvocationTargetException_New_Throwable_String ^{:tag (* InvocationTargetException)} [^Throwable_I target ^{:tag (* String)} s]
  (let [t (addr (lit InvocationTargetException))] (.Ctor_Throwable_String t target s) t))
(go/method Ctor_Throwable_String [^{:tag (* InvocationTargetException)} t ^Throwable_I target ^{:tag (* String)} s]
  (.Ctor_String_Throwable (.-ReflectiveOperationException t) t s nil)
  (set! (.-F_target t) target))
(go/method GetTargetException__Throwable ^Throwable_I [^{:tag (* InvocationTargetException)} t] (.-F_target t))
(go/method Ref ^any [^{:tag (* InvocationTargetException)} t] (when (== t nil) (return nil)) t)
(go/method GetClass__Class ^{:tag (* Class)} [^{:tag (* InvocationTargetException)} t] InvocationTargetException_class)
(go/method Clone__O ^any [^{:tag (* InvocationTargetException)} t] (panic (CloneNotSupported t)))
(go/method ToString__String ^{:tag (* String)} [^{:tag (* InvocationTargetException)} t] (.Impl_ToString__String t t))
(go/method GetMessage__String ^{:tag (* String)} [^{:tag (* InvocationTargetException)} t] (.Impl_GetMessage__String t t))
(go/method GetLocalizedMessage__String ^{:tag (* String)} [^{:tag (* InvocationTargetException)} t] (.Impl_GetLocalizedMessage__String t t))
(go/method GetCause__Throwable ^Throwable_I [^{:tag (* InvocationTargetException)} t] (.-F_target t))
(go/method InitCause_Throwable__Throwable ^Throwable_I [^{:tag (* InvocationTargetException)} t ^Throwable_I c] (.Impl_InitCause_Throwable__Throwable t t c))
(go/method SetCause_Throwable__V [^{:tag (* InvocationTargetException)} t ^Throwable_I c] (.Impl_SetCause_Throwable__V t t c))
(go/method FillInStackTrace__Throwable ^Throwable_I [^{:tag (* InvocationTargetException)} t] (.Impl_FillInStackTrace__Throwable t t))
(go/method GetStackTrace__StackTraceElement1 ^{:tag (* RefArray)} [^{:tag (* InvocationTargetException)} t] (.Impl_GetStackTrace__StackTraceElement1 t t))
(go/method SetStackTrace_StackTraceElement1__V [^{:tag (* InvocationTargetException)} t ^{:tag (* RefArray)} a] (.Impl_SetStackTrace_StackTraceElement1__V t t a))
(go/method PrintStackTrace__V [^{:tag (* InvocationTargetException)} t] (.Impl_PrintStackTrace__V t t))
(go/method AddSuppressed_Throwable__V [^{:tag (* InvocationTargetException)} t ^Throwable_I e] (.Impl_AddSuppressed_Throwable__V t t e))
(go/method GetSuppressed__Throwable1 ^{:tag (* RefArray)} [^{:tag (* InvocationTargetException)} t] (.Impl_GetSuppressed__Throwable1 t t))
(go/func InvocationTargetException_InstanceOf ^bool [^any x] (let [(values _ ok) (assert (* InvocationTargetException) x)] ok))
(go/func InvocationTargetException_Cast ^{:tag (* InvocationTargetException)} [^any x]
  (when (== x nil) (return nil))
  (let [(values v ok) (assert (* InvocationTargetException) x)]
    (when (not ok) (panic (ClassCast x InvocationTargetException_class)))
    v))

;; ClassInfo.IsInstance, set at init (§5.11)
(go/func init []
  (set! (.-IsInstance (.Info Number_class)) Number_InstanceOf)
  (set! (.-IsInstance (.Info Void_class)) Void_InstanceOf)
  (set! (.-IsInstance (.Info Type_class)) Type_InstanceOf)
  (set! (.-IsInstance (.Info InvocationTargetException_class)) InvocationTargetException_InstanceOf)
  (set! (.-IsInstance (.Info Boolean_class)) Boolean_InstanceOf)
  (set! (.-IsInstance (.Info Character_class)) Character_InstanceOf)
  (set! (.-IsInstance (.Info Byte_class)) Byte_InstanceOf)
  (set! (.-IsInstance (.Info Short_class)) Short_InstanceOf)
  (set! (.-IsInstance (.Info Integer_class)) Integer_InstanceOf)
  (set! (.-IsInstance (.Info Long_class)) Long_InstanceOf)
  (set! (.-IsInstance (.Info Float_class)) Float_InstanceOf)
  (set! (.-IsInstance (.Info Double_class)) Double_InstanceOf))
