;; Generated by test/jrt/standins.clj (bin/jrt standins); do not edit.
;; jrt's stand-in for java.lang.Character (doc/go/JRT-NOTES.md, "Stand-ins"): the case
;; mappings and properties String needs, over Go's unicode (Unicode 17.0.0, as JDK 26's
;; Character), with the special uppercase mappings of jdk26u's
;; src/java.base/share/data/unicodedata/SpecialCasing.txt (102 entries).
;; Replaced by calls of the translated Character when c2g's output joins the build.
(in-ns 'go.arbace.jrt)

(go/file "standin_character.go"
  :imports [[unicode "unicode"]])

(go/func charToUpper "charToUpper is Character.toUpperCase(int).\n" ^rune [^rune c]
  (when (or (< c 0) (> c 0x10FFFF)) (return c))
  (unicode/ToUpper c))

(go/func charToLower "charToLower is Character.toLowerCase(int).\n" ^rune [^rune c]
  (when (or (< c 0) (> c 0x10FFFF)) (return c))
  (unicode/ToLower c))

(go/func charToUpperEx
  "charToUpperEx is Character.toUpperCaseEx: -1 (Character.ERROR) when the uppercase is
several characters (charToUpperArray).\n"
  ^rune [^rune c]
  (let [(values _ ok) (aget specialUpper c)]
    (when ok (return -1)))
  (charToUpper c))

(go/func charToUpperArray "charToUpperArray is Character.toUpperCaseCharArray.\n"
  ^{:tag (slice uint16)} [^rune c]
  (let [(values s ok) (aget specialUpper c)]
    (when ok (return s)))
  (appendCodePoint nil (charToUpper c)))

(go/func charIsWhitespace
  "charIsWhitespace is Character.isWhitespace(int): space separators but the no-break spaces,
line and paragraph separators, and U+0009-U+000D, U+001C-U+001F.\n"
  ^bool [^rune c]
  (when (or (and (>= c 0x09) (<= c 0x0D)) (and (>= c 0x1C) (<= c 0x1F)))
    (return true))
  (when (or (== c 0xA0) (== c 0x2007) (== c 0x202F))
    (return false))
  (or (unicode/Is unicode/Zs c) (== c 0x2028) (== c 0x2029)))

(go/func isCased "isCased is ConditionalSpecialCasing.isCased.\n" ^bool [^rune c]
  (or (unicode/Is unicode/Lu c) (unicode/Is unicode/Ll c) (unicode/Is unicode/Lt c)
      (and (>= c 0x02B0) (<= c 0x02B8)) (and (>= c 0x02C0) (<= c 0x02C1))
      (and (>= c 0x02E0) (<= c 0x02E4)) (== c 0x0345) (== c 0x037A)
      (and (>= c 0x1D2C) (<= c 0x1D61)) (and (>= c 0x2160) (<= c 0x217F))
      (and (>= c 0x24B6) (<= c 0x24E9))))

(go/func isWordChar
  "isWordChar: whether c continues a word for the final sigma rule (letters, marks, digits,
connectors, apostrophes), jrt's approximation of java.text.BreakIterator's word boundaries.\n"
  ^bool [^rune c]
  (or (unicode/IsLetter c) (unicode/IsMark c) (unicode/IsDigit c) (unicode/Is unicode/Pc c)
      (== c \') (== c 0x2019) (== c 0x00B7)))

(go/var ^{:tag (map rune (slice uint16))} specialUpper
  (lit (map rune (slice uint16))
    [0x00DF (lit (slice uint16) 0x0053 0x0053)]
    [0x0149 (lit (slice uint16) 0x02BC 0x004E)]
    [0x01F0 (lit (slice uint16) 0x004A 0x030C)]
    [0x0390 (lit (slice uint16) 0x0399 0x0308 0x0301)]
    [0x03B0 (lit (slice uint16) 0x03A5 0x0308 0x0301)]
    [0x0587 (lit (slice uint16) 0x0535 0x0552)]
    [0x1E96 (lit (slice uint16) 0x0048 0x0331)]
    [0x1E97 (lit (slice uint16) 0x0054 0x0308)]
    [0x1E98 (lit (slice uint16) 0x0057 0x030A)]
    [0x1E99 (lit (slice uint16) 0x0059 0x030A)]
    [0x1E9A (lit (slice uint16) 0x0041 0x02BE)]
    [0x1F50 (lit (slice uint16) 0x03A5 0x0313)]
    [0x1F52 (lit (slice uint16) 0x03A5 0x0313 0x0300)]
    [0x1F54 (lit (slice uint16) 0x03A5 0x0313 0x0301)]
    [0x1F56 (lit (slice uint16) 0x03A5 0x0313 0x0342)]
    [0x1F80 (lit (slice uint16) 0x1F08 0x0399)]
    [0x1F81 (lit (slice uint16) 0x1F09 0x0399)]
    [0x1F82 (lit (slice uint16) 0x1F0A 0x0399)]
    [0x1F83 (lit (slice uint16) 0x1F0B 0x0399)]
    [0x1F84 (lit (slice uint16) 0x1F0C 0x0399)]
    [0x1F85 (lit (slice uint16) 0x1F0D 0x0399)]
    [0x1F86 (lit (slice uint16) 0x1F0E 0x0399)]
    [0x1F87 (lit (slice uint16) 0x1F0F 0x0399)]
    [0x1F88 (lit (slice uint16) 0x1F08 0x0399)]
    [0x1F89 (lit (slice uint16) 0x1F09 0x0399)]
    [0x1F8A (lit (slice uint16) 0x1F0A 0x0399)]
    [0x1F8B (lit (slice uint16) 0x1F0B 0x0399)]
    [0x1F8C (lit (slice uint16) 0x1F0C 0x0399)]
    [0x1F8D (lit (slice uint16) 0x1F0D 0x0399)]
    [0x1F8E (lit (slice uint16) 0x1F0E 0x0399)]
    [0x1F8F (lit (slice uint16) 0x1F0F 0x0399)]
    [0x1F90 (lit (slice uint16) 0x1F28 0x0399)]
    [0x1F91 (lit (slice uint16) 0x1F29 0x0399)]
    [0x1F92 (lit (slice uint16) 0x1F2A 0x0399)]
    [0x1F93 (lit (slice uint16) 0x1F2B 0x0399)]
    [0x1F94 (lit (slice uint16) 0x1F2C 0x0399)]
    [0x1F95 (lit (slice uint16) 0x1F2D 0x0399)]
    [0x1F96 (lit (slice uint16) 0x1F2E 0x0399)]
    [0x1F97 (lit (slice uint16) 0x1F2F 0x0399)]
    [0x1F98 (lit (slice uint16) 0x1F28 0x0399)]
    [0x1F99 (lit (slice uint16) 0x1F29 0x0399)]
    [0x1F9A (lit (slice uint16) 0x1F2A 0x0399)]
    [0x1F9B (lit (slice uint16) 0x1F2B 0x0399)]
    [0x1F9C (lit (slice uint16) 0x1F2C 0x0399)]
    [0x1F9D (lit (slice uint16) 0x1F2D 0x0399)]
    [0x1F9E (lit (slice uint16) 0x1F2E 0x0399)]
    [0x1F9F (lit (slice uint16) 0x1F2F 0x0399)]
    [0x1FA0 (lit (slice uint16) 0x1F68 0x0399)]
    [0x1FA1 (lit (slice uint16) 0x1F69 0x0399)]
    [0x1FA2 (lit (slice uint16) 0x1F6A 0x0399)]
    [0x1FA3 (lit (slice uint16) 0x1F6B 0x0399)]
    [0x1FA4 (lit (slice uint16) 0x1F6C 0x0399)]
    [0x1FA5 (lit (slice uint16) 0x1F6D 0x0399)]
    [0x1FA6 (lit (slice uint16) 0x1F6E 0x0399)]
    [0x1FA7 (lit (slice uint16) 0x1F6F 0x0399)]
    [0x1FA8 (lit (slice uint16) 0x1F68 0x0399)]
    [0x1FA9 (lit (slice uint16) 0x1F69 0x0399)]
    [0x1FAA (lit (slice uint16) 0x1F6A 0x0399)]
    [0x1FAB (lit (slice uint16) 0x1F6B 0x0399)]
    [0x1FAC (lit (slice uint16) 0x1F6C 0x0399)]
    [0x1FAD (lit (slice uint16) 0x1F6D 0x0399)]
    [0x1FAE (lit (slice uint16) 0x1F6E 0x0399)]
    [0x1FAF (lit (slice uint16) 0x1F6F 0x0399)]
    [0x1FB2 (lit (slice uint16) 0x1FBA 0x0399)]
    [0x1FB3 (lit (slice uint16) 0x0391 0x0399)]
    [0x1FB4 (lit (slice uint16) 0x0386 0x0399)]
    [0x1FB6 (lit (slice uint16) 0x0391 0x0342)]
    [0x1FB7 (lit (slice uint16) 0x0391 0x0342 0x0399)]
    [0x1FBC (lit (slice uint16) 0x0391 0x0399)]
    [0x1FC2 (lit (slice uint16) 0x1FCA 0x0399)]
    [0x1FC3 (lit (slice uint16) 0x0397 0x0399)]
    [0x1FC4 (lit (slice uint16) 0x0389 0x0399)]
    [0x1FC6 (lit (slice uint16) 0x0397 0x0342)]
    [0x1FC7 (lit (slice uint16) 0x0397 0x0342 0x0399)]
    [0x1FCC (lit (slice uint16) 0x0397 0x0399)]
    [0x1FD2 (lit (slice uint16) 0x0399 0x0308 0x0300)]
    [0x1FD3 (lit (slice uint16) 0x0399 0x0308 0x0301)]
    [0x1FD6 (lit (slice uint16) 0x0399 0x0342)]
    [0x1FD7 (lit (slice uint16) 0x0399 0x0308 0x0342)]
    [0x1FE2 (lit (slice uint16) 0x03A5 0x0308 0x0300)]
    [0x1FE3 (lit (slice uint16) 0x03A5 0x0308 0x0301)]
    [0x1FE4 (lit (slice uint16) 0x03A1 0x0313)]
    [0x1FE6 (lit (slice uint16) 0x03A5 0x0342)]
    [0x1FE7 (lit (slice uint16) 0x03A5 0x0308 0x0342)]
    [0x1FF2 (lit (slice uint16) 0x1FFA 0x0399)]
    [0x1FF3 (lit (slice uint16) 0x03A9 0x0399)]
    [0x1FF4 (lit (slice uint16) 0x038F 0x0399)]
    [0x1FF6 (lit (slice uint16) 0x03A9 0x0342)]
    [0x1FF7 (lit (slice uint16) 0x03A9 0x0342 0x0399)]
    [0x1FFC (lit (slice uint16) 0x03A9 0x0399)]
    [0xFB00 (lit (slice uint16) 0x0046 0x0046)]
    [0xFB01 (lit (slice uint16) 0x0046 0x0049)]
    [0xFB02 (lit (slice uint16) 0x0046 0x004C)]
    [0xFB03 (lit (slice uint16) 0x0046 0x0046 0x0049)]
    [0xFB04 (lit (slice uint16) 0x0046 0x0046 0x004C)]
    [0xFB05 (lit (slice uint16) 0x0053 0x0054)]
    [0xFB06 (lit (slice uint16) 0x0053 0x0054)]
    [0xFB13 (lit (slice uint16) 0x0544 0x0546)]
    [0xFB14 (lit (slice uint16) 0x0544 0x0535)]
    [0xFB15 (lit (slice uint16) 0x0544 0x053B)]
    [0xFB16 (lit (slice uint16) 0x054E 0x0546)]
    [0xFB17 (lit (slice uint16) 0x0544 0x053D)]))
