;; Expected forms of test/g2c/convert/units/s5_types.go (bin/g2c-convert-tests --regen; reviewed)
(go/file "s5_types.go" :doc "Types (SPEC §5): type forms, signatures, structs, interfaces, generics.\n" :imports [[io "io"]])
(go/type Point (struct ^int32 X ^int32 Y))
(go/type Named (struct Point ^{:go/tag "json:\"r\""} (* io/SectionReader) ^{:tag string :go/tag "json:\"name\""} Name ^{:tag (func [int & (slice any)] [int error]) :doc "F's doc.\n"} F ^int _))
(go/type [^:alias A int] [B (slice (map string (* Point)))] [C (array 4 (chan :send int))] [D (chan :recv (slice byte))] [E (array (* 2 3) (struct))] [F (interface io/Reader (^{:doc "Area's doc.\n"} Area ^float64 []) (Read2 [^{:tag (slice byte)} p] :results [^int n ^error err]) (Close []))] [G (func [^int x] [^int n ^error err])] [H (chan (chan :recv int))] [I (interface)])
(go/type Number (interface (| (tilde int) (tilde float64) string)))
(go/type Both (interface (tilde int) comparable))
(go/type Pair :type-params [^comparable K V] (struct ^K Key ^V Val))
(go/type List :type-params [T] (slice T))
(go/type ^:alias Set :type-params [^comparable K] (map K bool))
(go/type Tree :type-params [^{:tag (interface (Less ^bool [T]))} T] (struct ^{:tag (* (Tree T))} Left ^:go/grouped ^{:tag (* (Tree T))} Right ^T Val))
(go/method Len ^int [^{:tag (List T)} l] (len l))
(go/method Cap ^int [^{:tag (List _)} l] (cap l))
(go/func Map :type-params [^{:tag (tilde (slice E))} S E ^{:go/grouped false} F] ^{:tag (slice F)} [^S s ^{:tag (func [E] [F])} f] (let [^{:tag (slice F)} out (zero (slice F))] (range [_ x s] (set! out (append out (f x)))) out))
(go/func Two :type-params [A ^:go/grouped B] [^A a ^B b])
(go/func Grouped :type-params [T] [^{:tag (slice T)} a ^:go/grouped ^{:tag (slice T)} b ^T c])
(go/func Variadic [^string format & ^{:tag (slice any)} args])
(go/func Unnamed [int string] :results [bool error] (return false nil))
(go/func Use [] (set! _ (^{:inst [(List int) int string]} Map (lit (List int) 1) (fn ^string [^int i] ""))) (set! _ (lit (Pair string int) "a" 1)) (let [f (inst Map (slice int) int bool)] (set! _ f) ((inst ^{:inst [int string]} Two int) 1 "x") (let [^{:tag (Set int)} s (zero (Set int))] (set! _ s))))
