;; Expected forms of test/g2c/convert/units/s6_decls.go (bin/g2c-convert-tests --regen; reviewed)
(go/file "s6_decls.go" :doc "Declarations (SPEC §6): constants with their values, variables, types, functions,\nmethods, doc comments and directives (§9).\n" :imports [[_ "unsafe"]])
(go/type Weekday "Weekday is a day.\n" int)
(go/const [^{:tag Weekday :val 0} Sunday iota] [^{:val 1} Monday] [^{:val 2} Tuesday])
(go/const "Numbers fundamental to the encoding.\n" [^{:val \ufffd} RuneError \ufffd] [^{:val (rune 1114111)} MaxRune (rune 1114111)] [^{:val 1267650600228229401496703205376N} Big (<< 1 100)] [^{:val 4} Small (>> Big 98)] [^{:val 2.5} F 2.5] [^{:val 1E+400M} F2 1E+400M] [^{:val 1/3} Third (/ 1.0 3)] [^{:val (complex 1.0 2.0)} C (+ 1 (imaginary 2))] [^{:val "s"} S "s"] [^{:val (byte-string 255)} Bad (byte-string 255)] [^{:val true} T true] [^{:tag float32 :val 0.1000000014901161} Typed 0.1] [^{:tag complex64 :val (complex 0.0 1.0)} TC (imaginary 1)] [^{:val -1} Neg -1] [^{:val 1.0} Int (+ 1.0 0)])
(go/const ^{:val 4} Single 4)
(go/const (values ^{:val 1} X ^{:val 2} Y) (values 1 2))
(go/var ^{:doc "ErrX is a variable.\n"} ErrX 1)
(go/var [(values ^int a ^int b)] [(values c d) (values 1 2)] [^{:tag float64 :doc "e's doc.\n"} e 3])
(go/var ^any _ (conv (* T1) nil))
(go/var (values p q) (pair))
(go/func pair [] :results [int int] (return 1 2))
(go/var first (lit (array 4 uint8) 1 2 3 4))
(go/func ^:go/noinline ^:go/nosplit f [])
(go/func ^:extern ^{:go/linkname "nanotime runtime.nanotime"} nanotime "nanotime is implemented elsewhere.\n" ^int64 [])
(go/directive "//go:linkname other runtime.other")
(go/func init [])
(go/func init [])
(go/type T1 "T1 is a type.\n" (struct))
(go/method M [T1])
(go/method N "N doubles.\n" [^{:tag (* T1)} t ^int x] :results [^int r] (set! r (* x 2)) (return))
(go/type [^{:doc "G1's doc.\n"} G1 int] [^:alias G2 string])
