;; Go-build variant of sun.util.cldr.CLDRBaseLocaleDataMetaInfo (C2G-SPEC §4.6;
;; doc/go/JRT-NOTES.md, "Time"): read by c2g only. The class is generated by the JDK build's
;; CLDRConverter (bin/jrt-convert makes it the same way); jrt's locale providers read its
;; canonical zone IDs (tzCanonicalIDs, its nested holder's). Its static initializer fills the
;; parent locales and the language aliases, keyed by Locale.forLanguageTag, which jrt's Locale
;; does not have: cut (jrt's locale data are the root and English locales alone, whose chain
;; needs no parent locales, and jrt's Locale does not canonicalize languages), so that the two
;; maps are empty. Copyright (c) the Arbace authors; Eclipse Public License 1.0.
(in-ns 'sun.util.cldr)

(c2g/variant CLDRBaseLocaleDataMetaInfo
  (c2g/cut (static-initializer 0)))
