;; Harvested by bin/oracle harvest (test/oracle/harvest.clj) from Clojure's test suite,
;; clojure/clojure 98d735fab02f337cee654cb0629bddc09883a75a test/clojure/test_clojure/array_symbols.clj,
;; renamed to arbace.* by bin/clojure-tests: the expressions of its assertions that are
;; self-contained and deterministic. Eclipse Public License 1.0 (LICENSE.md). Do not edit.
(read-string "java.lang.String/1")
(read-string "String/1")
(read-string "int/2")
(Class/forName "[Z")
(resolve (quote boolean/1))
(Class/forName "[B")
(resolve (quote byte/1))
(Class/forName "[C")
(resolve (quote char/1))
(Class/forName "[S")
(resolve (quote short/1))
(Class/forName "[F")
(resolve (quote float/1))
(Class/forName "[D")
(resolve (quote double/1))
(Class/forName "[I")
(resolve (quote int/1))
(Class/forName "[J")
(resolve (quote long/1))
(Class/forName "[[J")
(resolve (quote long/2))
(Class/forName "[Ljava.lang.Object;")
(resolve (quote Object/1))
(Class/forName "[Ljava.lang.String;")
(resolve (quote String/1))
(Class/forName "[[Ljava.lang.String;")
(resolve (quote String/2))
(eval (quote long/1))
(class (make-array Long/TYPE 0))
(class (make-array String 0))
(resolve (quote java.lang.String/1))
(resolve (quote java.util.UUID/1))
(class (make-array java.util.UUID 0))
(class (into-array (class (make-array String 0)) [(into-array String ["a" "b"])]))
(print-str long/1)
(print-str (class (make-array Byte/TYPE 0)))
(print-str String/2)
(print-str [[String/2]])
(print-str java.util.UUID/4)
(print-str (Class/forName "[[[[[[[[[[Ljava.lang.Object;"))
(print-str (Class/forName "[[[[[[[[[Ljava.lang.Object;"))
(read-string "String/1:")
(read-string "String/0")
(read-string "String/42")
(eval (quote (deftype Foo/2 [a])))
