;; Harvested by bin/oracle harvest (test/oracle/harvest.clj) from Clojure's test suite,
;; clojure/clojure 98d735fab02f337cee654cb0629bddc09883a75a test/clojure/test_clojure/clojure_set.clj,
;; renamed to arbace.* by bin/clojure-tests: the expressions of its assertions that are
;; self-contained and deterministic. Eclipse Public License 1.0 (LICENSE.md). Do not edit.
(require (quote [arbace.set :as set]))
(set/union)
(set/union #{})
(set/union #{1})
(set/union #{1 3 2})
(set/union #{} #{})
(set/union #{} #{1})
(set/union #{} #{1 3 2})
(set/union #{1} #{})
(set/union #{1 3 2} #{})
(set/union #{1} #{2})
(set/union #{1} #{1 2})
(set/union #{2} #{1 2})
(set/union #{1 2} #{3})
(set/union #{1 2} #{3 2})
(set/union #{} #{} #{})
(set/union #{1} #{} #{})
(set/union #{} #{1} #{})
(set/union #{} #{} #{1})
(set/union #{1 2} #{3 2} #{})
(set/union #{1 2} #{4 3} #{6 5})
(set/union #{1 2} #{3 2} #{1 4 3})
(set/union #{1 2} #{:b :a} #{nil} #{true false} #{\c "abc"} #{[] [1 2]} #{{:a 1} {}} #{#{} #{1 2}})
(set/union (hash-set) (hash-set 1 2) (hash-set 2 3))
(hash-set 1 2 3)
(set/union (sorted-set) (sorted-set 1 2) (sorted-set 2 3))
(sorted-set 1 2 3)
(set/union (hash-set) (hash-set 1 2) (hash-set 2 3) (sorted-set) (sorted-set 4 5) (sorted-set 5 6))
(hash-set 1 2 3 4 5 6)
(set/intersection)
(set/intersection #{})
(set/intersection #{1})
(set/intersection #{1 3 2})
(set/intersection #{} #{})
(set/intersection #{} #{1})
(set/intersection #{} #{1 3 2})
(set/intersection #{1} #{})
(set/intersection #{1 3 2} #{})
(set/intersection #{1 2} #{1 2})
(set/intersection #{1 2} #{4 3})
(set/intersection #{1 2} #{1})
(set/intersection #{1 2} #{2})
(set/intersection #{1 4 2} #{4 3 2 5})
(set/intersection #{} #{} #{})
(set/intersection #{1} #{} #{})
(set/intersection #{1} #{1} #{})
(set/intersection #{1} #{} #{1})
(set/intersection #{1 2} #{3 2} #{})
(set/intersection #{1 2} #{3 2} #{2 5})
(set/intersection #{1 3 2} #{1 4 3} #{1 3})
(set/intersection #{1 3 2} #{4 3 5} #{3 2 8})
(set/intersection (hash-set 1 2) (hash-set 2 3))
(set/intersection (sorted-set 1 2) (sorted-set 2 3))
(set/intersection (hash-set 1 2) (hash-set 2 3) (sorted-set 1 2) (sorted-set 2 3))
(set/difference #{})
(set/difference #{1})
(set/difference #{1 3 2})
(set/difference #{1 2} #{1 2})
(set/difference #{1 2} #{4 3})
(set/difference #{1 2} #{1})
(set/difference #{1 2} #{2})
(set/difference #{1 4 2} #{4 3 2 5})
(set/difference #{1 2} #{3 2} #{2 5})
(set/difference #{1 3 2} #{1 4 3} #{1 3})
(set/difference #{1 3 2} #{4 3 5} #{3 2 8})
(set/select integer? #{})
(set/select integer? #{1 2})
(set/select integer? #{1 :c 2 :b :a})
(set/select integer? #{:c :b :a})
(set/project #{{}} [:name])
(set/rename #{{}} {:year :decade})
(set/rename-keys {:a "one", :b "two"} {:a :z})
(set/rename-keys {:a "one", :b "two"} {:a :z, :c :y})
(set/rename-keys {:a "one", :b "two", :c "three"} {:a :b, :b :a})
(set/index #{{:b 1} {:a 1, :b 2} {:c 2}} [:b])
(set/map-invert {:a "one", :b "two"})
(set/subset? #{} #{})
(set/subset? #{} #{1})
(set/subset? #{1} #{1})
(set/subset? #{1 2} #{1 2})
(set/subset? #{1 2} #{1 2 42})
(set/subset? #{false} #{false})
(set/subset? #{nil} #{nil})
(set/subset? #{nil} #{nil false})
(set/subset? #{nil 1 2} #{nil 1 4 2})
(not (set/subset? #{1} #{}))
(not (set/subset? #{2} #{1}))
(not (set/subset? #{1 3} #{1}))
(not (set/subset? #{nil} #{false}))
(not (set/subset? #{false} #{nil}))
(not (set/subset? #{nil false} #{nil}))
(not (set/subset? #{nil 1 2} #{1 2}))
(set/superset? #{} #{})
(set/superset? #{1} #{})
(set/superset? #{1} #{1})
(set/superset? #{1 2} #{1 2})
(set/superset? #{1 2 42} #{1 2})
(set/superset? #{false} #{false})
(set/superset? #{nil} #{nil})
(set/superset? #{nil false} #{false})
(set/superset? #{nil 1 4 2 false} #{nil 1 2})
(not (set/superset? #{} #{1}))
(not (set/superset? #{2} #{1}))
(not (set/superset? #{1} #{1 3}))
(not (set/superset? #{nil} #{false}))
(not (set/superset? #{false} #{nil}))
(not (set/superset? #{nil} #{nil false}))
(not (set/superset? #{nil 3 2} #{nil 3 2 false}))
