;; Harvested by bin/oracle harvest (test/oracle/harvest.clj) from Clojure's test suite,
;; clojure/clojure 98d735fab02f337cee654cb0629bddc09883a75a test/clojure/test_clojure/data_structures.clj,
;; renamed to arbace.* by bin/clojure-tests: the expressions of its assertions that are
;; self-contained and deterministic. Eclipse Public License 1.0 (LICENSE.md). Do not edit.
(require (quote [arbace.string :as string]))
(import (quote (java.util Collection)))
(not (= nil true))
(not (= nil false))
(not (= nil 0))
(not (= nil 0.0))
(not (= nil \space))
(not (= nil ""))
(not (= nil #""))
(not (= nil ()))
(not (= nil []))
(not (= nil #{}))
(not (= nil {}))
(not (= nil (lazy-seq nil)))
(not (= nil (lazy-seq ())))
(not (= nil (lazy-seq [])))
(not (= nil (lazy-seq {})))
(not (= nil (lazy-seq #{})))
(not (= nil (lazy-seq "")))
(not (= nil (lazy-seq (into-array []))))
(not (= nil (new Object)))
()
(sorted-set :a)
(sorted-set 1)
(class (sorted-set 1))
(class (hash-set 1))
(sorted-set-by <)
(hash-set)
(sorted-set-by < 1)
(hash-set 1)
(sorted-set-by < 3 2 1)
(hash-set 3 2 1)
(sorted-set)
(sorted-set 3 2 1)
(count nil)
(count ())
(count (quote (1)))
(count (quote (1 2 3)))
(count [])
(count [1])
(count [1 2 3])
(count #{})
(count #{1})
(count #{1 3 2})
(count {})
(count {:a 1})
(count {:a 1, :b 2, :c 3})
(count "")
(count "a")
(count "abc")
(count (into-array []))
(count (into-array [1]))
(count (into-array [1 2 3]))
(count (java.util.ArrayList. []))
(count (java.util.ArrayList. [1]))
(count (java.util.ArrayList. [1 2 3]))
(count (java.util.HashMap. {}))
(count (java.util.HashMap. {:a 1}))
(count (java.util.HashMap. {:a 1, :b 2, :c 3}))
(count [nil])
(count [true])
(count [false])
(count [0])
(count [0.0])
(count [""])
(count [\space])
(count [()])
(count [[]])
(count [#{}])
(count [{}])
(conj "" \a)
(conj (into-array []) 1)
(conj nil 1)
(conj nil 3 2 1)
(conj nil nil)
(conj nil nil nil)
(conj nil nil nil 1)
(conj () 1)
(conj () 1 2)
(conj (quote (2 3)) 1)
(conj (quote (2 3)) 1 4 3)
(conj () nil)
(conj () ())
(conj [] 1)
(conj [] 1 2)
(conj [2 3] 1)
(conj [2 3] 1 4 3)
(conj [] nil)
(conj [] [])
(conj {} {})
(conj {} {:a 1})
(conj {} {:a 1, :b 2})
(conj {} {:a 1, :b 2} {:c 3})
(conj {} {:a 1, :b 2} {:a 3, :c 4})
(conj {:a 1} {:a 7})
(conj {:a 1} {:b 2})
(conj {:a 1} {:a 7, :b 2})
(conj {:a 1} {:a 7, :b 2} {:c 3})
(conj {:a 1} {:a 7, :b 2} {:b 4, :c 5})
(conj {} (first {:a 1}))
(conj {:a 1} (first {:b 2}))
(conj {:a 1} (first {:a 7}))
(conj {:a 1} (first {:b 2}) (first {:a 5}))
(conj {} [:a 1])
(conj {:a 1} [:b 2])
(conj {:a 1} [:a 7])
(conj {:a 1} [:b 2] [:a 5])
(conj {} {nil {}})
(conj {} {{} nil})
(conj {} {{} {}})
(conj #{} 1)
(conj #{} 1 2 3)
(conj #{3 2} 1)
(conj #{3 2} 2)
(conj #{3 2} 2 3)
(conj #{3 2} 4 1 2 3)
(conj #{} nil)
(conj #{} #{})
(peek #{1})
(peek {:a 1})
(peek nil)
(peek ())
(peek (quote (1)))
(peek (quote (1 2 3)))
(peek (quote (nil)))
(peek (quote (1 nil)))
(peek (quote (nil 2)))
(peek (quote (())))
(peek (quote (() nil)))
(peek (quote (() 2 nil)))
(peek [])
(peek [1])
(peek [1 2 3])
(peek [nil])
(peek [1 nil])
(peek [nil 2])
(peek [[]])
(peek [[] nil])
(peek [[] 2 nil])
(pop #{1})
(pop #{1 :a})
(pop ())
(pop [])
(pop nil)
(pop (quote (1)))
(pop (quote (1 2 3)))
(pop (quote (nil)))
(pop (quote (1 nil)))
(pop (quote (nil 2)))
(pop (quote (())))
(pop (quote (() nil)))
(pop (quote (() 2 nil)))
(pop [1])
(pop [1 2 3])
(pop [nil])
(pop [1 nil])
(pop [nil 2])
(pop [[]])
(pop [[] nil])
(pop [[] 2 nil])
(list? ())
(list? (quote ()))
(list? (list))
(list? (list 1 2 3))
(not (= (list 1 2) (list 2 1)))
(not (= (list 3 1 2) (list 1 2 3)))
(list)
(list 1)
(list 1 2)
(list 1 (list 2 3) (list 3 (list 4 5 (list 6 (list 7)))))
(list true false nil)
(list 1 2.5 2/3 "ab" \x (quote cd) :kw)
(list (list 1 2) [3 4] {:a 1, :b 2} #{:c :d})
(list (+ 1 2) [(+ 2 3) (quote a)] (list (* 2 3) 8))
(list nil)
(list 1 nil)
(list nil 2)
(list ())
(list 1 ())
(list () 2)
(find {} :a)
(find {:a 1} :a)
(find {:a 1} :b)
(find {nil 1} nil)
(find {:a 1, :b 2} :a)
(find {:a 1, :b 2} :b)
(find {:a 1, :b 2} :c)
(find {} nil)
(find {:a 1} nil)
(find {:a 1, :b 2} nil)
(contains? {} :a)
(contains? {} nil)
(contains? {:a 1} :a)
(contains? {:a 1} :b)
(contains? {:a 1} nil)
(contains? {nil 1} nil)
(contains? {:a 1, :b 2} :a)
(contains? {:a 1, :b 2} :b)
(contains? {:a 1, :b 2} :c)
(contains? {:a 1, :b 2} nil)
(contains? #{} 1)
(contains? #{} nil)
(contains? #{1} 1)
(contains? #{1} 2)
(contains? #{1} nil)
(contains? #{1 3 2} 1)
(contains? #{1 3 2} 3)
(contains? #{1 3 2} 10)
(contains? #{1 3 2} nil)
(contains? (java.util.HashMap. {}) :a)
(contains? (java.util.HashMap. {}) nil)
(contains? (java.util.HashMap. {:a 1}) :a)
(contains? (java.util.HashMap. {:a 1}) :b)
(contains? (java.util.HashMap. {:a 1}) nil)
(contains? (java.util.HashMap. {:a 1, :b 2}) :a)
(contains? (java.util.HashMap. {:a 1, :b 2}) :b)
(contains? (java.util.HashMap. {:a 1, :b 2}) :c)
(contains? (java.util.HashMap. {:a 1, :b 2}) nil)
(contains? (java.util.HashSet. #{}) 1)
(contains? (java.util.HashSet. #{}) nil)
(contains? (java.util.HashSet. #{1}) 1)
(contains? (java.util.HashSet. #{1}) 2)
(contains? (java.util.HashSet. #{1}) nil)
(contains? (java.util.HashSet. #{1 3 2}) 1)
(contains? (java.util.HashSet. #{1 3 2}) 3)
(contains? (java.util.HashSet. #{1 3 2}) 10)
(contains? (java.util.HashSet. #{1 3 2}) nil)
(contains? [] 0)
(contains? [] -1)
(contains? [] 1)
(contains? [1] 0)
(contains? [1] -1)
(contains? [1] 1)
(contains? [1 2 3] 0)
(contains? [1 2 3] 2)
(contains? [1 2 3] 3)
(contains? [1 2 3] -1)
(contains? (into-array []) 0)
(contains? (into-array []) -1)
(contains? (into-array []) 1)
(contains? (into-array [1]) 0)
(contains? (into-array [1]) -1)
(contains? (into-array [1]) 1)
(contains? (into-array [1 2 3]) 0)
(contains? (into-array [1 2 3]) 2)
(contains? (into-array [1 2 3]) 3)
(contains? (into-array [1 2 3]) -1)
(keys ())
(keys [])
(keys #{})
(keys "")
(keys {})
(keys {:a 1})
(keys {nil 1})
(keys (sorted-map))
(keys (sorted-map :a 1))
(keys (hash-map))
(keys (hash-map :a 1))
(vals ())
(vals [])
(vals #{})
(vals "")
(vals {})
(vals {:a 1})
(vals {nil 1})
(vals (sorted-map))
(vals (sorted-map :a 1))
(vals (hash-map))
(vals (hash-map :a 1))
(sorted-map () 1)
(sorted-map #{} 1)
(sorted-map {} 1)
(assoc (sorted-map) () 1)
(assoc (sorted-map) #{} 1)
(assoc (sorted-map) {} 1)
(key (first (hash-map nil :value)))
(key (first (hash-map false :value)))
(key (first (hash-map true :value)))
(key (first (hash-map 0 :value)))
(key (first (hash-map 42 :value)))
(key (first (hash-map 0.0 :value)))
(key (first (hash-map 3.14 :value)))
(key (first (hash-map 2/3 :value)))
(key (first (hash-map 0M :value)))
(key (first (hash-map 1M :value)))
(key (first (hash-map \c :value)))
(key (first (hash-map "" :value)))
(key (first (hash-map "abc" :value)))
(key (first (hash-map (quote sym) :value)))
(key (first (hash-map :kw :value)))
(key (first (hash-map () :value)))
(key (first (hash-map (quote (1 2)) :value)))
(key (first (hash-map [] :value)))
(key (first (hash-map [1 2] :value)))
(key (first (hash-map {} :value)))
(key (first (hash-map {:a 1, :b 2} :value)))
(key (first (hash-map #{} :value)))
(key (first (hash-map #{1 2} :value)))
(val (first (hash-map :key nil)))
(val (first (hash-map :key false)))
(val (first (hash-map :key true)))
(val (first (hash-map :key 0)))
(val (first (hash-map :key 42)))
(val (first (hash-map :key 0.0)))
(val (first (hash-map :key 3.14)))
(val (first (hash-map :key 2/3)))
(val (first (hash-map :key 0M)))
(val (first (hash-map :key 1M)))
(val (first (hash-map :key \c)))
(val (first (hash-map :key "")))
(val (first (hash-map :key "abc")))
(val (first (hash-map :key (quote sym))))
(val (first (hash-map :key :kw)))
(val (first (hash-map :key ())))
(val (first (hash-map :key (quote (1 2)))))
(val (first (hash-map :key [])))
(val (first (hash-map :key [1 2])))
(val (first (hash-map :key {})))
(val (first (hash-map :key {:a 1, :b 2})))
(val (first (hash-map :key #{})))
(val (first (hash-map :key #{1 2})))
(get-in {:a 1} 5)
(select-keys {:a 1, :b 2, :c nil} [:a :c :d])
(select-keys nil [:a])
(select-keys #{:b :a} [:a :c])
(false? (map-entry? nil))
(false? (map-entry? 5))
(false? (map-entry? #{1 2}))
(false? (map-entry? (quote (1 2))))
(false? (map-entry? {:a 1}))
(false? (map-entry? []))
(false? (map-entry? [0]))
(false? (map-entry? [1 2 3]))
(true? (map-entry? (first (doto (java.util.HashMap.) (.put "x" 1)))))
(set? #{})
(set? #{1 2})
(set? (hash-set))
(set? (hash-set 1 2))
(hash-set 1 2)
(hash-set 2 1)
(hash-set 3 1 2)
(hash-set 1 2 3)
(class #{})
(class (hash-set))
(class #{1 2})
(class (hash-set 1 2))
(hash-set 1 (hash-set 2 3) (hash-set 3 (hash-set 4 5 (hash-set 6 (hash-set 7)))))
(hash-set true false nil)
(hash-set 1 2.5 2/3 "ab" \x (quote cd) :kw)
(hash-set (list 1 2) [3 4] {:a 1, :b 2} #{:c :d})
(hash-set (+ 1 2) [(+ 2 3) :a] (hash-set (* 2 3) 8))
(hash-set nil)
(hash-set 1 nil)
(hash-set nil 2)
(hash-set #{})
(hash-set 1 #{})
(hash-set #{} 2)
(hash-set (Integer. -1))
(hash-set (Long. -1))
(sorted-set 1 "a")
(sorted-set (quote (1 2)) [3 4])
(set? (sorted-set))
(set? (sorted-set 1 2))
(and (= (sorted-set nil) #{nil}) (= (sorted-set nil nil) (sorted-set nil)))
(and (= (sorted-set false) #{false}) (= (sorted-set false false) (sorted-set false)))
(and (= (sorted-set true) #{true}) (= (sorted-set true true) (sorted-set true)))
(and (= (sorted-set 0) #{0}) (= (sorted-set 0 0) (sorted-set 0)))
(and (= (sorted-set 42) #{42}) (= (sorted-set 42 42) (sorted-set 42)))
(and (= (sorted-set 0.0) #{0.0}) (= (sorted-set 0.0 0.0) (sorted-set 0.0)))
(and (= (sorted-set 3.14) #{3.14}) (= (sorted-set 3.14 3.14) (sorted-set 3.14)))
(and (= (sorted-set 2/3) #{2/3}) (= (sorted-set 2/3 2/3) (sorted-set 2/3)))
(and (= (sorted-set 0M) #{0M}) (= (sorted-set 0M 0M) (sorted-set 0M)))
(and (= (sorted-set 1M) #{1M}) (= (sorted-set 1M 1M) (sorted-set 1M)))
(and (= (sorted-set \c) #{\c}) (= (sorted-set \c \c) (sorted-set \c)))
(and (= (sorted-set "") #{""}) (= (sorted-set "" "") (sorted-set "")))
(and (= (sorted-set "abc") #{"abc"}) (= (sorted-set "abc" "abc") (sorted-set "abc")))
(and (= (sorted-set (quote sym)) #{(quote sym)}) (= (sorted-set (quote sym) (quote sym)) (sorted-set (quote sym))))
(and (= (sorted-set :kw) #{:kw}) (= (sorted-set :kw :kw) (sorted-set :kw)))
(and (= (sorted-set []) #{[]}) (= (sorted-set [] []) (sorted-set [])))
(and (= (sorted-set [1 2]) #{[1 2]}) (= (sorted-set [1 2] [1 2]) (sorted-set [1 2])))
(sorted-set ())
(sorted-set {})
(sorted-set #{})
(sorted-set (quote (1 2)) (quote (1 2)))
(sorted-set {:a 1, :b 2} {:a 1, :b 2})
(sorted-set #{1 2} #{1 2})
(sorted-set 1 2)
(seq (sorted-set 5 4 3 2 1))
(sorted-set nil)
(sorted-set 1 nil)
(sorted-set nil 2)
(sorted-set [])
(sorted-set-by < 1 "a")
(sorted-set-by < (quote (1 2)) [3 4])
(set? (sorted-set-by <))
(set? (sorted-set-by < 1 2))
(and (= (sorted-set-by compare nil) #{nil}) (= (sorted-set-by compare nil nil) (sorted-set-by compare nil)))
(and (= (sorted-set-by compare false) #{false}) (= (sorted-set-by compare false false) (sorted-set-by compare false)))
(and (= (sorted-set-by compare true) #{true}) (= (sorted-set-by compare true true) (sorted-set-by compare true)))
(and (= (sorted-set-by compare 0) #{0}) (= (sorted-set-by compare 0 0) (sorted-set-by compare 0)))
(and (= (sorted-set-by compare 42) #{42}) (= (sorted-set-by compare 42 42) (sorted-set-by compare 42)))
(and (= (sorted-set-by compare 0.0) #{0.0}) (= (sorted-set-by compare 0.0 0.0) (sorted-set-by compare 0.0)))
(and (= (sorted-set-by compare 3.14) #{3.14}) (= (sorted-set-by compare 3.14 3.14) (sorted-set-by compare 3.14)))
(and (= (sorted-set-by compare 2/3) #{2/3}) (= (sorted-set-by compare 2/3 2/3) (sorted-set-by compare 2/3)))
(and (= (sorted-set-by compare 0M) #{0M}) (= (sorted-set-by compare 0M 0M) (sorted-set-by compare 0M)))
(and (= (sorted-set-by compare 1M) #{1M}) (= (sorted-set-by compare 1M 1M) (sorted-set-by compare 1M)))
(and (= (sorted-set-by compare \c) #{\c}) (= (sorted-set-by compare \c \c) (sorted-set-by compare \c)))
(and (= (sorted-set-by compare "") #{""}) (= (sorted-set-by compare "" "") (sorted-set-by compare "")))
(and (= (sorted-set-by compare "abc") #{"abc"}) (= (sorted-set-by compare "abc" "abc") (sorted-set-by compare "abc")))
(and (= (sorted-set-by compare (quote sym)) #{(quote sym)}) (= (sorted-set-by compare (quote sym) (quote sym)) (sorted-set-by compare (quote sym))))
(and (= (sorted-set-by compare :kw) #{:kw}) (= (sorted-set-by compare :kw :kw) (sorted-set-by compare :kw)))
(and (= (sorted-set-by compare ()) #{()}) (= (sorted-set-by compare () ()) (sorted-set-by compare ())))
(and (= (sorted-set-by compare []) #{[]}) (= (sorted-set-by compare [] []) (sorted-set-by compare [])))
(and (= (sorted-set-by compare [1 2]) #{[1 2]}) (= (sorted-set-by compare [1 2] [1 2]) (sorted-set-by compare [1 2])))
(and (= (sorted-set-by compare {}) #{{}}) (= (sorted-set-by compare {} {}) (sorted-set-by compare {})))
(and (= (sorted-set-by compare #{}) #{#{}}) (= (sorted-set-by compare #{} #{}) (sorted-set-by compare #{})))
(sorted-set-by compare (quote (1 2)) (quote (1 2)))
(sorted-set-by compare {:a 1, :b 2} {:a 1, :b 2})
(sorted-set-by compare #{1 2} #{1 2})
(sorted-set-by >)
(sorted-set-by > 1)
(sorted-set-by > 1 2)
(seq (sorted-set-by < 5 4 3 2 1))
(sorted-set-by compare nil)
(sorted-set-by compare 1 nil)
(sorted-set-by compare nil 2)
(sorted-set-by compare #{})
(set? (set ()))
(set? (set (quote (1 2))))
(set? (set []))
(set? (set [1 2]))
(set? (set #{}))
(set? (set #{1 2}))
(set? (set {}))
(set? (set {:a 1, :b 2}))
(set? (set (into-array [])))
(set? (set (into-array [1 2])))
(set? (set ""))
(set? (set "abc"))
(set [nil nil])
(set [false false])
(set [true true])
(set [0 0])
(set [42 42])
(set [0.0 0.0])
(set [3.14 3.14])
(set [2/3 2/3])
(set [0M 0M])
(set [1M 1M])
(set [\c \c])
(set ["" ""])
(set ["abc" "abc"])
(set [(quote sym) (quote sym)])
(set [:kw :kw])
(set [() ()])
(set [(quote (1 2)) (quote (1 2))])
(set [[] []])
(set [[1 2] [1 2]])
(set [{} {}])
(set [{:a 1, :b 2} {:a 1, :b 2}])
(set [#{} #{}])
(set [#{1 2} #{1 2}])
(set ())
(set (quote (1 2)))
(set [])
(set [1 2])
(set #{})
(set #{1 2})
(set {})
(set {:a 1, :b 2})
(set (into-array []))
(set (into-array [1 2]))
(set "")
(set "abc")
(and (= :a (get #{:a} :a)) (= :a (get (transient #{:a}) :a 1)) (= :a (#{:a} :a)) (= :a ((transient #{:a}) :a 1)) (= :a (:a #{:a})) (= :a (:a #{:a} 1)))
(and (= nil (get #{:a} :b)) (= 1 (get (transient #{:a}) :b 1)) (= nil (#{:a} :b)) (= 1 ((transient #{:a}) :b 1)) (= nil (:b #{:a})) (= 1 (:b #{:a} 1)))
(and (= nil (get #{} :a)) (= 1 (get (transient #{}) :a 1)) (= nil (#{} :a)) (= 1 ((transient #{}) :a 1)) (= nil (:a #{})) (= 1 (:a #{} 1)))
(and (= nil (get #{nil} :a)) (= 1 (get (transient #{nil}) :a 1)) (= nil (#{nil} :a)) (= 1 ((transient #{nil}) :a 1)) (= nil (:a #{nil})) (= 1 (:a #{nil} 1)))
(disj (quote (1 2)) 1)
(disj [1 2] 1)
(disj {:a 1} :a)
(disj nil)
(disj #{})
(disj #{1 3 2})
(disj #{nil 0 0.0 0M "" 2/3 \c (quote sym) 3.14 {:a 1, :b 2} [] {} #{} true :kw "abc" false #{1 2} [1 2] 42 1M})
(class (disj (hash-set)))
(class (disj (hash-set 1 2)))
(class (disj (sorted-set)))
(class (sorted-set))
(class (disj (sorted-set 1 2)))
(class (sorted-set 1 2))
(disj nil :a)
(disj nil :a :b)
(disj #{} :a)
(disj #{} :a :b)
(disj #{:a} :a)
(disj #{:a} :a :b)
(disj #{:a} :c)
(disj #{:c :b :d :a} :a)
(disj #{:c :b :d :a} :a :d)
(disj #{:c :b :d :a} :a :b :c)
(disj #{:c :b :d :a} :d :a :c :b)
(disj #{nil} :a)
(disj #{nil} #{})
(disj #{nil} nil)
(disj #{#{}} nil)
(disj #{#{}} #{})
(disj #{#{nil}} #{nil})
(hash [1 2 3])
(range 5)
(range 1 6)
(range 6)
(range 0 6)
(read-string "#{1 2 3 4 1 5}")
(read-string "{:a 1, :b 2, :a -1, :c 3}")
(array-map 1 2 3)
(assoc [] 0 4)
(assoc [] 0 5 1 -7)
(assoc {} :a 1)
(assoc {} nil 1)
(assoc {} :b -2 :a 2)
(assoc [] 0 5 1)
(assoc {} :b -2 :a)
(nil? (merge-deep))
(nil? (merge-deep nil))
(merge-deep {:a 1})
(merge-deep nil nil)
(merge-deep {} nil)
(merge-deep nil {})
(merge-deep {:a 1} nil)
(merge-deep nil {:a 1})
(merge-deep {:a 1} {:a nil})
(merge-deep {:a nil} {:a 1})
(merge-deep {:a 1} {:a 2})
(merge-deep nil {:a {:x 1}})
(merge-deep {:a {:x 1}} nil)
(merge-deep {:a nil} {:a {:x 1}})
(merge-deep {:a {:x 1}} {:a nil})
(merge-deep {:a {:x 1}} {:a {:x 2}})
(merge-deep {:a {:b {:c 1}}} {:a {:b {:c 2}}})
(merge-deep [:a :b] {0 :c, 1 :d})
(merge-deep {0 :c, 1 :d} [:a :b])
(merge-deep nil nil nil)
(merge-deep {} nil nil)
(merge-deep nil {:a 2} {:a 3})
(merge-deep {:a 1} nil {:a 3})
(merge-deep {:a 1} {:a 2} nil)
(merge-deep {:a nil} {:a 2} {:a 3})
(merge-deep {:a 1} {:a 2} {:a nil})
(merge-deep {:a 1} {:a 2} {:a 3})
(merge-deep {:a 1} {:a {:x 1}} {:a nil})
(merge-deep {:a {:x 1}} {:a {:x 2}} {:a {:x 3}})
(merge-deep-with vector nil {:a nil})
(merge-deep-with vector nil {:a 1})
(merge-deep-with vector {:a 1} {:a nil})
(merge-deep-with vector {:a 1} {:a 2})
(nil? (merge))
(nil? (merge nil))
(nil? (merge nil nil))
(nil? (merge nil nil nil))
(merge {})
(merge {} nil)
(merge nil {})
(merge nil {} nil)
(merge {[2 3] :foo} nil {})
(merge {1 11} {} nil)
(merge {:a "a"} {:a "aaaaa"})
(merge {:a "aaaa"} {:a "a", :b "b"})
(merge {:a "aaaa"} {:a "a", :b "bbbb"} {:a "a", :b "b"})
(merge {:a "aaaa"} {:a "a", :b "bbbb", :c "c"} {:a nil, :b "b"})
(merge {:x 1, :y 5555} {:y 10, :z 100})
(merge {:ceo {:salary 1000000}} {:cto {:salary 500000}} {:ceo {:name "Alice"}} {:cto {:name "Brenda"}})
(let [{:keys! [a b]} {:a 1}] a)
(let [{:keys! [a & :b]} {:a 1}] a)
(let [{:keys! [:oracle.harvest.scratch/a & :oracle.harvest.scratch/b]} {:oracle.harvest.scratch/a 1, :oracle.harvest.scratch/b 2}] a)
(let [{:syms! [a b]} {:a 1}] a)
(let [{:syms! [a & (quote b)]} {:a 1}] a)
(let [{:strs! [a b]} {:a 1}] a)
(let [{:strs! [a & "b"]} {:a 1}] a)
(nil? (let [{{a :a} :n, :select s} nil] s))
(let [{{a :a} :n, :select s} {}] s)
(let [{{a :a} :n, :select s} {:n nil}] s)
(let [{{a :a} :n, :select s} {:n {}}] s)
(let [{{a :a, :or {a 42}} :n, :select s} nil] s)
(let [{{a :a, :or {a 42}} :n, :select s} {:n nil}] s)
(let [{:keys [a & (quote b)]} {:a 1}] a)
(let [{:keys! [a & (quote b) "c"]} {:a 1, (quote b) 2, "c" 3}] a)
(let [{:keys [a], :all m} {:a 1, :b 2, :c 3}] m)
(nil? (let [{:keys [a], :all m} nil] m))
(let [{:keys [a], :all m} {}] m)
(nil? (let [{{a :a} :n, :all m} nil] m))
(let [{{a :a} :n, :all m} {}] m)
(let [{{a :a} :n, :all m} {:n nil}] m)
(let [{{a :a} :n, :all m} {:n {}}] m)
(let [{a :a, :or {a 42}, :all m} {}] m)
(let [{a :a, :or {a 42}, :all m} {:a 1, :b 2}] m)
(nil? (let [{:keys [a], :or {}, :all m} nil] m))
(let [{:keys [a], :or {}, :all m} {}] m)
(let [{{a :a, :or {}} :n, :or {}, :all m} {:n {}}] m)
(let [{:keys [a], :or {a 42}, :all m} nil] m)
(let [{:keys [a], :or {a 42}, :all m} {}] m)
(let [{{a :a, :or {a 42}} :n, :all m} {:n nil}] m)
(eval (quote (let [{:keys [a], :or {a 1, z 2}, :all m} {}] m)))
(let [{:keys [a], :or {a 42}, :all m} {:a 1}] m)
(let [{{a :a, :or {a 42}} :n, :all m} nil] m)
(let [{{{a :a, :or {a 1}} :nn, :or {}} :n, :or {}, :all m} {:n {:nn {:b 2}}}] m)
(let [{{a :a, :or {a 1}, :all all-n1} :n1, {b :b, :or {b 2}, :all all-n2} :n2, :all outer-all} {:n1 {}, :n2 {:b 20, :c 30}}] [outer-all all-n1 all-n2])
(let [{:keys [a b & :c :z], :or {:z 42}, :all m} {:a 1, :b 2}] m)
(let [{:keys [a b & :c :z], :or {:z 42}, :all m} {:a 1, :b 2, :z 100}] m)
(eval (quote (let [{:keys [a b & :c], :or {c 42}, :all m} {:a 1, :b 2}] m)))
(nil? (let [{:excess ex} {}] ex))
(nil? (let [{:keys [a], :excess ex} nil] ex))
(eval (quote (selector {:keys [a b]})))
(eval (quote (selector sample-map)))
(eval (quote (selector nil)))
(eval (quote (selector {})))
