;; Harvested by bin/oracle harvest (test/oracle/harvest.clj) from Clojure's test suite,
;; clojure/clojure 98d735fab02f337cee654cb0629bddc09883a75a test/clojure/test_clojure/logic.clj,
;; renamed to arbace.* by bin/clojure-tests: the expressions of its assertions that are
;; self-contained and deterministic. Eclipse Public License 1.0 (LICENSE.md). Do not edit.
(if true :t)
(if true :t :f)
(if false :t)
(if false :t :f)
(if nil :t)
(if nil :t :f)
(if (byte 0) :t :f)
(if (short 0) :t :f)
(if (int 0) :t :f)
(if (long 0) :t :f)
(if (bigint 0) :t :f)
(if (float 0) :t :f)
(if (double 0) :t :f)
(if (bigdec 0) :t :f)
(if 0 :t :f)
(if "" :t :f)
(if #"" :t :f)
(if (symbol "") :t :f)
(if () :t :f)
(if [] :t :f)
(if {} :t :f)
(if #{} :t :f)
(if (into-array []) :t :f)
(if (byte 2) :t :f)
(if (short 2) :t :f)
(if (int 2) :t :f)
(if (long 2) :t :f)
(if (bigint 2) :t :f)
(if (float 2) :t :f)
(if (double 2) :t :f)
(if (bigdec 2) :t :f)
(if 2/3 :t :f)
(if \a :t :f)
(if "abc" :t :f)
(if #"a*b" :t :f)
(if (quote abc) :t :f)
(if :kw :t :f)
(if (quote (1 2)) :t :f)
(if [1 2] :t :f)
(if {:a 1, :b 2} :t :f)
(if #{1 2} :t :f)
(if (into-array [1 2]) :t :f)
(if (new java.util.Date) :t :f)
(if (first []) :no :yes)
(if (next [1]) :no :yes)
(if (rest [1]) :no :yes)
(if (butlast [1]) :no :yes)
(if (seq nil) :no :yes)
(if (seq []) :no :yes)
(if (sequence nil) :no :yes)
(if (sequence []) :no :yes)
(if (lazy-seq nil) :no :yes)
(if (lazy-seq []) :no :yes)
(if (filter (fn* [p1__965#] (> p1__965# 10)) [1 2 3]) :no :yes)
(if (map identity []) :no :yes)
(if (apply concat []) :no :yes)
(if (concat) :no :yes)
(if (concat []) :no :yes)
(if (reverse nil) :no :yes)
(if (reverse []) :no :yes)
(if (sort nil) :no :yes)
(if (sort []) :no :yes)
(and)
(and true)
(and nil)
(and false)
(and true nil)
(and true false)
(and 1 true :kw (quote abc) "abc")
(and 1 true :kw nil (quote abc) "abc")
(and 1 true :kw (quote abc) "abc" false)
(or)
(or true)
(or nil)
(or false)
(or nil false true)
(or nil false 1 2)
(or nil false "abc" :kw)
(or false nil)
(or nil false)
(or nil nil nil false)
(or nil true false)
(not nil)
(not false)
(not true)
(not 0)
(not 0.0)
(not 42)
(not 1.2)
(not 2/3)
(not \space)
(not \tab)
(not \a)
(not "")
(not "abc")
(not #"")
(not #"a*b")
(not (symbol ""))
(not (quote abc))
(not :kw)
(not ())
(not (quote (1 2)))
(not [])
(not [1 2])
(not {})
(not {:a 1, :b 2})
(not #{})
(not #{1 2})
(not (into-array []))
(not (into-array [1 2]))
(not (new java.util.Date))
(some? nil)
(some? false)
(some? 0)
(some? "abc")
(some? [])
