;; Harvested by bin/oracle harvest (test/oracle/harvest.clj) from Clojure's test suite,
;; clojure/clojure 98d735fab02f337cee654cb0629bddc09883a75a test/clojure/test_clojure/math.clj,
;; renamed to arbace.* by bin/clojure-tests: the expressions of its assertions that are
;; self-contained and deterministic. Eclipse Public License 1.0 (LICENSE.md). Do not edit.
(require (quote [arbace.math :as m]))
(NaN? (m/sin ##NaN))
(NaN? (m/sin ##-Inf))
(NaN? (m/sin ##Inf))
(NaN? (m/cos ##NaN))
(NaN? (m/cos ##-Inf))
(NaN? (m/cos ##Inf))
(m/cos 0.0)
(m/cos -0.0)
(NaN? (m/tan ##NaN))
(NaN? (m/tan ##-Inf))
(NaN? (m/tan ##Inf))
(NaN? (m/asin ##NaN))
(NaN? (m/asin 2.0))
(NaN? (m/asin -2.0))
(zero? (m/asin -0.0))
(NaN? (m/acos ##NaN))
(NaN? (m/acos -2.0))
(NaN? (m/acos 2.0))
(NaN? (m/atan ##NaN))
(NaN? (m/exp ##NaN))
(m/exp ##Inf)
(NaN? (m/log ##NaN))
(NaN? (m/log -1.0))
(m/log ##Inf)
(m/log 0.0)
(NaN? (m/log10 ##NaN))
(NaN? (m/log10 -1.0))
(m/log10 ##Inf)
(m/log10 0.0)
(NaN? (m/sqrt ##NaN))
(NaN? (m/sqrt -1.0))
(m/sqrt ##Inf)
(m/sqrt 4.0)
(NaN? (m/cbrt ##NaN))
(m/cbrt ##-Inf)
(m/cbrt ##Inf)
(m/cbrt 8.0)
(NaN? (m/IEEE-remainder ##NaN 1.0))
(NaN? (m/IEEE-remainder 1.0 ##NaN))
(NaN? (m/IEEE-remainder ##Inf 2.0))
(NaN? (m/IEEE-remainder ##-Inf 2.0))
(NaN? (m/IEEE-remainder 2 0.0))
(m/IEEE-remainder 5.0 4.0)
(NaN? (m/ceil ##NaN))
(m/ceil ##Inf)
(m/ceil ##-Inf)
(m/ceil m/PI)
(NaN? (m/floor ##NaN))
(m/floor ##Inf)
(m/floor ##-Inf)
(m/floor m/PI)
(NaN? (m/rint ##NaN))
(m/rint ##Inf)
(m/rint ##-Inf)
(m/rint 1.2)
(NaN? (m/atan2 ##NaN 1.0))
(NaN? (m/atan2 1.0 ##NaN))
(m/pow 4.0 0.0)
(m/pow 4.0 -0.0)
(m/pow 4.2 1.0)
(NaN? (m/pow 4.2 ##NaN))
(NaN? (m/pow ##NaN 2.0))
(m/pow 2.0 ##Inf)
(m/pow 0.5 ##-Inf)
(m/pow 2.0 ##-Inf)
(m/pow 0.5 ##Inf)
(NaN? (m/pow 1.0 ##Inf))
(m/pow 0.0 -2.0)
(m/pow ##Inf 2.0)
(m/pow -0.0 -1.5)
(m/pow ##-Inf 2.5)
(m/pow -0.0 -3.0)
(m/pow ##-Inf 3.0)
(m/pow -2.0 2.0)
(m/pow -2.0 3.0)
(m/pow 2.0 3.0)
(m/round ##NaN)
(m/round ##-Inf)
(m/round (- Long/MIN_VALUE 2.0))
(m/round ##Inf)
(m/round (+ Long/MAX_VALUE 2.0))
(m/round 3.5)
(inc Long/MIN_VALUE)
(m/negate-exact Long/MAX_VALUE)
(m/floor-div Long/MIN_VALUE -1)
(m/floor-div -2 5)
(m/floor-mod -2 5)
(NaN? (m/ulp ##NaN))
(m/ulp ##Inf)
(m/ulp ##-Inf)
(m/ulp 0.0)
(m/pow 2 971)
(m/ulp Double/MAX_VALUE)
(m/ulp (- Double/MAX_VALUE))
(NaN? (m/signum ##NaN))
(zero? (m/signum 0.0))
(zero? (m/signum -0.0))
(m/signum 42.0)
(m/signum -42.0)
(NaN? (m/sinh ##NaN))
(m/sinh ##Inf)
(m/sinh ##-Inf)
(m/sinh 0.0)
(NaN? (m/cosh ##NaN))
(m/cosh ##Inf)
(m/cosh ##-Inf)
(m/cosh 0.0)
(NaN? (m/tanh ##NaN))
(m/tanh ##Inf)
(m/tanh ##-Inf)
(m/tanh 0.0)
(m/hypot 1.0 ##Inf)
(m/hypot ##Inf 1.0)
(NaN? (m/hypot ##NaN 1.0))
(NaN? (m/hypot 1.0 ##NaN))
(m/hypot 5.0 12.0)
(NaN? (m/expm1 ##NaN))
(m/expm1 ##Inf)
(m/expm1 ##-Inf)
(m/expm1 0.0)
(NaN? (m/log1p ##NaN))
(m/log1p ##Inf)
(m/log1p -1.0)
(m/copy-sign 1.0 42.0)
(m/copy-sign 1.0 -42.0)
(m/copy-sign 1.0 ##-Inf)
(inc Double/MAX_EXPONENT)
(m/get-exponent ##NaN)
(m/get-exponent ##Inf)
(m/get-exponent ##-Inf)
(dec Double/MIN_EXPONENT)
(m/get-exponent 0.0)
(m/get-exponent 1.0)
(m/get-exponent 12345.678)
(NaN? (m/next-after ##NaN 1))
(NaN? (m/next-after 1 ##NaN))
(m/next-after ##Inf 1.0)
(NaN? (m/next-up ##NaN))
(m/next-up ##Inf)
(m/next-up 0.0)
(NaN? (m/next-down ##NaN))
(m/next-down ##-Inf)
(- Double/MIN_VALUE)
(m/next-down 0.0)
(NaN? (m/scalb ##NaN 1))
(m/scalb ##Inf 1)
(m/scalb ##-Inf 1)
(m/scalb 2.0 4)
