;; Harvested by bin/oracle harvest (test/oracle/harvest.clj) from Clojure's test suite,
;; clojure/clojure 98d735fab02f337cee654cb0629bddc09883a75a test/clojure/test_clojure/printer.clj,
;; renamed to arbace.* by bin/clojure-tests: the expressions of its assertions that are
;; self-contained and deterministic. Eclipse Public License 1.0 (LICENSE.md). Do not edit.
(binding [*print-dup* true] (print-str 1))
(binding [*print-dup* true] (print-str 1.0))
(binding [*print-dup* true] (print-str 1N))
(binding [*print-dup* true] (print-str (java.math.BigInteger. "1")))
(binding [*print-dup* true] (print-str 1M))
(binding [*print-dup* true] (print-str "hi"))
(let [x 1] (= x (read-string (binding [*print-dup* true] (print-str x)))))
(let [x 1.0] (= x (read-string (binding [*print-dup* true] (print-str x)))))
(let [x 1N] (= x (read-string (binding [*print-dup* true] (print-str x)))))
(let [x 1M] (= x (read-string (binding [*print-dup* true] (print-str x)))))
(let [x "hi"] (= x (read-string (binding [*print-dup* true] (print-str x)))))
(pr-str (var pr-str))
(pr-str (var var-with-meta))
(pr-str (var var-with-type))
(binding [*print-meta* true] (let [pstr (pr-str (var pr-str))] (and (.endsWith pstr "#'arbace.core/pr-str") (.startsWith pstr "^") (.contains pstr (pr-str (meta (var pr-str)))))))
(binding [*print-meta* true] (let [pstr (pr-str (var var-with-meta))] (and (.endsWith pstr "#'clojure.test-clojure.printer/var-with-meta") (.startsWith pstr "^") (.contains pstr (pr-str (meta (var var-with-meta)))))))
(binding [*print-meta* true] (let [pstr (pr-str (var var-with-type))] (and (.endsWith pstr "#'clojure.test-clojure.printer/var-with-type") (.startsWith pstr "^") (.contains pstr (pr-str (meta (var var-with-type)))))))
(let [e' (Exception. "heyo")] (= (-> e' Throwable->map) (-> e' pr-str read-string)))
(let [e' (Throwable. "I can a throwable" (Exception. "chain 1" (Exception. "chan 2")))] (= (-> e' Throwable->map) (-> e' pr-str read-string)))
(let [e' (ex-info "an ex-info" {:with "its", :data 29})] (= (-> e' Throwable->map) (-> e' pr-str read-string)))
(let [e' (Exception. "outer" (ex-info "an ex-info" {:with "data"} (Error. "less outer" (ex-info "the root" {:with "even", :more (quote data)}))))] (= (-> e' Throwable->map) (-> e' pr-str read-string)))
(pr-str Double/POSITIVE_INFINITY)
(pr-str Double/NEGATIVE_INFINITY)
(pr-str Double/NaN)
(pr-str Float/POSITIVE_INFINITY)
(pr-str Float/NEGATIVE_INFINITY)
(pr-str Float/NaN)
