;; Harvested by bin/oracle harvest (test/oracle/harvest.clj) from Clojure's test suite,
;; clojure/clojure 98d735fab02f337cee654cb0629bddc09883a75a test/clojure/test_clojure/reader.cljc,
;; renamed to arbace.* by bin/clojure-tests: the expressions of its assertions that are
;; self-contained and deterministic. Eclipse Public License 1.0 (LICENSE.md). Do not edit.
(require (quote [arbace.edn :as edn]))
(require (quote [arbace.edn :as edn]))
(symbol "abc")
(symbol "*+!-_?")
(symbol "abc:def:ghi")
(symbol "abc" "def")
(symbol "abc.def" "ghi")
(symbol "abc" "def.ghi")
(symbol "abc:def" "ghi:jkl.mno")
(instance? arbace.lang.Symbol (quote alphabet))
(str \a \b \c \d \e)
(str \a \b \c \newline \space \space \d \e \f)
(instance? Long 2147483647)
(instance? Long 1)
(instance? Long 0)
(instance? Long -1)
(instance? Long -2147483648)
(instance? Long 2147483648)
(instance? Long -2147483649)
(instance? Long 9223372036854775807)
(instance? Long -9223372036854775808)
(every? (fn* [p1__1226#] (instance? Long p1__1226#)) sequence)
(instance? Double 10.0)
(instance? Double 0.1)
(instance? Double -10.0)
(instance? Double -0.1)
(instance? Double 1.0)
(instance? Double 0.0)
(instance? Double -0.0)
(instance? Double -1.0)
(and (instance? Double ##NaN) (.isNaN ##NaN))
(instance? BigDecimal 9223372036854775808M)
(instance? BigDecimal -9223372036854775809M)
(instance? BigDecimal 2147483647M)
(instance? BigDecimal 1M)
(instance? BigDecimal 0M)
(instance? BigDecimal -1M)
(instance? BigDecimal -2147483648M)
(instance? BigDecimal 10M)
(instance? BigDecimal 1E+1M)
(instance? BigDecimal 0.10M)
(instance? BigDecimal 0.1M)
(instance? BigDecimal -10M)
(instance? BigDecimal -1E+1M)
(instance? BigDecimal -0.10M)
(instance? BigDecimal -0.1M)
(instance? BigDecimal 1.0M)
(instance? BigDecimal 0.0M)
(instance? BigDecimal -1.0M)
(first "o")
(char 0)
(char 39)
(char 255)
(first "u")
(first "A")
(char 55295)
(char 57344)
(char 65535)
(keyword "abc")
(keyword (quote abc))
(keyword "*+!-_?")
(keyword "abc:def:ghi")
(keyword "abc" "def")
(keyword (quote abc/def))
(keyword "abc.def" "ghi")
(keyword "abc" "def.ghi")
(keyword "abc:def" "ghi:jkl.mno")
(instance? arbace.lang.Keyword :alphabet)
(binding [*ns* (the-ns (quote user))] (read-string ":foo"))
(binding [*ns* (the-ns (quote user))] (read-string ":foo/bar"))
(binding [*ns* (the-ns (quote user))] (read-string "::foo"))
(read-string "foo:")
(read-string ":bar/")
(read-string "::does.not/exist")
(meta (quote ^{:static true, :bar :baz, :awesome true} sym))
(pr-str (read-string "#(vector)"))
(not (nil? (re-matches #"\(fn\* \[([\S]+)] \(vector \1\)\)" (pr-str (read-string "#(vector %)")))))
(not (nil? (re-matches #"\(fn\* \[([\S]+)] \(vector \1 \1\)\)" (pr-str (read-string "#(vector % %)")))))
(not (nil? (re-matches #"\(fn\* \[([\S]+)] \(vector \1 \1\)\)" (pr-str (read-string "#(vector % %1)")))))
(not (nil? (re-matches #"\(fn\* \[([\S]+) ([\S]+)] \(vector \1 \2\)\)" (pr-str (read-string "#(vector %1 %2)")))))
(not (nil? (re-matches #"\(fn\* \[([\S]+) ([\S]+) & ([\S]+)] \(vector \2 \3\)\)" (pr-str (read-string "#(vector %2 %&)")))))
(read-string "#(vector %%)")
(read-string "#(vector %1/2)")
(read-string "#(vector %1.5)")
(read-string "#(vector %-0.2)")
(read-string "#(vector %3M)")
(read-string "#(list %#_(first arg)1.00000001 %#_(secong arg)2r10 %#_(rest arg)-1.5)")
(arbace.core/list)
()
(class #inst "2010-11-12T13:14:15.666-00:00")
(class #uuid "550e8400-e29b-41d4-a716-446655440000")
(.equals #uuid "550e8400-e29b-41d4-a716-446655440000" #uuid "550e8400-e29b-41d4-a716-446655440000")
(not (identical? #uuid "550e8400-e29b-41d4-a716-446655440000" #uuid "550e8400-e29b-41d4-a716-446655440000"))
(.version #uuid "550e8400-e29b-41d4-a716-446655440000")
(print-str #uuid "550e8400-e29b-41d4-a716-446655440000")
(read-string "#foo [1 2]")
(read-string "#bar/foo [1 2]")
(read-string "#bar.baz/foo [1 2]")
(reader-conditional (quote (:clj foo :cljs bar)) false)
(reader-conditional (quote (:clj [foo])) true)
(read-string {:read-cond :preserve} "#js {:x 1 :y 2}")
(tagged-literal (quote js) {:x 1, :y 2})
(read-string {:read-cond :allow, :features #{:foo}} "[#?(:foo foo-form :bar bar-form)]")
(read-string {:read-cond :allow, :features #{:bar}} "[#?(:foo foo-form :bar bar-form)]")
(read-string {:read-cond :allow, :features #{:bar :foo}} "[#?(:foo foo-form :bar bar-form)]")
(read-string {:read-cond :allow, :features #{:baz}} "[#?( :foo foo-form :bar bar-form)]")
(read-string {:read-cond :allow} "#?((+ 1 2) :a)")
(read-string {:read-cond :allow} "#?(:cljs :a :clj)")
(read-string {:read-cond :allow} "#?@(:clj :a)")
(read-string {:read-cond :allow} "#?@(:foo :a :else :b)")
(read-string {:read-cond :allow} "#?[:foo :a :else :b]")
(read-string {:read-cond :BOGUS} "#?[:clj :a :default nil]")
(read-string "#?[:clj :a :default nil]")
(read-string {:read-cond :allow} "#?@(:clj [1 2])")
(read-string {:read-cond :allow} "#?@(:clj [1])")
(read-string {:read-cond :allow} "#?@(:clj []) 1")
(nil? nil)
(read-string {:eof 23} "")
(read {:eof 23} (arbace.lang.LineNumberingPushbackReader. (java.io.StringReader. "")))
(read-string "#:a{b 1 b/c 2}")
(read-string "#:::")
(read-string "#:s{1}")
(read-string "#:s/t{1 2}")
(read-string "#::BOGUS{1 2}")
(read-string "#: s{:a 1}")
(read-string "#::{:a 1 :a 2}")
(read-string "#::{a 1 a 2}")
(edn/read-string "#:a{1 1, :b 2, :b/c 3, :_/d 4}")
(edn/read-string "#:a {1 1, :b 2, :b/c 3, :_/d 4}")
(read-string "##5")
(edn/read-string "##5")
(read-string "##Foo")
(edn/read-string "##Foo")
(-> "^{:line 42 :column 99} (1 2)" read-string meta (select-keys [:line :column]))
(-> (quote explicit-line-numbering) resolve meta (select-keys [:line :column]))
(read-string "#λ 10")
