;; Harvested by bin/oracle harvest (test/oracle/harvest.clj) from Clojure's test suite,
;; clojure/clojure 98d735fab02f337cee654cb0629bddc09883a75a test/clojure/test_clojure/sequences.clj,
;; renamed to arbace.* by bin/clojure-tests: the expressions of its assertions that are
;; self-contained and deterministic. Eclipse Public License 1.0 (LICENSE.md). Do not edit.
(into [] (concat [1 2] "ab"))
(reduce + int-array)
(reduce + long-array)
(reduce + float-array)
(reduce + double-array)
(reduce + 1 int-array)
(reduce + 1 long-array)
(reduce + 1 float-array)
(reduce + 1 double-array)
(->> (repeat 500000 (cons 1 [1])) (apply concat) (reduce +))
(->> (range 100000) (mapcat (fn [_] (java.util.ArrayList. (range 10)))) (reduce +))
(map inc nil)
()
(map inc ())
(map inc [])
(map inc #{})
(map inc {})
(sequence (map inc) (range 10))
(range 1 11)
(seq? (lazy-seq nil))
(seq? (lazy-seq []))
(seq? (lazy-seq [1 2]))
(not (.equals (lazy-seq [3]) (lazy-seq [3N])))
(lazy-seq nil)
(lazy-seq [nil])
(lazy-seq ())
(lazy-seq [])
(lazy-seq #{})
(lazy-seq {})
(lazy-seq "")
(lazy-seq (into-array []))
(lazy-seq [3])
(lazy-seq (list 1 2))
(lazy-seq [1 2])
(lazy-seq (sorted-set 1 2))
(lazy-seq (sorted-map :a 1 :b 2))
(lazy-seq "abc")
(lazy-seq (into-array [1 2]))
(not (seq? (seq [])))
(seq? (seq [1 2]))
(not (.equals (seq [3]) (seq [3N])))
(seq nil)
(seq [nil])
(seq ())
(seq [])
(seq #{})
(seq {})
(seq "")
(seq (into-array []))
(seq [3])
(seq (list 1 2))
(seq [1 2])
(seq (sorted-set 1 2))
(seq (sorted-map :a 1 :b 2))
(seq "abc")
(seq (into-array [1 2]))
(cons 1 2)
(cons 1 nil)
(cons nil nil)
(cons \a nil)
(cons \a "")
(cons \a "bc")
(cons 1 ())
(cons 1 (quote (2 3)))
(cons 1 [])
(cons 1 [2 3])
(cons 1 #{})
(cons 1 (sorted-set 2 3))
(cons 1 (into-array []))
(cons 1 (into-array [2 3]))
(and (= (empty nil) nil))
(and (= (empty ()) ()))
(and (= (empty (quote (1 2))) ()))
(and (= (empty []) []))
(and (= (empty [1 2]) []))
(and (= (empty {}) {}))
(and (= (empty {:a 1, :b 2}) {}))
(and (= (empty (sorted-map)) (sorted-map)))
(and (= (empty (sorted-map :a 1 :b 2)) (sorted-map)))
(and (= (empty #{}) #{}))
(and (= (empty #{1 2}) #{}))
(and (= (empty (sorted-set)) (sorted-set)))
(and (= (empty (sorted-set 1 2)) (sorted-set)))
(and (= (empty (seq ())) nil))
(and (= (empty (seq (quote (1 2)))) ()))
(and (= (empty (seq [])) nil))
(and (= (empty (seq [1 2])) ()))
(and (= (empty (seq "")) nil))
(and (= (empty (seq "ab")) ()))
(and (= (empty (lazy-seq ())) ()))
(and (= (empty (lazy-seq (quote (1 2)))) ()))
(and (= (empty (lazy-seq [])) ()))
(and (= (empty (lazy-seq [1 2])) ()))
(and (= (empty 42) nil))
(and (= (empty 1.2) nil))
(and (= (empty "abc") nil))
(first (into (empty (sorted-set 1 2 3)) (sorted-set 1 2 3)))
(first (sorted-set 1 2 3))
(first (into (empty (sorted-map 1 :a 2 :b 3 :c)) (sorted-map 1 :a 2 :b 3 :c)))
(first (sorted-map 1 :a 2 :b 3 :c))
(not-empty ())
(not-empty [])
(not-empty {})
(not-empty #{})
(not-empty (seq ()))
(not-empty (seq []))
(not-empty (lazy-seq ()))
(not-empty (lazy-seq []))
(and (= (not-empty (quote (1 2))) (quote (1 2))) (= (class (not-empty (quote (1 2)))) (class (quote (1 2)))))
(and (= (not-empty [1 2]) [1 2]) (= (class (not-empty [1 2])) (class [1 2])))
(and (= (not-empty {:a 1}) {:a 1}) (= (class (not-empty {:a 1})) (class {:a 1})))
(and (= (not-empty #{1 2}) #{1 2}) (= (class (not-empty #{1 2})) (class #{1 2})))
(and (= (not-empty (seq (quote (1 2)))) (seq (quote (1 2)))) (= (class (not-empty (seq (quote (1 2))))) (class (seq (quote (1 2))))))
(and (= (not-empty (seq [1 2])) (seq [1 2])) (= (class (not-empty (seq [1 2]))) (class (seq [1 2]))))
(and (= (not-empty (lazy-seq (quote (1 2)))) (lazy-seq (quote (1 2)))) (= (class (not-empty (lazy-seq (quote (1 2))))) (class (lazy-seq (quote (1 2))))))
(and (= (not-empty (lazy-seq [1 2])) (lazy-seq [1 2])) (= (class (not-empty (lazy-seq [1 2]))) (class (lazy-seq [1 2]))))
(first true)
(first false)
(first 1)
(first \a)
(first (quote s))
(first :k)
(first nil)
(first "")
(first "a")
(first "abc")
(first ())
(first (quote (1)))
(first (quote (1 2 3)))
(first (quote (nil)))
(first (quote (1 nil)))
(first (quote (nil 2)))
(first (quote (())))
(first (quote (() nil)))
(first (quote (() 2 nil)))
(first [])
(first [1])
(first [1 2 3])
(first [nil])
(first [1 nil])
(first [nil 2])
(first [[]])
(first [[] nil])
(first [[] 2 nil])
(first #{})
(first #{1})
(first #{nil})
(first (sorted-set 1 nil))
(first (sorted-set nil 2))
(first #{#{}})
(first (sorted-set [] nil))
(first {})
(first (sorted-map :a 1))
(first (sorted-map :a 1 :b 2 :c 3))
(first (into-array []))
(first (into-array [1]))
(first (into-array [1 2 3]))
(first (to-array [nil]))
(first (to-array [1 nil]))
(first (to-array [nil 2]))
(next true)
(next false)
(next 1)
(next \a)
(next (quote s))
(next :k)
(next nil)
(next "")
(next "a")
(next "abc")
(next ())
(next (quote (1)))
(next (quote (1 2 3)))
(next (quote (nil)))
(next (quote (1 nil)))
(next (quote (1 ())))
(next (quote (nil 2)))
(next (quote (())))
(next (quote (() nil)))
(next (quote (() 2 nil)))
(next [])
(next [1])
(next [1 2 3])
(next [nil])
(next [1 nil])
(next [1 []])
(next [nil 2])
(next [[]])
(next [[] nil])
(next [[] 2 nil])
(next #{})
(next #{1})
(next (sorted-set 1 2 3))
(next #{nil})
(next (sorted-set 1 nil))
(next (sorted-set nil 2))
(next #{#{}})
(next (sorted-set [] nil))
(next {})
(next (sorted-map :a 1))
(next (sorted-map :a 1 :b 2 :c 3))
(next (into-array []))
(next (into-array [1]))
(next (into-array [1 2 3]))
(next (to-array [nil]))
(next (to-array [1 nil]))
(next (to-array [nil 2]))
(next (to-array [(into-array [])]))
(next (to-array [(into-array []) nil]))
(next (to-array [(into-array []) 2 nil]))
(and (= (seq nil) (nthnext nil 0)) (= nil (nthrest nil 0)))
(and (= (seq "") (nthnext "" 0)) (= "" (nthrest "" 0)))
(and (= (seq ()) (nthnext () 0)) (= () (nthrest () 0)))
(and (= (seq (quote (0))) (nthnext (quote (0)) 0)) (= (quote (0)) (nthrest (quote (0)) 0)))
(and (= (seq []) (nthnext [] 0)) (= [] (nthrest [] 0)))
(and (= (seq [0]) (nthnext [0] 0)) (= [0] (nthrest [0] 0)))
(and (= (seq #{}) (nthnext #{} 0)) (= #{} (nthrest #{} 0)))
(and (= (seq {}) (nthnext {} 0)) (= {} (nthrest {} 0)))
(and (= (seq {:a 1}) (nthnext {:a 1} 0)) (= {:a 1} (nthrest {:a 1} 0)))
(and (= (seq (range 5)) (nthnext (range 5) 0)) (= (range 5) (nthrest (range 5) 0)))
(and (= nil (nthnext nil 1)) (= () (nthrest nil 1)))
(and (= (quote (\b \c)) (nthnext "abc" 1)) (= (quote (\b \c)) (nthrest "abc" 1)))
(and (= nil (nthnext "abc" 3)) (= () (nthrest "abc" 3)))
(and (= nil (nthnext "abc" 4)) (= () (nthrest "abc" 4)))
(and (= nil (nthnext () 1)) (= () (nthrest () 1)))
(and (= nil (nthnext (quote (1)) 1)) (= () (nthrest (quote (1)) 1)))
(and (= nil (nthnext (quote (1)) 2)) (= () (nthrest (quote (1)) 2)))
(and (= nil (nthnext (quote (())) 1)) (= () (nthrest (quote (())) 1)))
(and (= nil (nthnext #{} 1)) (= () (nthrest #{} 1)))
(and (= nil (nthnext {:a 1} 1)) (= () (nthrest {:a 1} 1)))
(and (= nil (nthnext [] 1)) (= () (nthrest [] 1)))
(and (= nil (nthnext [0] 1)) (= () (nthrest [0] 1)))
(and (= nil (nthnext [0] 2)) (= () (nthrest [0] 2)))
(and (= (quote (2 nil)) (nthnext [[] 2 nil] 1)) (= (quote (2 nil)) (nthrest [[] 2 nil] 1)))
(and (= (quote (nil)) (nthnext [[] 2 nil] 2)) (= (quote (nil)) (nthrest [[] 2 nil] 2)))
(and (= nil (nthnext [[] 2 nil] 3)) (= () (nthrest [[] 2 nil] 3)))
(and (= (quote (3)) (nthnext (sorted-set 1 2 3) 2)) (= (quote (3)) (nthrest (sorted-set 1 2 3) 2)))
(and (= (quote ([:b 2])) (nthnext (sorted-map :a 1 :b 2) 1)) (= (quote ([:b 2])) (nthrest (sorted-map :a 1 :b 2) 1)))
(and (= nil (nthnext (into-array []) 1)) (= () (nthrest (into-array []) 1)))
(and (= nil (nthnext (into-array [1]) 1)) (= () (nthrest (into-array [1]) 1)))
(and (= (quote (3 4)) (nthnext (range 5) 3)) (= (quote (3 4)) (nthrest (range 5) 3)))
(and (= nil (nthnext (range 5) 5)) (= () (nthrest (range 5) 5)))
(last nil)
(last ())
(last (quote (1)))
(last (quote (1 2 3)))
(last (quote (nil)))
(last (quote (1 nil)))
(last (quote (nil 2)))
(last (quote (())))
(last (quote (() nil)))
(last (quote (() 2 nil)))
(last [])
(last [1])
(last [1 2 3])
(last [nil])
(last [1 nil])
(last [nil 2])
(last [[]])
(last [[] nil])
(last [[] 2 nil])
(last #{})
(last #{1})
(last (sorted-set 1 2 3))
(last #{nil})
(last (sorted-set 1 nil))
(last (sorted-set nil 2))
(last #{#{}})
(last (sorted-set [] nil))
(last {})
(last (sorted-map :a 1))
(last (sorted-map :a 1 :b 2 :c 3))
(last "")
(last "a")
(last "abc")
(last (into-array []))
(last (into-array [1]))
(last (into-array [1 2 3]))
(last (to-array [nil]))
(last (to-array [1 nil]))
(last (to-array [nil 2]))
(ffirst nil)
(ffirst ())
(ffirst (quote ((1 2) (3 4))))
(ffirst [])
(ffirst [[1 2] [3 4]])
(ffirst {})
(ffirst {:a 1})
(ffirst #{})
(ffirst #{[1 2]})
(fnext nil)
(fnext ())
(fnext (quote (1)))
(fnext (quote (1 2 3 4)))
(fnext [])
(fnext [1])
(fnext [1 2 3 4])
(fnext {})
(fnext (sorted-map :a 1))
(fnext (sorted-map :a 1 :b 2))
(fnext #{})
(fnext #{1})
(fnext (sorted-set 1 2 3 4))
(nfirst nil)
(nfirst ())
(nfirst (quote ((1 2 3) (4 5 6))))
(nfirst [])
(nfirst [[1 2 3] [4 5 6]])
(nfirst {})
(nfirst {:a 1})
(nfirst #{})
(nfirst #{[1 2]})
(nnext nil)
(nnext ())
(nnext (quote (1)))
(nnext (quote (1 2)))
(nnext (quote (1 2 3 4)))
(nnext [])
(nnext [1])
(nnext [1 2])
(nnext [1 2 3 4])
(nnext {})
(nnext (sorted-map :a 1))
(nnext (sorted-map :a 1 :b 2))
(nnext (sorted-map :a 1 :b 2 :c 3 :d 4))
(nnext #{})
(nnext #{1})
(nnext (sorted-set 1 2))
(nnext (sorted-set 1 2 3 4))
(nth {} 0)
(nth {:a 1, :b 2} 0)
(nth #{} 0)
(nth #{1 3 2} 0)
(nth (quote ()) 0)
(nth (quote (1 2 3)) 5)
(nth (quote ()) -1)
(nth (quote (1 2 3)) -1)
(nth [] 0)
(nth [1 2 3] 5)
(nth [] -1)
(nth [1 2 3] -1)
(nth (into-array []) 0)
(nth (into-array [1 2 3]) 5)
(nth (into-array []) -1)
(nth (into-array [1 2 3]) -1)
(nth "" 0)
(nth "abc" 5)
(nth "" -1)
(nth "abc" -1)
(nth (java.util.ArrayList. []) 0)
(nth (java.util.ArrayList. [1 2 3]) 5)
(nth (java.util.ArrayList. []) -1)
(nth (java.util.ArrayList. [1 2 3]) -1)
(nth (quote (1)) 0)
(nth (quote (1 2 3)) 0)
(nth (quote (1 2 3 4 5)) 1)
(nth (quote (1 2 3 4 5)) 4)
(nth (quote (1 2 3)) 5 :not-found)
(nth [1] 0)
(nth [1 2 3] 0)
(nth [1 2 3 4 5] 1)
(nth [1 2 3 4 5] 4)
(nth [1 2 3] 5 :not-found)
(nth (into-array [1]) 0)
(nth (into-array [1 2 3]) 0)
(nth (into-array [1 2 3 4 5]) 1)
(nth (into-array [1 2 3 4 5]) 4)
(nth (into-array [1 2 3]) 5 :not-found)
(nth "a" 0)
(nth "abc" 0)
(nth "abcde" 1)
(nth "abcde" 4)
(nth "abc" 5 :not-found)
(nth (java.util.ArrayList. [1]) 0)
(nth (java.util.ArrayList. [1 2 3]) 0)
(nth (java.util.ArrayList. [1 2 3 4 5]) 1)
(nth (java.util.ArrayList. [1 2 3 4 5]) 4)
(nth (java.util.ArrayList. [1 2 3]) 5 :not-found)
(distinct ())
(distinct (quote (1)))
(distinct (quote (1 2 3)))
(distinct (quote (1 2 3 1 1 1)))
(distinct (quote (1 1 1 2)))
(distinct (quote (1 2 1 2)))
(distinct [])
(distinct [1])
(distinct [1 2 3])
(distinct [1 2 3 1 2 2 1 1])
(distinct [1 1 1 2])
(distinct [1 2 1 2])
(distinct "")
(distinct "a")
(distinct "abc")
(distinct "abcabab")
(distinct "aaab")
(distinct "abab")
(distinct [nil nil])
(distinct [false false])
(distinct [true true])
(distinct [0 0])
(distinct [42 42])
(distinct [0.0 0.0])
(distinct [3.14 3.14])
(distinct [2/3 2/3])
(distinct [0M 0M])
(distinct [1M 1M])
(distinct [\c \c])
(distinct ["" ""])
(distinct ["abc" "abc"])
(distinct [(quote sym) (quote sym)])
(distinct [:kw :kw])
(distinct [() ()])
(distinct [(quote (1 2)) (quote (1 2))])
(distinct [[] []])
(distinct [[1 2] [1 2]])
(distinct [{} {}])
(distinct [{:a 1, :b 2} {:a 1, :b 2}])
(distinct [#{} #{}])
(distinct [#{1 2} #{1 2}])
(interpose 0 [])
(interpose 0 [1])
(interpose 0 [1 2])
(interpose 0 [1 2 3])
(interleave [1 2] [3 4])
(interleave [1] [3 4])
(interleave [1 2] [3])
(interleave [] [3 4])
(interleave [1 2] [])
(interleave [] [])
(interleave [1])
(interleave)
(zipmap [:a :b] [1 2])
(zipmap [:a] [1 2])
(zipmap [:a :b] [1])
(zipmap [] [1 2])
(zipmap [:a :b] [])
(zipmap [] [])
(concat)
(concat [])
(concat [1 2])
(concat [1 2] [3 4])
(concat [] [3 4])
(concat [1 2] [])
(concat [] [])
(concat [1 2] [3 4] [5 6])
(cycle [])
(take 3 (cycle [1]))
(take 5 (cycle [1 2 3]))
(take 3 (cycle [nil]))
(transduce (take 5) + (cycle [1]))
(transduce (take 5) + 2 (cycle [1]))
(transduce (take 5) + (cycle [3 7]))
(transduce (take 5) + 2 (cycle [3 7]))
(take 2 (cycle (map (fn* [p1__1240#] (/ 42 p1__1240#)) (quote (2 1 0)))))
(first (next (cycle (map (fn* [p1__1241#] (/ 42 p1__1241#)) (quote (2 1 0))))))
(into [] (take 2) (cycle (map (fn* [p1__1242#] (/ 42 p1__1242#)) (quote (2 1 0)))))
(partition 2 [1 2 3])
(partition 2 [1 2 3 4])
(partition 2 [])
(partition 2 3 [1 2 3 4 5 6 7])
(partition 2 3 [1 2 3 4 5 6 7 8])
(partition 2 3 [])
(partition 1 [])
(partition 1 [1 2 3])
(partition 5 [1 2 3])
(partition 4 4 [0 0 0] (range 10))
(partition -1 [1 2 3])
(partition -2 [1 2 3])
(map (fn* [p1__1243#] (reduce * (repeat p1__1243# 2))) (range 5))
(map (fn* [p1__1244#] (reduce * 3 (repeat p1__1244# 2))) (range 5))
(repeat 5 :x)
(hash (repeat 5 :x))
(hash (quote (:x :x :x :x :x)))
(assoc (array-map (repeat 1 :x) :y) (quote (:x)) :z)
(assoc (hash-map (repeat 1 :x) :y) (quote (:x)) :z)
(partitionv 2 [1 2 3])
(partitionv 2 [1 2 3 4])
(partitionv 2 [])
(partitionv 2 3 [1 2 3 4 5 6 7])
(partitionv 2 3 [1 2 3 4 5 6 7 8])
(partitionv 2 3 [])
(partitionv 1 [])
(partitionv 1 [1 2 3])
(partitionv 4 4 [0 0 0] (range 10))
(partitionv 5 [1 2 3])
(partitionv -1 [1 2 3])
(partitionv -2 [1 2 3])
(take 0 (iterate inc 0))
(take 1 (iterate inc 0))
(take 2 (iterate inc 0))
(take 5 (iterate inc 0))
(take 4 (iterate (fn* [p1__1245#] (if (= p1__1245# :foo) 42 :foo)) :foo))
(take 4 (iterate (fn* [p1__1246#] (instance? Boolean p1__1246#)) 1))
(take 10 (iterate (fn* [p1__1247#] (quot p1__1247# 2)) 256))
(take 2 (iterate zero? 0))
(first (next (next (iterate inc 0))))
(into [] (take 3) (next (iterate inc 0)))
(transduce (take 5) + (iterate (fn* [p1__1248#] (* 2 p1__1248#)) 2))
(transduce (take 5) + 1 (iterate (fn* [p1__1249#] (* 2 p1__1249#)) 2))
(reverse nil)
(reverse [])
(reverse [1])
(reverse [1 2 3])
(take 1 [1 2 3 4 5])
(take 3 [1 2 3 4 5])
(take 5 [1 2 3 4 5])
(take 9 [1 2 3 4 5])
(take 0 [1 2 3 4 5])
(take -1 [1 2 3 4 5])
(take -2 [1 2 3 4 5])
(take 1/4 [1 2 3 4 5])
(drop 1 [1 2 3 4 5])
(drop 3 [1 2 3 4 5])
(drop 5 [1 2 3 4 5])
(drop 9 [1 2 3 4 5])
(drop 0 [1 2 3 4 5])
(drop -1 [1 2 3 4 5])
(drop -2 [1 2 3 4 5])
(drop 1/4 [1 2 3 4 5])
(drop 4 [0 1 2 3 4 5])
(drop -2 (drop 4 [0 1 2 3 4 5]))
(drop 4 (seq [0 1 2 3 4 5]))
(drop -2 (drop 4 (seq [0 1 2 3 4 5])))
(drop 4 (range 6))
(drop -2 (drop 4 (range 6)))
(drop 4 (repeat 6 :x))
(drop -2 (drop 4 (repeat 6 :x)))
(nthrest [1 2 3 4 5] 1)
(nthrest [1 2 3 4 5] 3)
(nthrest [1 2 3 4 5] 5)
(nthrest [1 2 3 4 5] 9)
(nthrest [1 2 3 4 5] 0)
(nthrest [1 2 3 4 5] -1)
(nthrest [1 2 3 4 5] -2)
(nthrest [1 2 3 4 5] 1/4)
(nthrest [1 2 3 4 5] 1.2)
(let [r (nthrest [1 2 3] 0)] (and (= [1 2 3] r) (= (class [1 2 3]) (class r))))
(let [r (nthrest (seq [1 2 3]) 0)] (and (= (seq [1 2 3]) r) (= (class (seq [1 2 3])) (class r))))
(let [r (nthrest (range 10) 0)] (and (= (range 10) r) (= (class (range 10)) (class r))))
(let [r (nthrest (repeat 10 :x) 0)] (and (= (repeat 10 :x) r) (= (class (repeat 10 :x)) (class r))))
(let [r (nthrest (seq "abc") 0)] (and (= (seq "abc") r) (= (class (seq "abc")) (class r))))
(nthnext [1 2 3 4 5] 1)
(nthnext [1 2 3 4 5] 3)
(nthnext [1 2 3 4 5] 5)
(nthnext [1 2 3 4 5] 9)
(nthnext [1 2 3 4 5] 0)
(nthnext [1 2 3 4 5] -1)
(nthnext [1 2 3 4 5] -2)
(nthnext [1 2 3 4 5] 1/4)
(nthnext [1 2 3 4 5] 1.2)
(take-nth 1 [1 2 3 4 5])
(take-nth 2 [1 2 3 4 5])
(take-nth 3 [1 2 3 4 5])
(take-nth 4 [1 2 3 4 5])
(take-nth 5 [1 2 3 4 5])
(take-nth 9 [1 2 3 4 5])
(take-while pos? [])
(take-while pos? [1 2 3 4])
(take-while pos? [1 2 3 -1])
(take-while pos? [1 -1 2 3])
(take-while pos? [-1 1 2 3])
(take-while pos? [-1 -2 -3])
(drop-while pos? [])
(drop-while pos? [1 2 3 4])
(drop-while pos? [1 2 3 -1])
(drop-while pos? [1 -1 2 3])
(drop-while pos? [-1 1 2 3])
(drop-while pos? [-1 -2 -3])
(butlast [])
(butlast [1])
(butlast [1 2 3])
(drop-last [])
(drop-last [1])
(drop-last [1 2 3])
(drop-last 1 [])
(drop-last 1 [1])
(drop-last 1 [1 2 3])
(drop-last 2 [])
(drop-last 2 [1])
(drop-last 2 [1 2 3])
(drop-last 5 [])
(drop-last 5 [1])
(drop-last 5 [1 2 3])
(drop-last 0 [])
(drop-last 0 [1])
(drop-last 0 [1 2 3])
(drop-last -1 [])
(drop-last -1 [1])
(drop-last -1 [1 2 3])
(drop-last -2 [])
(drop-last -2 [1])
(drop-last -2 [1 2 3])
(vector? (split-at 2 []))
(vector? (split-at 2 [1 2 3]))
(split-at 2 [])
(split-at 2 [1 2 3 4 5])
(split-at 5 [1 2 3])
(split-at 0 [1 2 3])
(split-at -1 [1 2 3])
(split-at -5 [1 2 3])
(vector? (split-with pos? []))
(vector? (split-with pos? [1 2 -1 0 3 4]))
(split-with pos? [])
(split-with pos? [1 2 -1 0 3 4])
(split-with pos? [-1 2 3 4 5])
(split-with number? [1 -2 "abc" \x])
(take 0 (repeat 7))
(take 1 (repeat 7))
(take 2 (repeat 7))
(take 5 (repeat 7))
(repeat 0 7)
(repeat 1 7)
(repeat 2 7)
(repeat 5 7)
(repeat -1 7)
(repeat -3 7)
(repeat 3 nil)
(list nil nil nil)
(repeat 3 false)
(list false false false)
(repeat 3 true)
(list true true true)
(repeat 3 0)
(list 0 0 0)
(repeat 3 42)
(list 42 42 42)
(repeat 3 0.0)
(list 0.0 0.0 0.0)
(repeat 3 3.14)
(list 3.14 3.14 3.14)
(repeat 3 2/3)
(list 2/3 2/3 2/3)
(repeat 3 0M)
(list 0M 0M 0M)
(repeat 3 1M)
(list 1M 1M 1M)
(repeat 3 \c)
(list \c \c \c)
(repeat 3 "")
(list "" "" "")
(repeat 3 "abc")
(list "abc" "abc" "abc")
(repeat 3 (quote sym))
(list (quote sym) (quote sym) (quote sym))
(repeat 3 :kw)
(list :kw :kw :kw)
(repeat 3 ())
(list () () ())
(repeat 3 (quote (1 2)))
(list (quote (1 2)) (quote (1 2)) (quote (1 2)))
(repeat 3 [])
(list [] [] [])
(repeat 3 [1 2])
(list [1 2] [1 2] [1 2])
(repeat 3 {})
(list {} {} {})
(repeat 3 {:a 1, :b 2})
(list {:a 1, :b 2} {:a 1, :b 2} {:a 1, :b 2})
(repeat 3 #{})
(list #{} #{} #{})
(repeat 3 #{1 2})
(list #{1 2} #{1 2} #{1 2})
(drop 1 (repeat 2 :a))
(drop 2 (repeat 2 :a))
(drop 3 (repeat 2 :a))
(take 100 (range))
(range 100)
(range 0)
(range 1)
(range 5)
(range -1)
(range -3)
(range 2.5)
(range 7/3)
(range 0 3)
(range 0 1)
(range 0 0)
(range 0 -3)
(range 3 6)
(range 3 4)
(range 3 3)
(range 3 1)
(range 3 0)
(range 3 -2)
(range -2 5)
(range -2 0)
(range -2 -1)
(range -2 -2)
(range -2 -5)
(take 3 (range 3 9 0))
(take 3 (range 9 3 0))
(range 0 0 0)
(range 3 9 1)
(range 3 9 2)
(range 3 9 3)
(range 3 9 10)
(range 3 9 -1)
(range 10 10 -1)
(range 10 9 -1)
(range 10 8 -1)
(range 10 7 -1)
(range 10 0 -2)
(take 100 (iterate inc 0))
(range 1/2 5 1/3)
(range 0.5 8 1.2)
(range 0.5 -4 -2)
(take 3 (range Long/MAX_VALUE Double/POSITIVE_INFINITY))
(reduce + (take 100 (range)))
(reduce + 0 (take 100 (range)))
(reduce + (range 100))
(reduce + 0 (range 100))
(reduce + (range 0.0 100.0))
(reduce + 0 (range 0.0 100.0))
(reduce + (iterator-seq (.iterator (range 100))))
(reduce + (iterator-seq (.iterator (range 0.0 100.0 1.0))))
(range 10)
(with-meta (range 10) {:a 1})
(range 5 10)
(with-meta (range 5 10) {:a 1})
(range 5 10 1)
(with-meta (range 5 10 1) {:a 1})
(range 10.0)
(with-meta (range 10.0) {:a 1})
(range 5.0 10.0)
(with-meta (range 5.0 10.0) {:a 1})
(range 5.0 10.0 1.0)
(with-meta (range 5.0 10.0 1.0) {:a 1})
(empty? nil)
(empty? ())
(empty? (lazy-seq nil))
(empty? [])
(empty? {})
(empty? #{})
(empty? "")
(empty? (into-array []))
(empty? (transient []))
(empty? (transient #{}))
(empty? (transient {}))
(not (empty? (quote (1 2))))
(not (empty? (lazy-seq [1 2])))
(not (empty? [1 2]))
(not (empty? {:a 1, :b 2}))
(not (empty? #{1 2}))
(not (empty? "abc"))
(not (empty? (into-array [1 2])))
(not (empty? (transient [1])))
(not (empty? (transient #{1})))
(not (empty? (transient {1 2})))
(every? pos? nil)
(every? pos? ())
(every? pos? [])
(every? pos? {})
(every? pos? #{})
(every? pos? (lazy-seq []))
(every? pos? (into-array []))
(every? pos? [1])
(every? pos? [1 2])
(every? pos? [1 2 3 4 5])
(every? pos? [-1])
(every? pos? [-1 -2])
(every? pos? [-1 -2 3])
(every? pos? [-1 2])
(every? pos? [1 -2])
(every? pos? [1 2 -3])
(every? pos? [1 2 -3 4])
(every? #{:a} [:a :a])
(not-every? pos? nil)
(not-every? pos? ())
(not-every? pos? [])
(not-every? pos? {})
(not-every? pos? #{})
(not-every? pos? (lazy-seq []))
(not-every? pos? (into-array []))
(not-every? pos? [1])
(not-every? pos? [1 2])
(not-every? pos? [1 2 3 4 5])
(not-every? pos? [-1])
(not-every? pos? [-1 -2])
(not-every? pos? [-1 -2 3])
(not-every? pos? [-1 2])
(not-every? pos? [1 -2])
(not-every? pos? [1 2 -3])
(not-every? pos? [1 2 -3 4])
(not-every? #{:a} [:a :a])
(not-every? #{:a} [:a :b])
(not-every? #{:a} [:b :b])
(not-any? pos? nil)
(not-any? pos? ())
(not-any? pos? [])
(not-any? pos? {})
(not-any? pos? #{})
(not-any? pos? (lazy-seq []))
(not-any? pos? (into-array []))
(not-any? pos? [1])
(not-any? pos? [1 2])
(not-any? pos? [1 2 3 4 5])
(not-any? pos? [-1])
(not-any? pos? [-1 -2])
(not-any? pos? [-1 -2 3])
(not-any? pos? [-1 2])
(not-any? pos? [1 -2])
(not-any? pos? [1 2 -3])
(not-any? pos? [1 2 -3 4])
(not-any? #{:a} [:a :a])
(not-any? #{:a} [:a :b])
(not-any? #{:a} [:b :b])
(some pos? nil)
(some pos? ())
(some pos? [])
(some pos? {})
(some pos? #{})
(some pos? (lazy-seq []))
(some pos? (into-array []))
(some nil nil)
(some pos? [1])
(some pos? [1 2])
(some pos? [-1])
(some pos? [-1 -2])
(some pos? [-1 2])
(some pos? [1 -2])
(some #{:a} [:a :a])
(some #{:a} [:b :a])
(some #{:a} [:b :b])
(some #{:a} (quote (:a :b)))
(some #{:a} #{:b :a})
(flatten nil)
(flatten 1)
(flatten (quote test))
(flatten :keyword)
(flatten 1/2)
(flatten #"[\r\n]")
(flatten true)
(flatten false)
(flatten [[1 2] [3 4 [5]]])
(flatten [1 2 3 4 5])
(flatten [#{1 2} 3 4 5])
(flatten #{})
(flatten #{4 3 5 #{1 2}})
(flatten #{1 4 3 2 5})
(flatten (quote ()))
(flatten (arbace.core/seq (arbace.core/concat (arbace.core/list 1) (arbace.core/list 2) (arbace.core/list 3) (arbace.core/list 4) (arbace.core/list 5))))
(flatten {:a 1, :b 2})
(flatten (sort-by key {:a 1, :b 2}))
(flatten {[:a :b] 1, :c 2})
(flatten (sort-by val {[:a :b] 1, :c 2}))
(flatten (sort-by key {:a [1 2], :b 3}))
(flatten "12345")
(flatten (seq "12345"))
(flatten count)
(group-by even? [1 2 3 4 5])
(partition-by (comp even? count) ["a" "bb" "cccc" "dd" "eee" "f" "" "hh"])
(partition-by (comp even? count) (quote ("a" "bb" "cccc" "dd" "eee" "f" "" "hh")))
(partition-by #{\a \e \i \o \u} "abcdefghijklm")
(first (second (partition-by zero? (range))))
(frequencies "mississippi")
(frequencies [1 1 1 1 2 2 3])
(frequencies (quote (1 1 1 1 2 2 3)))
(reductions + nil)
(reductions + [1 2 3 4 5])
(reductions + 10 [1 2 3 4 5])
(reductions (constantly (reduced :x)) (range))
(reductions (fn [acc x] x) (reduced :x) (range))
(reductions (fn [acc x] (if (= x :stop) (reduced acc) (+ acc x))) [2 4 6 :stop 8 10])
(partition-all 4 [1 2 3 4 5 6 7 8 9])
(partition-all 4 2 [1 2 3 4 5 6 7 8 9])
(partitionv-all 4 [1 2 3 4 5 6 7 8 9])
(partitionv-all 4 2 [1 2 3 4 5 6 7 8 9])
((fn [& args] (apply (fn [a & b] (apply list b)) args)) 1 2 3)
(meta (sort (with-meta (range 10) {:a true})))
(meta (sort-by :a (with-meta (seq [{:a 5} {:a 2} {:a 3}]) {:a true})))
(and (= [:init] (reduce conj [:init] (seq []))) (= [] (reduce conj (seq []))))
(and (= [:init 1] (reduce conj [:init] (seq [1]))) (= 1 (reduce conj (seq [1]))))
(and (= [:init [1] 2] (reduce conj [:init] (seq [[1] 2]))) (= [1 2] (reduce conj (seq [[1] 2]))))
(and (= [:init] (reduce conj [:init] (seq {}))) (= [] (reduce conj (seq {}))))
(and (= [:init [1 1]] (reduce conj [:init] (seq {1 1}))) (= [1 1] (reduce conj (seq {1 1}))))
(and (= [:init [1 1] [2 2]] (reduce conj [:init] (seq {1 1, 2 2}))) (= [1 1 [2 2]] (reduce conj (seq {1 1, 2 2}))))
(and (= [:init] (reduce conj [:init] (seq (hash-map)))) (= [] (reduce conj (seq (hash-map)))))
(and (= [:init [1 1]] (reduce conj [:init] (seq (hash-map 1 1)))) (= [1 1] (reduce conj (seq (hash-map 1 1)))))
(and (= [:init [1 1] [2 2]] (reduce conj [:init] (seq (hash-map 1 1 2 2)))) (= [1 1 [2 2]] (reduce conj (seq (hash-map 1 1 2 2)))))
(and (= [:init] (reduce conj [:init] (seq (sorted-map)))) (= [] (reduce conj (seq (sorted-map)))))
(and (= [:init [1 1]] (reduce conj [:init] (seq (sorted-map 1 1)))) (= [1 1] (reduce conj (seq (sorted-map 1 1)))))
(and (= [:init [1 1] [2 2]] (reduce conj [:init] (seq (sorted-map 1 1 2 2)))) (= [1 1 [2 2]] (reduce conj (seq (sorted-map 1 1 2 2)))))
(and (= 100 (reduce + 100 (seq (range 0)))) (= 0 (reduce + (seq (range 0)))))
(and (= 101 (reduce + 100 (seq (range 1 2)))) (= 1 (reduce + (seq (range 1 2)))))
(and (= 103 (reduce + 100 (seq (range 1 3)))) (= 3 (reduce + (seq (range 1 3)))))
(.hashCode (iterate identity nil))
(.hashCode (cycle [1]))
(.hashCode (repeat 1))
(.hasheq (iterate identity nil))
(.hasheq (cycle [1]))
(.hasheq (repeat 1))
