;; Harvested by bin/oracle harvest (test/oracle/harvest.clj) from Clojure's test suite,
;; clojure/clojure 98d735fab02f337cee654cb0629bddc09883a75a test/clojure/test_clojure/string.clj,
;; renamed to arbace.* by bin/clojure-tests: the expressions of its assertions that are
;; self-contained and deterministic. Eclipse Public License 1.0 (LICENSE.md). Do not edit.
(require (quote [arbace.string :as s]))
(s/split "a-b" #"-")
(s/split "a-b-c" #"-" 2)
(vector? (s/split "abc" #"-"))
(s/reverse "bat")
(s/replace "foobar" \o \a)
(s/replace "foobar" \z \a)
(s/replace "foobarfoo" "foo" "bar")
(s/replace "foobarfoo" "baz" "bar")
(s/replace "food" "o" "$")
(s/replace "food" "o" "\\")
(s/replace "foobarfoo" #"foo" "bar")
(s/replace "foobarfoo" #"baz" "bar")
(s/replace "food" #"o" (s/re-quote-replacement "$"))
(s/replace "food" #"o" (s/re-quote-replacement "\\"))
(s/replace "foobarfoo" #"foo" s/upper-case)
(s/replace "foobarfoo" #"baz" s/upper-case)
(s/replace "foobarfoo" #"f(o+)" (fn [[m g1]] (s/upper-case g1)))
(s/replace "bazslashbangslash" #"slash" (constantly "\\"))
(s/replace-first "foobar" \o \a)
(s/replace-first "foobar" \z \a)
(s/replace-first "zoology" \o \.)
(s/replace-first "foobarfoo" "foo" "bar")
(s/replace-first "foobarfoo" "baz" "bar")
(s/replace-first "food" "o" "$")
(s/replace-first "food" "o" "\\")
(s/replace-first "foobarfoo" #"foo" "bar")
(s/replace-first "foobarfoo" #"baz" "bar")
(s/replace-first "food" #"o" (s/re-quote-replacement "$"))
(s/replace-first "food" #"o" (s/re-quote-replacement "\\"))
(s/replace-first "foobarfoo" #"foo" s/upper-case)
(s/replace-first "foobarfoo" #"baz" s/upper-case)
(s/replace-first "foobarfoo" #"f(o+)" (fn [[m g1]] (s/upper-case g1)))
(s/replace-first "bazslashbangslash" #"slash" (constantly "\\"))
(s/join nil)
(s/join [])
(s/join [1])
(s/join [1 2])
(s/join \, [1 2 3])
(s/join \, [])
(s/join \, [1])
(s/join " and-a " [1 2 3])
(s/trim-newline "foo\n")
(s/trim-newline "foo\r\n")
(s/trim-newline "foo")
(s/trim-newline "")
(s/capitalize "foobar")
(s/capitalize "FOOBAR")
(s/triml " foo ")
(s/triml "   ")
(s/triml "  \tbar")
(s/trimr " foo ")
(s/trimr "   ")
(s/trimr "bar\t  ")
(s/trim "  foo  \r\n")
(s/trim " bar\t  ")
(s/upper-case "Foobar")
(s/lower-case "FooBar")
(apply s/reverse [nil])
(apply s/replace [nil #"foo" "bar"])
(apply s/replace-first [nil #"foo" "bar"])
(apply s/re-quote-replacement [nil])
(apply s/capitalize [nil])
(apply s/upper-case [nil])
(apply s/lower-case [nil])
(apply s/split [nil #"-"])
(apply s/split [nil #"-" 1])
(apply s/trim [nil])
(apply s/triml [nil])
(apply s/trimr [nil])
(apply s/trim-newline [nil])
(let [[^CharSequence s & more] ["zap"]] (= "paz" (apply s/reverse (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["foo-bar" \- \:]] (= "foo:bar" (apply s/replace (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["abc" #"\w" s/upper-case]] (= "ABC" (apply s/replace (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["foo" #"o" (StringBuffer. "a")]] (= "faa" (apply s/replace (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["baz--quux" #"--" "::"]] (= "baz::quux" (apply s/replace-first (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["baz--quux" (StringBuffer. "--") (StringBuffer. "::")]] (= "baz::quux" (apply s/replace-first (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["zim zam" #" " (StringBuffer. "-")]] (= "zim-zam" (apply s/replace-first (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["\\ $"]] (= "\\\\ \\$" (apply s/re-quote-replacement (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["POW"]] (= "Pow" (apply s/capitalize (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["boom"]] (= "BOOM" (apply s/upper-case (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["whimPER"]] (= "whimper" (apply s/lower-case (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["foo-bar" #"-"]] (= ["foo" "bar"] (apply s/split (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["  calvino  "]] (= "calvino" (apply s/trim (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["  calvino  "]] (= "calvino  " (apply s/triml (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["  calvino  "]] (= "  calvino" (apply s/trimr (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["the end\r\n\r\r\n"]] (= "the end" (apply s/trim-newline (StringBuffer. s) more)))
(let [[^CharSequence s & more] [" "]] (= true (apply s/blank? (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["a\nb"]] (= ["a" "b"] (apply s/split-lines (StringBuffer. s) more)))
(let [[^CharSequence s & more] ["fo lo lo" {\o \a}]] (= "fa la la" (apply s/escape (StringBuffer. s) more)))
(s/escape "<foo&bar>" {\& "&amp;", \< "&lt;", \> "&gt;"})
(s/escape " \"foo\" " {\" "\\\""})
(s/escape "foobar" {\a \o, \o \a})
(s/blank? nil)
(s/blank? "")
(s/blank? " ")
(s/blank? " \t \n  \r ")
(not (s/blank? "  foo  "))
(list "foo")
(s/split-lines "foo")
(s/starts-with? (StringBuffer. "clojure west") "clojure")
(not (s/starts-with? (StringBuffer. "conj") "clojure"))
(s/ends-with? (StringBuffer. "Clojure West") "West")
(not (s/ends-with? (StringBuffer. "Conj") "West"))
(str ())
(str {})
(str [])
