;; Harvested by bin/oracle harvest (test/oracle/harvest.clj) from Clojure's test suite,
;; clojure/clojure 98d735fab02f337cee654cb0629bddc09883a75a test/clojure/test_clojure/transducers.clj,
;; renamed to arbace.* by bin/clojure-tests: the expressions of its assertions that are
;; self-contained and deterministic. Eclipse Public License 1.0 (LICENSE.md). Do not edit.
(require (quote [arbace.string :as s]))
(transduce (dedupe) conj [])
(transduce (dedupe) conj [1])
(transduce (dedupe) conj [1 2 3])
(transduce (dedupe) conj [1 2 3 1 2 2 1 1])
(transduce (dedupe) conj [1 1 1 2])
(transduce (dedupe) conj [1 1 1 1])
(transduce (dedupe) conj "")
(transduce (dedupe) conj "a")
(transduce (dedupe) conj "aaaa")
(transduce (dedupe) conj "aabaa")
(transduce (dedupe) conj "abba")
(transduce (dedupe) conj [nil nil nil])
(transduce (dedupe) conj [1 1.0 1.0M 1N])
(transduce (dedupe) conj [0.5 0.5])
(transduce cat conj [])
(transduce cat conj [[1 2]])
(transduce cat conj [[1 2] [3 4]])
(transduce cat conj [[] [3 4]])
(transduce cat conj [[1 2] []])
(transduce cat conj [[] []])
(transduce cat conj [[1 2] [3 4] [5 6]])
(transduce (partition-all 2) conj [1 2 3])
(transduce (partition-all 2) conj [1 2 3 4])
(transduce (partition-all 2) conj [])
()
(transduce (partition-all 1) conj [])
(transduce (partition-all 1) conj [1 2 3])
(transduce (partition-all 5) conj [1 2 3])
(transduce (take 1) conj [1 2 3 4 5])
(transduce (take 3) conj [1 2 3 4 5])
(transduce (take 5) conj [1 2 3 4 5])
(transduce (take 9) conj [1 2 3 4 5])
(transduce (take 0) conj [1 2 3 4 5])
(transduce (take -1) conj [1 2 3 4 5])
(transduce (take -2) conj [1 2 3 4 5])
(transduce (drop 1) conj [1 2 3 4 5])
(transduce (drop 3) conj [1 2 3 4 5])
(transduce (drop 5) conj [1 2 3 4 5])
(transduce (drop 9) conj [1 2 3 4 5])
(transduce (drop 0) conj [1 2 3 4 5])
(transduce (drop -1) conj [1 2 3 4 5])
(transduce (drop -2) conj [1 2 3 4 5])
(transduce (take-nth 1) conj [1 2 3 4 5])
(transduce (take-nth 2) conj [1 2 3 4 5])
(transduce (take-nth 3) conj [1 2 3 4 5])
(transduce (take-nth 4) conj [1 2 3 4 5])
(transduce (take-nth 5) conj [1 2 3 4 5])
(transduce (take-nth 9) conj [1 2 3 4 5])
(transduce (take-while pos?) conj [])
(transduce (take-while pos?) conj [1 2 3 4])
(transduce (take-while pos?) conj [1 2 3 -1])
(transduce (take-while pos?) conj [1 -1 2 3])
(transduce (take-while pos?) conj [-1 1 2 3])
(transduce (take-while pos?) conj [-1 -2 -3])
(transduce (drop-while pos?) conj [])
(transduce (drop-while pos?) conj [1 2 3 4])
(transduce (drop-while pos?) conj [1 2 3 -1])
(transduce (drop-while pos?) conj [1 -1 2 3])
(transduce (drop-while pos?) conj [-1 1 2 3])
(transduce (drop-while pos?) conj [-1 -2 -3])
(transduce (take 1) conj [:a])
(transduce (comp (take 1) (take 1)) conj [:a])
(transduce (comp (take 1) (take 1) (take 1)) conj [:a])
(transduce (comp (take 1) (take 1) (take 1) (take 1)) conj [:a])
(transduce (comp (partition-by keyword?) (take 1)) conj [] [:a])
(sequence (comp (partition-by keyword?) (take 1)) [:a])
(sequence (comp (partition-by keyword?) (take 1) (partition-by keyword?) (take 1)) [:a])
(transduce (comp (take 1) (partition-all 3) (take 1)) conj [] (range 15))
(transduce (take 1) conj (seq (long-array [1 2 3 4])))
(sequence (map +) [1 2 3 4] (repeat 10))
(sequence (map +) (repeat 10) [1 2 3 4])
(sequence (map +) (repeat 10) (repeat 20) [1 2 3 4])
(eduction (map inc) (range 5))
(eduction (map inc) (filter even?) (map str) (range 5))
(->> (range 5) (eduction (mapcat range) (map inc)) sort)
(vec (->> (range 5) (eduction (mapcat range) (map inc)) to-array))
(->> (range 5) (eduction (mapcat range) (map inc)) frequencies)
(->> ["cat" "dog" "fish" "bird" "aardvark"] (eduction (map arbace.string/reverse)) (sort-by first))
(eduction cat [[1 2 3 nil] [4 5 6 nil]])
(into [] (comp cat (partition-all 3)) (eduction (partition-all 5) (range 8)))
(nil? (run! identity [1]))
(nil? (run! reduced (range)))
(sequence (distinct []))
(sequence (distinct) [])
(range 10)
(sequence (distinct (range 10)))
(sequence (distinct) (range 10))
(sequence (distinct (repeat 10 0)))
(sequence (distinct) (repeat 10 0))
(sequence (distinct [0 0 1 1 2 2 1 1 0 0]))
(sequence (distinct) [0 0 1 1 2 2 1 1 0 0])
(sequence (distinct [1 1N]))
(sequence (distinct) [1 1N])
(sequence (interpose :s) (range 0))
(sequence (interpose :s) (range 1))
(sequence (interpose :s) (range 2))
(sequence (interpose :s) (range 3))
(sequence (map-indexed vector) [])
(sequence (map-indexed vector) (range 1 5))
(into [] (comp (filter some?) (halt-when #{:anomaly})) [1 2 3 :anomaly 4])
(into [] (halt-when :anomaly (fn* [p1__1261# p2__1260#] (assoc p2__1260# :partial-results p1__1261#))) [1 2 {:anomaly :oh-no!} 3 4])
