;; Harvested by bin/oracle harvest (test/oracle/harvest.clj) from Clojure's test suite,
;; clojure/clojure 98d735fab02f337cee654cb0629bddc09883a75a test/clojure/test_clojure/vectors.clj,
;; renamed to arbace.* by bin/clojure-tests: the expressions of its assertions that are
;; self-contained and deterministic. Eclipse Public License 1.0 (LICENSE.md). Do not edit.
(import (quote (java.util Collection Spliterator)))
(import (quote (java.util.function Consumer)))
(import (quote (java.util.stream Collectors)))
(.cons (seq (into (vector-of :int) [1])) :foo)
(let [prim-vec (into (vector-of :long) (range 1000))] (reduce + (subvec prim-vec 10 15)))
(arbace.lang.MapEntry. 0 1)
(arbace.lang.MapEntry. 2 3)
(arbace.lang.MapEntry. 4 5)
(and (empty? (vector-of :boolean)) (instance? arbace.core.Vec (vector-of :boolean)))
(and (empty? (vector-of :byte)) (instance? arbace.core.Vec (vector-of :byte)))
(and (empty? (vector-of :short)) (instance? arbace.core.Vec (vector-of :short)))
(and (empty? (vector-of :int)) (instance? arbace.core.Vec (vector-of :int)))
(and (empty? (vector-of :long)) (instance? arbace.core.Vec (vector-of :long)))
(and (empty? (vector-of :float)) (instance? arbace.core.Vec (vector-of :float)))
(and (empty? (vector-of :double)) (instance? arbace.core.Vec (vector-of :double)))
(and (empty? (vector-of :char)) (instance? arbace.core.Vec (vector-of :char)))
(vector-of nil)
(vector-of Float/TYPE)
(vector-of (quote int))
(vector-of :integer)
(vector-of "")
(and (instance? arbace.core.Vec (vector-of :int 1)) (= (into (vector-of :int) [1]) (vector-of :int 1)) (= [1] (vector-of :int 1)) (= (hash [1]) (hash (vector-of :int 1))))
(and (instance? arbace.core.Vec (vector-of :int 1 2)) (= (into (vector-of :int) [1 2]) (vector-of :int 1 2)) (= [1 2] (vector-of :int 1 2)) (= (hash [1 2]) (hash (vector-of :int 1 2))))
(and (instance? arbace.core.Vec (vector-of :int 1 2 3)) (= (into (vector-of :int) [1 2 3]) (vector-of :int 1 2 3)) (= [1 2 3] (vector-of :int 1 2 3)) (= (hash [1 2 3]) (hash (vector-of :int 1 2 3))))
(and (instance? arbace.core.Vec (vector-of :int 1 2 3 4)) (= (into (vector-of :int) [1 2 3 4]) (vector-of :int 1 2 3 4)) (= [1 2 3 4] (vector-of :int 1 2 3 4)) (= (hash [1 2 3 4]) (hash (vector-of :int 1 2 3 4))))
(and (instance? arbace.core.Vec (vector-of :int 1 2 3 4 5)) (= (into (vector-of :int) [1 2 3 4 5]) (vector-of :int 1 2 3 4 5)) (= [1 2 3 4 5] (vector-of :int 1 2 3 4 5)) (= (hash [1 2 3 4 5]) (hash (vector-of :int 1 2 3 4 5))))
(and (instance? arbace.core.Vec (vector-of :int 1 2 3 4 5 6)) (= (into (vector-of :int) [1 2 3 4 5 6]) (vector-of :int 1 2 3 4 5 6)) (= [1 2 3 4 5 6] (vector-of :int 1 2 3 4 5 6)) (= (hash [1 2 3 4 5 6]) (hash (vector-of :int 1 2 3 4 5 6))))
(and (instance? arbace.core.Vec (apply vector-of :int (range 1000))) (= (into (vector-of :int) (apply vector (range 1000))) (apply vector-of :int (range 1000))) (= (apply vector (range 1000)) (apply vector-of :int (range 1000))) (= (hash (apply vector (range 1000))) (hash (apply vector-of :int (range 1000)))))
(and (instance? arbace.core.Vec (vector-of :int 1M 2.0 3.1)) (= (into (vector-of :int) [1 2 3]) (vector-of :int 1M 2.0 3.1)) (= [1 2 3] (vector-of :int 1M 2.0 3.1)) (= (hash [1 2 3]) (hash (vector-of :int 1M 2.0 3.1))))
(and (instance? arbace.core.Vec (vector-of :int \a \b \c)) (= (into (vector-of :int) [97 98 99]) (vector-of :int \a \b \c)) (= [97 98 99] (vector-of :int \a \b \c)) (= (hash [97 98 99]) (hash (vector-of :int \a \b \c))))
(vector-of :int nil)
(vector-of :int 1 nil)
(vector-of :int 1 2 nil)
(vector-of :int 1 2 3 nil)
(vector-of :int 1 2 3 4 nil)
(vector-of :int 1 2 3 4 5 nil)
(vector-of :int 1 2 3 4 5 6 nil)
(vector-of :int true)
(vector-of :int 1 2 3 4 5 false)
(vector-of :int {:a 1, :b 2})
(vector-of :int [1 2 3 4] [5 6])
(vector-of :int (quote (1 2 3 4)))
(vector-of :int #{1 4 3 2})
(vector-of :int (sorted-set 1 2 3 4))
(vector-of :int 1 2 "3")
(vector-of :int "1" "2" "3")
(instance? arbace.lang.IPersistentVector (vector-of :int 1 2 3))
(instance? arbace.lang.IPersistentVector (vector-of :double 1 2 3))
(.length (vector-of :int 1 2 3))
(.length (vector-of :double 1 2 3))
(vec (first {1 2}))
(vec [0 1 2 3])
(vec (list 0 1 2 3))
(vec (sorted-set 0 1 2 3))
(vec (sorted-map 1 2 3 4))
(vec (range 4))
(vec "abcd")
(vec (object-array (range 4)))
(vec (eduction (map inc) (range 4)))
(vec (reify arbace.lang.IReduceInit (reduce [_ f start] (reduce f start (range 4)))))
(reduce-kv + 10 [2 4 6])
(reduce-kv + 10 (subvec [0 2 4 6] 1))
(take 3 (range))
(new java.util.ArrayList [0 1 2])
(take 1 (cycle [1 2]))
(eduction cat [[1 2 3 nil] [4 5 6 nil]])
