;; The image of prepared namespaces (B1a step 6, doc/go/EXEC-NOTES.md): the encoding of the
;; analyzed forms of the namespaces embedded in the program (Compiler$Image's natives, through
;; jrt.Image). Part of the program's main package, which knows every type of the program
;; (image_types.go, generated by c2g --program). Written as Go and converted with g2c
;; (bin/g2c convert's arbace.g2c.main on a godump of the package), positions dropped.
(in-ns 'go.arbace.cmd.arbace) (go/file "image.go" :imports [


    [bytes "bytes"]
    [binary "encoding/binary"]
    [fmt "fmt"]
    [math "math"]
    [os "os"]
    [reflect "reflect"]
    [debug "runtime/debug"]
    [sort "sort"]
    [strings "strings"]
    [sync "sync"]
    [time "time"]
    [unsafe "unsafe"]

    [jrt "arbace/jrt"]
    [lang "arbace/lang"]])


;; The image of prepared namespaces (Compiler$Image; doc/go/EXEC-NOTES.md).

(go/const ^{:val "ARBACE-IMAGE-1\n"} imageMagic "ARBACE-IMAGE-1\n")

(go/const
  [^{:val 0} tNil iota]
  [^{:val 1} tRef]
  [^{:val 2} tObj]
  [^{:val 3} tStr]
  [^{:val 4} tLong]
  [^{:val 5} tInt]
  [^{:val 6} tDouble]
  [^{:val 7} tTrue]
  [^{:val 8} tFalse]
  [^{:val 9} tChar]
  [^{:val 10} tShort]
  [^{:val 11} tByte]
  [^{:val 12} tFloat]
  [^{:val 13} tKeyword]
  [^{:val 14} tVar]
  [^{:val 15} tNs]
  [^{:val 16} tClass]
  [^{:val 17} tMethod]
  [^{:val 18} tCtor]
  [^{:val 19} tField]
  [^{:val 20} tRefArray]
  [^{:val 21} tPrimArray]
  [^{:val 22} tStatic]
  [^{:val 23} tPattern]
  [^{:val 24} tSymbol]
  [^{:val 25} tMapRebuild]
  [^{:val 26} tSetRebuild]
  [^{:val 27} tLazySeq]
  [^{:val 28} tAtomicRef]
  [^{:val 29} tAtomicInt]
  [^{:val 30} tAtomicBool]
  [^{:val 31} tPlainObj])


(go/var plainObjectType (reflect/TypeOf (jrt/Object_New)))

;; ---------------------------------------------------------------------------------------
;; Types and their plans

(go/var ^{:tag (map string reflect/Type)} imageTypes)

(go/func registerImageTypes [^{:tag (slice reflect/Type)} ts]
  (set! imageTypes (make (map string reflect/Type) (len ts)))
  (range [_ t ts]
    (aset imageTypes (.String t) t)))



(go/type fieldPlan (struct
    ^{:tag (slice int)} index
    ^{:tag uintptr} off ; the field's offset in the struct (decoding writes it directly)
    ^{:tag reflect/Type} t
    ^{:tag reflect/Kind} kind
    ^{:tag bool} zero)) ; a cached hash: not encoded, zero when decoded


(go/type typePlan (struct
    ^{:tag reflect/Type} t
    ^{:tag (slice fieldPlan)} fields
    ^{:tag string} err
    ^{:tag bool} inited)) ; the class's static initialization ran (decoding)


(go/var
  [^sync/Mutex plansMu]
  [plans (lit (map reflect/Type (* typePlan)))]
  [objectType (reflect/TypeOf (lit jrt/Object))])






(go/var ^{:doc "imageSkipped are the fields the analysis fills for the bytecode back end only, which the Go\nbuild's evaluator never reads: not encoded, nil when decoded. ObjExpr.src, the fn's or type's\nwhole form, is read by ObjExpr.compile's class generation; the clearing paths by emit's\nlocals clearing\n"} imageSkipped (lit (map string bool)
    ["Compiler_ObjExpr.F_src" true]
    ["Compiler_LocalBindingExpr.F_clearPath" true]
    ["Compiler_LocalBindingExpr.F_clearRoot" true]))


(go/func planOf ^{:tag (* typePlan)} [^reflect/Type t]
  (.Lock plansMu)
  (defer (.Unlock plansMu))
  (when [(values p ok) (aget plans t)] ok
    (return p))

  (let [p (addr (lit typePlan :t t))
      ^{:tag (func [^reflect/Type t ^{:tag (slice int)} prefix ^uintptr base])} walk (zero (func [^reflect/Type t ^{:tag (slice int)} prefix ^uintptr base]))]
    (set! walk (fn [^reflect/Type t ^{:tag (slice int)} prefix ^uintptr base]
        (for [i 0] (< i (.NumField t)) (inc! i)
          (let [f (.Field t i)
              idx (append (append (conv (slice int) nil) (spread prefix)) i)]
            (when (and (.-Anonymous f) (== (.-Type f) objectType))
              (continue))

            (when (and (.-Anonymous f) (== (.Kind (.-Type f)) reflect/Struct))
              (walk (.-Type f) idx (+ base (.-Offset f)))
              (continue))

            (when (not (.IsExported f))
              (set! (.-err p) (fmt/Sprintf "unexported field %s of %s" (.-Name f) t))
              (return))

            (switch (.Kind (.-Type f))
              (case [reflect/Interface reflect/Pointer reflect/Bool reflect/Int8 reflect/Int16
                  reflect/Int32 reflect/Int64 reflect/Uint16 reflect/Float32 reflect/Float64]
                (set! (.-fields p) (append (.-fields p) (lit fieldPlan :index idx :off (+ base (.-Offset f)) :t (.-Type f)
                      :kind (.Kind (.-Type f)) :zero (or (== (.-Name f) "F__hash") (== (.-Name f) "F__hasheq")
                        (aget imageSkipped (+ (.Name t) "." (.-Name f))))))))
              (default
                (set! (.-err p) (fmt/Sprintf "field %s of %s has type %s" (.-Name f) t (.-Type f)))
                (return)))))))



    (walk t nil 0)
    (aset plans t p)
    p))


;; ---------------------------------------------------------------------------------------
;; Canonical objects: statics the decoded graph must share with the running program

(go/var
  [^sync/Once staticsOnce]
  [^{:tag (slice any)} statics]
  [^{:tag (map any int)} staticIdx])


(go/func initStatics []
  (.Do staticsOnce (fn []
      (lang/PersistentList_Init)
      (lang/PersistentVector_Init)
      (lang/PersistentArrayMap_Init)
      (lang/PersistentHashMap_Init)
      (lang/PersistentHashSet_Init)
      (lang/PersistentTreeMap_Init)
      (lang/PersistentTreeSet_Init)
      (lang/PersistentQueue_Init)
      (lang/Compiler_Init)
      (lang/RT_Init)
      (set! statics (lit (slice any)
          lang/PersistentList_EMPTY lang/PersistentVector_EMPTY lang/PersistentVector_EMPTY_NODE
          lang/PersistentArrayMap_EMPTY lang/PersistentHashMap_EMPTY lang/PersistentHashSet_EMPTY
          lang/PersistentTreeMap_EMPTY lang/PersistentTreeSet_EMPTY lang/PersistentQueue_EMPTY
          lang/Compiler_NIL_EXPR lang/Compiler_TRUE_EXPR lang/Compiler_FALSE_EXPR
          lang/RT_EMPTY_ARRAY lang/PersistentHashMap_NOT_FOUND))

      (set! staticIdx (make (map any int) (len statics)))
      (range [i s statics]
        (when (!= s nil)
          (aset staticIdx s i))))))





;; ---------------------------------------------------------------------------------------
;; The encoder: one per source, its objects numbered in order of first encounter

(go/type encoder (struct
    ^{:tag string} name
    ^{:tag bytes/Buffer} buf
    ^{:tag (map any int)} ids
    ^{:tag int} nobj
    ^{:tag (map string int)} strs
    ^{:tag (map reflect/Type int)} types
    ^{:tag (map string int)} counts
    ^{:tag (slice string)} path


    ^{:tag (map string bool) :doc "the classes the unit being encoded makes (its events): referred to by name only once\ntheir event is made again\n"} defined
    ^{:tag (array binary/MaxVarintLen64 byte)} tmp))


(go/method fail [^{:tag (* encoder)} e ^string msg]
  (let [n (len (.-path e))
      from 0]
    (when (> n 12)
      (set! from (- n 12)))

    (panic (fmt/Sprintf "image: %s: %s (in %s)" (.-name e) msg (strings/Join (subslice (.-path e) from) " < ")))))


(go/func newEncoder ^{:tag (* encoder)} [^string name]
  (initStatics)
  (addr (lit encoder :name name :ids (lit (map any int)) :strs (lit (map string int))
      :types (lit (map reflect/Type int)) :counts (lit (map string int)))))


(go/method b [^{:tag (* encoder)} e ^byte x] (.WriteByte (.-buf e) x))
(go/method uv [^{:tag (* encoder)} e ^uint64 x] (.Write (.-buf e) (subslice (.-tmp e) _ (binary/PutUvarint (subslice (.-tmp e)) x))))
(go/method sv [^{:tag (* encoder)} e ^int64 x] (.Write (.-buf e) (subslice (.-tmp e) _ (binary/PutVarint (subslice (.-tmp e)) x))))


(go/method str "a Go string through the source's table\n" [^{:tag (* encoder)} e ^string s]
  (when [(values i ok) (aget (.-strs e) s)] ok
    (.uv e (conv uint64 i))
    (return))

  (let [i (len (.-strs e))]
    (aset (.-strs e) s i)
    (.uv e (conv uint64 i))
    (.uv e (conv uint64 (len s)))
    (.WriteString (.-buf e) s)))



(go/method jstr "a nullable Java string as a table string (absent: index 0 reserved? no: a flag byte)\n" [^{:tag (* encoder)} e ^{:tag (* jrt/String)} s]
  (when (== s nil)
    (.b e 0)
    (return))

  (.b e 1)
  (.str e (.String s)))


(go/method newID [^{:tag (* encoder)} e ^any x]
  (aset (.-ids e) x (.-nobj e))
  (inc! (.-nobj e)))


(go/func className ^string [^{:tag (* jrt/Class)} c] (.String (.GetName__String c)))

(go/method value [^{:tag (* encoder)} e ^any x]
  (when (== x nil)
    (.b e tNil)
    (return))

  (when [rv (reflect/ValueOf x)] (and (== (.Kind rv) reflect/Pointer) (.IsNil rv))
    (.b e tNil)
    (return))

  (when [(values id ok) (aget (.-ids e) x)] ok
    (.b e tRef)
    (.uv e (conv uint64 id))
    (return))

  (when [(values i ok) (aget staticIdx x)] ok
    (.b e tStatic)
    (.uv e (conv uint64 i))
    (return))

  (type-switch [v x]
    (case [(* jrt/Boolean)]
      (if (.-F_value v)
        (.b e tTrue)

        (.b e tFalse))

      (return))
    (case [(* jrt/Long)]
      (.b e tLong)
      (.sv e (.-F_value v))
      (return))
    (case [(* jrt/Integer)]
      (.b e tInt)
      (.sv e (conv int64 (.-F_value v)))
      (return))
    (case [(* jrt/Short)]
      (.b e tShort)
      (.sv e (conv int64 (.-F_value v)))
      (return))
    (case [(* jrt/Byte)]
      (.b e tByte)
      (.sv e (conv int64 (.-F_value v)))
      (return))
    (case [(* jrt/Character)]
      (.b e tChar)
      (.uv e (conv uint64 (.-F_value v)))
      (return))
    (case [(* jrt/Double)]
      (.b e tDouble)
      (.uv e (math/Float64bits (.-F_value v)))
      (return))
    (case [(* jrt/Float)]
      (.b e tFloat)
      (.uv e (conv uint64 (math/Float32bits (.-F_value v))))
      (return))
    (case [(* jrt/String)]
      (.newID e x)
      (.b e tStr)
      (.str e (.String v))
      (inc! (aget (.-counts e) "String"))
      (return))
    (case [(* lang/Keyword)]
      (.newID e x)
      (.b e tKeyword)
      (.jstr e (.-F_ns (.-F_sym v)))
      (.str e (.String (.-F_name (.-F_sym v))))
      (return))
    (case [(* lang/Symbol)]
      (.newID e x)
      (.b e tSymbol)
      (.jstr e (.-F_ns v))
      (.str e (.String (.-F_name v)))
      (.value e (.-F__meta v))
      (inc! (aget (.-counts e) "Symbol"))
      (return))
    (case [(* lang/Var)]
      (when (== (.-F_ns v) nil)
        (panic (fmt/Sprintf "image: %s: a Var without a namespace (%v)" (.-name e) (.-F_sym v))))

      (.newID e x)
      (.b e tVar)
      (.str e (.String (.-F_name (.-F_name (.-F_ns v)))))
      (.str e (.String (.-F_name (.-F_sym v))))
      (return))
    (case [(* lang/Namespace)]
      (.newID e x)
      (.b e tNs)
      (.str e (.String (.-F_name (.-F_name v))))
      (return))
    (case [(* jrt/Class)]
      (.newID e x)
      (.b e tClass)
      (.classRef e v)
      (return))
    (case [(* jrt/Method)]
      (.newID e x)
      (.b e tMethod)
      (.member e ^{:go/via [Executable]} (.GetDeclaringClass__Class v) (.String (.GetName__String v)) ^{:go/via [Executable]} (.GetParameterTypes__Class1 v))
      (.classRef e (.GetReturnType__Class v))
      (return))
    (case [(* jrt/Constructor)]
      (.newID e x)
      (.b e tCtor)
      (.member e ^{:go/via [Executable]} (.GetDeclaringClass__Class v) "" ^{:go/via [Executable]} (.GetParameterTypes__Class1 v))
      (return))
    (case [(* jrt/Field)]
      (.newID e x)
      (.b e tField)
      (.member e (.GetDeclaringClass__Class v) (.String (.GetName__String v)) nil)
      (return))
    (case [(* jrt/Pattern)]
      (.newID e x)
      (.b e tPattern)
      (.str e (.String (.-F_pattern v)))
      (.sv e (conv int64 (.-F_flags0 v)))
      (return))
    (case [(* jrt/RefArray)]
      (.newID e x)
      (.b e tRefArray)
      (.classRef e (.-Comp v))
      (.uv e (conv uint64 (len (.-A v))))
      (range [_ y (.-A v)]
        (.value e y))

      (inc! (aget (.-counts e) "Object[]"))
      (return))
    (case [(* jrt/ByteArray) (* jrt/CharArray) (* jrt/IntArray) (* jrt/LongArray) (* jrt/ShortArray)
        (* jrt/BooleanArray) (* jrt/FloatArray) (* jrt/DoubleArray)]
      (.newID e x)
      (.b e tPrimArray)
      (.primArray e x)
      (return))
    (case [(* jrt/AtomicReference)]
      (when [(values _ ok) (assert (* jrt/Thread) (.Get__O v))] ok
        (.fail e "an AtomicReference holding a Thread (a transient being edited)"))

      (.newID e x)
      (.b e tAtomicRef)
      (.value e (.Get__O v))
      (return))
    (case [(* jrt/AtomicInteger)]
      (.newID e x)
      (.b e tAtomicInt)
      (.sv e (conv int64 (.Get__I v)))
      (return))
    (case [(* jrt/AtomicBoolean)]
      (.newID e x)
      (.b e tAtomicBool)
      (if (.Get__Z v)
        (.b e 1)

        (.b e 0))

      (return))
    (case [(* lang/LazySeq)]
      (.newID e x)
      (.b e tLazySeq)
      (.value e ^{:go/via [Obj]} (.-F__meta v))
      (.value e (.Seq__ISeq v))
      (inc! (aget (.-counts e) "LazySeq"))
      (return))
    (case [(* lang/PersistentHashMap)]
      (when (unstableMap v)
        (.newID e x)
        (.b e tMapRebuild)
        (.value e (.-F__meta v))
        (.uv e (conv uint64 (.-F_count v)))
        (for [s (.Seq__ISeq v)] (!= s nil) (set! s (.Next__ISeq s))
          (let [me (assert lang/IMapEntry (.First__O s))]
            (.value e (.Key__O me))
            (.value e (.Val__O me))))

        (inc! (aget (.-counts e) "PersistentHashMap (rebuilt)"))
        (return)))

    (case [(* lang/PersistentHashSet)]
      (when (unstableSet v)
        (.newID e x)
        (.b e tSetRebuild)
        (.value e (.-F__meta v))
        (.uv e (conv uint64 (.Count__I v)))
        (for [s (.Seq__ISeq v)] (!= s nil) (set! s (.Next__ISeq s))
          (.value e (.First__O s)))

        (inc! (aget (.-counts e) "PersistentHashSet (rebuilt)"))
        (return))))


  (let [rv (reflect/ValueOf x)]
    (when (== (.Type rv) plainObjectType)
      (.newID e x)
      (.b e tPlainObj)
      (return))

    (when (or (!= (.Kind rv) reflect/Pointer) (!= (.Kind (.Elem rv)) reflect/Struct))
      (.fail e (fmt/Sprintf "cannot encode a %T" x)))

    (let [t (.Type (.Elem rv))
        p (planOf t)]
      (when (!= (.-err p) "")
        (.fail e (fmt/Sprintf "cannot encode a %T: %s" x (.-err p))))

      (when [(values _ ok) (aget imageTypes (.String t))] (not ok)
        (.fail e (fmt/Sprintf "the type %s is not in the image's table" t)))

      (.newID e x)
      (.b e tObj)
      (if [(values i ok) (aget (.-types e) t)] ok
        (.uv e (conv uint64 i))
        (do
          (set! i (len (.-types e)))
          (aset (.-types e) t i)
          (.uv e (conv uint64 i))
          (.str e (.String t))))

      (.sv e (conv int64 (jrt/PeekIdentityHash x)))
      (inc! (aget (.-counts e) (.String t)))
      (let [ev (.Elem rv)]
        (set! (.-path e) (append (.-path e) (.Name t)))
        (defer ((fn [] (set! (.-path e) (subslice (.-path e) _ (- (len (.-path e)) 1))))))
        (range [_ f (.-fields p)]
          (when (.-zero f)
            (continue))

          (let [fv (.FieldByIndex ev (.-index f))]
            (switch (.-kind f)
              (case [reflect/Interface reflect/Pointer]
                (if (.IsNil fv)
                  (.b e tNil)

                  (.value e (.Interface fv))))

              (case [reflect/Bool]
                (if (.Bool fv)
                  (.b e 1)

                  (.b e 0)))

              (case [reflect/Int8 reflect/Int16 reflect/Int32 reflect/Int64]
                (.sv e (.Int fv)))
              (case [reflect/Uint16]
                (.uv e (.Uint fv)))
              (case [reflect/Float32 reflect/Float64]
                (.uv e (math/Float64bits (.Float fv)))))))))))




(go/method member [^{:tag (* encoder)} e ^{:tag (* jrt/Class)} c ^string name ^{:tag (* jrt/RefArray)} ps]
  (.classRef e c)
  (.str e name)
  (when (== ps nil)
    (.uv e 0)
    (return))

  (.uv e (conv uint64 (len (.-A ps))))
  (range [_ p (.-A ps)]
    (.classRef e (assert (* jrt/Class) p))))




(go/method classRef "a class by name, and whether the unit's events make it\n" [^{:tag (* encoder)} e ^{:tag (* jrt/Class)} c]
  (let [n (className c)]
    (.str e n)
    (if (aget (.-defined e) n)
      (.b e 1)

      (.b e 0))))



(go/method primArray [^{:tag (* encoder)} e ^any x]
  (type-switch [v x]
    (case [(* jrt/ByteArray)]
      (.b e \B)
      (.uv e (conv uint64 (len (.-A v))))
      (range [_ y (.-A v)]
        (.b e (conv byte y))))

    (case [(* jrt/BooleanArray)]
      (.b e \Z)
      (.uv e (conv uint64 (len (.-A v))))
      (range [_ y (.-A v)]
        (if y
          (.b e 1)

          (.b e 0))))


    (case [(* jrt/CharArray)]
      (.b e \C)
      (.uv e (conv uint64 (len (.-A v))))
      (range [_ y (.-A v)]
        (.uv e (conv uint64 y))))

    (case [(* jrt/ShortArray)]
      (.b e \S)
      (.uv e (conv uint64 (len (.-A v))))
      (range [_ y (.-A v)]
        (.sv e (conv int64 y))))

    (case [(* jrt/IntArray)]
      (.b e \I)
      (.uv e (conv uint64 (len (.-A v))))
      (range [_ y (.-A v)]
        (.sv e (conv int64 y))))

    (case [(* jrt/LongArray)]
      (.b e \J)
      (.uv e (conv uint64 (len (.-A v))))
      (range [_ y (.-A v)]
        (.sv e y)))

    (case [(* jrt/FloatArray)]
      (.b e \F)
      (.uv e (conv uint64 (len (.-A v))))
      (range [_ y (.-A v)]
        (.uv e (conv uint64 (math/Float32bits y)))))

    (case [(* jrt/DoubleArray)]
      (.b e \D)
      (.uv e (conv uint64 (len (.-A v))))
      (range [_ y (.-A v)]
        (.uv e (math/Float64bits y))))))







(go/func unstableKey "whether a key's hash may differ in another process: it holds a var or a namespace, whose\nhashes are identity hashes (a class's identity hash is its name's, jrt.presetClassHash;\nthe other objects of the graph keep theirs)\n" ^bool [^any k ^int depth]
  (type-switch [v k]
    (case [nil]
      (return false))
    (case [(* lang/Var) (* lang/Namespace)]
      (return true))
    (case [(* jrt/Class) (* jrt/String) (* lang/Keyword) (* lang/Symbol) (* jrt/Long) (* jrt/Integer) (* jrt/Character) (* jrt/Boolean) (* jrt/Double)]
      (return false))
    (case [lang/IPersistentCollection]
      (when (> depth 8)
        (return true))

      (for [s (lang/RT_Seq_O__ISeq v)] (!= s nil) (set! s (.Next__ISeq s))
        (when (unstableKey (.First__O s) (+ depth 1))
          (return true)))))



  false)


(go/func unstableMap ^bool [^{:tag (* lang/PersistentHashMap)} m]
  (for [s (.Seq__ISeq m)] (!= s nil) (set! s (.Next__ISeq s))
    (when (unstableKey (.Key__O (assert lang/IMapEntry (.First__O s))) 0)
      (return true)))


  false)


(go/func unstableSet ^bool [^{:tag (* lang/PersistentHashSet)} m]
  (for [s (.Seq__ISeq m)] (!= s nil) (set! s (.Next__ISeq s))
    (when (unstableKey (.First__O s) 0)
      (return true)))


  false)


;; ---------------------------------------------------------------------------------------
;; The decoder: one per source, its objects numbered as the encoder numbered them

(go/type pending (struct
    ^{:tag byte} kind
    ^{:tag string} name ; class name
    ^{:tag string} member
    ^{:tag (slice string)} params
    ^{:tag string} ret
    ^{:tag (slice (func [any]))} setters

    ^{:tag (slice string) :doc "the classes it names that the unit's events make\n"} deferred))


(go/type decoder (struct
    ^{:tag string} name
    ^{:tag string} data
    ^{:tag int} pos
    ^{:tag (slice any)} objs
    ^{:tag (map int (* pending))} pend
    ^{:tag (slice string)} strs
    ^{:tag (slice reflect/Type)} types
    ^{:tag (slice (* typePlan))} planned
    ^{:tag int} hidden

    ^{:tag (map string int) :doc "the index of the event of the current unit that makes each class\n"} eventOf

    ^{:tag time/Duration :doc "time spent decoding (ARBACE_IMAGE_TIMES)\n"} spent
    ^{:tag int} units


    ^{:tag time/Time :doc "when the last unit was returned, and its line: the time until the next is the unit's\nevaluation (ARBACE_IMAGE_TIMES)\n"} last
    ^{:tag any} lastLine))



(go/method classRef "a class name as classRef wrote it, noting a class the unit's events make\n" ^string [^{:tag (* decoder)} d ^{:tag (* pending)} p]
  (let [n (.str d)]
    (when (!= (.byte_ d) 0)
      (set! (.-deferred p) (append (.-deferred p) n)))

    n))


(go/method byte_ ^byte [^{:tag (* decoder)} d]
  (let [b (aget (.-data d) (.-pos d))]
    (inc! (.-pos d))
    b))


(go/method uv ^uint64 [^{:tag (* decoder)} d]
  (let [^uint64 x (zero uint64)
      ^{:tag uint} s (zero uint)]
    (while true
      (let [b (aget (.-data d) (.-pos d))]
        (inc! (.-pos d))
        (when (< b 0x80)
          (return (bit-or x (<< (conv uint64 b) s))))

        (set! x bit-or (<< (conv uint64 (bit-and b 0x7f)) s))
        (set! s + 7)))))



(go/method sv ^int64 [^{:tag (* decoder)} d]
  (let [u (.uv d)
      x (conv int64 (>> u 1))]
    (when (!= (bit-and u 1) 0)
      (set! x (bit-not x)))

    x))


(go/method str ^string [^{:tag (* decoder)} d]
  (let [i (conv int (.uv d))]
    (when (< i (len (.-strs d)))
      (return (aget (.-strs d) i)))

    (let [n (conv int (.uv d))
        s (subslice (.-data d) (.-pos d) (+ (.-pos d) n))]
      (set! (.-pos d) + n)
      (set! (.-strs d) (append (.-strs d) s))
      s)))


(go/method jstr ^{:tag (* jrt/String)} [^{:tag (* decoder)} d]
  (when (== (.byte_ d) 0)
    (return nil))

  (jrt/Str (.str d)))


(go/method slot ^int [^{:tag (* decoder)} d]
  (set! (.-objs d) (append (.-objs d) nil))
  (- (len (.-objs d)) 1))




(go/method value "value decodes one value; set receives it, now or (a class or member not made yet) when it\nis resolved\n" [^{:tag (* decoder)} d ^{:tag (func [any])} set]
  (let [(values v p) (.read d)]
    (cond (!= p nil)
      (set! (.-setters p) (append (.-setters p) set))
      (!= v nil)
      (set v))))





(go/method read "read decodes one value: the value, or (a class or member not made yet) its pending\nresolution, to which the caller adds where it goes\n" [^{:tag (* decoder)} d] :results [any (* pending)]
  (switch [tag (.byte_ d)] tag
    (case [tNil]
      (return nil nil))
    (case [tRef]
      (let [id (conv int (.uv d))]
        (when [(values p ok) (aget (.-pend d) id)] ok
          (return nil p))

        (return (aget (.-objs d) id) nil)))
    (case [tStatic]
      (return (aget statics (.uv d)) nil))
    (case [tTrue]
      (return jrt/Boolean_TRUE nil))
    (case [tFalse]
      (return jrt/Boolean_FALSE nil))
    (case [tLong]
      (return (jrt/Long_ValueOf_J__Long (.sv d)) nil))
    (case [tInt]
      (return (jrt/Integer_ValueOf_I__Integer (conv int32 (.sv d))) nil))
    (case [tShort]
      (return (jrt/Short_ValueOf_S__Short (conv int16 (.sv d))) nil))
    (case [tByte]
      (return (jrt/Byte_ValueOf_B__Byte (conv int8 (.sv d))) nil))
    (case [tChar]
      (return (jrt/Character_ValueOf_C__Character (conv uint16 (.uv d))) nil))
    (case [tDouble]
      (return (jrt/Double_ValueOf_D__Double (math/Float64frombits (.uv d))) nil))
    (case [tFloat]
      (return (jrt/Float_ValueOf_F__Float (math/Float32frombits (conv uint32 (.uv d)))) nil))
    (case [tStr]
      (let [id (.slot d)
          s (jrt/Str (.str d))]
        (aset (.-objs d) id s)
        (return s nil)))
    (case [tKeyword]
      (let [id (.slot d)
          ns (.jstr d)
          k (lang/Keyword_Intern_String_String__Keyword ns (jrt/Str (.str d)))]
        (aset (.-objs d) id k)
        (return k nil)))
    (case [tSymbol]
      (let [id (.slot d)
          ns (.jstr d)
          s (lang/Symbol_Intern_String_String__Symbol ns (jrt/Str (.str d)))]
        (aset (.-objs d) id s)
        (when [(values m _) (.read d)] (!= m nil)
          (set! (.-F__meta s) (assert lang/IPersistentMap m)))

        (return s nil)))
    (case [tVar]
      (let [id (.slot d)
          ns (lang/Namespace_FindOrCreate_Symbol__Namespace (lang/Symbol_Intern_String__Symbol (jrt/Str (.str d))))
          sym (lang/Symbol_Intern_String__Symbol (jrt/Str (.str d)))
          v (.FindInternedVar_Symbol__Var ns sym)]
        (when (== v nil)
          (set! v (lang/Var_Intern_Namespace_Symbol__Var ns sym)))

        (aset (.-objs d) id v)
        (return v nil)))
    (case [tNs]
      (let [id (.slot d)
          ns (lang/Namespace_FindOrCreate_Symbol__Namespace (lang/Symbol_Intern_String__Symbol (jrt/Str (.str d))))]
        (aset (.-objs d) id ns)
        (return ns nil)))
    (case [tClass]
      (let [id (.slot d)
          p (addr (lit pending :kind tClass))]
        (set! (.-name p) (.classRef d p))
        (return (.pendingRef d id p))))
    (case [tMethod]
      (let [id (.slot d)
          p (addr (lit pending :kind tMethod))]
        (.memberSpec d p)
        (set! (.-ret p) (.classRef d p))
        (return (.pendingRef d id p))))
    (case [tCtor]
      (let [id (.slot d)
          p (addr (lit pending :kind tCtor))]
        (.memberSpec d p)
        (return (.pendingRef d id p))))
    (case [tField]
      (let [id (.slot d)
          p (addr (lit pending :kind tField))]
        (.memberSpec d p)
        (return (.pendingRef d id p))))
    (case [tPattern]
      (let [id (.slot d)
          pat (jrt/Pattern_Compile_String_I__Pattern (jrt/Str (.str d)) (conv int32 (.sv d)))]
        (aset (.-objs d) id pat)
        (return pat nil)))
    (case [tRefArray]
      (let [id (.slot d)
          cp (addr (lit pending :kind tClass))]
        (set! (.-name cp) (.classRef d cp))
        (let [n (conv int (.uv d))
            a (addr (lit jrt/RefArray :A (make (slice any) n)))]
          (aset (.-objs d) id a)
          (if [(values c p) (.pendingRef d -1 cp)] (!= p nil)
            (set! (.-setters p) (append (.-setters p) (fn [^any c] (set! (.-Comp a) (assert (* jrt/Class) c)))))

            (set! (.-Comp a) (assert (* jrt/Class) c)))

          (for [i 0] (< i n) (inc! i)
            (let [(values v p) (.read d)]
              (if (!= p nil)
                (let [i i]
                  (set! (.-setters p) (append (.-setters p) (fn [^any v] (aset (.-A a) i v)))))

                (aset (.-A a) i v))))


          (return a nil))))
    (case [tPrimArray]
      (let [id (.slot d)
          a (.primArray d)]
        (aset (.-objs d) id a)
        (return a nil)))
    (case [tPlainObj]
      (let [id (.slot d)
          o (jrt/Object_New)]
        (aset (.-objs d) id o)
        (return o nil)))
    (case [tAtomicRef]
      (let [id (.slot d)
          a (jrt/AtomicReference_New)]
        (aset (.-objs d) id a)
        (.value d (fn [^any v] (.Set_O__V a v)))
        (return a nil)))
    (case [tAtomicInt]
      (let [id (.slot d)
          a (jrt/AtomicInteger_New_I (conv int32 (.sv d)))]
        (aset (.-objs d) id a)
        (return a nil)))
    (case [tAtomicBool]
      (let [id (.slot d)
          a (jrt/AtomicBoolean_New_Z (!= (.byte_ d) 0))]
        (aset (.-objs d) id a)
        (return a nil)))
    (case [tLazySeq]
      (let [id (.slot d)
          ^{:tag lang/IPersistentMap} meta (zero lang/IPersistentMap)
          ^{:tag lang/ISeq} s (zero lang/ISeq)]
        (when [(values m _) (.read d)] (!= m nil)
          (set! meta (assert lang/IPersistentMap m)))

        (when [(values x _) (.read d)] (!= x nil)
          (set! s (assert lang/ISeq x)))

        (let [ls (lang/LazySeq_New_IPersistentMap_ISeq meta s)]
          (aset (.-objs d) id ls)
          (return ls nil))))
    (case [tMapRebuild tSetRebuild]
      (let [id (.slot d)
          (values meta _) (.read d)
          n (conv int (.uv d))
          k n]
        (when (== tag tMapRebuild)
          (set! k (* 2 n)))

        (let [kvs (jrt/NewRefArray jrt/Object_class (conv int32 k))]
          (for [i 0] (< i k) (inc! i)
            (let [i i]
              (.value d (fn [^any v] (aset (.-A kvs) i v)))))

          (let [^any r (zero any)]
            (if (== tag tMapRebuild)
              (let [m (lang/PersistentHashMap_Create_O1__PersistentHashMap kvs)]
                (when (!= meta nil)
                  (set! m (.WithMeta_IPersistentMap__PersistentHashMap m (assert lang/IPersistentMap meta))))

                (set! r m))

              (let [m (lang/PersistentHashSet_Create_O1__PersistentHashSet kvs)]
                (when (!= meta nil)
                  (set! m (.WithMeta_IPersistentMap__PersistentHashSet m (assert lang/IPersistentMap meta))))

                (set! r m)))

            (aset (.-objs d) id r)
            (return r nil)))))
    (case [tObj]
      (return (.object d) nil)))

  (panic (fmt/Sprintf "image: %s: bad tag at %d" (.-name d) (- (.-pos d) 1))))



(go/method object "object decodes a struct of the program, its fields written in place\n" ^any [^{:tag (* decoder)} d]
  (let [ti (conv int (.uv d))]
    (when (== ti (len (.-types d)))
      (let [tn (.str d)
          (values t ok) (aget imageTypes tn)]
        (when (not ok)
          (panic (fmt/Sprintf "image: %s: unknown type %s" (.-name d) tn)))

        (set! (.-types d) (append (.-types d) t))
        (set! (.-planned d) (append (.-planned d) (planOf t)))))

    (let [p (aget (.-planned d) ti)]
      (when (not (.-inited p))
        ;; the class's static initialization, as making an instance runs it on the JVM
        (when [(values o ok) (assert jrt/Object_I (.Interface (reflect/New (.-t p))))] ok
          (when [c (.GetClass__Class o)] (and (!= c nil) (!= (.-Init (.Info c)) nil))
            ((.-Init (.Info c)))))


        (set! (.-inited p) true))

      (let [h (conv int32 (.sv d))
          pv (reflect/New (.-t p))
          x (.Interface pv)]
        (when (!= h 0)
          (jrt/SetIdentityHash x h))

        (let [id (.slot d)]
          (aset (.-objs d) id x)
          (let [base (.UnsafePointer pv)]
            (range [i (.-fields p)]
              (let [f (addr (aget (.-fields p) i))]
                (when (.-zero f)
                  (continue))

                (let [at (unsafe/Add base (.-off f))]
                  (switch (.-kind f)
                    (case [reflect/Interface reflect/Pointer]
                      (let [(values v pd) (.read d)]
                        (cond (!= pd nil)
                          (set! (.-setters pd) (append (.-setters pd) (fn [^any v] (setRef at f v))))
                          (!= v nil)
                          (setRef at f v))))

                    (case [reflect/Bool]
                      (set! @(conv (* bool) at) (!= (.byte_ d) 0)))
                    (case [reflect/Int8]
                      (set! @(conv (* int8) at) (conv int8 (.sv d))))
                    (case [reflect/Int16]
                      (set! @(conv (* int16) at) (conv int16 (.sv d))))
                    (case [reflect/Int32]
                      (set! @(conv (* int32) at) (conv int32 (.sv d))))
                    (case [reflect/Int64]
                      (set! @(conv (* int64) at) (.sv d)))
                    (case [reflect/Uint16]
                      (set! @(conv (* uint16) at) (conv uint16 (.uv d))))
                    (case [reflect/Float32]
                      (set! @(conv (* float32) at) (conv float32 (math/Float64frombits (.uv d)))))
                    (case [reflect/Float64]
                      (set! @(conv (* float64) at) (math/Float64frombits (.uv d))))))))


            x))))))



(go/type ifaceWords "the words of an interface value\n" (struct
    ^{:tag unsafe/Pointer} tab
    ^{:tag unsafe/Pointer} data))


(go/type itabKey (struct
    ^{:tag reflect/Type} iface ^reflect/Type concrete))


(go/var
  [^sync/Mutex itabsMu]
  [itabs (lit (map itabKey unsafe/Pointer))])





(go/func setRef "setRef stores v, a pointer to a Java object, in the reference field at: a pointer field its\npointer, an interface field the interface's table for v's type (made once by reflect) and\nthe pointer\n" [^unsafe/Pointer at ^{:tag (* fieldPlan)} f ^any v]
  (let [w (conv (* ifaceWords) (conv unsafe/Pointer (addr v)))]
    (when (== (.-kind f) reflect/Pointer)
      (set! @(conv (* unsafe/Pointer) at) (.-data w))
      (return))

    (when (== (.NumMethod (.-t f)) 0)
      (set! @(conv (* any) at) v)
      (return))

    (let [k (lit itabKey (.-t f) (reflect/TypeOf v))]
      (.Lock itabsMu)
      (let [(values tab ok) (aget itabs k)]
        (.Unlock itabsMu)
        (when (not ok)
          (let [tmp (reflect/New (.-t f))]
            (.Set (.Elem tmp) (reflect/ValueOf v))
            (set! tab (.-tab (conv (* ifaceWords) (.UnsafePointer tmp))))
            (.Lock itabsMu)
            (aset itabs k tab)
            (.Unlock itabsMu)))

        (let [dst (conv (* ifaceWords) at)]
          (set! (.-tab dst) tab)
          (set! (.-data dst) (.-data w)))))))




(go/method slot2 "a hidden slot (the encoder numbers nothing there): the array's class is pending under a\nnegative key\n" ^int [^{:tag (* decoder)} d]
  (dec! (.-hidden d))
  (.-hidden d))


(go/method memberSpec [^{:tag (* decoder)} d ^{:tag (* pending)} p]
  (set! (.-name p) (.classRef d p))
  (set! (.-member p) (.str d))
  (let [n (conv int (.uv d))]
    (set! (.-params p) (make (slice string) n))
    (range [i (.-params p)]
      (aset (.-params p) i (.classRef d p)))))




(go/method pendingRef "pendingRef: the class or member p names, or p itself, pending until it can be resolved\n" [^{:tag (* decoder)} d ^int id ^{:tag (* pending)} p] :results [any (* pending)]
  (when (== (len (.-deferred p)) 0)
    (when [v (.lookup p)] (!= v nil)
      (when (>= id 0)
        (aset (.-objs d) id v))

      (return v nil)))


  (when (== (.-pend d) nil)
    (set! (.-pend d) (lit (map int (* pending)))))

  (when (< id 0)
    (set! id (.slot2 d)))

  (aset (.-pend d) id p)
  (return nil p))


(go/var primClasses (lit (map string (* jrt/Class))))

(go/func classByName ^{:tag (* jrt/Class)} [^string n]
  (when (== (len primClasses) 0)
    (range [_ c (lit (slice (* jrt/Class)) jrt/Prim_boolean jrt/Prim_byte jrt/Prim_char jrt/Prim_short
          jrt/Prim_int jrt/Prim_long jrt/Prim_float jrt/Prim_double jrt/Prim_void)]
      (aset primClasses (className c) c)))


  (when [(values c ok) (aget primClasses n)] ok
    (return c))

  (jrt/ForName n))


(go/method lookup ^any [^{:tag (* pending)} p]
  (when [v (.lookup1 p)] (or (!= v nil) (== (.-kind p) tClass))
    (return v))

  ;; a class made at run time gains members after its Class (setMethod, addInterfaceMethod)
  (when [c (classByName (.-name p))] (!= c nil)
    (.Lock membersMu)
    (delete memberMap c)
    (.Unlock membersMu))

  (.lookup1 p))


(go/method lookup1 ^any [^{:tag (* pending)} p]
  (let [c (classByName (.-name p))]
    (when (== c nil)
      (return nil))

    (when (== (.-kind p) tClass)
      (return c))

    (let [ps (make (slice (* jrt/Class)) (len (.-params p)))]
      (range [i n (.-params p)]
        (when [(aset ps i (classByName n))] (== (aget ps i) nil)
          (return nil)))


      (let [same (fn ^bool [^{:tag (* jrt/RefArray)} a]
            (when (!= (len (.-A a)) (len ps))
              (return false))

            (range [i x (.-A a)]
              (when (!= (assert (* jrt/Class) x) (aget ps i))
                (return false)))


            true)]

        (switch (.-kind p)
          (case [tMethod]
            (range [_ x (.-methods (members c))]
              (let [m (assert (* jrt/Method) x)]
                (when (and (== (.String (.GetName__String m)) (.-member p)) (same ^{:go/via [Executable]} (.GetParameterTypes__Class1 m))
                    (== (className (.GetReturnType__Class m)) (.-ret p)))
                  (return m)))))


          (case [tCtor]
            (range [_ x (.-ctors (members c))]
              (let [k (assert (* jrt/Constructor) x)]
                (when (same ^{:go/via [Executable]} (.GetParameterTypes__Class1 k))
                  (return k)))))


          (case [tField]
            (range [_ x (.-fields (members c))]
              (let [f (assert (* jrt/Field) x)]
                (when (== (.String (.GetName__String f)) (.-member p))
                  (return f))))))



        nil))))




(go/type memberLists "a class's declared members, listed once per class (a class made at run time again is\nanother Class)\n" (struct
    ^{:tag (slice any)} methods ^{:tag (slice any)} ctors ^{:tag (slice any)} fields))


(go/var
  [^sync/Mutex membersMu]
  [memberMap (lit (map (* jrt/Class) (* memberLists)))])


(go/func members ^{:tag (* memberLists)} [^{:tag (* jrt/Class)} c]
  (.Lock membersMu)
  (defer (.Unlock membersMu))
  (when [(values m ok) (aget memberMap c)] ok
    (return m))

  (let [m (addr (lit memberLists :methods (.-A (.GetDeclaredMethods__Method1 c)) :ctors (.-A (.GetDeclaredConstructors__Constructor1 c))
          :fields (.-A (.GetDeclaredFields__Field1 c))))]
    (aset memberMap c m)
    m))




(go/method resolve "resolve resolves what the units decoded so far name, once the first k events of the\ncurrent unit are made again\n" [^{:tag (* decoder)} d ^int k ^bool strict]
  (range [id p (.-pend d)]
    (let [blocked false]
      (range [_ n (.-deferred p)]
        (when [(values i ok) (aget (.-eventOf d) n)] (and ok (>= i k))
          (set! blocked true)))


      (when blocked
        (continue))

      (when [v (.lookup p)] (!= v nil)
        (when (>= id 0)
          (aset (.-objs d) id v))

        (range [_ s (.-setters p)]
          (s v))

        (delete (.-pend d) id))))


  (when (and strict (> (len (.-pend d)) 0))
    (let [^{:tag (slice string)} ns (zero (slice string))]
      (range [_ p (.-pend d)]
        (set! ns (append ns (+ (.-name p) " " (.-member p)))))

      (sort/Strings ns)
      (panic (jrt/Thrown (jrt/IllegalStateException_New_String (jrt/Str
              (+ "image: " (.-name d) ": not found: " (strings/Join ns ", ")))))))))



(go/method primArray ^any [^{:tag (* decoder)} d]
  (let [k (.byte_ d)
      n (conv int (.uv d))]
    (switch k
      (case [\B]
        (let [a (jrt/NewByteArray (conv int32 n))]
          (range [i (.-A a)]
            (aset (.-A a) i (conv int8 (.byte_ d))))

          (return a)))
      (case [\Z]
        (let [a (jrt/NewBooleanArray (conv int32 n))]
          (range [i (.-A a)]
            (aset (.-A a) i (!= (.byte_ d) 0)))

          (return a)))
      (case [\C]
        (let [a (jrt/NewCharArray (conv int32 n))]
          (range [i (.-A a)]
            (aset (.-A a) i (conv uint16 (.uv d))))

          (return a)))
      (case [\S]
        (let [a (jrt/NewShortArray (conv int32 n))]
          (range [i (.-A a)]
            (aset (.-A a) i (conv int16 (.sv d))))

          (return a)))
      (case [\I]
        (let [a (jrt/NewIntArray (conv int32 n))]
          (range [i (.-A a)]
            (aset (.-A a) i (conv int32 (.sv d))))

          (return a)))
      (case [\J]
        (let [a (jrt/NewLongArray (conv int32 n))]
          (range [i (.-A a)]
            (aset (.-A a) i (.sv d)))

          (return a)))
      (case [\F]
        (let [a (jrt/NewFloatArray (conv int32 n))]
          (range [i (.-A a)]
            (aset (.-A a) i (math/Float32frombits (conv uint32 (.uv d)))))

          (return a)))
      (case [\D]
        (let [a (jrt/NewDoubleArray (conv int32 n))]
          (range [i (.-A a)]
            (aset (.-A a) i (math/Float64frombits (.uv d))))

          (return a))))

    (panic "image: bad primitive array")))


;; ---------------------------------------------------------------------------------------
;; The hooks (jrt.ImageHooks)

(go/type image (struct
    ^{:tag sync/Mutex} mu
    ^{:tag string} prepare
    ^{:tag (map string (* encoder))} recs
    ^{:tag (map string (slice byte))} done
    ^{:tag (slice string)} order
    ^{:tag string} data
    ^{:tag (map string (array 2 int))} index
    ^{:tag (map string (* decoder))} decoders

    ^{:tag int :doc "the garbage collector's setting before the start raised it\n"} gcPercent
    ^{:tag bool} gcRaised))


(go/method Mode ^int32 [^{:tag (* image)} im]
  (when (!= (.-prepare im) "")
    (return 1))

  0)


(go/method Begin ^bool [^{:tag (* image)} im ^string name]
  (.Lock (.-mu im))
  (defer (.Unlock (.-mu im)))
  (when [(values _ ok) (aget (.-done im) name)] ok
    (return false))

  (when [(values _ ok) (aget (.-recs im) name)] ok
    (return false))

  (aset (.-recs im) name (newEncoder name))
  true)


(go/method Unit [^{:tag (* image)} im ^string name ^{:tag (* jrt/RefArray)} u]
  (.Lock (.-mu im))
  (let [e (aget (.-recs im) name)]
    (.Unlock (.-mu im))
    (set! (.-defined e) (unitClasses u))
    (.value e u)
    (set! (.-defined e) nil)))




(go/func unitClasses "unitClasses: the names of the classes a unit's events make (an event is {kind, the class it\nmakes or null, args...}; the unit's events are its element 6)\n" ^{:tag (map string bool)} [^{:tag (* jrt/RefArray)} u]
  (let [m (lit (map string bool))]
    (when [(values evs ok) (assert (* jrt/RefArray) (aget (.-A u) 6))] ok
      (range [_ ev (.-A evs)]
        (when [(values n ok) (assert (* jrt/String) (aget (.-A (assert (* jrt/RefArray) ev)) 1))] ok
          (aset m (.String n) true))))



    m))


(go/method End [^{:tag (* image)} im ^string name ^bool ok]
  (.Lock (.-mu im))
  (defer (.Unlock (.-mu im)))
  (let [e (aget (.-recs im) name)]
    (delete (.-recs im) name)
    (when (not ok)
      (fmt/Fprintf os/Stderr "image: %s not recorded (its load failed)\n" name)
      (return))

    (aset (.-done im) name (.Bytes (.-buf e)))
    (set! (.-order im) (append (.-order im) name))
    (when (!= (os/Getenv "ARBACE_IMAGE_STATS") "")
      (let-type [kv (struct
            ^{:tag string} k
            ^{:tag int} v)]

        (let [^{:tag (slice kv)} kvs (zero (slice kv))]
          (range [k v (.-counts e)]
            (set! kvs (append kvs (lit kv k v))))

          (sort/Slice kvs (fn ^bool [^int i ^int j] (> (.-v (aget kvs i)) (.-v (aget kvs j)))))
          (fmt/Fprintf os/Stderr "image: %s: %d bytes, %d objects, %d strings, %d types\n" name (.Len (.-buf e)) (.-nobj e) (len (.-strs e)) (len (.-types e)))
          (range [i x kvs]
            (when (>= i 25)
              (break))

            (fmt/Fprintf os/Stderr "  %8d %s\n" (.-v x) (.-k x))))))))




(go/method write ^error [^{:tag (* image)} im]
  (let [^bytes/Buffer out (zero bytes/Buffer)
      ^{:tag (array binary/MaxVarintLen64 byte)} tmp (zero (array binary/MaxVarintLen64 byte))
      uv (fn [^int x] (.Write out (subslice tmp _ (binary/PutUvarint (subslice tmp) (conv uint64 x)))))]
    (.WriteString out imageMagic)
    (let [names (append (conv (slice string) nil) (spread (.-order im)))]
      (sort/Strings names)
      (uv (len names))
      (let [off 0]
        (range [_ n names]
          (uv (len n))
          (.WriteString out n)
          (uv off)
          (uv (len (aget (.-done im) n)))
          (set! off + (len (aget (.-done im) n))))

        (range [_ n names]
          (.Write out (aget (.-done im) n)))

        (os/WriteFile (.-prepare im) (.Bytes out) 0644)))))


(go/method readIndex [^{:tag (* image)} im]
  (when (!= (.-index im) nil)
    (return))

  (set! (.-index im) (lit (map string (array 2 int))))
  (when (not (strings/HasPrefix (.-data im) imageMagic))
    (return))

  (let [d (addr (lit decoder :data (.-data im) :pos (len imageMagic)))
      n (conv int (.uv d))]
    (let-type [ent (struct
          ^{:tag string} name
          ^{:tag int} off ^int len)]

      (let [es (make (slice ent) n)]
        (range [i es]
          (let [l (conv int (.uv d))]
            (set! (.-name (aget es i)) (subslice (.-data d) (.-pos d) (+ (.-pos d) l)))
            (set! (.-pos d) + l)
            (set! (.-off (aget es i)) (conv int (.uv d)))
            (set! (.-len (aget es i)) (conv int (.uv d)))))

        (range [_ e es]
          (aset (.-index im) (.-name e) (lit (array 2 int) (+ (.-pos d) (.-off e)) (+ (.-pos d) (.-off e) (.-len e)))))))))



(go/method Has ^bool [^{:tag (* image)} im ^string name]
  (when (or (!= (.-prepare im) "") (== (.-data im) ""))
    (return false))

  (.Lock (.-mu im))
  (defer (.Unlock (.-mu im)))
  (.readIndex im)
  (let [(values _ ok) (aget (.-index im) name)]
    ok))


(go/method decoder ^{:tag (* decoder)} [^{:tag (* image)} im ^string name]
  (.Lock (.-mu im))
  (defer (.Unlock (.-mu im)))
  (.readIndex im)
  (let [d (aget (.-decoders im) name)]
    (when (== d nil)
      (let [r (aget (.-index im) name)]
        (initStatics)
        (set! d (addr (lit decoder :name name :data (subslice (.-data im) _ (aget r 1)) :pos (aget r 0))))
        (aset (.-decoders im) name d)))

    d))


(go/method Next ^{:tag (* jrt/RefArray)} [^{:tag (* image)} im ^string name]
  (let [d (.decoder im name)]
    (when (and imageTimes (not (.IsZero (.-last d))))
      (when [t (time/Since (.-last d))] (> t (* 3 time/Millisecond))
        (fmt/Fprintf os/Stderr "image: %s:%v evaluated in %d ms\n" name (.-lastLine d) (.Milliseconds t))))


    (when (>= (.-pos d) (len (.-data d)))
      (.Lock (.-mu im))
      (delete (.-decoders im) name)
      (.Unlock (.-mu im))
      (when imageTimes
        (fmt/Fprintf os/Stderr "image: %s: %d units, %d objects decoded in %d ms\n" name (.-units d) (len (.-objs d)) (.Milliseconds (.-spent d))))

      (return nil))

    (when imageTimes
      (let [t0 (time/Now)]
        (defer ((fn [] (set! (.-spent d) + (time/Since t0)) (inc! (.-units d)))))))

    (let [^{:tag (* jrt/RefArray)} u (zero (* jrt/RefArray))]
      (.value d (fn [^any v] (set! u (assert (* jrt/RefArray) v))))
      (when imageTimes
        (defer ((fn [] (set! (.-last d) (time/Now)) (set! (.-lastLine d) (aget (.-A u) 1))))))

      (set! (.-eventOf d) (lit (map string int)))
      (when [(values evs ok) (assert (* jrt/RefArray) (aget (.-A u) 6))] ok
        (range [i ev (.-A evs)]
          (when [(values n ok) (assert (* jrt/String) (aget (.-A (assert (* jrt/RefArray) ev)) 1))] ok
            (aset (.-eventOf d) (.String n) i))))



      u)))


(go/method Resolve [^{:tag (* image)} im ^string name ^int32 k ^bool strict]
  (let [d (.decoder im name)]
    (when imageTimes
      (let [t0 (time/Now)]
        (defer ((fn [] (set! (.-spent d) + (time/Since t0)))))))

    (.resolve d (conv int k) strict)))


(go/var imageTimes (!= (os/Getenv "ARBACE_IMAGE_TIMES") ""))

(go/var ^{:tag (* image)} theImage)






(go/func setupImage "setupImage installs the image (ARBACE_NO_IMAGE: none, the namespaces are read and analyzed\nfrom their sources; ARBACE_PREPARE: record them into that file). While the program starts\n(until Main.main has loaded arbace.main) the garbage collector runs at GOGC=400 unless GOGC\nis set: the start allocates the decoded namespaces and the objects their evaluation makes,\nmost of which stay\n" [^string data]
  (set! theImage (addr (lit image :prepare (os/Getenv "ARBACE_PREPARE") :recs (lit (map string (* encoder)))
        :done (lit (map string (slice byte))) :decoders (lit (map string (* decoder))) :data data)))
  (when (!= (os/Getenv "ARBACE_NO_IMAGE") "")
    (set! (.-data theImage) ""))

  (when [(values _ set) (os/LookupEnv "GOGC")] (not set)
    (set! (.-gcPercent theImage) (debug/SetGCPercent 400))
    (set! (.-gcRaised theImage) true))

  (set! jrt/Image theImage))


(go/method Started [^{:tag (* image)} im]
  (when (.-gcRaised im)
    (set! (.-gcRaised im) false)
    (debug/SetGCPercent (.-gcPercent im))))



(go/func finishImage []
  (when (and (!= theImage nil) (!= (.-prepare theImage) ""))
    (when [err (.write theImage)] (!= err nil)
      (fmt/Fprintln os/Stderr "image:" err)
      (os/Exit 1))))
