(ns arbace.c2g.out
  "c2g's output (C2G-SPEC §4.3): Go forms files, one per class forms file, plus the generated
  files of each package (c2g_classes: registrations and member tables, §5.11; c2g_strings: the
  literal pool, §7.5; c2g_frames: the frame table, §7.9.6; c2g_support: c2g's helpers), and
  the merge with jrt's hand-written forms into one program root for bin/g2c build."
  (:require [arbace.string :as str]
            [arbace.java.io :as io]
            [arbace.classes.types :as t]
            [arbace.classes.env :as env]
            [arbace.classes.analyze :as a]
            [arbace.classes.emit :as e]
            [arbace.c2g.model :as m]
            [arbace.c2g.names :as nm]
            [arbace.c2g.jrt :as jrt]
            [arbace.c2g.code :as c]
            [arbace.c2g.decls :as d])
  (:import (arbace.asm Opcodes)))

(defn- tag [sym type] (with-meta sym {:tag type}))

;; ---------------------------------------------------------------------------------------
;; printing forms

(defn clean
  "f without the reader's position metadata (quoted forms in c2g's source carry it)."
  [f]
  (let [cm (fn [x] (let [mt (meta x)]
                     (if mt
                       (let [mt (dissoc mt :line :column :file :end-line :end-column)
                             mt (if (contains? mt :tag) (update mt :tag clean) mt)]
                         (with-meta x (if (empty? mt) nil mt)))
                       x)))]
    (cond
      (symbol? f) (cm f)
      (seq? f) (cm (with-meta (apply list (map clean f)) (meta f)))
      (vector? f) (cm (with-meta (mapv clean f) (meta f)))
      (map? f) (into {} (map (fn [[k v]] [(clean k) (clean v)]) f))
      :else f)))

(declare write-form)

(defn- write-meta [^StringBuilder sb mt]
  (when (seq mt)
    (if (and (= [:tag] (keys mt)) (symbol? (:tag mt)))
      (do (.append sb "^") (write-form sb (:tag mt)) (.append sb " "))
      (do (.append sb "^") (write-form sb mt) (.append sb " ")))))

(defn- write-form [^StringBuilder sb f]
  (let [mt (when (or (symbol? f) (seq? f) (vector? f)) (meta f))]
    (write-meta sb mt)
    (cond
      (seq? f) (do (.append sb "(")
                   (doseq [[i x] (map-indexed vector f)]
                     (when (pos? i) (.append sb " "))
                     (write-form sb x))
                   (.append sb ")"))
      (vector? f) (do (.append sb "[")
                      (doseq [[i x] (map-indexed vector f)]
                        (when (pos? i) (.append sb " "))
                        (write-form sb x))
                      (.append sb "]"))
      (map? f) (do (.append sb "{")
                   (doseq [[i [k v]] (map-indexed vector f)]
                     (when (pos? i) (.append sb " "))
                     (write-form sb k) (.append sb " ") (write-form sb v))
                   (.append sb "}"))
      (symbol? f) (.append sb (str f))
      :else (.append sb (binding [*print-meta* false] (pr-str f))))))

(defn form-text [f]
  (let [sb (StringBuilder.)]
    (write-form sb (clean f))
    (str sb)))

(def import-paths
  {"jrt" "arbace/jrt" "math" "math" "atomic" "sync/atomic" "reflect" "reflect" "unsafe" "unsafe"
   "strings" "strings" "lang" "arbace/lang"})

(defn- used-qualifiers [forms]
  (let [acc (volatile! #{})]
    (letfn [(w [x]
              (cond
                (symbol? x) (do (when-let [q (namespace x)] (vswap! acc conj q))
                                (when-let [mt (meta x)] (w (:tag mt))))
                (seq? x) (do (when-let [mt (meta x)] (w (:tag mt))) (run! w x))
                (vector? x) (do (when-let [mt (meta x)] (w (:tag mt))) (run! w x))
                (map? x) (run! w (vals x))
                :else nil))]
      (run! w forms))
    @acc))

(defn file-text
  "The text of a Go forms file of package pkg named go-name holding forms."
  [pkg go-name forms & [header]]
  (let [quals (used-qualifiers forms)
        imports (vec (for [q (sort quals)
                           :when (contains? import-paths q)
                           :when (not (and (= pkg :jrt) (= q "jrt")))
                           :when (not (and (= q "arbace.core")))]
                       [(symbol q) (import-paths q)]))
        sb (StringBuilder.)]
    (.append sb (str ";; Generated by c2g (arbace/c2g, doc/go/C2G-SPEC.md); do not edit.\n"))
    (when header (.append sb header))
    (.append sb (str "(in-ns '" (nm/pkg-ns pkg) ")\n\n"))
    (.append sb (form-text (list 'go/file go-name :imports imports)))
    (.append sb "\n")
    (doseq [f forms]
      (if (and (seq? f) (= 'c2g/comment (first f)))
        (.append sb (str "\n;; " (second f) "\n"))
        (.append sb (str "\n" (form-text f) "\n"))))
    (str sb)))

(defn go-file-name
  "The Go file of a class forms file (§4.3): its name for arbace/lang, the Java source path
  with _ for / in jrt; _c2g appended when the name would read as a build constraint."
  [pkg top]
  (let [base (if (= pkg :jrt)
               (str/replace top "/" "_")
               (subs top (inc (.lastIndexOf ^String top "/"))))
        base (str/replace base "$" "_")
        parts (str/split base #"_")
        constraint #{"aix" "android" "darwin" "dragonfly" "freebsd" "hurd" "illumos" "ios" "js" "linux"
                     "nacl" "netbsd" "openbsd" "plan9" "solaris" "wasip1" "windows" "zos" "tamago"
                     "386" "amd64" "arm" "arm64" "loong64" "mips" "mipsle" "mips64" "mips64le" "ppc64"
                     "ppc64le" "riscv64" "s390x" "wasm" "test"}]
    (str base (if (and (> (count parts) 1) (constraint (last parts))) "_c2g" "") ".go")))

;; ---------------------------------------------------------------------------------------
;; generated package files

(defn strings-forms
  "The literal pool (§7.5): Lit_n vars interned at package initialization."
  [pkg lits]
  (for [[s sym] (sort-by (comp #(Long/parseLong (subs (name %) 4)) val) lits)]
    (let [units (map int s)
          lone? (some (fn [[i ch]]
                        (let [hi (Character/isHighSurrogate (char ch))
                              lo (Character/isLowSurrogate (char ch))]
                          (or (and hi (not (and (< (inc i) (count s)) (Character/isLowSurrogate (.charAt ^String s (inc i))))))
                              (and lo (not (and (pos? i) (Character/isHighSurrogate (.charAt ^String s (dec i)))))))))
                      (map-indexed vector units))]
      (list 'go/var (tag sym (list '* (m/jrt-sym pkg "String")))
            (if lone?
              (list (m/jrt-sym pkg "InternUTF16") (apply list 'lit '(slice uint16) units))
              (list (m/jrt-sym pkg "Intern") s))))))

(defn ups-forms
  "The nil-preserving conversions Up_From_To (§5.6) the package's code needs."
  [pkg ups]
  (binding [c/*f* {:pkg pkg}]
    (for [[from to] (sort ups)]
      (list 'go/func (symbol (str "Up_" (nm/desc-code from) "_" (nm/desc-code to)))
            (with-meta [(tag 'p (m/go-type pkg from))] {:tag (m/go-type pkg to)})
            (list 'when (list '== 'p nil) (list 'return nil))
            'p))))

(defn adapter-forms
  "The adapter F_Fn of functional interface fi (§7.11): its SAM calls Fn, default methods
  forward to their functions."
  [pkg fi]
  (let [g (m/go-name fi)
        a (str g "_Fn")
        sam (a/find-sam fi)
        [ps r] (t/parse-method-desc (:desc sam))
        pn (vec (for [i (range (count ps))] (symbol (str "p" i))))
        recv (tag 't (list '* (symbol a)))
        ftype (if (= "V" r)
                (list 'func (vec (map #(m/go-type pkg %) ps)))
                (list 'func (vec (map #(m/go-type pkg %) ps)) [(m/go-type pkg r)]))
        call (apply list (list '.-Fn 't) pn)]
    (concat
      [(list 'c2g/comment (str "---- the lambda adapter of " (str/replace fi "/" ".")))
       (list 'go/type (symbol a) (list 'struct (m/jrt-sym pkg "Object") (tag 'Fn ftype)))
       (list 'go/method (symbol (nm/method-base (:name sam) (:desc sam)))
             (cond-> (vec (cons recv (map #(tag %1 (m/go-type pkg %2)) pn ps)))
               (not= "V" r) (vary-meta assoc :tag (m/go-type pkg r)))
             (if (= "V" r) call (list 'return call)))]
      (for [j (cons fi (d/interface-closure fi))]
        (list 'go/method (symbol (str "Is_" (m/go-name j))) [recv]))
      ;; default methods of the interface and its superinterfaces
      (for [[[name desc :as k] mm] (m/vmethods fi)
            :when (not= [name desc] [(:name sam) (:desc sam)])
            :let [impl (m/impl-of fi k)
                  [mps mr] (t/parse-method-desc desc)
                  mpn (vec (for [i (range (count mps))] (symbol (str "p" i))))
                  base (nm/method-base name desc)]]
        (list 'go/method (symbol base)
              (cond-> (vec (cons recv (map #(tag %1 (m/go-type pkg %2)) mpn mps)))
                (not= "V" mr) (vary-meta assoc :tag (m/go-type pkg mr)))
              (if (and impl (= :default (:kind impl)))
                (apply list (m/class-sym pkg (:owner impl) (str "_" base)) 't mpn)
                (list 'panic (list (m/jrt-sym pkg "C2g_NotTranslated") (str "abstract " name desc))))))
      [(list 'go/method 'Ref (with-meta [recv] {:tag 'any}) (list 'when (list '== 't nil) (list 'return nil)) 't)
       (list 'go/method 'GetClass__Class (with-meta [recv] {:tag (list '* (m/jrt-sym pkg "Class"))}) (symbol (str a "_class")))
       (list 'go/method 'ToString__String (with-meta [recv] {:tag (list '* (m/jrt-sym pkg "String"))})
             (list (m/jrt-sym pkg "Object_toString") 't))
       (list 'go/method 'Clone__O (with-meta [recv] {:tag 'any}) (list 'panic (list (m/jrt-sym pkg "CloneNotSupported") 't)))
       (list 'go/var (symbol (str a "_class"))
             (list (m/jrt-sym pkg "Define")
                   (list 'addr (list 'lit (m/jrt-sym pkg "ClassInfo")
                                     :Name (str (str/replace fi "/" ".") "$$Lambda")
                                     :Modifiers 0x1010 :Kind (m/jrt-sym pkg "KindClass")
                                     :Super (m/jrt-sym pkg "Object_class")
                                     :Interfaces (list 'lit (list 'slice (list '* (m/jrt-sym pkg "Class"))) (m/class-sym pkg fi "_class"))
                                     :Go (str (nm/pkg-path pkg) "." a)))))])))

(defn support-forms
  "c2g's helpers in package jrt (c2g_support): what translated code calls besides jrt's API."
  []
  (let [bool-translated (m/translated? "java/lang/Boolean")
        bool-init (and bool-translated (not (m/trivial-init? "java/lang/Boolean")))]
    (remove nil? [(list 'go/var (tag 'C2g_AssertionsDisabled 'bool) true)
     (list 'go/func 'C2g_NotTranslated (with-meta [(tag 'what 'string)] {:tag 'Throwable_I})
           (list 'UnsupportedOperationException_New_String (list 'Str (list '+ "c2g: not translated: " 'what))))
     (list 'go/func 'C2g_Missing :type-params ['T] (with-meta [(tag 'why 'string)] {:tag 'T})
           (list 'panic (list 'Thrown (list 'UnsupportedOperationException_New_String (list 'Str (list '+ "c2g: " 'why))))))
     (list 'go/func 'C2g_NotNull :type-params ['T] (with-meta [(tag 'x 'T)] {:tag 'T})
           (list 'when (list '== (list 'conv 'any 'x) nil) (list 'panic (list 'NPE)))
           'x)
     (apply list 'go/func 'C2g_Truth (with-meta [(tag 'x 'any)] {:tag 'bool})
            (remove nil?
                    [(list 'when (list '== 'x nil) (list 'return false))
                     (when bool-init (list 'Boolean_Init))
                     (list 'return (list '!= 'x (list 'conv 'any 'Boolean_FALSE)))]))
     (list 'go/func 'C2g_CastArray :type-params ['T] (with-meta [(tag 'x 'any) (tag 'cls '(* Class))] {:tag 'T})
           (list 'when (list '== 'x nil) (list 'let [(tag 'z 'T) (list 'zero 'T)] (list 'return 'z)))
           (list 'let ['y (list '.Cast_O__O 'cls 'x)]
                 (list 'assert 'T 'y)))
     (list 'go/func 'C2g_Discard (with-meta [(tag 'x 'any)] {:tag 'bool}) false)
     '(go/func C2g_RefP "C2g_RefP is a pointer as an any, nil-preserving (§5.6).\n"
        :type-params [T] ^any [^{:tag (* T)} p]
        (when (== p nil) (return nil))
        p)
     (when (and (m/translated? "java/util/Formatter")
                (not (contains? (:funcs (arbace.c2g.jrt/scan-file (java.io.File. "go/arbace/jrt/string.clj"))) "String_Format_String_O1__String")))
       '(go/func String_Format_String_O1__String
          "String_Format_String_O1__String is String.format: a new Formatter's format (c2g's, over the
translated java.util.Formatter).\n"
          ^{:tag (* String)} [^{:tag (* String)} format ^{:tag (* RefArray)} args]
          (.ToString__String (.Format_String_O1__Formatter (Formatter_New) format args))))
     (when (m/translated? "java/util/Formatter")
       '(go/func String_Format_Locale_String_O1__String
          "String_Format_Locale_String_O1__String is String.format(Locale, ...).\n"
          ^{:tag (* String)} [^{:tag (* Locale)} l ^{:tag (* String)} format ^{:tag (* RefArray)} args]
          (.ToString__String (.Format_String_O1__Formatter (Formatter_New_Locale l) format args))))
     ;; records' derived equals and hashCode (java.lang.runtime.ObjectMethods)
     '(go/func C2g_ObjHash "C2g_ObjHash is Objects.hashCode.\n" ^int32 [^any x]
        (when (== x nil) (return 0))
        (HashCode x))
     '(go/func C2g_ObjEquals "C2g_ObjEquals is Objects.equals.\n" ^bool [^any a ^any b]
        (when (== a b) (return true))
        (when (or (== a nil) (== b nil)) (return false))
        (Equals a b))
     '(go/func C2g_DoubleBits "C2g_DoubleBits is Double.doubleToLongBits (one NaN).\n" ^int64 [^float64 d]
        (when (math/IsNaN d) (return 0x7ff8000000000000))
        (conv int64 (math/Float64bits d)))
     '(go/func C2g_FloatBits "C2g_FloatBits is Float.floatToIntBits (one NaN).\n" ^int32 [^float32 f]
        (when (!= f f) (return 0x7fc00000))
        (conv int32 (math/Float32bits f)))
     (list 'go/type 'C2gCloner (list 'interface (list 'CloneShallow (with-meta [] {:tag 'any}))))
     (list 'go/func 'C2g_ObjectClone (with-meta [(tag 'x 'any)] {:tag 'any})
           (list '.CloneShallow (list 'assert 'C2gCloner 'x)))])))

(defn- modifiers [n]
  (let [dd (a/decl n)
        fl (if (and dd (not= :top (:nesting dd))) (:inner-flags dd) (:flags (m/info n)))
        fl (or fl 1)]
    (bit-and fl 0x761f)))

(defn- kind-sym [pkg n]
  (let [dd (or (a/decl n) {:kind (if (m/interface? n) :interface :class)})]
    (m/jrt-sym pkg (case (:kind dd)
                     :interface "KindInterface" :annotation "KindAnnotation" :enum "KindEnum"
                     :record "KindRecord" "KindClass"))))

(defn- arg-conv [pkg d x]
  (cond (t/prim? d) (list 'assert (m/go-type pkg d) x)
        (= d "Ljava/lang/Object;") x
        :else (list (list 'inst (m/jrt-sym pkg "As") (m/go-type pkg d)) x)))

(defn- result-any [pkg d call]
  (cond (= d "V") nil
        (m/pointer-desc? d) (list (m/jrt-sym pkg "C2g_RefP") call)
        :else call))

(defn member-tables
  "The member tables (§5.11, amendment R12) of translated class n: its public members."
  [pkg n]
  (binding [c/*f* {:pkg pkg}]
    (let [g (m/go-name n)
          iface (m/interface? n)
          leaf (and (not iface) (m/leaf? n))
          rty (cond iface (symbol g) leaf (list '* (symbol g)) :else (symbol (str g "_I")))
          abstract (m/has? (:flags (a/decl n)) Opcodes/ACC_ABSTRACT)
          public? #(m/has? (:flags %) Opcodes/ACC_PUBLIC)
          cls (fn [dd] (c/class-val dd))
          methods (for [mm (d/class-methods n)
                        :when (and (public? mm) (not= "<init>" (:name mm)))
                        :let [[ps r] (t/parse-method-desc (:desc mm))
                              base (nm/method-base (:name mm) (:desc mm))
                              static (m/static? mm)
                              args (map-indexed (fn [i p] (arg-conv pkg p (list 'aget 'args i))) ps)
                              call (cond static (apply list (symbol (str g "_" base)) args)
                                         :else (apply list (symbol (str "." base)) (list 'assert rty 'this) args))
                              body (if (= "V" r) [call nil] [(result-any pkg r call)])]]
                    (list 'lit (m/jrt-sym pkg "MethodInfo")
                          :Name (:name mm)
                          :Params (when (seq ps) (apply list 'lit (list 'slice (list '* (m/jrt-sym pkg "Class"))) (map cls ps)))
                          :Return (cls r)
                          :Modifiers (bit-and (:flags mm) 0x1fff)
                          :Invoke (list* 'fn (with-meta [(tag 'this 'any) (tag 'args '(slice any))] {:tag 'any}) body)))
          ctors (for [mm (d/class-methods n)
                      :when (and (public? mm) (= "<init>" (:name mm)) (not abstract) (not iface))
                      :let [real (e/ctor-real-desc n mm)
                            [ps _] (t/parse-method-desc (:desc mm))
                            [rps _] (t/parse-method-desc real)]
                      :when (= (count ps) (count rps))]
                  (list 'lit (m/jrt-sym pkg "CtorInfo")
                        :Params (when (seq ps) (apply list 'lit (list 'slice (list '* (m/jrt-sym pkg "Class"))) (map cls ps)))
                        :Modifiers (bit-and (:flags mm) 0x1fff)
                        :New (list 'fn (with-meta [(tag 'args '(slice any))] {:tag 'any})
                                   (apply list (symbol (nm/new-name g real))
                                          (map-indexed (fn [i p] (arg-conv pkg p (list 'aget 'args i))) ps)))))
          fields (for [f (d/class-fields n)
                       :when (public? f)
                       :let [static (m/static? f)
                             place (if static (symbol (nm/static-field-name g (:name f)))
                                       (list (symbol (str ".-" (nm/field-name (:name f))))
                                             (if (or iface leaf) (list 'assert rty 'o)
                                                 (list (symbol (str ".Self_" g)) (list 'assert rty 'o)))))
                             vol (c/volatile-field? f)
                             cval (env/const-value f)
                             final (m/has? (:flags f) Opcodes/ACC_FINAL)]]
                   (list* 'lit (m/jrt-sym pkg "FieldInfo")
                          :Name (:name f) :Type (cls (:desc f)) :Modifiers (bit-and (:flags f) 0x5fff)
                          :Get (list 'fn (with-meta [(tag 'o 'any)] {:tag 'any})
                                     (let [r (if vol (c/volatile-read place (:desc f)) place)]
                                       (or (result-any pkg (:desc f) r) r)))
                          (when-not (or final vol)
                            [:Set (list 'fn [(tag 'o 'any) (tag 'v 'any)]
                                        (list 'set! place (arg-conv pkg (:desc f) 'v)))])))]
      {:methods methods :ctors ctors :fields fields})))

(defn class-registration
  "C_class (Define, hierarchy only) and the init function setting its function and table
  fields (§5.11, amendment J1)."
  [pkg n]
  (binding [c/*f* {:pkg pkg}]
    (let [g (m/go-name n)
          dd (or (a/decl n) (assoc (m/info n) :kind :interface :nesting (if (:outer (m/info n)) :member :top)
                                   :simple (t/simple-name-of n) :reflected true))
          iface (m/interface? n)
          sup (:super dd)
          ifaces (filter m/in-world? (:interfaces dd))
          tables (if (:reflected dd) {} (member-tables pkg n))
          cls-sym (symbol (str g "_class"))]
      [(list 'go/var cls-sym
             (list (m/jrt-sym pkg "Define")
                   (list 'addr
                         (apply list 'lit (m/jrt-sym pkg "ClassInfo")
                                (concat
                                  [:Name (str/replace n "/" ".") :Modifiers (modifiers n) :Kind (kind-sym pkg n)]
                                  (when (and sup (not iface)) [:Super (c/class-val (str "L" sup ";"))])
                                  (when (seq ifaces)
                                    [:Interfaces (apply list 'lit (list 'slice (list '* (m/jrt-sym pkg "Class")))
                                                        (map #(c/class-val (str "L" % ";")) ifaces))])
                                  (when (and (= :member (:nesting dd)) (m/in-world? (:outer dd)))
                                    [:Declaring (c/class-val (str "L" (:outer dd) ";"))])
                                  (when-not (= :top (:nesting dd))
                                    [:Simple (or (:simple dd) "")])
                                  [:Go (str (nm/pkg-path pkg) "." g)])))))
       (list 'go/func 'init []
             (list* 'let ['i (list '.Info cls-sym)]
                    (concat
                      [(list 'set! (list '.-IsInstance 'i) (symbol (str g "_InstanceOf")))]
                      (when-not (m/trivial-init? n)
                        [(list 'set! (list '.-Init 'i) (symbol (str g "_Init")))])
                      (when (= :enum (:kind dd))
                        [(list 'set! (list '.-Enum 'i)
                               (list* 'fn (with-meta [] {:tag (list '* (m/jrt-sym pkg "RefArray"))})
                                      (concat (when-not (m/trivial-init? n) [(list (symbol (str g "_Init")))])
                                              [(symbol (str g "__VALUES"))])))])
                      (when (seq (:methods tables))
                        [(list 'set! (list '.-Methods 'i) (apply list 'lit (list 'slice (m/jrt-sym pkg "MethodInfo")) (:methods tables)))])
                      (when (seq (:ctors tables))
                        [(list 'set! (list '.-Ctors 'i) (apply list 'lit (list 'slice (m/jrt-sym pkg "CtorInfo")) (:ctors tables)))])
                      (when (seq (:fields tables))
                        [(list 'set! (list '.-Fields 'i) (apply list 'lit (list 'slice (m/jrt-sym pkg "FieldInfo")) (:fields tables)))])
                      (when-not iface
                        [(list (m/jrt-sym pkg "RegisterGoType") cls-sym (list (list 'inst 'reflect/TypeFor (symbol g))))]))))])))

(defn cut-forms
  "Class objects of classes outside the closed world that code names (class literals):
  registered by name only, so that Class.forName finds them and nothing is their instance
  (\"cut\" classes, C2G-SPEC §4.1)."
  [pkg classes]
  (for [n (sort classes)]
    (list 'go/var (symbol (str (m/go-name n) "_class"))
          (list (m/jrt-sym pkg "Define")
                (list 'addr (list 'lit (m/jrt-sym pkg "ClassInfo")
                                  :Name (str/replace n "/" ".")
                                  :Modifiers 1 :Kind (if (env/interface? n) (m/jrt-sym pkg "KindInterface") (m/jrt-sym pkg "KindClass"))
                                  :Super (when-not (env/interface? n) (m/jrt-sym pkg "Object_class"))
                                  :Go (str (nm/pkg-path pkg) "." (m/go-name n) " (cut)")))))))

(defn frames-forms
  "The frame table (§7.9.6, amendment J4): entries for methods whose Java names the demangler
  cannot read back (names with _ or $)."
  [pkg classes]
  (let [entries (for [n classes
                      :when (a/decl n)
                      :let [g (m/go-name n)]
                      mm (d/class-methods n)
                      :when (and (not= "<init>" (:name mm)) (re-find #"[_$]" (:name mm)))
                      :let [base (nm/method-base (:name mm) (:desc mm))
                            static (m/static? mm)
                            iface (m/interface? n)
                            leaf (and (not iface) (m/leaf? n))
                            gofn (str (nm/pkg-path pkg) "."
                                      (cond (or static iface) (str g "_" base)
                                            leaf (str "(*" g ")." base)
                                            :else (str "(*" g ").Impl_" base)))]]
                  (list 'lit '_ gofn (str/replace n "/" ".") (:name mm) 0))]
    (when (seq entries)
      [(list 'go/func 'init []
             (list (m/jrt-sym pkg "RegisterFrames") (apply list 'lit (list 'slice (m/jrt-sym pkg "FrameInfo")) entries)))])))
