;   Copyright (c) Rich Hickey. All rights reserved.
;   The use and distribution terms for this software are covered by the
;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
;   which can be found in the file epl-v10.html at the root of this distribution.
;   By using this software in any fashion, you are agreeing to be bound by
;   the terms of this license.
;   You must not remove this notice, or any other, from this software.

;; The Go build's arbace/core_proxy.clj (doc/go/EVAL-NOTES.md, "Namespace variants" and phase
;; 2A): it replaces arbace/core_proxy.clj in the executable. The JVM's proxy generates a class
;; with ASM; here the class is made at run time over Dyn (Compiler$Dyn/defineProxyClass): a
;; Dyn class when the superclass is Object, else an object of c2g's Go type DynSub_C, which
;; embeds the superclass's struct (the classes of arbace.c2g.dyn/proxy-supers). The methods
;; are those generate-proxy overrides (the superclass's non-final public and protected
;; instance methods, the interfaces' methods, with their bridges), each a fn looking its name
;; up in the proxy's fn map (field 0) as the generated bytecode does: the mapped fn is called
;; with the proxy and the arguments; without one, a superclass method runs the superclass's
;; implementation (the fn answers Compiler$Dyn/superMarker) and an interface method throws
;; UnsupportedOperationException. Everything else is arbace/core_proxy.clj's. A proxy of a
;; class the Go build cannot extend expands to a throw, so that code using it loads. bean is
;; arbace/core_bean.clj's, shared with the JVM (by reflection, without java.beans).

(in-ns 'arbace.core)

;; arbace/core_proxy.clj's imports, less ASM's (the namespaces after it use them)
(import
 '(java.lang.reflect Modifier Constructor)
 '(java.io Serializable NotSerializableException)
 '(arbace.lang IProxy Reflector DynamicClassLoader IPersistentMap PersistentHashMap RT
               Compiler$Dyn))

(defn method-sig [^java.lang.reflect.Method meth]
  [(. meth (getName)) (seq (. meth (getParameterTypes))) (. meth getReturnType)])

(defn- most-specific [rtypes]
  (or (some (fn [t] (when (every? #(isa? t %) rtypes) t)) rtypes)
    (throw (Exception. "Incompatible return types"))))

(defn- group-by-sig
  "Takes a collection of [msig meth] and returns a seq of maps from
   return-types to meths."
  [coll]
  (vals (reduce1 (fn [m [msig meth]]
                  (let [rtype (peek msig)
                        argsig (pop msig)]
                    (assoc m argsig (assoc (m argsig {}) rtype meth))))
          {} coll)))

(defn proxy-name
 {:tag String}
 [^Class super interfaces]
  (let [inames (into1 (sorted-set) (map #(.getName ^Class %) interfaces))]
    (apply str (.replace (str *ns*) \- \_) ".proxy"
      (interleave (repeat "$")
        (concat
          [(.getName super)]
          (map #(subs % (inc (.lastIndexOf ^String % "."))) inames)
          [(Integer/toHexString (hash inames))])))))

(defn- proxy-methods
  "The methods generate-proxy overrides: {:super (the superclass's, which call the
  superclass's implementation without a mapping), :ifaces (the interfaces' and the abstract
  ones, which throw), :bridges ([dest bridges] for each signature with several return types)}."
  [^Class super interfaces]
  (let [[mm considered]
          (loop [mm {} considered #{} c super]
            (if c
              (let [[mm considered]
                    (loop [mm mm
                           considered considered
                           meths (concat
                                  (seq (. c (getDeclaredMethods)))
                                  (seq (. c (getMethods))))]
                      (if (seq meths)
                        (let [^java.lang.reflect.Method meth (first meths)
                              mods (. meth (getModifiers))
                              mk (method-sig meth)]
                          (if (or (considered mk)
                                  (not (or (Modifier/isPublic mods) (Modifier/isProtected mods)))
                                  (. Modifier (isStatic mods))
                                  (. Modifier (isFinal mods))
                                  (= "finalize" (.getName meth)))
                            (recur mm (conj considered mk) (next meths))
                            (recur (assoc mm mk meth) (conj considered mk) (next meths))))
                        [mm considered]))]
                (recur mm considered (. c (getSuperclass))))
              [mm considered]))
        ifaces-meths (into1 {}
                       (for [^Class iface interfaces meth (. iface (getMethods))
                             :let [msig (method-sig meth)] :when (not (considered msig))]
                         {msig meth}))
        ;; Treat abstract methods as interface methods
        [mm ifaces-meths] (let [abstract? (fn [[_ ^java.lang.reflect.Method meth]]
                                            (Modifier/isAbstract (. meth (getModifiers))))
                                mm-no-abstract (remove abstract? mm)
                                abstract-meths (filter abstract? mm)]
                            [mm-no-abstract (concat ifaces-meths abstract-meths)])
        mgroups (group-by-sig (concat mm ifaces-meths))
        rtypes (map #(most-specific (keys %)) mgroups)
        mb (map #(vector (%1 %2) (vals (dissoc %1 %2))) mgroups rtypes)
        bridge? (reduce1 into1 #{} (map second mb))]
    {;; the Go build: of Object's methods only those a Dyn can override (its slots)
     :super (remove #(or (bridge? %)
                         (and (= Object (.getDeclaringClass ^java.lang.reflect.Method %))
                              (not (#{"toString" "hashCode" "equals"} (.getName ^java.lang.reflect.Method %)))))
                    (vals mm))
     :ifaces (remove bridge? (vals ifaces-meths))
     :bridges mb}))

(def ^:private proxy-super-marker (Compiler$Dyn/superMarker))

(defn- proxy-method-fn
  "The fn of a proxy's method named mname: the fn map's, else the superclass's implementation
  (super?) or UnsupportedOperationException."
  [^String mname super?]
  (if super?
    (fn [this & args]
      (let [f (get (Compiler$Dyn/getField this 0) mname)]
        (if f (apply f this args) proxy-super-marker)))
    (fn [this & args]
      (let [f (get (Compiler$Dyn/getField this 0) mname)]
        (if f (apply f this args) (throw (UnsupportedOperationException. mname)))))))

(defn- set-proxy-method [^Class c ^java.lang.reflect.Method meth f]
  (Compiler$Dyn/setMethod c (.getName meth) (.getParameterTypes meth) (.getReturnType meth) f))

(defn- define-proxy
  "The proxy class of super and interfaces named pname, made at run time."
  [^String pname ^Class super interfaces]
  (let [c (Compiler$Dyn/defineProxyClass pname super (into-array Class (cons IProxy interfaces)))
        ;; made while a form is analyzed (proxy's expansion): an event of the image of prepared
        ;; namespaces (Compiler$Image), which makes it again by get-proxy-class; only once it is
        ;; made (a proxy of a class the Go build cannot extend throws, and proxy's expansion
        ;; throws when evaluated, as arbace.classes.env's proxies of ASM's visitors do)
        _ (arbace.lang.Compiler$Image/event (object-array ["proxy" pname super (into-array Class interfaces)]))
        {sms :super ims :ifaces mb :bridges} (proxy-methods super interfaces)
        fns (volatile! {})]
    ;; IProxy: the fn map in field 0
    (Compiler$Dyn/setMethod c "__initArbaceFnMappings" (into-array Class [IPersistentMap]) Void/TYPE
                            (fn [this m] (Compiler$Dyn/setField this 0 m) nil))
    (Compiler$Dyn/setMethod c "__updateArbaceFnMappings" (into-array Class [IPersistentMap]) Void/TYPE
                            (fn [this m]
                              (Compiler$Dyn/setField this 0 (.cons ^arbace.lang.IPersistentCollection (Compiler$Dyn/getField this 0) m))
                              nil))
    (Compiler$Dyn/setMethod c "__getArbaceFnMappings" (make-array Class 0) IPersistentMap
                            (fn [this] (Compiler$Dyn/getField this 0)))
    (doseq [^java.lang.reflect.Method m sms]
      (let [f (proxy-method-fn (.getName m) true)]
        (vswap! fns assoc m f)
        (set-proxy-method c m f)))
    (doseq [^java.lang.reflect.Method m ims]
      (let [f (proxy-method-fn (.getName m) false)]
        (vswap! fns assoc m f)
        (set-proxy-method c m f)))
    ;; the superclass's methods reflection does not list (protected ones of jrt's classes)
    (when-not (= super Object)
      (Compiler$Dyn/fillProxySlots c (fn [n] (proxy-method-fn n true))))
    ;; a bridge answers as the method it bridges to
    (doseq [[^java.lang.reflect.Method dest bridges] mb
            ^java.lang.reflect.Method meth bridges]
      (set-proxy-method c meth (or (@fns dest)
                                   (proxy-method-fn (.getName dest)
                                                    (not (or (.isInterface (.getDeclaringClass dest))
                                                             (Modifier/isAbstract (.getModifiers dest))))))))
    c))

(defn- get-super-and-interfaces [bases]
  (if (. ^Class (first bases) (isInterface))
    [Object bases]
    [(first bases) (next bases)]))

(defn get-proxy-class
  "Takes an optional single class followed by zero or more
  interfaces. If not supplied class defaults to Object.  Creates an
  returns an instance of a proxy class derived from the supplied
  classes. The resulting value is cached and used for any subsequent
  requests for the same class set. Returns a Class object."
  {:added "1.0"}
  [& bases]
    (let [[super interfaces] (get-super-and-interfaces bases)
          pname (proxy-name super interfaces)]
      (or (RT/loadClassForName pname)
          (define-proxy pname super interfaces))))

(defn construct-proxy
  "Takes a proxy class and any arguments for its superclass ctor and
  creates and returns an instance of the proxy."
  {:added "1.0"}
  [c & ctor-args]
    (. Reflector (invokeConstructor c (to-array ctor-args))))

(defn init-proxy
  "Takes a proxy instance and a map of strings (which must
  correspond to methods of the proxy superclass/superinterfaces) to
  fns (which must take arguments matching the corresponding method,
  plus an additional (explicit) first arg corresponding to this, and
  sets the proxy's fn map.  Returns the proxy."
  {:added "1.0"}
  [^IProxy proxy mappings]
    (. proxy (__initArbaceFnMappings mappings))
    proxy)

(defn update-proxy
  "Takes a proxy instance and a map of strings (which must
  correspond to methods of the proxy superclass/superinterfaces) to
  fns (which must take arguments matching the corresponding method,
  plus an additional (explicit) first arg corresponding to this, and
  updates (via assoc) the proxy's fn map. nil can be passed instead of
  a fn, in which case the corresponding method will revert to the
  default behavior. Note that this function can be used to update the
  behavior of an existing instance without changing its identity.
  Returns the proxy."
  {:added "1.0"}
  [^IProxy proxy mappings]
    (. proxy (__updateArbaceFnMappings mappings))
    proxy)

(defn proxy-mappings
  "Takes a proxy instance and returns the proxy's fn map."
  {:added "1.0"}
  [^IProxy proxy]
    (. proxy (__getArbaceFnMappings)))

(defmacro proxy
  "class-and-interfaces - a vector of class names

  args - a (possibly empty) vector of arguments to the superclass
  constructor.

  f => (name [params*] body) or
  (name ([params*] body) ([params+] body) ...)

  Expands to code which creates a instance of a proxy class that
  implements the named class/interface(s) by calling the supplied
  fns. A single class, if provided, must be first. If not provided it
  defaults to Object.

  The interfaces names must be valid interface types. If a method fn
  is not provided for a class method, the superclass method will be
  called. If a method fn is not provided for an interface method, an
  UnsupportedOperationException will be thrown should it be
  called. Method fns are closures and can capture the environment in
  which proxy is called. Each method fn takes an additional implicit
  first arg, which is bound to 'this. Note that while method fns can
  be provided to override protected methods, they have no other access
  to protected members, nor to super, as these capabilities cannot be
  proxied."
  {:added "1.0"}
  [class-and-interfaces args & fs]
   (let [bases (map #(or (resolve %) (throw (Exception. (str "Can't resolve: " %))))
                    class-and-interfaces)
         [super interfaces] (get-super-and-interfaces bases)
         ;; the Go build: a proxy of a class it cannot extend throws when evaluated
         pc-effect (try (apply get-proxy-class bases)
                        (catch UnsupportedOperationException e e))
         pname (proxy-name super interfaces)]
     (if (instance? Throwable pc-effect)
       `(throw (UnsupportedOperationException. ~(.getMessage ^Throwable pc-effect)))
       (do
     ;remember the class to prevent it from disappearing before use
     (intern *ns* (symbol pname) pc-effect)
     `(let [;pc# (get-proxy-class ~@class-and-interfaces)
            p# (new ~(symbol pname) ~@args)] ;(construct-proxy pc# ~@args)]
        (init-proxy p#
         ~(loop [fmap {} fs fs]
            (if fs
              (let [[sym & meths] (first fs)
                    meths (if (vector? (first meths))
                            (list meths)
                            meths)
                    meths (map (fn [[params & body]]
                                   (cons (apply vector 'this params) body))
                               meths)]
                (if-not (contains? fmap (name sym))
                (recur (assoc fmap (name sym) (cons `fn meths)) (next fs))
							 (throw (IllegalArgumentException.
										(str "Method '" (name sym) "' redefined")))))
              fmap)))
        p#)))))

(defn proxy-call-with-super [call this meth]
 (let [m (proxy-mappings this)]
    (update-proxy this (assoc m meth nil))
    (try
      (call)
      (finally (update-proxy this m)))))

(defmacro proxy-super
  "Use to call a superclass method in the body of a proxy method.
  Note, expansion captures 'this"
  {:added "1.0"}
  [meth & args]
 `(proxy-call-with-super (fn [] (. ~'this ~meth ~@args))  ~'this ~(name meth)))
