;; Writes test/oracle/forms/defclass_corpus.clj from the class forms compiler's tests
;; (test/classes/*_test.clj): every vector of class forms they compile (same-shapes?, forms-classes,
;; load-forms) becomes one defclasses form at the REPL, in a namespace of its own, so that the
;; oracle checks that the Go build defines what the JVM compiles (and fails where it fails, with
;; the analysis's messages). Run: bin/arbace-j test/classforms/gen_corpus.clj (then bin/oracle record
;; forms/defclass_corpus).
(ns classforms.gen-corpus
  (:require [arbace.string :as str]
            [arbace.walk :as walk]))

(defn- read-all [file]
  (let [r (arbace.lang.LineNumberingPushbackReader. (java.io.FileReader. ^String file))]
    (binding [*read-eval* false]
      (doall (take-while #(not= % ::eof) (repeatedly #(read {:eof ::eof :read-cond :allow} r)))))))

(defn- vectors
  "The quoted vectors of class forms in form: '[(Name ...) ...] arguments."
  [form]
  (let [acc (atom [])]
    (walk/prewalk
      (fn [x]
        (when (and (seq? x) (= 'quote (first x)) (vector? (second x))
                   (seq (second x)) (every? #(and (seq? %) (symbol? (first %))) (second x)))
          (swap! acc conj (second x)))
        x)
      form)
    @acc))

(defn- p
  "Form x as text, its metadata (but source positions) written out as maps (pr's ^T shorthand
  of a :tag does not read back for list tags)."
  [x]
  (let [m (apply dissoc (meta x) [:line :column :end-line :end-column :file])
        base (cond
               (seq? x) (str "(" (str/join " " (map p x)) ")")
               (vector? x) (str "[" (str/join " " (map p x)) "]")
               (map? x) (str "{" (str/join " " (map (fn [[k v]] (str (p k) " " (p v))) x)) "}")
               (set? x) (str "#{" (str/join " " (map p x)) "}")
               :else (binding [*print-meta* false] (pr-str x)))]
    (if (and (seq m) (instance? arbace.lang.IObj x))
      (str "^" (p m) " " base)
      base)))

(defn -main []
  (let [files (sort (filter #(str/ends-with? % "_test.clj")
                            (map str (.list (java.io.File. "test/classes")))))
        n (atom 0)
        out (StringBuilder.)]
    (.append out (str ";; Generated by test/classforms/gen_corpus.clj from the class forms compiler's tests\n"
                      ";; (test/classes/*_test.clj; doc/go/CLASSFORMS-REPL.md): each vector of class forms they\n"
                      ";; compile, defined at the REPL by defclasses in a namespace of its own.\n"))
    (doseq [f files
            form (read-all (str "test/classes/" f))
            v (vectors form)]
      (let [i (swap! n inc)]
        (binding [*print-length* nil *print-level* nil]
          (.append out (str "\n;; " f "\n"
                            "(ns cfcorpus.c" i ")\n"
                            (p (cons 'defclasses (map #(cons 'defclass %) v))) "\n")))))
    (.append out "\n(in-ns 'user)\n")
    (spit "test/oracle/forms/defclass_corpus.clj" (str out))
    (println @n "class form vectors")))

(-main)
